KhronosGroup/SPIRV-Tools

CMakeLists.txt, include/libspirv/libspirv.h, source/instruction.h
Don't use SYSTEM attribute on include_directories directive
for the SPIR-V standard header files.  When you do, object files
are not considered dependent on those headers.
Checked by looking at the dependency file source/disassemble.cpp.o.d,
and by trying to compile after a trivial edit to spirv.h
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/7
Also, use "" inclusion instead of <> inclusion for standard SPIR-V
headers.
=> Object files should depend on spirv.h and friends

external/include/headers/spirv.h
Use the new spirv.h from the SPIR-V registry.
The SPV_VERSION macro value was updated to be 0x10000.
Previously it was missing the "0x" prefix, which caused
confusion.
The value of the const unsigned int SpvVersion has always
been 0x00010000.  That's what should appear as the version
word in the SPIR-V header.
The SPV_VERSION symbol is to be used in preprocessor directives.
=> Updated spirv.h header. Fixes SPV_VERSION macro

source/binary.cpp, source/diagnostic.cpp, source/diagnostic.h, source/disassemble.cpp, source/print.cpp, source/print.h, test/DiagnosticStream.cpp
Each exported functions either has an "spv" prefix, or is in the libspirv
namespace.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/18
=> Put DiagnosticStream and clr exports in libspirv namespace

source/binary.cpp
The asserts check the length of the endian-converted words
vector with the reported number of words in the instruction.
=> Fix compilation of an assert.

source/endian.cpp, test/UnitSPIRV.h
=> Aliasing through a union member is valid.

include/libspirv/libspirv.h, test/BinaryParse.cpp, test/UnitSPIRV.h
Add a non-zero spv_result_t value SPV_REQUESTED_TERMINATION
which should be used to signal an ok result, but signals
early termination for a process, such as binary parsing.
Tests include:
- correct contents sent to header and instruction callbacks
- non-zero status from a callback should terminate parsing,
but the parser should not generate its own diagnostic.
TODO: Check diagnostics generated by the parser itself.
=> Several unit tests for spvBinaryParse

CMakeLists.txt
The tests now use mocked methods.  This requires runtime type
information for those test classes.
https://github.com/google/googletest/issues/610
This has been fixed recently upstream in googletest.  Until we pick
up that fix, add -frtti for the the test executable only.
=> Add -frtti for tests that use mocking

CMakeLists.txt, README.md
Using -frtti caused link failures when both of the following are
in effect:
-DDISABLE_EXCEPTIONS=ON
-DDISABLE_RTTI=ON
The correct fix is to use tip-of-tree googletest.
Specifically, we need a version of googletest with the fix in
https://github.com/google/googletest/pull/612
In particular, it must be later than googletest 1.7.0.
=> Don't add -frtti for tests. Use newer googletest.

source/opcode.cpp, test/BinaryParse.cpp, test/TextToBinary.Annotation.cpp
There are two commits in this PR.
The first adds a test case where the string operand occurs last in the instruction, but has fewer words than implied by the instruction word count.
The second adds short string test cases where the string operand is not the last operand in an instruction.  This only occurs with OpDecorate and OpMemberDecorate for LinkageAttributes decorations.  A LinkageAttributes decoration takes a literal string operand, followed by an attributes enum word.  It should take nothing else.  But to enforce that, we have to tweak the grammar to drop the OperandVariableLiterals at the end of OpDecorate and OpMemberDecorate when parsing opcode.inc.  So I did that and also wrote a few more failing assembler and disassembler cases for OpDecorate and OpMemberDecorate. …
=> test binary parsing where the string operand is shorter than implied by the word count

CMakeLists.txt, README.md
An enclosing CMake project should be able to set the
off-by-default CMake options in SPIRV-Tools by just doing:
set(SPIRV_SKIP_EXECUTABLES ON)
instead of
set(SPIRV_SKIP_EXECUTABLES ON CACHE BOOL "" FORCE)
Also, fix the SPIRV_WARN_EVERYTHING option processing so Cmake understands which options
to send to Clang vs. GCC.
Note: With SPIRV_WARN_EVERYTHING enabled, the code doesn't
compile with either Clang or GCC.
=> Fix setting of off-by-default cmake options

CMakeLists.txt, test/AssemblyContext.cpp, test/BinaryHeaderGet.cpp, test/BinaryToText.cpp, test/GeneratorMagicNumber.cpp, test/OperandPattern.cpp, test/TextToBinary.cpp, test/UnitSPIRV.h
Adds CMAKE_CURRENT_SOURCE_DIR to the include path for UnitSPIRV
=> Avoid relative path in #include

source/binary.cpp, test/BinaryParse.cpp
Emit a diagnostic if the OpSwitch selector refers to an ID that
is valid but has no type.
Discovered by afl-fuzz.
=> Fix parser assert failure for a bad OpSwitch

include/util/hex_float.h, test/HexFloat.cpp
Fixes formatting of disassembler output after printing
a hex float, e.g. for a NaN or subnormal.
=> operator<< on FloatProxy preserves float and fill

include/util/hex_float.h, source/binary.cpp, source/diagnostic.h, source/disassemble.cpp, source/text.cpp, source/validate.cpp, source/validate_id.cpp
Avoid:
- variable or argument shadowing
- implicit narrowing conversions
- implicit conversions of character array to bool (that the compiler complains about)
=> Fix strict clang warnings

CMakeLists.txt, include/util/hex_float.h, test/BinaryDestroy.cpp, test/BinaryHeaderGet.cpp, test/BinaryParse.cpp, test/BinaryToText.cpp, test/HexFloat.cpp, test/ImmediateInt.cpp, test/TestFixture.h, test/TextToBinary.cpp, test/UnitSPIRV.h
Added additional compilation flags to gcc and clang builds.
Adds -Wall -Wextra -Wno-long-long -Wshadow -Wundef -Wconversion
-WNo-sign-conversion and -Wno-missing-field-initializers
where appropriate.
Does not add -Wundef to tests, because GTEST tests undefined
macros all over the place.
=> Made compilation with gcc and clang more strict.

CMakeLists.txt, include/libspirv/libspirv.h, test/DiagnosticDestroy.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/62
=> spvDiagnosticDestroy is safe to call on nullptr

source/validate_types.cpp, source/validate_types.h
The `diag` argument shadows the `diag` method, so the strict build fails.
=> Fix build by renaming ValidationState_t constructor argument.

source/validate_types.cpp
Signed/Unsigned mismatch in progressToNextLayoutStageOrder().
=> Fixed warning in VS2013 build.

CMakeLists.txt
C4503 is "decorated name length exceeded", triggered
by some heavily templated types.
=> Disable warnings C4503 on MSVC for test code

.travis.yml
Try to re-run the build with ninja -j 1 if the build fails,
this should reduce the number of build failures we see.
=> Since g++-4.9 has an ICE occasionally in travis add a retry.

include/libspirv/libspirv.h, source/disassemble.cpp, test/BinaryToText.cpp, tools/dis/dis.cpp
The option is disabled by default.
The offset is printed in hex, as a comment after each instruction.
=> Add disassembler option to show byte offset

CMakeLists.txt
If a third-party project defines a CMake function with the same
name, by importing that project's CMake configuration, we may end
up overwriting our own copy. Qualify all defined functions to
reduce that probability.
=> Qualify CMake function names with "spvtools" to avoid conflictions.

include/libspirv/libspirv.h, source/operand.cpp, source/operand.h, source/validate_instruction.cpp, test/Operand.cpp
Adds spvOperandIsConcreteMask.
Use spvOperandIsConcreteMask to determine if an operand is a bitmask.  Check its individual
bits in a generic way.
=> Validate mask operand capabilities in a more data driven way

external/include/headers/GLSL.std.450.h, external/include/headers/spirv.h, external/include/headers/spirv.py
Refresh from the SPIR-V registry.
=> Use SPIR-V headers for 1.0 Rev3

include/util/hex_float.h, test/HexFloat.cpp
This should address problems on Windows:
https://github.com/KhronosGroup/SPIRV-Tools/issues/104
=> Don't promise particular values when float parsing fails.

source/ext_inst.cpp, test/ExtInstGLSLstd450.cpp
These appear first in GLSL.std.450 in 1.0 Rev3
=> Add GLSL instructions NMin, NMax, NClamp

CMakeLists.txt, README.md, include/spirv-tools/libspirv.h, test/Version.cpp
- Update version numbers in libspirv.h.
Add a test for the relevant macros.
- Update the README
=> SPIR-V Tools fully supports SPIR-V 1.0 Rev3

README.md
It now reflects the new header file organization.
It also tells API clients what to add to the search
include path.
=> Fix the source organization section in README.md

tools/as/as.cpp, tools/val/val.cpp
* Support outputting to stdout in `as`.
* Fix command line option errors in `val`.
* There is no `-capability`.
* `-rules` is missing.
* `-id` by default is turned off.
=> More modifications to support pipe in command line tools

source/text_handler.cpp, test/TextWordGet.cpp
This addresses Bug #126 where EOL is missing at the end of
source file.
=> getWord() should not go beyond the end of the source text.

CMakeLists.txt
Also change PYTHON_EXE to PYTHON_EXECUTABLE to match what
the cmake documentation says.
=> Actually find the python executable before use.

source/util/bitutils.h
=> Added missing <cstdint> in bitutils.

utils/update_build_version.py
Addresses #144.
* Use `print_function` from `__future__` to tackle the print syntax
change.
* In Python3 `str` and `bytes` are no longer the same thing. Need
proper decode.
=> Improve Python3 Compatibility

utils/update_build_version.py
When the given directory is not inside the SPIRV-Tools project,
`describe()` returns a `str` instance instead of `bytes` instance
in Python3, which will case problem when calling `decode()` on it.
=> Fix the corner case in version generation script.

CMakeLists.txt
As far as I know, CMake <2.8.12 will not have `target_compile_options`. See the [CMake 2.8.12 ChangeLog](https://cmake.org/files/v2.8/CMakeChangeLog-2.8.12) for details.
=> Add patchlevel to CMake requirement

source/text.cpp, source/text_handler.cpp, source/text_handler.h, test/TextWordGet.cpp, test/UnitSPIRV.h
* It's redundant to provide two mutable `spv_position` to `getWord()`.
* `getWord()` should take string pointer by the style guide.
=> Change the interface for getWord().

include/spirv-tools/libspirv.h, source/binary.cpp, source/opcode.cpp, source/operand.cpp, test/OperandPattern.cpp, test/TextToBinary.ModeSetting.cpp
Previously, the grammar allowed many execution modes for a single
OpExecutionMode instruction.
Removes the variable- and optional- execution mode operand type
enum values.
Issue found by antiagainst@
=> OpExecutionMode only takes a single ExecutionMode

CMakeLists.txt
Required for linking against libSPIRV-Tools from LVL's
libVkLayer_core_validation.so.
=> Enable linking against libSPIRV-Tools from linux shared libraries

utils/generate_grammar_tables.py
Now we can generate tables only for the core grammar or for a specific extended instruction set.
=> Allow to only build certain grammar tables.

include/spirv-tools/libspirv.h, source/spirv_target_env.cpp, source/table.cpp, tools/as/as.cpp, tools/dis/dis.cpp, tools/val/val.cpp
Revisions proliferate quickly and we don't promise to retain extra
grammar copies for every historical one.
@antiagainst @AWoloszyn @dneto0 @Qining PTAL
=> Remove revision from SPV_ENV_*.

source/spirv.core.grammar.json, utils/generate_grammar_tables.py
* `IdType` is renamed to `IdResultType`.
* `version` is splitted into `major_version` and `minor_version`.
* Seperate `Scope` and `IdScope` operand kinds. Same for `MemorySemantics`.
* `OpPhi` now uses `PairIdRefIdRef` as the last operand.
=> Grammar update

CMakeLists.txt, source/CMakeLists.txt
Use `add_custom_command()` to generate all .inc files and manage
dependency with `set_source_files_properties()`.
Tested:
* `touch` the grammar json, then `ninja` once, rebuild the `.inc` files. `ninja` twice, clean.
* `touch` `generate_grammar_tables.py`, then `ninja` once, rebuild the `.inc` files. `ninja` twice, clean.
* `touch source/print.cpp`, then `ninja` once, `print.o` got rebuilt and all things depends on it. no rebuilding of `.inc` files. `ninja` twice, clean.
=> Rework CMake rules for building grammar tables.

source/text_handler.cpp, test/TextAdvance.cpp
This fixes a heap-buffer-overflow problem reported by clang asan.
=> Avoid going out of bound in advanceLine() and refine comments.

test/Validate.Capability.cpp
Replace `#ifdef 0` with comment inside a macro call.
=> Fix Windows build.

test/TextToBinary.ModeSetting.cpp, test/UnitSPIRV.h
Previously v1.1 testing was dead.
=> Refactor OpExecutionModeTest and apply it on v1.1.

test/TextToBinary.Debug.cpp
Simplify the instantiation by using Values() instead of ValuesIn().
Run clang-format.
=> Remove done TODOs in OpNameTest.

test/Validate.CFG.cpp
On Windows, test::MatchesRegex() doesn't support brackets.  On Linux, \d
doesn't work. :(
@dneto0 @antiagainst @AWoloszyn @Qining @umar456 PTAL.
=> Make googletest regexes portable.

source/val/ValidationState.cpp, source/validate_layout.cpp, test/Validate.Layout.cpp
Fixed invalid error message when an instruction that appears in a block is encountered before a function declaration.
Fixes #228
=> Fix diagnostic message for layout errors

test/BinaryParse.cpp, test/ExtInst.OpenCL.std.cpp, test/TextToBinary.Extension.cpp, utils/generate_grammar_tables.py
The operands following the extended instruction literal
number are determined by the extended instruction itself.
So drop the zero-or-more IdRef pattern at the end of OpExtInst.
It's arguable whether this should actually be a grammar fix.  I've
chosen to patch this in SPIRV-Tools instead of in the grammar file.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/233
Also fix two test cases for OpenCL extended instructions.  These
errors of supplying too many operands are now detected.
=> Fix ExtInst parsing: no IdRef* at end

source/val/BasicBlock.cpp, source/val/BasicBlock.h, source/val/Function.cpp, source/val/Function.h, source/val/ValidationState.cpp, source/validate.cpp, source/validate.h, source/validate_cfg.cpp, test/Validate.CFG.cpp, test/Validate.Layout.cpp
For dominance calculations we use an "augmented" CFG
where we always add a pseudo-entry node that is the predecessor
in the augmented CFG to any nodes that have no predecessors in the
regular CFG.  Similarly, we add a pseudo-exit node that is the
predecessor in the augmented CFG that is a successor to any
node that has no successors in the regular CFG.
Fixes a subtle problem where we were implicitly creating
the block_details for the pseudo-exit node since it didn't
appear in the idoms map, and yet we referenced it.  In such a case the
contents of the block details could be garbage, or zero-initialized.
That sometimes caused incorrect calculation of immediate dominators
and post-dominators.  For example, on a debug build where the details
could be zero-initialized, the dominator of an …
=> Use pseudo entry and pseudo exit blocks for dominance.

source/validate_instruction.cpp, test/Validate.Capability.cpp
Works around issue 248 by weakening the test:
https://github.com/KhronosGroup/SPIRV-Tools/issues/248
The validator should try to track (32-bit) constant values, and then
for capability checks on IDs, check the referenced value, not the
raw ID number.
=> Avoid capability checks on ID values. They are not literals

test/BinaryToText.cpp, test/OperandCapabilities.cpp
For DependencyInfinite and DependencyLength, test
that they don't require a capability to be turned on.
Also, that they are assembled, binary parsed, and disassembled
correctly.
=> Test v1.1 loop dependency support

test/OperandCapabilities.cpp, test/Validate.Capability.cpp
* The `Input` StorageClass doesn't require the `Shader` capability
anymore.
* The `Sampled1D` and `SampledBuffer` capabilities don't require
the `Shader` capability anymore. So they do not indirectly
depend on the `Matrix` capability. So are the `Image1D` and
`ImageBuffer` capabilities, which depend on `Sampled1D` and
`SampledBuffer`.
A new GLSL grammar file is uploaded for SPIR-V 1.1, but it's the
same as the existing one for SPIR-V 1.0.
Now tracking commit 3814effb879ab5a98a7b9288a4b4c7849d2bc8ac in
SPIRV-Headers.
=> Track changes in SPIRV-Headers for SPIR-V 1.1 rev 2.

CHANGES, include/spirv-tools/libspirv.h, source/CMakeLists.txt, source/disassemble.cpp, source/name_mapper.cpp, source/name_mapper.h, test/BinaryToText.cpp, test/CMakeLists.txt, test/NameMapper.cpp, tools/dis/dis.cpp
Add a `FriendlyNameMapper` to deduce friendly names for IDs based on
`OpName`, type structure, etc.
Taking over PR #263 @dneto0 did, fix issues here since I cannot push into
his branch.
=> Disassembling: map IDs to friendly names.

test/opt/test_pass_manager.cpp
Fix the test failure in a24506266bbdb849785678402d247c43acd234e7
Change "Null" to "null" in pass manager test
=> Fix a test failure in pass manager test

CHANGES, source/val/BasicBlock.cpp, source/val/BasicBlock.h, source/val/Function.cpp, source/val/Function.h, source/validate.h, source/validate_cfg.cpp, test/Validate.CFG.cpp
Ensure the dominance calculation visits all nodes in the CFG.
The successor list of the pseudo-entry node is augmented with
a single node in each cycle that otherwise would not be visited.
Similarly, the predecssors list of the pseduo-exit node is augmented
with the a single node in each cycle that otherwise would not
be visited.
Pulls DepthFirstSearch out so it's accessible outside of the dominator
calculation.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/279
=> Fix infinite loop in dominance calculation.

source/assembly_grammar.cpp
Pendding for now until the spec is fixed.
=> Allow OpINotEqual in OpSpecConstantOp inst

test/opt/CMakeLists.txt, test/opt/assembly_builder.h, test/opt/test_assembly_builder.cpp
AssemblyBuilder contains boilplates and adds OpName instructions for all
added defining instructions.
=> Simple Assembly code builder for test uses

source/val/Function.cpp, source/val/Function.h, source/validate_cfg.cpp, test/Validate.CFG.cpp
- Find unreachable continue targets.  Look for back edges
with a DFS traversal separate from the dominance traversals,
where we count the OpLoopMerge from the header to the continue
target as an edge in the graph.
- It's ok for a loop to have multiple back edges, provided
they are all from the same block, and we call that the latch block.
This may require a clarification/fix in the SPIR-V spec.
- Compute postdominance correctly for infinite loop:
Bias *predecessor* traversal root finding so that you use
a later block in the original list.  This ensures that
for certain simple infinite loops in the CFG where neither
block branches to a node without successors, that we'll
compute the loop header as dominating the latch block, and the
latch block as postdominating the loop header.
=> Validator cfg fixes

source/val/ValidationState.h, source/validate.cpp, source/validate_id.cpp
* Deletes the ValidationState_t copy constructor
* Removes needless copies of the copy constructor
=> Remove needless copies. Delete copy constructor.

source/opt/module.cpp, source/opt/module.h, source/opt/passes.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/test_eliminate_dead_const.cpp, tools/opt/opt.cpp
A pass to remove dead constants, including both front-end constants and spec
constants.
This pass does not handle dead variables and types.
=> Dead constants elimination

test/opt/pass_fixture.h
Just print the shader text that failed in either assembling or disassembling during optimization tests.
=> Print the shader when module building failed

source/opt/CMakeLists.txt, source/opt/pass.h, source/opt/passes.h
Future pass implementations should only need to include pass.h
This is also necessary for the implementation of pass registry to support -load=*.so in future.
=> Separate pass.h from passes.h

source/opt/instruction.cpp, source/opt/instruction.h
This is because some old visual studio versions (e.g., 2013) do
not support automatically generating move constructors/assignments.
=> Manually create move the constructor/assignment for Instruction.

test/opt/assembly_builder.h
assembly_builder was missing an include for cstdint.
=> Fixed the build for MSVC.

source/opt/basic_block.h, source/opt/function.cpp, source/opt/function.h, source/opt/ir_loader.cpp, source/opt/module.cpp, source/opt/module.h, source/val/BasicBlock.h, test/opt/test_pass_manager.cpp
Previously we use vectors of objects and move semantics to handle
ownership. That approach has the flaw that inserting an object into
the middle of a vector, which may trigger a vector reallocation,
can invalidate some addresses taken from instructions.
Now the in-memory representation internally uses vector of unique
pointers to handle ownership. Since objects are explicitly heap-
allocated now, pointers to them won't be invalidated by vector
resizing anymore.
A follow up PR #321 introduces an iterator class.
=> Change the interfaces of in-memory representation to use pointers.

test/opt/test_types.cpp
VS2013 is not happy with using initializer-list to initialize
vector parameters to explicit constructors taking one vector.
Sorry for this. The previous PR passed all checks, but that's
before I submit the PR to turn on VS2013 buildbots.
=> Fix build error about passing initializer-list to constructor.

tools/io.h
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/349
=> Avoid integer modulo by 1, to avoid warning

source/opt/iterator.h, test/opt/test_ir_loader.cpp
And `ptrdiff_t` is a implementation defined signed type. Comparing it
with unsigned number literal causes compiler warnings.
=> Make clear that we are using ptrdiff_t as the iterator difference type.

source/opt/def_use_manager.cpp, source/opt/def_use_manager.h, test/opt/test_def_use.cpp
Rebase and refine the CL #347 .
Removed the test for analyzing two modules, as current Module is bind to a module when it is created.
Based on CL #354
=> Add tests for individual instruction def-use analysis

source/validate_instruction.cpp, test/Validate.Capability.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/365
=> Relax ClipDistance, CullDistance capability check in all environments

source/opt/basic_block.h, source/opt/function.cpp, source/opt/function.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_loader.cpp, source/opt/module.cpp, source/opt/module.h, test/opt/test_def_use.cpp, test/opt/test_ir_loader.cpp
Also:
- Add const forms of ForEachInst
- Rewrite Module::ToBinary in terms of ForEachInst
- Add Instruction::ToBinaryWithoutAttachedDebugInsts
- Delete the ToBinary method on Function, BasicBlock, and Instruction
since it can now be implemented with ForEachInst in a less confusing
way, e.g. without recursion.
- Preserve debug line instructions on OpFunctionEnd (and store that
instruction as a unique-pointer, for regularity).
=> ForEachInst optionally runs on attached debug line insts

source/opt/basic_block.h, source/opt/function.cpp, source/opt/ir_loader.cpp, source/opt/ir_loader.h, test/opt/test_ir_loader.cpp
This lets us write smaller test cases with the IrLoader, avoiding
boilerplate for function begin/end, and basic block begin/end.
Also ForEachInst is more forgiving of cases where a basic block
doesn't have a label, and when a function doesn't have a defining
or end instruction.
=> IrLoader gracefully handles incomplete blocks and functions

source/opt/module.cpp, source/opt/module.h, test/opt/test_module.cpp
When IDs change, something should use this utility method
and Module::SetIdBound before writing out the binary.
ForEachInst is more forgiving of cases where a basic block doesn't
have a label, and when a function doesn't have a defining instruction
or end instruction.
=> Add Module::ComputeIdBound

source/opt/pass_manager.h, test/opt/CMakeLists.txt, test/opt/module_utils.h, test/opt/test_module.cpp, test/opt/test_pass_manager.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/371
in the sense that the id bound is correct after all the passes
have been run.  But it might be inconsistent between passes.
=> Pass manager recomputes Id bound automatically.

CHANGES, source/opt/CMakeLists.txt, source/opt/constants.h, source/opt/fold_spec_const_op_composite.cpp, source/opt/passes.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/test_fold_spec_const_op_composite.cpp, tools/opt/opt.cpp
For the spec constants defined by OpSpecConstantOp and
OpSpecContantComposite, if all of their operands are constants with
determined values (front-end constants), get the correct values of
the spec constants and re-define them as front-end constants.
In short, this pass replaces all the spec constants with front-end
constants when possible.
Note that this pass does not unify front-end constants. This means it is
possible to have multiple constants defined with same value, due to new
added constant instructions.
=> Fold spec constants to front-end constants

source/opt/CMakeLists.txt, source/opt/unify_const_pass.cpp, source/opt/unify_const_pass.h, test/opt/CMakeLists.txt, test/opt/test_unify_const.cpp, tools/opt/opt.cpp
Unify the constant uses in SPIR-V module. If two constants are defined exactly
the same, only one of them will be kept and all the uses of the removed
constant will be redirected to the kept one.
=> Unify constants pass

README.md, tools/CMakeLists.txt, tools/emacs/50spirv-tools.el, tools/emacs/CMakeLists.txt, utils/check_copyright.py
I've marked this PR as WIP for the moment, since I've not submitted anything to SPIRV-Tools before, have probably mangled something, and it could use a good looking over.  This PR adds automatic spirv-dis and spirv-as support when saving and loading binaries in emacs, per discussion in #359.
Some particulars to note:
- Unlike the other tools, this installs into an absolute path (ignoring CMAKE_INSTALL_PREFIX), since that is the only way it will be found upon emacs startup.  This might be considered intrusive, and the functionality is a bit niche at any rate.  Unclear to me if it's worthwhile in the balance, given it's only useful to emacs users.  That's a choice for SPIRV-Tools maintainers.  It might be a stronger case with a vi version as well, but I don't know how to make that.
- It …
=> add spirv-dis/spirv-as support for emacs when loading .spv binaries

source/util/parse_number.cpp, source/util/parse_number.h, test/ParseNumber.cpp
Returns false if the given string is as nullptr.
=> Guard against nullptr in ParseNumber()

source/opt/set_spec_constant_default_value_pass.cpp, source/opt/set_spec_constant_default_value_pass.h, test/opt/test_set_spec_const_default_value.cpp
Add function `ParseDefaultValuesString()` to build the spec id->default
value string mapping required by `SetSpecConstantDefaultValuePass`.
This CL depends on #390
=> Build "spec id->default val str" mapping from string

CHANGES, source/validate_id.cpp, test/val/Validate.SSA.cpp
Defer removal of a Phi's result id from the undefined-forward-reference
set until after you've scanned the arguments.  The reordering is only
significant for Phi.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/415
=> Fix validator SSA check: Phi can use its own value sometimes

include/spirv-tools/libspirv.h, test/BinaryParse.cpp
It's a valid use case: I might mostly trust my binaries and I don't
care to to collect detailed diagnostic feedback.
=> Clarify: Ok to pass null diagnostic to spvBinaryParse

CHANGES, source/name_mapper.cpp, source/name_mapper.h, test/NameMapper.cpp
Handles only OpDecorate
Does not handle:
- decorations on struct members
- decoration via OpGroupDecorate
=> Make friendly names for built-in variables.

include/spirv-tools/libspirv.h, source/binary.cpp, source/diagnostic.cpp, source/diagnostic.h, source/disassemble.cpp, source/message.h, source/opt/libspirv.cpp, source/opt/libspirv.hpp, source/table.cpp, source/table.h, source/text.cpp, source/text_handler.h, source/val/ValidationState.cpp, source/val/ValidationState.h, source/validate.cpp, source/validate.h, source/validate_id.cpp, test/BinaryParse.cpp, test/BinaryToText.cpp, test/CMakeLists.txt, test/TextLiteral.cpp, test/TextToBinary.cpp, test/c_interface.cpp, test/diagnostic.cpp, test/val/ValidationState.cpp
Every time an event happens in the library that the user should be
aware of, the callback will be invoked.
The existing diagnostic mechanism is hijacked internally by a
callback that creates an diagnostic object each time an event
happens.
=> 1. Callback mechanism for error handling

CMakeLists.txt, source/opt/CMakeLists.txt, source/opt/log.h, test/CMakeLists.txt, test/test_log.cpp
Depends on #401.
Add the following macros for logging purpose:
* `SPIRV_ASSERT`
* `SPIRV_DEBUG`
* `SPIRV_UNIMPLEMENTED`
* `SPIRV_UNREACHABLE`
The last two is always turned on, while the first two can only
be turned on in debug build.
=> 2. Add macros for error and status logging.

source/diagnostic.cpp, source/message.cpp, source/message.h, source/opt/log.h, test/BinaryParse.cpp, test/TextLiteral.cpp, test/c_interface.cpp, test/cpp_interface.cpp, test/test_log.cpp, tools/opt/opt.cpp
This allows us to create C interface with `MessageLevel` later.
=> Change to use enum instead of enum class for MessageLevel.

source/opt/build_module.cpp, source/opt/ir_loader.cpp, source/opt/ir_loader.h, source/opt/log.h, test/opt/test_ir_loader.cpp
* Add methods for getting positions of instructions and operands.
* Add SPIRV_ERROR() macro for returning user errors.
=> Do normal errors instead of asserts in IrLoader

source/message.h, source/opt/pass.h, source/opt/pass_manager.h, test/opt/pass_fixture.h, test/opt/test_def_use.cpp, test/opt/test_ir_loader.cpp, test/opt/test_module.cpp, test/opt/test_type_manager.cpp
There is no difference between the previous `IgnoreMessage()` function
and a null `std::function`, from functionality's perspective.
The user can set `nullptr` as the `MessageConsumer`, so need to guard
against `nullptr` before calling the consumer anyway. It's better
we use it internally so that it may expose problems by us instead
of the user.
=> Use nullptr as the default message consumer to ignore all messages.

tools/opt/opt.cpp
Format:
```
--set-spec-constant-default-value <spec id A>:<default value A> <spec id
B>:<default value B>...
```
Example:
shader: `test.vert`
```
layout(constant_id = 100) const int myint = 10;
layout(constant_id = 101) const int myuint = 100;
layout(constant_id = 200) const float myfloat = 1.25;
layout(constant_id = 201) const double mydouble = 2.34;
void main() {}
```
command line:
```
spirv-opt --set-spec-const-default-value 100:12   101:200 200:1.2323
201:1.2345 test.vert -o output.spv
```
output:
```
...
OpDecorate %7 SpecId 100
OpDecorate %8 SpecId 101
OpDecorate %10 SpecId 200
OpDecorate %12 SpecId 201
%void = OpTypeVoid
%3 = OpTypeFunction %void
%int = OpTypeInt 32 1
%7 = OpSpecConstant %int 12
%8 = OpSpecConstant %int 200
%float = OpTypeFloat 32
%10 = OpSpecConstant %float …
```
=> Command line option for set default value for spec constant

source/message.cpp, test/opt/test_ir_loader.cpp, tools/opt/opt.cpp
EOL should be appended when outputing to streams by the tool.
=> Avoid appending EOL in StringifyMessage().

source/val/BasicBlock.h, source/val/Construct.h, source/validate_cfg.cpp
Example of an error:
spirv-tools/source/validate_cfg.cpp:516:45: error: chosen constructor is
explicit in copy-initialization:
_.current_function().RegisterBlockEnd({}, opcode);
=> Fix compilation errors when building inside Chromium

.gitignore
Modifications to e.g. ``source/opt/build_module.cpp`` are ignored due to the content of .gitignore.
=> Do not gitignore source/opt/build_module.*

source/enum_set.h
Implicit casts from int to bool cause a warning in visual studio.
PTAL
=> enum_set: Fix bool performance warning.

.travis.yml
As of November 2016, the default OSX image is Xcode 7.3.1, which works.
=> Use the default Xcode image on OSX

source/validate_id.cpp, test/val/val_id_test.cpp
It is acceptable for OpAccessChain, OpInBoundsAccessChain,
OpPtrAccessChain, OpInBoundsPtrAccessChain, OpCompositeInsert, and
OpCompositeExtract to not take any indexes as arguments. In such cases,
no indexing will be done on the Base pointer/composite.
=> Fixes issue #532.

source/validate_decorations.cpp, test/val/val_decoration_test.cpp
The Linkage Attributes Decoration cannot be applied to functions
targeted by an OpEntryPoint instruction.
=> Fixes Issue #497

CHANGES, source/val/construct.h, source/validate_cfg.cpp, test/val/val_cfg_test.cpp
If a merge block is reachable, then it must be *strictly* dominated
by its header.  Until now we've allowed the header and the merge
block to be the same.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/551
Also: Use dominates and postdominates methods on BasicBlock to
improve readability.
=> Check strict domination of merge block

source/validate_type_unique.cpp, test/val/val_type_unique_test.cpp
OpTypeRuntimeArray is an aggregate and therefore can have duplicate
declarations.
=> Validator: unique type check allows runtime arrays

test/operand_capabilities_test.cpp
The SPIR-V core grammar file in a recent SPIRV-Headers
applied the fix from Rev 7 of SPV_KHR_16bit_storage:
FPRoundingMode enums are now enabled by the capabilities
introduced by that extension.
Update the SPIRV-Tools tests accordingly.
=> Update capability tests for SPV_KHR_16bit_storage rev 7

CHANGES, source/opt/optimizer.cpp, test/opt/CMakeLists.txt, test/opt/optimizer_test.cpp
Added a test for this too.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/611
=> Optimizer should save the binary when a pass succeeds without changes

CHANGES, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/flatten_decoration_pass.cpp, source/opt/flatten_decoration_pass.h, source/opt/optimizer.cpp, test/opt/CMakeLists.txt, test/opt/flatten_decoration_test.cpp, tools/opt/opt.cpp
Replaces OpDecorationGroup and its uses in OpGroupDecorate and OpMemberDecorate with repeated instances of OpDecorate and OpMemberDecorate.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/602
=> Flatten decoration groups

source/opt/basic_block.h, source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_test.cpp, tools/opt/opt.cpp
Currently the exhaustive inliner is generating invalid SPIR-V when inlining functions with multiple returns. 
This fix will quickly stop generation of invalid SPIR-V by inhibiting inlining of any such functions.
I will follow this up shortly with inlining such functions where no return is in a loop. This is likely the majority of the cases.
=> Inline: Do not inline functions with multiple returns (for now)

source/opt/log.h
Tries to fix https://github.com/KhronosGroup/SPIRV-Tools/issues/642
See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80655
=> Avoid snprintf warning in GCC 7.1

source/cfa.h, source/val/function.cpp
This the final step in leveraging the dominator calculation code from the validator in other parts of spirv-tools, specifically spirv-opt.
CFA continues to be stateless, but pushing data into it in subsequent updates remains a possibility, and is perhaps desirable.
=> CFA: Move TraversalRoots and ComputeAugmentedCFG into CFA

external/CMakeLists.txt
When building with the Google Test framework in the external directory, calling `make install` would also install Google Test and Mock libraries and header files into my system.  This change prevents that.
=> Don't install googletest and googlemock

source/opt/inline_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
Don't stop just after one because of short-circuiting logical-or.
=> Transform multiple entry points

.travis.yml
This gives us shorter testing time since we can use the container
based testing environment, which starts faster. Also using make
means we don't need to install ninja separately.
=> Travis CI: stop requiring sudo and use make instead of ninja

CHANGES, source/opt/instruction.h, test/opt/instruction_test.cpp
Fixes Instruction::ForEachInId so it covers
SPV_OPERAND_TYPE_MEMORY_SEMANTICS_ID and SPV_OPERAND_TYPE_SCOPE_ID.
Future proof a bit by using the common spvIsIdType routine.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/697
=> Include memory and semantics IDs when iterating over inbound IDs

source/comp/markv_codec.cpp
Visual Studio was complaining about possible loss of data on 64-bit builds, due to an implicit cast from `size_t` to `int`. This changes the data to use an int all around.
Since the project is set to treat warnings as errors by default, this means that 64-bit builds of the repo were failing unless the user specifically disabled the `/Werror` flag.
=> Fix Visual Studio size_t cast compiler warning

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, test/opt/local_single_block_elim.cpp
GetPtr now returns the first non-CopyObject in the pointer of a load or store.
=> Opt: Fix handling of CopyObject in GetPtr and its call sites

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_block_elim_pass.h, source/opt/local_ssa_elim_pass.h
Verifies that targeted variables have only access chain or direct
loads and stores as references.
=> Opt: LocalBlockElim: Add HasOnlySupportedRefs

source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_test.cpp
Avoid generating an invalid OpLabel.
Create the continue target for the single-trip loop only if
you actually created the header for the single-trip loop.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/755
=> Inliner: callee can have early return that isn't multi-return

test/operand_capabilities_test.cpp, test/val/val_capability_test.cpp
SPIRV-Headers recently fixed the capability dependency
for SampleMask.  It depends on Shader, not SampleRateShading
=> Updated capabilites for SampleMask

source/util/bit_stream.cpp, test/bit_stream.cpp
Bit stream writer was manifesting incorrect behaviour when the following
two conditions were met:
- writer was on 64-bit word boundary
- WriteBits was invoked with num_bits=0 (can happen when a Huffman codec has only one
value)
The bug was causing very rare sporadic corruption which was detected by
tests after a random experimental change in MARK-V model.
=> Fix encode zero bits on word boundary bug

source/opt/basic_block.cpp, source/opt/basic_block.h, source/opt/inline_pass.cpp, test/opt/inline_test.cpp
First commit:
- Add BasicBlock methods GetMergeInst(), GetLoopMergeInst(), and ctail()
Second commit:  
If the caller block is a single-block loop and inlining will
replace the caller block by several blocks, then:
- The original OpLoopMerge instruction will end up in the *last*
such block.  That's the wrong place to put it.
- Move it back to the end of the first block.
- Update its Continue Target ID to point to the last block
We also have to take care of cases where the inlined code
begins with a structured header block.  In this case
we need to ensure the restored OpLoopMerge does not appear
in the same block as the merge instruction from the callee's
first block.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/787
=> Inline: Fix single-block loop caller cases

source/opt/inline_pass.cpp, test/opt/inline_test.cpp
Otherwise cloned phis can be invalid.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/790
=> Inliner: Remap callee entry block id to single-trip loop header

source/print.cpp
source/print.cpp doesn't compile due to integer conversion.
Tested by @dneto0 on a Windows machine.
=> Fix mingw build (source/print.cpp)

CHANGES, source/opt/inline_pass.cpp, test/opt/inline_test.cpp
This adapts the fix for the single-block loop.  Split the loop like
before.  But when we move the OpLoopMerge back to the loop header,
redirect the continue target only when the original loop was a single
block loop.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/800
=> Inliner: Fix LoopMerge when inline into loop header of multi block loop

source/val/validation_state.cpp, source/val/validation_state.h, source/validate_layout.cpp, test/val/val_layout_test.cpp
Recent spec fix from SPIR Working group:
Allow OpModuleProcessed after debug names, but before any
annotation instructions.
=> validator: OpModuleProcessed allowed in layout section 7c

source/opt/local_ssa_elim_pass.cpp, source/opt/local_ssa_elim_pass.h, test/opt/local_ssa_elim_test.cpp
There can already be OpPhi instructions in a loop header that
are unrelated to the optimization.  We should not be patching those.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/826
=> elim-multi-store: only patch loop header phis that we created

source/validate_logicals.cpp, test/val/val_logicals_test.cpp
OpSelect works with pointers also when capability
VariablePointersStorageBuffer is declared (before worked only with
capability VariablePointers).
=> Validator: fix logicals pass for OpSelect pointers

source/opt/compact_ids_pass.cpp, test/opt/compact_ids_test.cpp
Also update the result type field.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/827
=> Compact-ids pass should update instruction's result_id member

source/diagnostic.cpp, source/diagnostic.h, test/diagnostic_test.cpp
… object
- Take over contents of the expiring message stream
- Prevent the expiring object from emitting anything during destruction
=> DiagnosticStream move ctor moves output duties to new object

CMakeLists.txt
When including this Project as subdirectory, cmake pushes a warning about the CMP0048 Policy. #864
=> Set cmake-policy CMP0048 to NEW

source/opt/CMakeLists.txt, source/opt/fold.cpp, source/opt/fold.h, source/opt/fold_spec_constant_op_and_composite_pass.cpp
There are no functional changes in this patch.  The generic folding
routines in FoldSpecConstantOpAndCompositePass are now inside opt/fold.{cpp,h}.
This code will be used by the upcoming constant propagation pass.  In
time, we'll add more expression folding and simplification into these
two files.
=> Re-factor generic constant folding code out of fold spec constants pass

source/opt/cfg_cleanup_pass.cpp, source/opt/common_uniform_elim_pass.cpp, source/opt/dead_branch_elim_pass.cpp, source/opt/dead_variable_elimination.cpp, source/opt/eliminate_dead_functions_pass.cpp, source/opt/inline_exhaustive_pass.cpp, source/opt/inline_opaque_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, source/opt/mem_pass.h, source/opt/pass.h, source/opt/strength_reduction_pass.cpp
This implements two cleanups suggested by @s-perron
(https://github.com/KhronosGroup/SPIRV-Tools/pull/921):
- Move FindNamedOrDecoratedIds() into MemPass::InitializeProcessing().
- Remove FinalizeNextId(). Always call SetIdBound() from
Pass::TakeNextId().
=> More re-factoring to simplify pass initialization.

source/opt/cfg.cpp, source/opt/cfg.h, source/opt/pass.h
It makes more sense to have the CFG inside the ir name space, as it is
descriptive of the representation.
=> Move class CFG from namespace opt to namespace ir.

.appveyor.yml
Pushing a commit to the master branch will trigger a build on
Appveyor. If the build is successful, the artifacts will be
collected and pushed to GitHub Releases, under the "master-tot"
release.
=> Appveyor: auto deploy build artifacts to GitHub Releases

CMakeLists.txt, source/opt/aggressive_dead_code_elim_pass.h, source/opt/cfg_cleanup_pass.h, source/opt/dead_branch_elim_pass.h, source/opt/dead_variable_elimination.h, source/opt/def_use_manager.cpp, source/opt/def_use_manager.h, source/opt/eliminate_dead_functions_pass.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_access_chain_convert_pass.h, source/opt/local_single_block_elim_pass.h, source/opt/local_single_store_elim_pass.h, source/opt/local_ssa_elim_pass.h, source/opt/mem_pass.cpp, source/opt/pass.cpp
Originally the passes that extended from MemPass were those that are
of the def-use manager.  I am assuming they would be able to preserve
it because of that.
The IRContext relies on the pass to tell it if something is invalidated.
It is possible that the pass lied.  To help identify those situations,
we will check if the valid analyses are correct after each pass.
This will be enabled by default for the debug build, and disabled in the
production build.  It can be disabled in the debug build by adding
"-DSPIRV_CHECK_CONTEXT=OFF" to the cmake command.
This is part of #608.
=> Have all MemPasses preserve the def-use manager.

.appveyor.yml
VS2017 Debug tests should suffice for intresting Debug cases.
This will save us ~30min of waiting time for each build job.
For #959
=> Appveyor: Stop testing VS 2013/2015 Debug

source/link/linker.cpp, source/opcode.cpp, source/opcode.h, source/opt/common_uniform_elim_pass.cpp, source/opt/common_uniform_elim_pass.h, source/opt/dead_branch_elim_pass.cpp, source/opt/dead_variable_elimination.cpp, source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/eliminate_dead_functions_pass.cpp, source/opt/inline_pass.cpp, source/opt/inline_pass.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_access_chain_convert_pass.cpp, source/opt/mem_pass.cpp, source/opt/mem_pass.h, source/opt/pass.h, source/opt/remove_duplicates_pass.cpp, source/opt/remove_duplicates_pass.h, test/opt/ir_context_test.cpp
To make the decoration manger available everywhere, and to reduce the
number of times it needs to be build, I add one the IRContext.
As the same time, I move code that modifies decoration instruction into
the IRContext from mempass and the decoration manager.  This will make
it easier to keep everything up to date.
This should take care of issue #928.
=> Add the decoration manager to the IRContext.

test/opt/ir_context_test.cpp
If SPIRV-Tools is used as an external project and have
googletest being kept in the same directory as it, we
won't have gmock-matchers.h in external/. This will
result in a compilation error.
Use gmock.h instead.
=> Fix hard-coded header path

source/opt/optimizer.cpp
This pass is very useful in reducing the size of the code, and reducing
the amount of work done by other optimizations.
=> Add dead function elimination to -O and -Os

Android.mk, include/spirv-tools/optimizer.hpp, source/opcode.cpp, source/opcode.h, source/opt/CMakeLists.txt, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_redundancy_elimination.cpp, source/opt/local_redundancy_elimination.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/value_number_table.cpp, source/opt/value_number_table.h, test/opt/CMakeLists.txt, test/opt/instruction_test.cpp, test/opt/local_redundancy_elimination_test.cpp, test/opt/value_table_test.cpp, tools/opt/opt.cpp
Creates a pass that removes redundant instructions within the same basic
block.  This will be implemented using a hash based value numbering
algorithm.  This is the first part of the fix for #960.
=> Create a local redundancy elimination pass

source/val/decoration.h
Re-formatted the source tree with the command:
$ /usr/bin/clang-format -style=file -i \
$(find include source tools test utils -name '*.cpp' -or -name '*.h')
This required a fix to source/val/decoration.h.  It was not including
spirv.h, which broke builds when the #include headers were re-ordered by
clang-format.
=> Re-format source tree - NFC.

Android.mk, source/opcode.cpp, source/opcode.h, source/opt/CMakeLists.txt, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/basic_block.h, source/opt/cfg.h, source/opt/instruction.h, source/opt/propagator.cpp, source/opt/propagator.h, test/opt/CMakeLists.txt, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/propagator_test.cpp
_**NOTE: I am adding tests and debugging at the moment.  I'm sending this initial version for review and discussion.  This will be used as the basis for SSA-CCP, copy propagation and range propagation (if we decide to add it).**_
This class implements a generic value propagation algorithm based on the
conditional constant propagation algorithm proposed in
Constant propagation with conditional branches,
Wegman and Zadeck, ACM TOPLAS 13(2):181-210.
The implementation is based on
A Propagation Engine for GCC
Diego Novillo, GCC Summit 2005
http://ols.fedoraproject.org/GCC/Reprints-2005/novillo-Reprint.pdf
The purpose of this implementation is to act as a common framework for any
transformation that needs to propagate values from statements producing new
values to statements using those …
=> Generic value propagation engine.

source/disassemble.cpp, source/print.cpp, source/print.h
Previously we required _PRINT to enable _COLOR, which forbids
outputting colored disassembly into a string in library.
This commit will allow library users to request enabling
ANSI color escape sequences.
=> Support outputting ANSI color escape sequences in library

source/opt/inline_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/mem_pass.cpp
Those are reported as errors by clang 5.0.0, due to the flags -Werror and -Wunused-lambda-capture.
=> Opt: Remove unused lambda captures

.travis.yml
MacOS support in Travis is flakey right now. MacOS build jobs
take a long time to start.
We have extensive checks for Linux and Windows, which should give
us confidence.
=> Travis: mark MacOS builds as optional

CONTRIBUTING.md
github keeps PRs in the refs/pull namespace, so it is a bit simpler to just get a PR directly from there instead of the more convoluted process of getting the user id and branch to review.
For reviewing PR 9999, the flow then becomes:
$ git fetch upstream
$ git checkout pr/9999
The rest remains the same.  The new documentation explains how to do the first time setup and subsequent workflow.
I've tried it with other PRs and it is no different than before.  Just shorter.  I will also try it with this one, once approved.
=> Add simplified instructions for pushing a reviewed PR.

source/opt/def_use_manager.h, source/opt/ir_loader.cpp
I fixed a typo that leaks to the binary and might leak to users.
The typo was found by lintian when I was packaging glslang.
=> Fixed typo that leaked to the binary

source/opt/local_redundancy_elimination.cpp, source/opt/value_number_table.cpp, source/opt/value_number_table.h, test/opt/value_table_test.cpp
Computing the value numbers on demand, as we do now, can lead to
different results depending on the order in which the users asks for
the value numbers.  To make things more stable, we compute them ahead
of time.
The algorithm used is similar to the dominator tree algorithm in [Preston Briggs, Keith D. Cooper, and L. Taylor Simpson. 1997. Value numbering. Softw. Pract. Exper. 27, 6 (June 1997), 701-724.](https://www.cs.rice.edu/~keith/Promo/CRPC-TR94517.pdf.gz).
=> Compute value number when the value table is constructed.

source/link/linker.cpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/basic_block.h, source/opt/common_uniform_elim_pass.cpp, source/opt/common_uniform_elim_pass.h, source/opt/dead_branch_elim_pass.cpp, source/opt/eliminate_dead_constant_pass.cpp, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/opt/insert_extract_elim.cpp, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/instruction_list.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_access_chain_convert_pass.h, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, source/opt/mem_pass.cpp, source/opt/mem_pass.h, source/opt/merge_return_pass.cpp, source/opt/module.cpp, source/opt/remove_duplicates_pass.cpp, source/opt/strength_reduction_pass.cpp, source/opt/unify_const_pass.cpp, test/opt/def_use_test.cpp
The current method of removing an instruction is to call ToNop.  The
problem with this is that it leaves around an instruction that later
passes will look at.  We should just delete the instruction.
First part of #1003.
=> Change IRContext::KillInst to delete instructions.

source/opt/propagator.cpp, source/opt/propagator.h, test/opt/propagator_test.cpp
When I moved the CFG into IRContext
(https://github.com/KhronosGroup/SPIRV-Tools/pull/1019), I forgot to
update SSAPropagator to stop requiring one.
Fixed with this patch.
=> Remove cfg_ field from SSAPropagator class - NFC.

source/opt/mem_pass.cpp
In DCEInst, it is possible that the same instruction ends up in the
queue multiple times, if the same id is used multiple times in the
same instruction.
The solution is to keep the ids in a set, to ensure no duplication in
the list.
Fixes issue #1051
=> DCEInst kill the same instruction twice.

.appveyor.yml
Windows builds are not using CMAKE_BUILD_TYPE.  Fixed with this patch.
=> Fix build type for windows builds

external/CMakeLists.txt, test/CMakeLists.txt
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1057
=> CMake: allow both SPIRV-Headers and spirv-headers

tools/opt/opt.cpp
It's slightly easier to read flags from --help if they're sorted.
I'm starting to think that we want to use a flag parsing library for this.
=> Sort flags in help message - NFC.

source/opt/inline_exhaustive_pass.cpp, test/opt/inline_test.cpp
Currently when inlining a call, the name and decorations for the result of the call is not deleted.  This should be changed.  Just before deleting the basic block that contains the call, we delete the name and decorations for the call.
This fixes issue #622.
=> Kill names and decoration in inlining.

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/local_redundancy_elimination.cpp, source/opt/local_redundancy_elimination.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/redundancy_elimination.cpp, source/opt/redundancy_elimination.h, source/opt/value_number_table.cpp, source/opt/value_number_table.h, test/opt/CMakeLists.txt, test/opt/redundancy_elimination_test.cpp, tools/opt/opt.cpp
Adds a pass that looks for redundant instruction in a function, and
removes them.  The algorithm is a hash table based value numbering
algorithm that traverses the dominator tree.
This pass removes completely redundant instructions, not partially
redundant ones.
This finish issue #960, and #700.
=> Add global redundancy elimination

.gitignore
b93c066b allowed for both SPIRV-Headers and spirv-headers as valid paths, but only the latter is being ignored by Git.
=> Add external/SPIRV-Headers to .gitignore

external/CMakeLists.txt, test/CMakeLists.txt
Work around faulty logic in googletest, where ::testing::Combine
is accidentally disabled for VS 2017.
See https://github.com/google/googletest/issues/1352
=> Force gtest to expose ::testing::Combine

.appveyor.yml
re2 requires VS2015 or later since:
https://github.com/google/re2/commit/97957299d1c9f7617cfe653f344536d733582d9e
=> Appveyor: stop testing on VS 2013

source/opt/inline_exhaustive_pass.cpp, test/opt/inline_test.cpp
Inlining is not setting the parent (function) for each basic block.
This can cause problems for later optimizations.  The solution is to set
the parent for each new block just before it is linked into the
function.
Fixes issue #1083.
=> Set the parent for basic blocks during inlining.

source/opt/local_single_store_elim_pass.cpp
-Os is not smart enough to realize that this variable is actually never used uninitialized.  Added an initializer to help it.
=> Fix uninitialized warning at -Os.

source/validate_image.cpp, test/val/val_image_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1100
@ehsannas had filed an issue against SPIR-V spec, concerning
Image Operands section (3.14):
Sample
A following operand is the sample number of the sample to use. Only
valid with OpImageFetch, OpImageRead, and OpImageWrite.
Relaxing the check to allow OpImageSparseRead and
OpImageSparseFetch to fix failing tests.
=> Image Operand Sample allows sparse image opcodes

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/inline_pass.cpp, source/opt/inline_pass.h, source/opt/ir_context.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/private_to_local_pass.cpp, source/opt/private_to_local_pass.h, source/opt/type_manager.cpp, source/opt/type_manager.h, test/opt/CMakeLists.txt, test/opt/private_to_local_test.cpp, tools/opt/opt.cpp
When a private variable is used in a single function, it can be
converted to a function scope variable in that function.  This adds a
pass that does that.  The pass can be enabled using the option
`--private-to-local`.
This transformation allows other transformations to act on these
variables.
Also moved `FindPointerToType` from the inline class to the type manager.
Fixes issue #1086.
=> Convert private variables to function scope.

include/spirv-tools/optimizer.hpp, source/opcode.cpp, source/opcode.h, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, source/opt/mem_pass.cpp, source/opt/mem_pass.h, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/instruction_test.cpp, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp, test/opt/local_ssa_elim_test.cpp
A few optimizations are updates to handle code that is suppose to be
using the logical addressing mode, but still has variables that contain
pointers as long as the pointer are to opaque objects.  This is called
"relaxed logical addressing".  It applies only to spirv-opt.  spirv-val will
not use the relaxed rules.
|Instruction::GetBaseAddress| will check that pointers that are use meet
the relaxed logical addressing rules.  Optimization that now handle
relaxed logical addressing instead of logical addressing are:
- aggressive dead-code elimination
- local access chain convert
- local store elimination passes.
Some of the work needed for #1096.
=> Allow pointers to pointers in logical addressing mode.

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/ccp_pass.cpp, source/opt/ccp_pass.h, source/opt/constants.cpp, source/opt/constants.h, source/opt/fold.cpp, source/opt/fold.h, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/propagator.cpp, source/opt/propagator.h, test/opt/CMakeLists.txt, test/opt/ccp_test.cpp, test/opt/fold_spec_const_op_composite_test.cpp, tools/opt/opt.cpp
This implements the conditional constant propagation pass proposed in
Constant propagation with conditional branches,
Wegman and Zadeck, ACM TOPLAS 13(2):181-210.
The implementation uses the SSA propagation engine added in #985 and is the final fix needed for #889.
The implementation required several changes in the constant manager.  I believe I should separate those changes into a separate PR.  I'll see about doing this early next week.
The test cases cover all the possible CFG situations the propagator can find itself in.  CCP has the potential of leaving unreachable regions in the CFG (when it simplifies conditionals) and dead code (when it propagates an assignment).
I've scheduled CCP in -O and -Os so that DCE and CFGCleanup run after it.  We'll need to adjust this as we test with …
=> Implement SSA CCP (SSA Conditional Constant Propagation)

utils/generate_grammar_tables.py
One part of this file had indented using tabs. This causes newer
versions of python to complain. This changes the indentation to
consistently use four spaces throughout the file, to be consistent
with the rest of the file and the rest of the project.
=> utils/generate_grammar_tables.py: use spaces for indentation

source/opcode.cpp, source/opcode.h, source/opt/basic_block.h, source/opt/instruction.h, source/opt/propagator.cpp, test/opt/ccp_test.cpp
This fixes issue #1153.
When building CFG edges, edges out of a OpKill and OpUnreachable
instruction should be directed to the CFG's pseudo exit block.
=> Handle execution termination instructions when building edges.

source/opt/basic_block.h, source/opt/dead_branch_elim_pass.cpp
When deleting branches and blocks, also remove them from
the backedges set, in case they were there.
This prevents us from keeping stale pointers to deleted Instruction
objects.  That memory could be used later by another instruction,
incorrectly signaling that something has a backedge reference, and
the dead branch eliminator could end up deleting live blocks.
Adds accessor method ir::BasicBlock::terminator
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1168
=> dead branch elim: Track killed backedges

.gitignore, utils/check_copyright.py
Having that script locally, for example to run check_code_format.sh before sending a pull request, would cause the copyright notices check to fail.
Also add the script to .gitignore.
=> Ignore clang-format-diff.py from copyrights check

source/opt/propagator.cpp, source/opt/propagator.h, test/opt/ccp_test.cpp
This fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1159.  I
had missed a nuance in the original algorithm.  When simulating Phi
instructions, the SSA edges out of a Phi instruction should never be
added to the list of edges to simulate.
Phi instructions can be in SSA def-use cycles with other Phi
instructions.  This was causing the propagator to fall into an infinite
loop when the same def-use edge kept being added to the queue.
The original algorithm in the paper specifically separates the visit of
a Phi instruction vs the visit of a regular instruction.  This fix makes
the implementation match the original algorithm.
=> Fix infinite simulation cycles in SSA propagator.

source/opt/ccp_pass.cpp, source/opt/ccp_pass.h, source/opt/optimizer.cpp, source/opt/propagator.cpp, source/opt/propagator.h, test/opt/ccp_test.cpp
This fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1143.
When an instruction transitions from constant to bottom (varying) in the
lattice, we were telling the propagator that the instruction was
varying, but never updating the actual value in the values table.
This led to incorrect value substitutions at the end of propagation.
=> Fix constant propagation of induction variables.

source/opt/ccp_pass.cpp, source/opt/fold.cpp, source/opt/fold.h, source/opt/instruction.cpp, source/opt/instruction.h
The current folding routines have a very cumbersome interface, make them
harder to use, and not a obvious how to extend.
This change is to create a new interface for the folding routines, and
show how it can be used by calling it from CCP.
This does not make a significant change to the behaviour of CCP.  In
general it should produce the same code as before; however it is
possible that an instruction that takes 32-bit integers as inputs and
the result is not a 32-bit integer or bool will not be folded as before.
Contributes to #1164.
=> Add generic folding function and use in CCP

source/opt/ccp_pass.cpp, source/opt/constants.cpp, source/opt/constants.h, source/opt/instruction.h, test/opt/ccp_test.cpp
The current code expects the users of the constant manager to initialize
it with all of the constants in the module.  The problem is that you do
not want to redo the work multiple times.  So I decided to move that
code to the constructor of the constant manager.  This way it will
always be initialized on first use.
I also removed an assert that expects all constant instructions to be
successfully mapped.  This is because not all OpConstant* instruction
can map to a constant, and neither do the OpSpecConstant* instructions.
The real problem is that an OpConstantComposite can contain a member
that is OpUndef.  I tried to treat OpUndef like OpConstantNull, but this
failed because an OpSpecConstantComposite with an OpUndef cannot be
changed to an OpConstantComposite.  Since I feel this case …
=> Move initialization of the const mgr to the constructor.

source/opt/aggressive_dead_code_elim_pass.cpp
Addresses #1210 
Previous commit 80b743a570a6a616484d9aa9233774fed6cc5463. It removed a check that the user was a branch or conditional branch. Should have been updated to say it was still a "branch" (branch, conditional branch or switch).
=> Fixing missing early exit from break identification

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/workaround1209.cpp, source/opt/workaround1209.h, test/opt/CMakeLists.txt, test/opt/workaround1209_test.cpp, tools/opt/opt.cpp
We have come across a driver bug where and OpUnreachable inside a loop
is causing the shader to go into an infinite loop.  This commit will try
to avoid this bug by turning OpUnreachable instructions that are
contained in a loop into branches to the loop merge block.
This is not added to "-O" and "-Os" because it should only be used if
the driver being targeted has this problem.
Fixes #1209.
=> Create a pass to work around a driver bug related to OpUnreachable.

source/spirv_target_env.cpp, source/spirv_target_env.h, source/validate_image.cpp, test/val/val_image_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1115
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1116
Implemented Vulkan-specific rules:
- OpTypeImage must declare a scalar 32-bit float or 32-bit integer type
for the “Sampled Type”.
- OpSampledImage must only consume an “Image” operand whose type has its
“Sampled” operand set to 1.
=> Added Vulkan-specifc checks to image validation

source/opt/dead_branch_elim_pass.cpp, test/opt/dead_branch_elim_test.cpp
Addresses #1245 
* If the dead branch elim is performed on a module without structured
control flow, the OpSelectionMerge may not be present
* Add a check for pointer validity before dereferencing
* Added a test to catch the bug
=> Fix dereference of possibly nullptr in dead branch elim

source/opt/optimizer.cpp
While it is theoretically possible for SROA to increase the SPIR-V size of a shader, in practice we are seeing the opposite. Over a variety of shaders, adding SROA is not increasing size for any, and over half are seeing reductions in size, many significantly (over 10%) and some as high as 20-30%. The main benefit comes from dead code elimination whose analysis is improved by breaking structs into components.
This fixes #1249. While the benefit for this shader is modest, it exemplifies how SROA simplifies analysis and  allows other passes (eg DeadInsertElim) to operate better.
=> Opt: Add ScalarReplacement to RegisterSizePasses

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/replace_invalid_opc.cpp, source/opt/replace_invalid_opc.h, test/opt/CMakeLists.txt, test/opt/pass_fixture.h, test/opt/replace_invalid_opc_test.cpp, tools/opt/opt.cpp
Creates a pass that will remove instructions that are invalid for the
current shader stage.  For the instruction to be considered for replacement
1) The opcode must be valid for a shader modules.
2) The opcode must be invalid for the current shader stage.
3) All entry points to the module must be for the same shader stage.
4) The function containing the instruction must be reachable from an entry point.
Fixes #1247.
=> Add pass to replace invalid opcodes

source/opt/cfg.cpp, source/opt/cfg.h, source/opt/common_uniform_elim_pass.cpp, source/opt/dead_branch_elim_pass.cpp, source/opt/dominator_tree.cpp, source/opt/inline_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/loop_descriptor.cpp, source/opt/mem_pass.cpp, source/opt/propagator.cpp
This helps VisualStudio 2013 compile the code.
Contributes to #1262
=> Disambiguate between const and nonconst ForEachSuccessorLabel

test/opt/type_manager_test.cpp
Without this fix, the build breaks when the Effcee source is absent or Effcee is not configured to build:
type_manager_test.cpp:682:63: error: ‘GenerateAllTypes’ was not declared in this scope                                                    
std::vector<std::unique_ptr<Type>> types = GenerateAllTypes();
=> Fix test inclusion when Effcee is absent

.appveyor.yml, external/CMakeLists.txt
Disable use of Effcee and RE2 with MSVC compilers older than VisualStudio 2015
since RE2 doesn't support them.
=> Enable Visual Studio 2013 again

source/opt/const_folding_rules.h
This is important when SPIRV-Headers are not checked out to external/
folder and mirrors other places in the code where spirv.h is included.
=> Fix spirv.h include to rely on include paths

source/opt/inline_pass.cpp
There seems to only be a single location where the def-use manager is
used.  It is to get information about a type.  We can do that with the
type manager instead.
Fixes #1285
=> Avoid using the def-use manager during inlining.

source/opt/mem_pass.h
This header file was using the wrong include guard.  NFC.
=> Use proper #include guard in mem-pass.h

source/opt/ccp_pass.cpp, test/opt/ccp_test.cpp
Fixes #1295
* Undef now marked as varying in ccp
* this prevents incorrect meet operations since phis were always not
interesting
* added a test to catch the bug
I'm going to file an issue to catch (and fix) invalid lattice transitions.
=> Mark undef values as varying in ccp.

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/dominator_tree.h, source/opt/ir_builder.h, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_unroller.cpp, source/opt/loop_unroller.h, source/opt/loop_utils.h, source/opt/optimizer.cpp, source/opt/passes.h, test/opt/loop_optimizations/CMakeLists.txt, test/opt/loop_optimizations/unroll_assumptions.cpp, test/opt/loop_optimizations/unroll_simple.cpp, tools/opt/opt.cpp
This patch contains the initial support for loop unrolling in the form of a series of utility classes which perform the actual unrolling. Before performing the optimization we check that the incoming IR meets a series of assumptions made, some of these will be softened in subsequent patches.
The unroller will only unroll code which:
- Has had its induction variable as a phi node (i.e has run through opt::LocalMultiStoreElimPass prior)
- Induction variable is in a canonicalised form with the initial value, final value, and step all being constant integers, and that the step is an OpIAdd and the condition is OpSLessThan.
- That thee are no Phi instructions (other than the induction variable) which are used both inside the loop and outside.
-  That the loop is in the Structured Control Flow …
=> Initial support for loop unrolling

source/opt/if_conversion.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_redundancy_elimination.h, source/opt/private_to_local_pass.h, source/opt/scalar_replacement_pass.h
Adding a map from an id to it set of OpName and OpMemberName
instructions.  This will be used in KillNameAndDecorates to kill the
names for the ids that are being removed.
In my test, the compile time for 50 shaders went from 1m57s to 55s.
This was on linux using the release build.
Fixes #1290.
=> Add id to name map

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
We can fold OpSelect into one of the operands in two cases:
- condition is constant
- both results are the same
Even if the original shader doesn't have either of these, if-conversion
pass sometimes ends up generating instructions like
%7127 = OpSelect %int %3220 %7058 %7058
And this optimization cleans them up.
=> Add folding of redundant OpSelect insns

source/enum_string_mapping.cpp, source/enum_string_mapping.h, source/opt/feature_manager.cpp, source/validate.cpp, source/validate_instruction.cpp, test/enum_string_mapping_test.cpp, utils/generate_grammar_tables.py
unordered_map is not POD. Using it as static may cause problems
when operator new() and operator delete() is customized.
Also changed some function signatures to use const char* instead
of std::string, which will give caller the flexibility to avoid
creating a std::string.
=> Avoid using static unordered_map

CMakeLists.txt
Need to do this in case cmake is not on the path.
This should fix the Android NDK build, as in when building the NDK
itself.
=> Invoke cmake via CMAKE_COMMAND variable

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
I mixed up two cases when folding an OpCompositeExtract that is feed by
and OpCompositeInsert.  The specific cases are demonstracted in the new
test.  I mixed up the conditions for the cases, and treated one like the
other.
Fixes #1323.
=> Fix folding insert feeding extract

source/opt/optimizer.cpp
In some shaders there are a lot of very large and deeply nested
structures.  This creates a lot of work for scalar replacement.  Also,
since commit ca4457b we have been very aggressive as rewriting
variables.  This has causes a large increase in compile time in creating
and then deleting the instructions.
To help low the costs, I want to run a cleanup of some of the easy loads
and stores to remove.  This reduces the number of symbols sroa has to
work on.  It also reduces the amount of code the simplifier has to
simplify because it was not generated by sroa.
To confirm the improvement, I ran numbers on three different sets of
shaders:
Time to run --legalize-hlsl:
Set #1: 55.89s -> 12.0s
Set #2: 1m44s -> 1m40.5s
Set #3: 6.8s -> 5.7s
Time to run -O
Set #1: 18.8s -> 10.9s
Set #2: 5m44s -> …
=> Clean up variables before sroa

include/spirv-tools/optimizer.hpp, source/opt/ir_builder.h, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_unroller.cpp, source/opt/loop_unroller.h, source/opt/loop_utils.h, source/opt/optimizer.cpp, test/opt/loop_optimizations/unroll_assumptions.cpp, test/opt/loop_optimizations/unroll_simple.cpp, tools/opt/opt.cpp
Adds support to unrolls loops with multiple induction variables. The condition remains that the each loop must only be bound by one induction variable.
`for(int i = 0, j =2, k=0; i < 10; ++i, ++j, ++k)`
Would be unrolled, however:
`for(int i = 0, j =2, k=0; i < 10 && k < 10; ++i, ++j, ++k)`
Will not be unrolled.
=> Support for multiple inductions in loop unroller

source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_single_store_elim_pass.h, source/opt/local_ssa_elim_pass.cpp, source/opt/local_ssa_elim_pass.h, source/opt/mem_pass.cpp, source/opt/mem_pass.h, source/opt/optimizer.cpp, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp, test/opt/local_ssa_elim_test.cpp
The algorithm used in DCEInst to remove dead code is very slow.  It is
fine if you only want to remove a small number of instructions, but, if
you need to remove a large number of instructions, then the algorithm in
ADCE is much faster.
This PR removes the calls to DCEInst in the load-store removal passes
and adds a pass of ADCE afterwards.
A number of different iterations of the order of optimization, and I
believe this is the best I could find.
The results I have on 3 sets of shaders are:
Legalization:
Set 1: 5.39 -> 5.01
Set 2: 13.98 -> 8.38
Set 3: 98.00 -> 96.26
Performance passes:
Set 1: 6.90 -> 5.23
Set 2: 10.11 -> 6.62
Set 3: 253.69 -> 253.74
Size reduction passes:
Set 1: 7.16 -> 7.25
Set 2: 17.17 -> 16.81
Set 3: 112.06 -> 107.71
Note that the third set's compile time is large …
=> Remove uses DCEInst and call ADCE

Android.mk
Some tokens are only showing up in the unified1 grammar.
So enum string mappings have to be generated from that grammar, not
the grammar from the (deprecated) include/spirv/1.2 grammar.
Example: capabilities FragmentFullyCovered, Float16ImageAMD
=> Android.mk: Generate enum mappings from unified1 grammar

source/opt/remove_duplicates_pass.cpp, test/opt/pass_remove_duplicates_test.cpp
The merging types we do not remove other information related to the
types.  We simply leave it duplicated, and hope it is removed later.
This is what happens with decorations.  They are removed in the next
phase of remove duplicates.  However, for OpNames that is not the case.
We end up with two different names for the same id, which does not make
sense.
The solution is to remove the names and decorations for the type being
removed instead of rewriting them to refer to the other type.
Note that it is possible that if the first type does not have a name,
then the types will end up with no name.  That is fine because the names
should not have any semantic significance anyway.
The was identified in issue #1372, but this does not fix that issue.
=> Avoid generating duplicate names when merging types

source/opt/block_merge_pass.cpp, source/opt/block_merge_pass.h, source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, source/opt/dead_insert_elim_pass.cpp, source/opt/dead_insert_elim_pass.h, source/opt/insert_extract_elim.cpp, source/opt/insert_extract_elim.h
Remove extension whitelists from transforms that are essentially
combinatorial (and avoiding pointers) or which affect only control flow.
It's very very unlikely an extension will add a new control flow construct.
Remove from:
- dead branch elimination
- dead insertion elimination
- insert extract elimination
- block merge
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1392
=> Remove extension whitelist from some transforms

source/opt/dead_insert_elim_pass.cpp, source/opt/dead_insert_elim_pass.h
Found from an internal shader compiled via DXC. Compile was killed after 150 minutes on windows. With this fix, dead insert elim (and -O) complete in seconds.
Problematic case had many phis with the same incoming value for multiple edges. These phis formed long chains causing significant amounts of repeated work.
Changed the traversal to unique incoming values. Also changed the way visited phis are tracked to avoid numerous inserts and erases.
This should result in no functional changes.
=> NFC: Speed up dead insert phi traversal on Windows.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/common_uniform_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp
Optimizations should work in the presence of recent
SPV_GOOGLE_decorate_string and SPV_GOOGLE_hlsl_functionality1
SPV_GOOGLE_decorate_string:
- Adds operation OpDecorateStringGOOGLE to decorate an object with decorations
having string operands.
SPV_GOOGLE_hlsl_functionality1:
- Adds HlslSemanticGOOGLE, used to decorate an interface variable with
an HLSL semantic string.  Optimizations already preserve those variables
as required because they are interface variables (with uses), independent
of whether they have HLSL decorations.
- Adds HlslCounterBufferGOOGLE, used to associate a buffer with a
counter variable.
Fixes #1391
=> Add recent Google extensions to optimizer whitelists

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/strip_reflect_info_pass.cpp, source/opt/strip_reflect_info_pass.h, test/opt/CMakeLists.txt, test/opt/strip_reflect_info_test.cpp, tools/opt/opt.cpp
Strips reflection info. This is limited to decorations and
decoration instructions related to the SPV_GOOGLE_hlsl_functionality1
extension.
It will remove the OpExtension for SPV_GOOGLE_hlsl_functionality1.
It will also remove the OpExtension for SPV_GOOGLE_decorate_string
if there are no further remaining uses of OpDecorateStringGOOGLE.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1398
=> Add --strip-reflect pass

source/opt/ssa_rewrite_pass.h
VS 2013 does not accept defaulting the move constructor.  This fixes the build problems with it.
=> Fix VS2013 build failures.

source/validate_atomics.cpp, test/val/val_atomics_test.cpp
Atomic instructions must declare a scalar 32-bit integer type for the “Result Type”.
=> Add Vulkan specific atomic result type restriction

test/hex_float_test.cpp
This was caught by UBSan. The given double would overflow
the underlying float, which is undefined. Instead test
with an explicit float::infinity.
=> Replace an undefined double->float cast with infinity.

source/opt/copy_prop_arrays.cpp, source/opt/copy_prop_arrays.h, test/opt/copy_prop_array_test.cpp
When we change the type of an object that gets stored, we do not want to
change the type of the memory location being stored to.  In order to
still be able to do the rewrite, we will decompose and rebuild the
object so it is the type that can be stored.
=> Handle more cases in copy propagate arrays.

source/spirv_target_env.cpp, source/validate_barriers.cpp, test/val/val_barriers_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1427
Adjusting validation to the new rule:
"Before version 1.3, it is only valid to use this instruction with
TessellationControl, GLCompute, or Kernel execution models.
There is no such restriction starting with version 1.3."
Also fixed wrong version numbers in source/spirv_target_env.cpp.
=> WIP New spirv-1.3 rules for control barrier

source/opt/copy_prop_arrays.cpp, source/opt/copy_prop_arrays.h, source/opt/type_manager.cpp, test/opt/copy_prop_array_test.cpp
The first implementation of MemroyObject, which is used in copy
propagate arrays, forced the access chain to be like the access chains
in OpCompositeExtract.  This excluded the possibility of the memory
object from representing an array element that was extracted with a
variable index.   Looking at the code, that restriction is not
neccessary.  I also see some opportunities for doing this in some real
shaders.
Contributes to #1430.
=> Handle non-constant accesses in memory objects (copy prop arrays)

source/opt/copy_prop_arrays.cpp, source/opt/copy_prop_arrays.h, source/opt/optimizer.cpp, test/opt/copy_prop_array_test.cpp
When the original code copies an entire array or struct one element at a
time, this turns into a series of OpCompositeInsert instruction followed
by a store of the whole array.  We currently miss opportunities in copy
propagate arrays because we do not recognize this as a copy.
This commit adds code to copy propagate arrays to identify this code
pattern.
Also updates the performance passed to run array copy propagation.
=> In copy-prop-arrays, indentify copies via OpCompositeInsert

source/opcode.cpp, source/operand.cpp, source/validate_instruction.cpp, utils/generate_grammar_tables.py
Previously we use symbols in spv_target_env as the minimum version
requirements for features. That makes version check implicitly
relies on the order of entries in the spv_target_env enum, which
also contains client APIs. Instead, we should use the standard
scheme for constructing SPIR-V version; and by doing that we can
also map client API entries to universial SPIR-V versions.
=> Use standard SPIR-V version scheme for version requirement

source/opt/private_to_local_pass.cpp, test/opt/private_to_local_test.cpp
OpImageTexelPointer acts like a special kind of load.  It is still
safe to change the storage class of a variable used in a
OpImageTexalPointer instruction.
Contributes to #1445.
=> Teach the private to local about OpImageTexelPointer.

source/opt/copy_prop_arrays.cpp, test/opt/copy_prop_array_test.cpp
OpImageTexelPointer acts like a special kind of load.  It is not an
array load, but it also cannot be removed the same way a regular
load can.  The type of propagation that needs to be done is similar
to what we do for arrays, so I want to merge that code into that
optmization.
Contributers to #1445.
=> Teach array copy propagation about OpImageTexelPointer.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/instruction.cpp, source/opt/mem_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
Currently OpImageTexelPointer operations are treat like a use of the
pointer, but it does
not look for the memory being referenced to make sure stores are not
removed.
This change teaches it so identify the memory being accessed, and
treats it as if that memory is loaded.
Contributes to #1445.
=> Teach ADCE about OpImageTexelPointer

source/opt/copy_prop_arrays.cpp, test/opt/copy_prop_array_test.cpp
Current names and decorations stop us from propagating arrays.  I don't think they should.  Definitely not the name.  Let me know if there are any specific decorations that would.
=> OpName and decorations should not stop array copy prop.

test/val/val_version_test.cpp
Missing tests from #1433
Adding tests for OpenCL 1.2 and embedded profiles
=> Version tests for OpenCL 1.2 and embedded profiles

source/opt/const_folding_rules.cpp, source/opt/constants.cpp, source/opt/constants.h, source/opt/folding_rules.cpp, test/opt/fold_test.cpp
Adding three rules to fold OpDot (implemented as two).
- When an OpDot has two constants, then fold to the resulting const.
- When one of the inputs is the 0 vector, then fold to zero.
- When one of the inputs is a single 1 with 0s, then rewrite to an
OpCompositeExtract of the appropriate element.  This will help find
even more folding opportunities.
Contributes to #709.
=> Fold OpDot

include/spirv-tools/optimizer.hpp, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_peeling.cpp, source/opt/loop_peeling.h, source/opt/loop_utils.cpp, source/opt/loop_utils.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/scalar_analysis.cpp, source/opt/scalar_analysis.h, test/opt/loop_optimizations/CMakeLists.txt, test/opt/loop_optimizations/peeling.cpp, test/opt/loop_optimizations/peeling_pass.cpp, tools/opt/opt.cpp
For each loop in a function, the pass walks the loops from inner to outer most loop
and tries to peel loop for which a certain amount of iteration can be done before or after the loop.
To limit code growth, peeling will not happen if the growth in code size goes above a configurable threshold.
=>  Add a loop peeling pass.

source/opt/pass.cpp, source/opt/pass.h, source/opt/pass_manager.cpp
Many passes contain state information in the pass.  In general, we have not been careful to make sure that state gets reset when the pass is run.  It will also be hard to keep correct in the future.  To fix this problem we will enforce a rule that an instance of a pass can only be run once.
At the same time, we will destroy the passes in the pass manager immediately after they are run.  This way we can reduce the peak memory usage.
=> Don't allow an instance of a pass to be run multiple times.

source/validate_barriers.cpp, test/val/val_barriers_test.cpp
Fixes #1469
* New error that prevents CrossDevice memory scope for all vulkan
* Old error specifically references Vulkan 1.0
* New tests
=> Allow subgroup memory scope for Vulkan 1.1

source/opt/mem_pass.cpp, source/opt/mem_pass.h
Pass a hashtable by const ref instead of by value.  Big impact on
compile time.
Contributes to https://github.com/KhronosGroup/SPIRV-Tools/issues/1328.
=> Change parameter to Mempass::RemovePhiOperands

source/opt/dominator_analysis.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_single_store_elim_pass.h, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp
The local-single-store-elim algorithm is not fundamentally bad.
However, when there are a large number of variables, some of the
maps that are used can become very large.  These large data structures
then take a very long time to be destroyed.  I've seen cases around 40%
if the time.
I've rewritten that algorithm to not use as much memory.  This give a
significant improvement when running a large number of shader through
DXC.
I've also made a small change to local-single-block-elim to delete the
loads that is has replaced.  That way local-single-store-elim will not
have to look at those.  local-single-store-elim now does the same thing.
The time for one set goes from 309s down to 126s.  For another set, the
time goes from 102s down to 88s.
Contributes to …
=> Rewrite local-single-store-elim to not create large data structures.

source/opt/loop_dependence_helpers.cpp
This is needed to fix the Android NDK build.
=> Fix for old XCode: std::set has explicit ctor

Android.mk, include/spirv-tools/optimizer.hpp, source/opcode.cpp, source/opcode.h, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/vector_dce.cpp, source/opt/vector_dce.h, source/util/bit_vector.cpp, source/util/bit_vector.h, source/util/ilist_node.h, test/opt/CMakeLists.txt, test/opt/vector_dce_test.cpp, test/util/CMakeLists.txt, test/util/bit_vector_test.cpp, tools/opt/opt.cpp
Introduce a pass that does a DCE type analysis for vector elements
instead of the whole vector as a single element.
It will then rewrite instructions that are not used with something else.
For example, an instruction whose value are not used, even though it is
referenced, is replaced with an OpUndef.
Contributes to #1511.
=> Vector DCE

source/opt/const_folding_rules.cpp, source/opt/constants.cpp, source/opt/constants.h, source/opt/folding_rules.cpp, test/opt/fold_test.cpp
If one of the operands to an OpVectorTimesScalar instruction is zero,
then the result will be the 0 vector.  Currently we do not fold the
insturction unless both operands are constants.  This change fixes that.
We also allow folding of OpPhi instructions where the incoming values
are either an OpUndef or the OpPhi instruction itself.  As with other
cases, this can be simplified to the OpUndef.
Contributes to #709.
=> Fold OpVectorTimesScalar and OpPhi better.

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
We want to fold code like (x*y)/x and other permutations of this.
Fixes #1531.
=> Fold divide and multiply by same value.

source/opt/if_conversion.cpp, source/opt/if_conversion.h, source/opt/instruction.cpp, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/value_number_table.cpp, source/opt/value_number_table.h, test/opt/if_conversion_test.cpp
When doing if-conversion, we do not currently move code out of the side
nodes.  The reason for this is that it can increase the number of
instructions that get executed because both side nods will have to be
executed now.
In this commit, we add code to move an instruction, and all of the
instructions it depends on, out of a side node and into the header of
the selection construct.  However to keep the cost down, we only do it
when the two values in the OpPhi node compute the same value.  This way
we have to move only one of the instructions and the other becomes
unused most of the time.  So no real extra cost.
Fixes #1526.
=> Allow hoisting code in if-conversion. 

source/opt/const_folding_rules.cpp, source/opt/constants.cpp, source/opt/constants.h, test/opt/fold_test.cpp
An FClamp instruction forces a values to be within a certain interval.
When the upper or lower bound of the FClamp is a constant and the value
being compared with is a constant, then in some case we can fold the
compared because the entire range is say less than the value.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1549.
=> Fold fclamp feeding compare.

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
Currently in scalar replacement, we create a new variable for every
memeber of the composite being divided.  It is often overkill, because
not all of those members will be used.  This change will check which
elements are used and only create variable for the members that are
used.
This reduces the compile time for one set of shader from 248s to 165s.
Part of https://github.com/KhronosGroup/SPIRV-Tools/issues/1494.
=> SROA: Only create symbols that are loaded.

source/validate_builtins.cpp, test/val/val_builtins_test.cpp
SPV_EXT_shader_viewport_index_layer enables using ViewportIndex
and Layer in vertex and tessellation shaders.
Also, as per the Vulkan spec:
> The ViewportIndex decoration must be used only within vertex,
> tessellation evaluation, geometry, and fragment shaders.
> In a vertex, tessellation evaluation, or geometry shader, any
> variable decorated with ViewportIndex must be declared using
> the Output storage class.
> In a fragment shader, any variable decorated with ViewportIndex
> must be declared using the Input storage class.
Similarly for Layer.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1563
=> Allow ViewportIndex & Layer to be used in VS/DS with extension

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp, tools/opt/opt.cpp
Removes the limit on scalar replacement because it has to happen for
legalization.
Part of #1494.
=> Remove the limit on struct size in SROA.

source/opt/copy_prop_arrays.cpp, source/opt/type_manager.cpp, source/opt/type_manager.h, source/opt/types.cpp, source/opt/types.h, test/opt/type_manager_test.cpp, test/opt/types_test.cpp
By using forward pointers, we are able to define a struct that has a
pointer to itself.  This could be directly or indirectly.  The current
implementation of the type manager did not handle this case.  There are
three changes that are made in this commit inorder to handle this case:
1) Change the handling of OpTypeForwardPointer
The current handling of OpTypeForwardsPointer is broken if there is a
reference to the pointer before the real definition.  When build the
type that contain the forward delared pointer, the type manager will ask
for the type for that ID, and will get a nullptr because it does not
exists.  This nullptr is not handleded very well.
The change is to keep track of the incomplete types the first time
through all of the types.  An incomplete type is a ForwardPointer or …
=> Handle types with self references.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/block_merge_pass.cpp, source/opt/block_merge_pass.h, source/opt/ccp_pass.h, source/opt/compact_ids_pass.h, source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, source/opt/dead_insert_elim_pass.h, source/opt/local_single_block_elim_pass.h, source/opt/local_single_store_elim_pass.h, source/opt/private_to_local_pass.cpp, source/opt/private_to_local_pass.h, source/opt/reduce_load_size.h
The following passes are updated to preserve the inst-to-block and
def-use analysies:
private-to-local
aggressive dead-code elimination
dead branch elimination
local-single-block elimination
local-single-store elimination
reduce load size
compact ids (inst-to-block only)
merge block
dead-insert elimination
ccp
The one execption is that compact ids still kills the def-use manager.
This is because it changes so many ids it is faster to kill and rebuild.
Does everything in
https://github.com/KhronosGroup/SPIRV-Tools/issues/1593 except for the
changes to merge return.
=> Preserve inst-to-block and def-use in passes.

source/validate_id.cpp, test/val/val_id_test.cpp
This CL updates the validate_id code to output the name of the object along with
the id number. There were a few instances which already output the name, this
just extends to all of them. Now, the output should say 123[obj] instead of just
123.
Issue #1581
=> [val] Output id names along with numbers in validate_id

test/link/CMakeLists.txt, test/link/global_values_amount_test.cpp, test/opt/dominator_tree/CMakeLists.txt, test/opt/function_utils.h, test/opt/loop_optimizations/CMakeLists.txt, test/opt/loop_optimizations/peeling_pass.cpp, test/val/CMakeLists.txt
Try to reduce the amount of disk space used by especially by debug builds,
which may be contributing to AppVeyor failures.
Collapses tests in categories:
- validator
- loop optimizations
- dominator analysis
- linker
Contributes to #1615
=> Make fewer test executables

source/CMakeLists.txt, source/opt/constants.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_builder.h, source/opt/loop_unswitch_pass.cpp, source/util/small_vector.h, test/util/CMakeLists.txt, test/util/small_vector_test.cpp
We replace the std::vector in the Operand class by a new class that does
a small size optimization.  This helps improve compile time on Windows.
Tested on three sets of shaders.  Trying various values for the small
vector.  The optimal value for the operand class was 2.  However, for
the Instruction class, using an std::vector was optimal.  Size of "0"
means that an std::vector was used.
<table>
<tr>
<td>OperandData Size
</td>
<td colspan="3" >OperandList size
</td>
</tr>
<tr>
<td>
</td>
<td>0
</td>
<td>4
</td>
<td>8
</td>
</tr>
<tr>
<td>0
</td>
<td>489s (baseline)    
</td>
<td>544s
</td>
<td>684s
</td>
</tr>
<tr>
<td>1
</td>
<td>593s    
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>2
</td>
<td>469s
</td>
<td>487s
</td>
<td>
</td>
</tr>
<tr>
<td>4
</td>
<td>473s
</td>
<td>570s
</td>
<td> …
=> Small vector optimization for operands.

source/validate.cpp, test/val/val_data_test.cpp
The DataRule validators call FindDefs with the assumption that they
definitions being looked at can be found. This may not be true if we
have not validated identifiers first.
This CL flips the IdPass and DataRulesPass to fix this issue.
=> Validate Ids before DataRules.

source/validate_decorations.cpp, test/val/val_decoration_test.cpp
This CL reverts the revert of 'Disallow array-of-arrays with DescriptorSets when
validating." Other changes have been committed which should aleviate the
AppVeryor resource constraints.
This reverts commit f2c93c6e124836797311facb8449f9a0b76fefc2.
This CL adds validation to disallow using an array-of-arrays when attached to a
DescriptorSet.
Fixes #1522
=> Reland "Disallow array-of-arrays with DescriptorSets when validating"

source/opt/compact_ids_pass.h, source/opt/ir_context.cpp
During the compact IDs optimization pass, the result IDs of some
basic blocks can change. In spite of this, GetPreservedAnalyses
indicated that the CFG was preserved. But the CFG relies on
the basic blocks having the same IDs. Simply removing this flag
resolves the issue by preventing the CFG check.
However, the CFG retrieval would update the CFG if this bit
is set. So it's not necessary to skip the CFG test even when it
has been changed. So I've removed that early exit too
Addresses https://github.com/KhronosGroup/SPIRV-Tools/issues/1648
=> fix assert during compact IDs pass

source/opt/folding_rules.cpp, source/opt/simplification_pass.cpp, test/opt/fold_test.cpp
When storing an undef, any value is valid, including the one already in
that memory location.  So we can avoid the store.
Part of https://github.com/KhronosGroup/SPIRV-Tools/issues/1631.
=> Remove stores of undef.

source/opt/optimizer.cpp, source/opt/remove_duplicates_pass.cpp, source/opt/remove_duplicates_pass.h, test/opt/pass_remove_duplicates_test.cpp
Fixes #1655.
The change for commit 455186d5ab037c0a659cb50301c9f57ef1313cc6, was not correct, and must expanded to handle more cases or reverted.  The value in running remove duplicates was compile time and code size.  Turning it off does not effect compile time.  So I chose to revert my change and turn off remove duplicates in the -O and -Os paths.  The extra complication of the code is not worth the gains we are not seeing.
=> Revert change and stop running remove duplicates

source/diagnostic.cpp, source/val/basic_block.cpp, source/val/basic_block.h, source/val/validation_state.cpp, source/validate.cpp, source/validate.h, source/validate_cfg.cpp, test/val/val_cfg_test.cpp
This CL fixes up several issues with the diagnostic error line output
in the CFG validation code. For the cases where we can determine a
better line it has been output. For other cases, we removed the
diagnostic line and the error line number from the results.
Fixes #1657
=> Produce better error diagnostics in the CFG validation.

source/val/validation_state.cpp, source/val/validation_state.h, source/validate_datarules.cpp, test/enum_string_mapping_test.cpp, test/text_to_binary.extension_test.cpp, test/val/val_data_test.cpp
- Add asm/dis test for SPV_KHR_8bit_storage
- validator: SPV_KHR_8bit_storage capabilities enable declaration of 8bit int
TODO:
- validator: ban arithmetic on 8bit unless Int8 is enabled
Covered by https://github.com/KhronosGroup/SPIRV-Tools/issues/1595
=> Support SPV_KHR_8bit_storage

source/opt/constants.cpp, source/opt/constants.h, source/opt/fold.cpp, source/opt/ir_context.h, source/opt/private_to_local_pass.cpp, source/opt/scalar_replacement_pass.cpp, source/opt/type_manager.cpp, test/opt/CMakeLists.txt, test/opt/constant_manager_test.cpp, test/opt/private_to_local_test.cpp, test/opt/scalar_replacement_test.cpp, test/opt/type_manager_test.cpp
There are a few locations where we need to handle duplicate types.  We
cannot merge them because they may be needed for reflection.  When this
happens we need do some extra lookups in the type manager.
The specific fixes are:
1) When generating a constant through `GetDefiningInstruction` accept
and use an id for the desired type of the constant.  This will make sure
you get the type that is needed.
2) In Private-to-local, make sure we to update the def-use chains when a
new pointer type is created.
3) In the type manager, make sure that `FindPointerToType` returns a
pointer that points to the given type and not a duplicate type.
4) In scalar replacment, make sure the null constants that are created
are the correct type.
=> Make sure the constant folder get the correct type.

source/opt/fold.cpp, source/opt/fold.h
Just a few changes to pass `std::function` objects by const reference
instead of by value.
=> Fix up code to make ClangTidy happy.

source/val/validation_state.cpp, source/val/validation_state.h, source/validate_decorations.cpp, test/val/val_decoration_test.cpp
Other environments do not.
Add tests for OpenGL 4.5 and SPIR-V universal 1.0 to ensure
they still check monotonic layout.
For universal 1.0, we're assuming it otherwise follows Vulkan
rules for block layout.
Fixes #1685
=> Vulkan permits non-monotonic offsets for block members

source/val/validate_decorations.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_decoration_test.cpp
- Vulkan 1.0 uses strict layout rules
- Vulkan 1.0 with relaxed-block-layout validator option
enforces all rules except for the relaxation of vector
offset.
- Vulkan 1.1 and later always supports relaxed block layout
Add spot check tests for the relaxed-block-layout scenarios.
Fixes #1697
=> Enforce block layout rules even when relaxed

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
In some cases, there will be an OpVectorShuffle instruction feeding another where the end result only uses elements from two of the input vectors.  In those cases, the multiple OpVectorShuffle instructions can replaced by a single instructions.
=> Add folding rule to merge a vector shuffle feeding another one.

source/opt/const_folding_rules.cpp, source/opt/const_folding_rules.h, source/opt/fold.cpp, source/opt/fold.h, source/opt/folding_rules.cpp, source/opt/folding_rules.h, source/opt/ir_context.h
This CL updates the folding rules to receive the IRContext as a paramter
instead of retrieving off of the Instruction.
Issue #1703
=> Pass the IRContext into the folding rules.

source/opt/cfg.cpp, source/opt/dominator_analysis.h, source/opt/dominator_tree.cpp, source/opt/dominator_tree.h, source/opt/function.h, source/opt/ir_context.cpp, source/opt/loop_fusion_pass.cpp, test/opt/dominator_tree/generated.cpp
This CL removes the context() method from opt::Function. In the places
where the context() was used we can retrieve, or provide, the context in
another fashion.
#1703
=> Remove context() method from opt::Function

source/opt/inline_pass.cpp, source/opt/private_to_local_pass.cpp, source/opt/reduce_load_size.cpp
Instead of going through the instruction we can access the context()
directly from the pass.
Issue #1703
=> Cleanup some pass code to get context directly.

source/opt/cfg.cpp, source/opt/cfg.h
This CL removes some unused methods from CFG, makes the constructor
explicit and moves the using statement to the cpp file where it's used.
=> Cleanup CFG header.

source/link/linker.cpp, source/opt/dominator_analysis.h, source/opt/dominator_tree.h, source/opt/function.h, source/opt/ir_context.cpp, source/opt/ir_loader.cpp, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, test/opt/loop_optimizations/lcssa.cpp, test/opt/loop_optimizations/loop_descriptions.cpp, test/opt/loop_optimizations/unroll_simple.cpp
The function class provides a {Set|Get}Parent call in order to provide
the context to the LoopDescriptor methods. This CL removes the module
from Function and provides the needed context directly to LoopDescriptor
on creation.
Issue 1703.
=> Remove the module from opt::Function.

source/opt/folding_rules.cpp, source/val/validate_id.cpp, test/opt/fold_test.cpp
When folding a vector shuffle that feeds another vector shuffle causes
the size of the first operand to change, when other indices have to be
adjusted reletive to the new size.
=> Fix size error when folding vector shuffle.

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
When folding an OpVectorShuffle where the first operand is defined by
an OpVectorShuffle, is unused, and is equal to the second, we end up
with an infinite loop.  This is because we think we change the
instruction, but it does not actually change.  So we keep trying to
folding the same instruction.
This commit fixes up that specific issue.  When the operand is unused,
we replace it with Null.
=> Fix infinite loop while folding OpVectorShuffle

testing/fuzzers/BUILD.gn
This group needs to be wrapped in the if conditional otherwise the deps can't be found.
=> Wrap bin group in conditional for BUILD.gn

source/val/validate_composites.cpp
This Cl splits the CompositePass switch to have one method per case
label. This makes the code a lot simpler to follow.
=> Move CompositePass code into methods.

source/val/validate_composites.cpp, source/val/validate_id.cpp, test/val/val_id_test.cpp
This CL moves the OpVectorShuffle ID check out of validate_id and into
validate_composites with the rest of the composite checks.
=> Move OpVectorShuffle check into validate_composites

source/val/validate_image.cpp, test/val/val_image_test.cpp
This CL splits the switch in ImagePass into individual validate
functions. The error messages have been updated to drop the
suffix/prefix of the opcode name since it will be displayed in the
disassembly.
=> Split ImagePass into individual methods.

source/val/validate_composites.cpp, test/val/val_composites_test.cpp
This CL removes the redundant operator name from the error messages in
validate_composites. The operator will be printed on the next line with
the disassembly.
=> Update error messages in validate_composites.

source/val/validate.cpp, source/val/validate.h, source/val/validate_capability.cpp, source/val/validate_id.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/cpp_interface_test.cpp, test/val/val_ssa_test.cpp
Currently, some instructions will be missing from the list of
ordered_instructions. This will cause issues due to the debug change
which passed the last instruction into subsequent passes.
This CL moves the addition to the ordered list out of the
RegisterInstruction method into AddOrderedInstruction. This method is
called first in ProcessInstruction and the CapabilitiesPass and IdPass
are updated to take an Instruction parameter.
=> Make sure all instructions are in the ordered list.

tools/opt/opt.cpp
Dereference occurred in the wrong spot.
Fixes #1748
=> Fix bug determining next arg

source/val/validate_cfg.cpp, source/val/validate_composites.cpp, source/val/validation_state.cpp, source/val/validation_state.h
This CL changes the signature of diag() to accept an Instruction instead
of the instructions position.
A deprecated variant that accepts the position is available but will be
removed in the near future.
=> Change ValidationState::diag to accept an Instruction.

source/val/validate.cpp, test/val/val_layout_test.cpp
This CL changes validate.cpp to use diag providing an explicit
instruction. This changes the result of the function end checks to not
output a disassembly anymore as printing the last line of the module
didn't seem to make sense.
=> Switch validate to use explicit diag() method.

source/val/validate_adjacency.cpp
Previously the adjacency messages would output the last line of the file
as the disassembly. This is incorrect, as we have an instruction they
can be attached too. This CL fixes the messages to attach to the correct
line number.
=> Fix disassembly line for adjacency validations.

source/val/validate_arithmetics.cpp
This CL updates the diag() calls in validate_arithmetics to explicitly
provide the instruction the diagnostic is attached too.
=> Pass the instruction to diag in arithmetic validation

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
This CL updates the diag() calls in validate_cfg to provide the
associated instruction. This fixes a couple places where we output the
last line of the file instead of the instruction as the disassembly.
=> Update diag() calls in validate_cfg.

source/comp/markv_codec.cpp, source/operand.h, source/spirv_stats.cpp, source/val/validate.cpp, source/val/validation_state.cpp, source/val/validation_state.h
This CL removes the two deque's from ValidationState and converts them
into std::vectors. In order to maintain the stability of instructions we
walk over the binary and counter the instructions and functions in the
ValidationState constructor and reserve the required number of items in
the module_functions_ and ordered_instructions_ vectors.
Issue #1176.
=> Remove std::deque in favour of std::vector.

source/val/validate_literals.cpp
This CL updates the diag() call in validate_literals to provide the
=> Update diag() calls in validate_literals.

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
When creating a new phi for a value in the function, merge return will
rewrite all uses of an id that are no longer dominated by its
definition.  Uses that are not in a basic block, like OpName or
decorations, are not dominated, but they should not be replaced.
Fixes #1736.
=> Don't change decorations and names in merge return.

BUILD.gn
The SPIRV-Tools target doesn't build anything, it just depends on the other libraries. As such, there is no static_library generated and this should be a group() instead.
=> Fixup BUILD.gn to use a group for SPIRV-Tools

source/val/validate_id.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_ssa_test.cpp
This CL removes the two diag() overloads and leaves only the version
which accepts an Instruction. This is safer as we never use the
implicit location from the validation state.
=> Remove diag() overloads.

source/val/instruction.cpp, source/val/instruction.h, source/val/validate.cpp, source/val/validate_id.cpp, source/val/validation_state.cpp, source/val/validation_state.h
The instruction counter is the same as the size of the
ordered_instruction list when we insert a new instruction. This Cl
removes instruction_counter_ and uses that instead.
=>  Remove instruction_counter from ValidationState.

source/opt/basic_block.cpp, source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
In the merge return pass, we will split a block, but not update the phi
instructions that reference the block.  Since the branch in the original
block is now part of the block with the new id, the phi nodes must be
updated.
This commit will change this.
I have also considered other places where an id of a basic block could
be referenced, and I don't think any of them need to change.
1) Branch and merge instructions: These jump to the start of the
original block, and so we want them to jump to the block that uses the
original id.  Nothing needs to change.
2) Names and decorations: I don't think it matters with block keeps the
name, and there are no decorations that apply to basic blocks.
Fixes #1736.
=> Update OpPhi instructions after splitting block.

testing/fuzzers/spvtools_opt_fuzzer.cpp
The spirv-opt fuzzer is not registering any passes to run, so it is not
currently testing anything.  For now we will just register the
performance passes.
We should add different fuzzers for the legalization pass
(RegisterLegalizationPasses()), and the size passes
(RegisterSizePasses()).
=> Register passes in the spirv-opt fuzzer.

source/val/instruction.cpp, source/val/instruction.h, source/val/validate.cpp, source/val/validation_state.cpp
This CL moves most of the logic out of validation ProcessInstruction and
groups it into validate. This places all of the validation logic in the
same place making it clearer what is running.
The Instruction class is changed to allow setting the function and block
after creation.
=> Simplify validation ProcessInstruction

source/val/validate.cpp, test/val/val_layout_test.cpp
When validating a FunctionCall we can trigger an assert if we are not
currently within a function body. This CL adds verification that we are
within a function before attempting to add a function call.
Issue 1789.
=> Validation within function body when doing a FunctionCall.

CMakeLists.txt
The warning should only be applied for Clang builds, it was accidentally
also being included for GCC builds.
=> Fixup Wno-self-assign warning

PRESUBMIT.py, test/link/global_values_amount_test.cpp, test/link/linker_fixture.h, test/opt/decoration_manager_test.cpp, test/opt/pass_remove_duplicates_test.cpp, test/opt/types_test.cpp
This CL removes the un-needed virtual qualifiers from methods already
marked as override.
=> Fixup readabilty/inheritance warnings

source/comp/CMakeLists.txt, source/comp/markv_codec.cpp, source/util/move_to_front.cpp, source/util/move_to_front.h, test/CMakeLists.txt, test/move_to_front_test.cpp
This CL removes the templating from the MoveToFront code as all non-test
code uses uint32_t as the variable.
=> Simplify MoveToFront

source/CMakeLists.txt, test/stats/CMakeLists.txt, test/stats/stats_aggregate_test.cpp, test/stats/stats_analyzer_test.cpp, tools/CMakeLists.txt, tools/stats/spirv_stats.cpp, tools/stats/spirv_stats.h, tools/stats/stats.cpp, tools/stats/stats_analyzer.cpp, tools/stats/stats_analyzer.h
The spirv_stats code is only used by the tools/stats module. This CL
moves the code to that module.
=> Move spirv_stats into tools/stats.

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, tools/opt/opt.cpp
In previous changes, the option `--skip-validation` was disabled.  This
change is to reenable it.
=> Reenable --skip-validation.

source/opt/type_manager.cpp
In `TypeManager::RebuildType`, the base cases call `Clone`, which will
copy the decorations for the type.  After that it breaks out of the
switch statement and copies the decorations again.
This has not causes any real problems yet because none of those types
are allowed to have decorations.  However to make the code more robust
it is best to not copy twice because it should be empty.
This way if a new base type or decoration is added that changes this
rule the code will be correct.
https://crbug.com/873890
=> Don't copy decorations twice when rebuilding a type.

source/opt/local_access_chain_convert_pass.cpp, source/opt/local_access_chain_convert_pass.h, source/opt/local_single_block_elim_pass.cpp, test/opt/local_access_chain_convert_test.cpp, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp
In local-access-chain-convert, we replace loads by load the entire
variable, then doing the extract.  The extract will have the same value
as the load.  However, if the load has a decoration on it, the
decoration is lost because we do not copy any them to the new id.
This is fixed by rewritting the load into the extract and keeping the
same result id.
This change has the effect that we do not call DCEInst on the loads
because the load is not being deleted, but replaced.  This could leave
OpAccessChain instructions around that are not used.  This is not a
problem for -O and -Os.  They run local_single_*_elim passes and then
dead code elimination.  The dce will remove the unused access chains,
and the load elimination passes work even if there are unused access
chains.  I have added test to …
=> Keep decorations when replacing loads in access-chain-convert.

source/val/validate.cpp, source/val/validate_id.cpp, test/val/val_data_test.cpp
When doing the validator checks, an instruction is currently registered
at the end of IdPass.  This creates an inconsistency.  In IdPass, an
instruction that uses its own result will treat that use as a forward
reference.  Then in the following passes it will not because the
definition can be found.
It seems best to update the state after all of the check have been done
for the current instruction.  This makes it consistent for all of the
passes.
This makes a different when trying to verify OpTypeStruct.
Fixes https://crbug.com/874372.
=> Change when instruction is registered in validator.

BUILD.gn
This CL adds a target to build spirv-as through the GN build. Code was added to generate the build-version.inc file as well.
=> Add GN rules to build spriv-as

.gitignore
This is needed for the new python testing harness added in #1802.
=> Ignore *.pyc files in git commands.

source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, test/opt/dead_branch_elim_test.cpp
When dead-branch-elim folds a conditional branch, it also deletes the
OpSelectionMerge instruction.  If that construct contains a
conditional branch to the merge node, it will not have its own
OpSelectionMerge.  When the headers merge instruction is deleted, the
the inner conditional branch will no longer be legal.  It will be a
selection to a node that is not a merge node.
We fix this up by moving the OpSelectionMerge to a new location if it is
still needed.
=> Have dead-branch-elim handle conditional exits from selections.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp
dead code elimination assumes that are conditional branches except for
breaks and continues in loops will have an OpSelectionMerge before them.
That is not true when breaking out of a selection construct.
The fix is to look for breaks in selection constructs in the same place
we look for breaks and continues for loops.
=> Handle breaks from structured-ifs in DCE.

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
In PredicateBlocks, we currently skip instructions with side effects,
but it still follows the same control flow (sort-of).  This causes a
problem, when we are trying to predicate code in a loop.  We skip all
of the code with side effects (IV increment), but still follow the
same control flow (jump back the start of the loop).  This creates an
infinite loop because the code will keep jumping back to the start of
the loop without changing the values that effect the exit condition.
This is a large change to merge-return.  When predicating a block that
is in a loop or merge construct, it will jump to the merge block of the
construct.  Once out of all constructs we will generate code as we did
before.
Fixes #1845.
=> Have PredicateBlocks jump the existing merge blocks.

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
When doing predicate blocks in the merge return pass, we need to traverse every block in
structured order in order to keep track of which construct a block is
contained in.  The standard way of traversing code in structured order
is to create a list with all of the nodes in order.  However, when
predicating blocks, new blocks are created, and those blocks are missed.
This causes branches that go too far.
The solution is to update the order as new blocks are created.  Since
we are using an std::list, we do not have to worry about invalidation of
iterators when changing the list.
=> Update the order when predicating blocks.

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
If seems like at least 1 driver does not like a condition jump to the end
of a selection construct.  We are generating these in the merge return
pass.  This change stops merge return from generating this sequence.
Part of #1861.
=> Don't "break" from selection constructs.

source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/local_access_chain_convert_pass.cpp, source/opt/merge_return_pass.cpp, source/opt/ssa_rewrite_pass.cpp, test/opt/decoration_manager_test.cpp, test/opt/local_access_chain_convert_test.cpp, test/opt/local_ssa_elim_test.cpp, test/opt/pass_merge_return_test.cpp
When creating a new value based on an old value, we need to copy the
decorations to the new id.  This change does this in 3 places:
1) The variable holding the return value of the function generated by
merge return should get decorations from the function.
2) The results of the OpPhi instructions should get decorations from the
variable they are replacing in the ssa writer.
3) In local access chain convert the intermediate struct (result of
OpCompositeInsert) generated for the store replacement should get its
decorations from the variable being stored to.
Fixes #1787.
=> Copy decorations when creating new ids.

source/val/validate_type.cpp, test/val/val_id_test.cpp
In the specification of `OpTypeFunction`, it says
> OpFunction is the only valid use of OpTypeFunction.
This commit add a check in the validator for this rule.  I followed the pattern used in #1834.
A test started to fail because the new check happens before the check
the test case is testing.  Updated the test case to still fail the
check it was suppose to fail originally.
http://crbug.com/874571
=> Validate uses of OpTypeFunction.

source/val/validate_cfg.cpp, source/val/validate_composites.cpp, source/val/validate_id.cpp, test/val/val_composites_test.cpp, test/val/val_id_test.cpp
The validator does not check if the type of an instruction is actually
a type unless the OpCode has a specific requirement.  For example,
OpFAdd is checked, but OpUndef is not.
The commit add a generic check that if there is a type id then the id
defines a type.
http://crbug.com/876694
=> Validate all type ids.

BUILD.gn
This splits the spvtools_config into a public and private part to avoid
leaking internal bits to dependents. A new target is added for the
public headers so that "gn check" works for dependents.
PTAL @dj2
=> BUILD.gn: Make a better interface with dependents.

source/val/validate_image.cpp, test/binary_parse_test.cpp, test/operand_capabilities_test.cpp, test/operand_pattern_test.cpp, test/text_to_binary.extension_test.cpp
Support SPV_KHR_vulkan_memory_model rev2
Support collapsed into one commit:
- Asm/Dis support for SPV_KHR_vulkan_memory_model
- Add Vulkan mem model image operands to switch
- Add TODO for source/validate_image.cpp
- val: Image operands NonPrivateTexelKHR, VolatileTexelKHR have no operands
This is required for memory model tests to pass SPIR-V validation.
- Round trip tests: Test new flags on OpCopyMemory*
Update Dim capabilities
Corresponds to grammar changes for SPIR-V 1.3 Rev4.
=> Update for SPV_KHR_vulkan_memory_model, and grammar changes for SPIR-V 1.3 Rev 4

source/opt/block_merge_pass.cpp, test/opt/block_merge_test.cpp
In merge blocks, we do not allow the merging of two blocks with merge
instructions.  This is because if the two block are merged only 1 of
those instructions can exists.  However, if the successor block is the
merge block of the predecessor, then we can delete the merge instruction
in the predecessor.  In this case, we are able to merge the blocks.
=> Allow merge blocks to merge two header blocks in some cases.

Android.mk, BUILD.gn, source/opt/CMakeLists.txt, source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/CMakeLists.txt, test/opt/dead_branch_elim_test.cpp, test/opt/struct_cfg_analysis_test.cpp
* Create structed cfg analysis.
There are lots of optimization that have to traverse the CFG in a
structured order just because it wants to know which constructs a
basic block in contained in.  This adds extra complexity to these
optimizations, for causes too much refactoring of older optimizations.
To help with this problem, I have written an analysis that can give this
information.
* Identify branches breaking from loops.
Dead branch elimination does a search for a conditional branch to the
end of the current selection construct.  This search assumes that the
only way to leave the construct is through the merge node.  But that is
not true.  The code can jump to the merge node of a loop that contains
the construct.
The search needs to take this into consideration.
=> Fix infinite loop in dead-branch-elimination

source/val/validate_annotation.cpp, source/val/validate_instruction.cpp
We currently register decorations in the first pass through the
instructions.  This is a problem because the validator has not even
checked if the decoration instructions are valid yet.  This can lead to
unexpected behaviour from these side table.  For example, in
https://github.com/KhronosGroup/SPIRV-Tools/issues/1882, we use 5GB of
data to store 1 decoration for ids that are not even defined.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1882.
=> Move the registration of decorations.

source/opt/ir_context.cpp, test/opt/ir_context_test.cpp
It seems like the current implementation of KillNameAndDecorates does
not handle group decorations correctly.  The id being removed is not
removed from the OpGroupDecorate instructions.  Even worst, any
decorations that apply to that group are removed.
The solution is to use the function in the decoration manager that will
remove the decorations and update the instructions instead of doing the
work itself.
Part of #1916.
=> Get KillNameAndDecorates to handle group decorations.

source/opt/optimizer.cpp, test/tools/opt/flags.py
A limit of 0 for the scalar replacement options it used to indicate that
there is no limit.  The current implementation does not allow 0.  This
should be fixed.
=> Allow 0 as argument to scalar replacement.

test/stats/stats_aggregate_test.cpp, tools/stats/spirv_stats.cpp, tools/stats/spirv_stats.h, tools/stats/stats.cpp
Instead of using the source/table.h methods, this CL switches the stats
tool to use the spvtools::Context class and assign the message consumer
through the public API.
=> Remove stats use of internal API

test/binary_parse_test.cpp
This CL removes the use of SetContextMessageConsumer from the
binary_parse_test tests and creates a Context object and uses
SetMessageConsumer instead.
=> Remove use of SetContextMessageConsumer from binary_parse_test

source/opt/basic_block.cpp, source/opt/basic_block.h, source/opt/loop_unroller.cpp, source/opt/loop_unroller.h
Add code to keep the def-use manger and the inst-to-block mapping up-to-date.  This means we do not have to rebuild them later.
To make this work, we will have to have to find places to update the
def-use manager.  Updating the def-use manager is not straight forward
because we are unrolling loops, and we have circular references.
This forces one pass to register all of the definitions.  A second one
to analyze the uses.  Also because there will be references to the new
instructions in the old code, we want to register the definitions of the
new instructions early, so we can update the uses of the older code as
we go along.
The inst-to-block mapping is not too difficult.  It can be done as instructions are created.
Fixes #1928.
=> Keep analyses live in unrolling

source/val/validate.cpp, source/val/validate.h, source/val/validate_memory.cpp
* Rename ValidateMemoryInstructions to MemoryPass
* Changed functions to take pointer to an instruction instead of
reference
This makes the memory instruction validation consistent with other instruction validation.
=> Unify memory instruction validation style

source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, test/opt/decoration_manager_test.cpp, test/opt/ir_context_test.cpp
In DecorationManager::RemoveDecorationsFrom, we do not remove the id
from a decoration group if the group has no decorations.  This causes
problems because KillNamesAndDecorates is suppose to remove all
references to the id, but in this case, there is still a reference.
This is fixed by adding a special case.
Also, there is the possibility of a double free because
RemoveDecorationsFrom will delete the instructions defining |id| when
|id| is a decoration group.  Later, KillInst would later write to memory
that has been deleted when trying to turn it into a Nop.  To fix this,
we will only remove the decorations that use |id| and not its definition
in RemoveDecorationsFrom.
Part of #1916.
=> Handle decoration groups with no decorations.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/block_merge_pass.cpp, source/opt/block_merge_pass.h, source/opt/dead_branch_elim_pass.cpp, source/opt/def_use_manager.cpp, source/opt/loop_unroller.cpp
The def-use manager needs to fill in the `inst_to_used_ids_` field for
every instruction.  This means we have to analyze the uses for every
instruction, even if they do not have any uses.
This mistake was not found earlier because there was a typo in the
equality check for def-use managers.  No new tests are needed.
While looking into this I found redundant work in block merge.  Cleaning
that up at the same time.
=> Analyze uses for all instructions.

source/CMakeLists.txt, source/opt/CMakeLists.txt
cmake builds using MSVC normally get parallelism by building N projects in parallel, with each project using 1-2 CPU cores. But as spirv-tools has grown, it has become a serial bottleneck in CTS and glslang builds. Most other projects depend on it (unclear whether it is a real dependency or artificial) and it gets no parallelism.
Applying /MP (parallelize to N cores) risks using N^2 cores if N projects are doing it. This is intended to be a conservative change that uses a modest number of cores and only in the two libraries with the longest compile times. And N=4 solves 75% of the problem, the rest is diminishing returns ;-)
Some build times from my system:
SPIRV-Tools release build: 8m32s -> 4m57s
glslang release build: 6m59s -> 3m15s
Vulkan CTS release build (rough estimate): 12m -> 10m
=> Enable /MP4 (parallel build across 4 cores for MSVC) for SPIRV-Tools/source[/opt]

source/opt/copy_prop_arrays.cpp, source/opt/copy_prop_arrays.h, source/opt/type_manager.cpp, test/opt/copy_prop_array_test.cpp
There are a few spots where copy propagate arrays is trying
to go from a Type to an id, but the type is not unique.  When generating
code this pass needs specific ids, otherwise we get type mismatches.
However, the ambigous types means we can sometimes get the wrong type
and generate invalid code.
That code has been rewritten to not rely on the type manager, and just
look at the instructions instead.
I have opened https://github.com/KhronosGroup/SPIRV-Tools/issues/1939 to
try to get a way to make this more robust.
=> Fix erroneous uses of the type manager in copy-prop-arrays.

source/val/validate.cpp, source/val/validate.h, source/val/validate_builtins.cpp, source/val/validate_cfg.cpp, source/val/validate_id.cpp, source/val/validate_instruction.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_extensions_test.cpp, test/val/val_state_test.cpp
This commit will change the message for unknown extensions from an error
to a warning.
Code was added to limit the number of warning messages so that consummer
of the messages are not overwhelmed.  This is standard practice in
compilers.
Many other issues were found at while looking into this. They have been
documented in #1950.
Fixes http://crbug.com/875547.
=> Change handling of unknown extentions in validtor.

source/spirv_target_env.cpp, source/spirv_target_env.h, source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp
For OpenCL environments, an atomic operation on a *Pointer* to a **Function** *Storage Class* is valid, but the SPIR-V validator currently flags this as an invalid operation.  This change relaxes the SPIR-V validator for OpenCL environments only to allow atomic operations on *Pointers* to the **Function** *Storage Class*.  There is no change for other environments.
=> allow atomics on Function pointers for OpenCL

source/val/construct.cpp, test/opt/loop_optimizations/fusion_legal.cpp, test/val/val_cfg_test.cpp
Fixes #1960
* Only allows blocks that are dominated by the header
* Fixed a bad loop fusion test
* Added a test derived from the reported bug
=> Fix bug in construct block calculation

source/opt/fold.cpp, test/opt/fold_test.cpp
The current implementation in the folder when seeing a division by zero
is to assert.  In the release build, the compiler will attempt to
compute the value, which causes its own problems.
The solution I will go with is to fold the division, and just give it
the value of 0.  The same goes for remainder and mod operations.
Fixes #1961.
=> Fold divisions by 0.

source/opt/dead_branch_elim_pass.cpp, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, source/opt/optimizer.cpp, source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/pass_merge_return_test.cpp, test/opt/pass_utils.cpp, test/opt/pass_utils.h, test/opt/replace_invalid_opc_test.cpp, test/tools/opt/flags.py
Merge return assumes that the only unreachable blocks are those needed
to keep the structured cfg valid.  Even those must be essentially empty
blocks.
If this is not the case, we get unpredictable behaviour.  This commit
add a check in merge return, and emits an error if it is not the case.
Fixes #1962.
=> Check for unreachable blocks in merge-return.

source/val/validate_mode_setting.cpp, test/val/val_modes_test.cpp
Correponds to the update to Rev2 of SPV_NV_mesh_shader
Fixes #1968
=> Validator: TaskNV can use LocalSize or LocalSizeId

source/opt/CMakeLists.txt, source/opt/pch.cpp, source/opt/pch.h
This reduces build time for spirv-tools-opt by about 45 seconds on my system (after my previous /MP4 change to enable parallelism). This helps a lot with the spirv-tools bottleneck in the Vulkan CTS build.
=> Enable precompiled headers for MSVC for spirv-tools-opt

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp
Was removing control structures which didn't have data dependency
with enclosed live loop and otherwise did not contain live code.
An example is a counting loop around a live loop.
Still need to add regression test.
=> Fix ADCE liveness to include all enclosing control structures. (#1967)

source/val/validate_annotation.cpp, test/val/val_decoration_test.cpp
Fixes https://crbug.com/896200
* Adds a check to validation of OpGroupDecorate that OpDecorationGroup
cannot be targeted
=> OpGroupDecorate may not target OpDecorationGroup

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
We currently run merge-return on all functions, but
dead-branch-elimination only runs on function reachable from an entry
point or exported function.  Since dead-branch-elimination is needed for
merge-return, they have to match.
Fixes #1976.
=> Only run merge-returnon reachable functions.

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
ADCE liveness algorithm should treat OpUnreachable at least like other
branch instructions. It was being treated as always live which was
preventing useless structured constructs from being eliminated.
OpUnreachable is generated by dead branch elimination which is now
being required by merge return, so this fix should accompany that
change.
=> Fix ADCE to treat OpUnreachable correctly during liveness analysis

source/CMakeLists.txt
In CMake, we are not suppose to have multiple targets depend on the same
custom command.  To avoid this, we have to add a custom target around
the command.
=> Add custom target to wrap around custom commands.

CMakeLists.txt
We started hitting this limit, so increaseing from 256 to 1024.
Fixes #1994.
=> Increase the template nesting depth for clang.

source/opt/copy_prop_arrays.cpp, test/opt/copy_prop_array_test.cpp
We are missing a check for a nullptr that is causing things to fail.
Added an extra test case, and fixed up others.
=> Add a nullptr check to array copy propagation.

source/val/validate_conversion.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_conversion_test.cpp
The SPV_KHR_8bit_storage extension does not permit 8-bit integers to be
cast directly to floating point types. We are seeing shaders in the
wild, being produced by toolchains like glslang, that are generating
invalid SPIR-V.
This change adds validation to check for the patterns not permitted, and
some tests that expose the failure.
=> Add validaton for SPV_KHR_8bit_storage + convert to/from floats.

source/opt/CMakeLists.txt
Once the PCH change made it into Vulkan CTS, I ran into a problem where switching between release and debug builds complained about mismatching compile flags in the PCH, because they were inadvertently sharing a PCH file.
This change uses the MSVC builtin macro $(IntDir) (the path intermediate files go to) to select a per-config location for the PCH file.
=> Use per-configuration location for pch file

source/opt/dead_branch_elim_pass.cpp, test/opt/dead_branch_elim_test.cpp
When looking for a break from a selection construct, we do not need to
look inside nested constructs.  However, if a loop header has an
unconditional branch, then we enter the loop.  Entering the loop causes
an infinite loop because we keep going through the loop.
The solution is to look for a merge block, if one exsits, even for block
terminated by an OpBranch.
Fixes #1979.
=> Fix dead branch elim infinite loop.

source/opt/strip_reflect_info_pass.cpp, test/opt/strip_reflect_info_test.cpp
The strip-reflect pass is not removing the reflection decorations that
are decorating members.  With this commit, they will now be removed.
Fixes #2019.
=> Remove MemberDecorateStringGOOGLE during stript-refect.

test/CMakeLists.txt, test/opt/CMakeLists.txt, test/opt/aggressive_dead_code_elim_test.cpp, test/stats/CMakeLists.txt, test/tools/opt/CMakeLists.txt, test/util/CMakeLists.txt
This CL combines a bunch of tests targets into single executables. This reduces the number of build targets and number of test suites to be run in ctest.
=> Reduce number of test targets

include/spirv-tools/libspirv.h, source/spirv_optimizer_options.cpp
When building C code with gcc and the
-Wstrict-prototypes option, function declarations
and definitions that don't specify their argument
types generate warnings.  Functions that don't
take parameters need to specify (void) as their
parameter list, rather than leaving it empty.
Note this only applies to C, so only the functions
exported in C-compatible headers need fixing.  In
C++ functions can't be declared/defined without a
parameter list, so C++ can safely allow an empty
parameter list to imply (void).
=> Add explicit void parameter in libspirv.h again

include/spirv-tools/libspirv.h, source/spirv_validator_options.cpp, source/spirv_validator_options.h, source/val/validate.cpp, test/val/val_limits_test.cpp, tools/opt/opt.cpp, tools/val/val.cpp
Validates that the id bound for the module is not larger than the max id
bound.  Also adds an option to set the max id bound.  Allows the
optimizer option to set the max id bound to also set the id bound for
the validation run done by the optimizer.
Fixes #2030.
=> Validate the id bound.

CMakeLists.txt, source/CMakeLists.txt, source/opt/CMakeLists.txt, test/CMakeLists.txt, test/opt/CMakeLists.txt, test/opt/pch_test_opt.cpp, test/opt/pch_test_opt.h
When trying to pull precompiled header support into glslang I realized that the macro names conflict and since they have slightly different behavior they need to have different names. This PR changes the name to match the naming convention for the other spvtools macros.
Also add pch to test/opt. Not sure how I missed this, or if it was lost in one of the cleanups.
=> Rename PCH macro to spvtools_pch to avoid conflicts with other projects.

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
The Vulkan specification does not permit use of the `VertexId` and `InstanceId` BuiltIn decorations, so add a check to ensure they are not being used when the target environment is Vulkan.
=> Validate that VertexId and InstanceId are not allowed in Vulkan.

source/opt/instruction.cpp, test/opt/instruction_test.cpp
That function currently only handled OpPtrAccessChain if it was in the
middle of the chain, but not at the start.  Fixing that up.
Fixes crbug.com/905271.
=> Instruction::GetBaseAddress to handle OpPtrAccessChain

source/opt/types.cpp
The type manager in spirv-opt currently asserts if a function parameter
has type void.  It is not exactly clear from the spec that this is
disallowed, even if it probably will be disallowed.  In either case,
asserts should be used to verify assumptions that will actually make a
difference to the code.  As far as the optimizer is concerned, a void
parameter does not matter.  I don't see the point of the assert.  I'll
just remove it and let the validator decide whether to accept it or not.
No test was added because it is not clear that it is legal, and should
not force us to accept it in the future unless the spec make it clear
that it is legal.
Fixes crbug.com/903088.
=> Don't assert on void function parameters.

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
When looking for the Volatile mask on a store, the instruction folder
accesses an out-of-bounds element.  We fix that up.
Fixes crbug.com/904027.
=> Fix folding of volatile store.

source/val/validate_memory.cpp, test/val/CMakeLists.txt, test/val/val_builtins_test.cpp, test/val/val_decoration_test.cpp, test/val/val_memory_test.cpp
From the Vulkan 1.1 spec 14.5.2:
Variables identified with the UniformConstant storage class are used
only as handles to refer to opaque resources. Such variables must be
typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, or an array
of one of these types.
Fixes #2008
=> Validate variable types for UniformConstant storage in Vulkan (#2008)

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
Fixes #2046
* Allows InstanceId in the Vulkan environment if MeshShadingNV
capability is specified
=> Allow InstanceId for NV ray tracing

source/opt/instruction.cpp
Was looking for decorations based on opcode. Should use result_id.
=> Fix Instruction::IsFloatingPointFoldingAllowed()

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/function.cpp, source/opt/function.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/process_lines_pass.cpp, source/opt/process_lines_pass.h, source/val/validate_adjacency.cpp, test/opt/CMakeLists.txt, test/opt/process_lines_test.cpp
These are bookend passes designed to help preserve line information
across passes which delete, move and clone instructions. The propagation
pass attaches a debug line instruction to every instruction based on
SPIR-V line propagation rules. It should be performed before optimization.
The redundant line elimination pass eliminates all line instructions
which match the previous line instruction. This pass should be performed
at the end of optimization to reduce physical SPIR-V file size.
=> Add passes to propagate and eliminate redundant line instructions (#2027).

source/val/validate_memory.cpp, test/opt/ir_builder.cpp, test/val/val_id_test.cpp, test/val/val_memory_test.cpp, test/val/val_ssa_test.cpp, test/val/val_storage_test.cpp
From SPIR-V spec, section 3.32.8 on OpVariable:
Its Storage Class operand must be the same as the Storage Class
operand of the result type.
Fixes #941
=> Ensure for OpVariable that result type and storage class operand agree

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Fix min base alignment

test/val/val_id_test.cpp
This covers the data rules for matrix types specified in the SPIR-V
spec, section 2.16.1, and the WebGPU SPIR-V Execution Environment
spec.
Fixes #2065 
Fixes #2080
=> Add tests for matrix type data rule validation

README.md
Both effcee and re2 are now required dependencies, add their checkout in build instructions.
=> Update build instructions: add effcee, re2

source/opcode.cpp, source/opcode.h, source/val/validate_debug.cpp, test/val/val_webgpu_test.cpp
For WebGPU execution environments, check that all of the debug
instructions have already been stripped before validation.
Fixes #2063
=> Validate that debugging instructions are not present for WebGPU

source/val/validate_annotation.cpp, test/val/val_decoration_test.cpp
From the WebGPU SPIR-V Execution Enviroment spec:
OpDecorationGroup, OpGroupDecorate, OpGroupMemberDecorate are not
allowed.
Fixes #2062
=> Check forbidden Annotation instructions for WebGPU env

.gitignore, include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/CMakeLists.txt, source/reduce/CMakeLists.txt, source/reduce/change_operand_reduction_opportunity.cpp, source/reduce/change_operand_reduction_opportunity.h, source/reduce/operand_to_const_reduction_pass.cpp, source/reduce/operand_to_const_reduction_pass.h, source/reduce/reducer.cpp, source/reduce/reducer.h, source/reduce/reduction_opportunity.cpp, source/reduce/reduction_opportunity.h, source/reduce/reduction_pass.cpp, source/reduce/reduction_pass.h, source/reduce/remove_instruction_reduction_opportunity.cpp, source/reduce/remove_instruction_reduction_opportunity.h, source/reduce/remove_unreferenced_instruction_reduction_pass.cpp, source/reduce/remove_unreferenced_instruction_reduction_pass.h, source/spirv_reducer_options.cpp, source/spirv_reducer_options.h, test/CMakeLists.txt, test/reduce/CMakeLists.txt, test/reduce/operand_to_constant_reduction_pass_test.cpp, test/reduce/reduce_test_util.cpp, test/reduce/reduce_test_util.h, test/reduce/reducer_test.cpp, test/reduce/remove_unreferenced_instruction_reduction_pass_test.cpp, tools/CMakeLists.txt, tools/reduce/reduce.cpp
This PR contributes the design of a new tool, spirv-reduce, for shrinking down a SPIR-V binary according to some user-defined "interestingness test" (inspired by the interestingness tests used by C-Reduce).
Currently only a couple of reduction passes are implemented - one that replaces a non-constant operand id with a constant, and another that removes an instruction whose id is not used.
I have re-used infrastructure from spirv-opt where possible, but have not tried to over-unify things; e.g. a reduction pass is fundamentally different from an optimization pass.
=> Initial commit for spirv-reduce.

source/val/validate_instruction.cpp, test/val/val_decoration_test.cpp, test/val/val_id_test.cpp, test/val/val_version_test.cpp, test/val/val_webgpu_test.cpp
Adding validation that the addressing declared by OpMemoryModel is
Logical and the memory model declared is VulkanKHR. Updating a bunch
of tests that were broken by this.
Fixes #2060
=> Ensure correct Addressing and Memory model set for WebGPU

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
For WebGPU environments variables must have the storage class Output,
Private, or Function if they have an initializer.
Fixes #2071
=> Make sure that initialized variable have correct storage class

source/reduce/pch_source_reduce.cpp, source/reduce/pch_source_reduce.h
Trying to generate VS2017 project files, and cmake complains about can't find pch_source_reduce.cpp and .h. Somehow CI systems don't catch this. Maybe because spvtools_pch is only enabled in VS.
This change add these 2 files to fix this problem.
=> Fix the missing pch files in spirv-reduce

source/CMakeLists.txt
```
$ cmake --help-property-list | grep ^VERSION$
VERSION
```
Note: I haven't really ran into any problems because of that, but there's no need to clash with this.
=> Don't use CMake's own property as variable name

source/util/hex_float.h
When we want to set a the value of a HexFloat to inf or nan, we
construct the specific bit pattern in an appropriately sized integer.
That integer is copied to a FloatProxy object through a memcpy.  GCC8
complains about the memcpy because it is overwriting a private member of
the class.
The original solution worked well because the template to the HexFloat
could be anything.  However, we only used some instantiation of FloatProxy,
which has a construction from that takes its uint_type, so I decided to use
that constructor instead of the memcpy.  This puts an extra requirement
on the templace for HexFloat, but it will be fine for us.
Part of #1541.
=> Change HexFloat to work with gcc8.

include/spirv-tools/libspirv.h, source/binary.cpp, source/val/validate.cpp, source/val/validation_state.cpp
Fixes https://crbug.com/906669
* Ensure allocated diagnostics are deleted before losing a reference to
them in the binary parsing
=> Prevent diagnostic memory leak

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
The validation rules for OpArrayLength are not checked by the validator.
This with add them.
Fixes https://crbug.com/907451.
=> Add validation for OpArrayLength.

source/val/validate_capability.cpp, test/val/val_capability_test.cpp, test/val/val_decoration_test.cpp, test/val/val_webgpu_test.cpp
This covers whitelisting Matrix, Shader, Sampled1D, Image1D,
DerivativeControl, and ImageQuery. These are the allowed capabilities
that don't require an extension. Whitelisting VulkanMemoryModelKHR
will be handled by whitelisting its extension in a seperate patch.
Fixes #2101
=> Restrict capabilities to WebGPU spec

source/val/validate_memory.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp, test/opt/local_ssa_elim_test.cpp, test/opt/pass_fixture.h, test/val/val_id_test.cpp
Fixes #2104
* Checks the rules for logical addressing and variable pointers
* Has an out for relaxed logical pointers
* Updated PassFixture to expose validator options
* enabled relaxed logical pointers for some tests
* New validator tests
=> Validate pointer variables

source/val/validate_decorations.cpp, source/val/validate_memory.cpp, test/val/val_decoration_test.cpp, test/val/val_memory_test.cpp
Check that PushConstant OpVariable is identified by Block decoration and type is struct or array of structs.
=> Validate PushConstants annotation and type

source/val/validate_atomics.cpp, source/val/validate_barriers.cpp, source/val/validate_constants.cpp, source/val/validate_scopes.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp
Fixes #2133
* Don't return OpSpecConstant* as constants in that method
* cleaned up uses
* added tests to catch shader semantics and scope bugs
=> Clean uses of EvalInt32IfConst

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/upgrade_memory_model.cpp, source/opt/upgrade_memory_model.h, test/opt/CMakeLists.txt, test/opt/pass_fixture.h, test/opt/upgrade_memory_model_test.cpp, tools/opt/opt.cpp
Updates from Logical GLSL450 memory model to Logical VulkanKHR memory model.
* Adds capability and extension
* changes memory model
* removes coherent and volatile decorations and adds them to individual instructions as operands
* adds output memory semantics to control barriers in tessellation control shaders
* changes device memory scope to queue family scope
=> Update memory model

source/val/validate_id.cpp, test/val/val_arithmetics_test.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp, test/val/val_composites_test.cpp, test/val/val_conversion_test.cpp, test/val/val_derivatives_test.cpp, test/val/val_ext_inst_test.cpp, test/val/val_id_test.cpp, test/val/val_image_test.cpp, test/val/val_memory_test.cpp
Catches many places earlier in validation where type is incorrectly used. #2137 will make the message easier to understand.
Whitelists sets of instructions that can take a type as regular id reference.
=> Strict validation of where type ids are acceptable

source/val/validate_id.cpp, test/val/val_id_test.cpp
For some reason we do not make sure the uses of ids that are defined
in unreachable blocks are dominated by their def.  This is causing
invalid code to pass the validator.
Fixes #2143
=> Validate uses of ids defined in unreachable blocks.

source/val/validate.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/cpp_interface_test.cpp, test/val/val_adjacency_test.cpp, test/val/val_arithmetics_test.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp, test/val/val_cfg_test.cpp, test/val/val_composites_test.cpp, test/val/val_conversion_test.cpp, test/val/val_data_test.cpp, test/val/val_decoration_test.cpp, test/val/val_derivatives_test.cpp, test/val/val_ext_inst_test.cpp, test/val/val_id_test.cpp, test/val/val_image_test.cpp, test/val/val_limits_test.cpp, test/val/val_memory_test.cpp, test/val/val_ssa_test.cpp
This CL changes the id/name output from the validator to always use a
consistent id[%name] style. This removes the need for getIdOrName. The
name lookup is changed to use the NameMapper so the output is consistent
with what the disassembler will produce.
Fixes #2137
=> [val] Fixup id name output

source/val/validate_image.cpp, source/val/validate_memory.cpp, source/val/validate_scopes.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp, test/val/val_image_test.cpp, test/val/val_memory_test.cpp
Disallowed without VulkanMemoryModelDeviceScopeKHR capability. Had to fix a few tests.
Fixes #2147
=> Check device scope for Vulkan memory model

source/opt/fold.cpp, test/opt/fold_test.cpp
We currently simulate all shift operations when the two operand are
constants.  The problem is that if the shift amount is larger than
32, the result is undefined.
I'm changing the folder to return 0 if the shift value is too high.
That way, we will have defined behaviour.
https://crbug.com/910937.
=> Remove undefined behaviour when folding shifts.

source/val/validate_type.cpp, test/val/val_data_test.cpp, test/val/val_id_test.cpp
The validator does not have a a check that OpForwardPointer is giving
a forward reference to a pointer type.  We add that check.
https://crbug.com/910852
=> Validate OpForwardPointer

source/val/validate_decorations.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_decoration_test.cpp
* Only check for binding and descriptor set on variables that are
statically used by an entry point
* updated tests and added a couple new ones
* new method for collecting entry points that statically reference an
id
The new validation state method will be useful for #2151
=> Loosen binding and descriptor check

test/val/val_builtins_test.cpp
Fixes #1545 
This check seems to be already handled in https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validate_builtins.cpp#L2446.
This is an explicit test for such case. Feel free to discard if it doesn't add any value.
=> Test for WorkgroupId not being a uvec3

README.md
There was some confusion about the SPIRV_WERROR option when it is turned
off.  When the option is off nothing is done.  That is, we do not add
-Wno-error.  This means that if the parent project added -Werorr to the
C flags or CXX flags, then warnings will still be treated as errors.
I've updated the README.md to make this explicit.
Fixes #2121.
=> Be more explicit about SPIRV_WERROR option.

source/val/validate_memory_semantics.cpp, test/val/val_atomics_test.cpp
Fail to validate memory semantics value if it includes set bits that
are not on the whitelist from the spec.
Fixes #2070
=> Restrict mask bits for memory semantics in WebGPU

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
When we create a new phi node for a value say %10, we have to replace
all of the uses of %10 that are no longer dominated by the def of %10
by the result id of the new phi.  However, if the use is in a phi node,
it is possible that the bb contains the use is not dominated by either.
In this case, needs to be handled differently.
=> Fix invalid OpPhi generated by merge-return.

test/opt/CMakeLists.txt
MSVC doesn't like building pass_utils.cpp twice in the same folder with different PCH settings.
=> Add PCH_FILE for upgrade_memory_model target

source/reduce/CMakeLists.txt, source/reduce/remove_opname_instruction_reduction_pass.cpp, source/reduce/remove_opname_instruction_reduction_pass.h, test/reduce/CMakeLists.txt, test/reduce/reducer_test.cpp, test/reduce/remove_opname_instruction_reduction_pass_test.cpp, tools/reduce/reduce.cpp
Add a spirv-reduce pass which removes OpName and OpMemberName instructions.
This is useful to enable other reduction passes, e.g. RemoveUnreferencedInstruction may not be able to remove an instruction creating an id whose only usage is an OpName for this id.
=> Add RemoveOpNameInstruction reduction pass

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/ir_context.cpp, test/opt/aggressive_dead_code_elim_test.cpp
If the decoration manager is kept live the the contex will try to keep
it up to date.  ADCE deals with group decorations by changing the
operands in |OpGroupDecorate| instructions directly without informing
the decoration manager.  This puts it in an invalid state, which will
cause an error when the context tries to update it.  To Avoid this
problem, we will invalidate the decoration manager upfront.
At the same time, the decoration manager is now considered when checking
the consistency of the decoration manager.
=> Invalidate the decoration manager at the start of ADCE.

source/val/validate_memory_semantics.cpp, test/val/val_atomics_test.cpp
There is inconsistencies between the different specs about whether or
not this capability is required/allowed, so tooling like glslang
currently ignores it. Once this is resolved the check and test can be
re-enabled.
=> Disable checking that AtomicStorage capability is present

source/opt/reflect.h, source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h, test/opt/ir_builder.cpp, test/opt/type_manager_test.cpp, test/opt/types_test.cpp
This was reported to me as a validation layer crash. The root cause ended up being that validation runs spirv-opt on all shader modules(?!) and the spirv-opt irbuilder was dropping this type instruction because it didn't recognize it.
=> Recognize OpTypeAccelerationStructureNV as a type instruction

source/text_handler.cpp
In the function `AssemblyContext::binaryEncodeString`, we want to copy
a nul terminated string to an instruction.  When coping the string, we
did not copy the nul at the end of the source.  It was added by setting
the entire last word to 0, which is mandated by the spir-v spec.  This
is not a bug, but it does trigger a warning in GCC8 when doing a release
build.
To avoid the warning, we will copy the nul character at the end of the
string too.
Fixes #1541.
=> Avoid GCC8 warning in text_handler.cpp.

source/opt/ssa_rewrite_pass.cpp, test/opt/local_ssa_elim_test.cpp
If there are multiple edges to a basic block, then the ssa rewriter will
create OpPhi instructions with duplicate entries.  This is invalid, and
it is fixed in this commit.
Fixes #2202.
=> SSA-rewriter: make sure phi entries are unique.

source/opt/loop_unswitch_pass.cpp, test/opt/loop_optimizations/unswitch.cpp
Loop unswitching is unswitching the conditional branch that creates the
back-edge. In the version of the loop, where the bachedge is not taken,
there is no back-edge. This is what causes the validator to complain.
The solution I will go with will be to now unswitch a condition with a
back-edge. At this time we do not now if loop unswitching is used. We do
not include it in the optimization sets provided, nor is it used in
glslang's set. When there are opportunities and no breaks from the loop,
the loop with either be a single iteration loop, or an infinite loop.
There is no performance advantage to performing loop unswitching in
either of those cases. If there is a break, maintaining structured
control flow will be tricky. Unless we see a clear advantage to handling
these case, I would go …
=> Don't unswitch the latch block.

source/opt/loop_unswitch_pass.cpp, test/opt/loop_optimizations/unswitch.cpp
Folding branches can have a lot of special cases, and can be a little
error prone.  So I only want it in one place.  That will be in dead
branch elimination.  I will change loop unswitching to set the branches
that were being folded to have a constant condition.  Then subsequent
pass of dead branch elimination will be able to remove the code.
At the same time, I added a check that loop unswitching will not
unswitch a branch with a constant condition.  It is not useful to do it
because dead branch elimination will simple fold the branch anyway.
Also it avoid an infinite loop that would other wise be introduced by my
first change.
Fixes #2203.
=> Don't fold specialized branches in loop unswitch

source/opt/common_uniform_elim_pass.cpp, test/opt/common_uniform_elim_test.cpp
We currently place the load instructions at the start of the basic block
that dominates all of the loads.  If that basic block contains OpPhi
instructions, then this will generate invalid code.  We just need to
search for a location that comes after all of the OpPhi instructions.
Fixes #2204.
=> Place load after OpPhi instructions in block.

source/opt/scalar_replacement_pass.cpp, test/opt/scalar_replacement_test.cpp
We initially assumed that if the type manager returned the correct id
for the pointee type, that we would get the correct pointer type back,
but that is not true.  See the unit test added with this commit.  We
need to fall back to the linear search any time we are looking for a
pointer to a type that may not be unique.
At the same time, SROA considered an OpName on a variable to be a use of
the entire variable.  That has been fixed.
Fixes #2209.
=> Ensure SROA gets the correct pointer type.

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
The function `UpdatePhiNodes` was being called inconsistently.  In one
case, the cfg had already been updated to include the new edge, and in
another place the cfg was not updated.  This caused the function to
miss flagging a block as needing new phi nodes.  I picked that the cfg
should not be updated before making the call.  I documented it, and
change the call sites to match.
Fixes #2207.
=> Fix missing OpPhi after merge return.

source/opt/aggressive_dead_code_elim_pass.h, source/opt/block_merge_pass.h, source/opt/ccp_pass.h, source/opt/cfg_cleanup_pass.h, source/opt/combine_access_chains.h, source/opt/copy_prop_arrays.h, source/opt/dead_branch_elim_pass.h, source/opt/dead_insert_elim_pass.h, source/opt/dead_variable_elimination.h, source/opt/eliminate_dead_functions_pass.h, source/opt/if_conversion.h, source/opt/instrument_pass.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/local_access_chain_convert_pass.h, source/opt/local_redundancy_elimination.h, source/opt/local_single_block_elim_pass.h, source/opt/local_single_store_elim_pass.h, source/opt/local_ssa_elim_pass.h, source/opt/loop_unroller.h, source/opt/merge_return_pass.h, source/opt/private_to_local_pass.h, source/opt/process_lines_pass.h, source/opt/reduce_load_size.h, source/opt/scalar_replacement_pass.h, source/opt/simplification_pass.h, source/opt/strip_reflect_info_pass.h, source/opt/vector_dce.h
Currently it is impossible to invalidate the constnat and type manager.
However, the compact ids pass changes the ids for the types and
constants, which makes them invalid.  This change will make them
analyses that have to been explicitly marked as preserved by passes.
This will allow compact ids to invalidate them.
Fixes #2220.
=> Make the constant and type manager analyses.

test/tools/opt/oconfig.py, tools/opt/opt.cpp
When processing options in a file, it does have access to the
ValidatorOptions and OptimizerOptions object, so options that change
those do not work.  We just need to pass it in.
Fixes #2219.
=> Process moer options when processing options file.

tools/lesspipe/spirv-lesspipe.sh
Its better to allow generic shell for compatible with other distro
=> tools/lesspipe: Allow generic shell

source/opt/vector_dce.cpp, test/opt/vector_dce_test.cpp
In the spec, there it nothing that forces an OpCompositeInsert to have
an index, but VDCE assumes there is at least 1 in a couple places.
This commit updates VDCE to handle these cases.
=> Handle CompositeInsert with no indices in VDCE

source/val/validate_id.cpp, test/val/val_composites_test.cpp, test/val/val_id_test.cpp, test/val/val_memory_test.cpp
Fixes https://crbug.com/911700
* Adds a broader check for when id operands require a type
* updated a few tests
* added a test to catch the original issue
I'm not certain whether this check is too complicated in this location, but it does catch a large class of errors at a single location.
=> Broader check for ids that require a type

source/opt/ir_builder.h, source/opt/upgrade_memory_model.cpp, source/opt/upgrade_memory_model.h, test/opt/CMakeLists.txt, test/opt/pass_fixture.h, test/opt/upgrade_memory_model_test.cpp
Fixes #2138
* Modf and frexp are upgraded to use the struct version of the
instruction and generate an explicit store whose flags can be upgraded
seperately
* Fixed major bug where availability and visibility were reversed for
non-copy memory instructions
* Upgraded all opt tests to use SPV_ENV_UNIVERSAL_1_3
* Started running the upgrade tests
* was missing from CMakeLists.txt and had old define
=> Upgrade modf and frexp

source/opt/fold.cpp, test/opt/fold_test.cpp
In C++, a bit shift of the same size as the type is undefined, but it is
defined in spir-v.  When folding those cases, we have to be careful.  We
cannot simply do the shift in C++.
Fixes https://crbug.com/917697.
=> Fix up bit shifts by 32.

test/binary_parse_test.cpp, test/binary_to_text_test.cpp, test/ext_inst.glsl_test.cpp, test/test_fixture.h, test/val/val_fixtures.h, test/val/val_id_test.cpp
Fixes all but 1 leak in test_spirv_unit_tests
Generally, a test fixture in a method that can generatea a binary
should release any previously cached binary.  Similarly for diagnostics.
=> Fix leaks in tests

source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_unroller.cpp, test/opt/pass_manager_test.cpp, tools/opt/opt.cpp
During unrolling a new loop is created, but its ownership is not clear
as it gets passed through the code.  Changed something to unique_ptr to
make that clearer.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2299.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2296
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2297
=> Fix memory leak in unrolling.

source/opt/fold.cpp, test/opt/fold_test.cpp
When doing (-INT_MIN) is considered overflow, so we cannot fold it by
actually performing the negation.
Fixes https://crbug.com/917991
=> Fix overflow when negating INT_MIN.

source/opt/scalar_replacement_pass.cpp, test/opt/scalar_replacement_test.cpp
It is legal, but not generated by any SPIR-V producer: an OpAccessChain
with no indexes.  This is essentially just a copy of the pointer.
I have decided to treat it like an OpCopyObject.  In CheckUses, we
return that it is not okay.
When looking at this I realized that we had code in GetUsedComponents
that cannot be reached.  If there is a use in an OpCopyObject the it
will not call GetUsedComponents.  I removed that dead code.
Fixes https://crbug.com/918311.
=> Handle access chain with no index in SROA.

source/opt/vector_dce.cpp, source/opt/vector_dce.h, test/opt/vector_dce_test.cpp
It is legal, but not generated by any SPIR-V producer: an OpCompositeExtract
with no indexes.  This is essentially just a copy of the object, so we
treat them that way.  We simply propagate the live variables of the
result to the operand.
Fixes https://crbug.com/919181.
=> Handle extract with no index in VDCE.

source/opt/code_sink.cpp, test/opt/code_sink_test.cpp
When looking at the uses of the result of an instruction, code sinking
assumes that all uses are in a basic block.  However, this is not true
if there is a decoration or name for the result of that insturction.
This commit checks for this.
Fixes https://crbug.com/923243.
=> Handle instructions not in blocks in code sinking.

source/val/validate_datarules.cpp, test/val/val_data_test.cpp
In a recent PR, we allowed a forward reference for the element type in
an array declaration.  However, we do not have other check to make sure
the forward reference is a pointer type first reference in
OpTypeForawrdPointer.  We add that check.
Fixes https://crbug.com/920074.
=> Check forward reference in OpTypeArray.

source/opt/ir_context.cpp
Invalidate ConstantsManager when invalidating TypeManager since ConstantsManager contains pointers into TypeManager. But... also need to also remove Constants from the valid_analyses set when
invalidating, otherwise Constants is not reinitialized before used the next time.
Note that #2303 does not create a new bug. It just makes a partial (and thus ineffective) fix. It deletes an invalid ConstantsManager but then doesn't remove it from the valid_analyses set, so it doesn't get reinitialized before use, so following passes still get a bad ConstantsManager, although empty rather than invalid.
=> Fix Constants Analyses bug inserted by #2302

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
This has a formatting fix for #2310
=> Fix layout checks for nested struct in relaxed layout; and descriptor arrays

include/spirv-tools/libspirv.hpp, source/libspirv.cpp
Add a method to determine if a SpirvTools object was successfully
constructed and can be used.  It might not be depending on the parameter
to the constructor.
This is something a fuzzer wants to know before trying to use an
SpirvTools object constructed with a fuzzed parameter.
=> Add SpirvTools::IsValid().

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
=> spirv-val: Emit an error when an OpSwitch target is not an OpLabel

source/val/validate_decorations.cpp
There are a few data structures in the function
`CheckDecorationsCompatibility` that are allocated using `new` and their
address is stored in a static pointer.  This code pattern causes the
MSVC memory leak checker to say there is a memory leak.  Some people
are interested in keeping that clean.
To work around it, I have replaced them with either a function or an
array of POD types.  The array can be kept as a static directly because
it has a trivial destructor, and we don't have to worry about it being
destroyed too early.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2317.
=> Remove the static maps from CheckDecorationsCompatibility

source/opt/optimizer.cpp
Community feedback says it is not generaly benificial, so we will remove
it from the standard optimization set.
=> Remove code sinking for -O.

source/val/validate_decorations.cpp, source/val/validate_type.cpp, source/val/validation_state.h, test/val/val_capability_test.cpp, test/val/val_decoration_test.cpp
Also permit NonWritable on members of structs used for UBO and SSBO.
(That seems inadvertently removed in recent revisions of the spec.)
=> Validate NonWritable decoration

source/val/validate_function.cpp, test/val/CMakeLists.txt, test/val/val_function_test.cpp, test/val/val_id_test.cpp
Fixes #2105 
Checks rules from 2.16.1. Validates storage class and memory object declaration-ness.
=> Validate variable pointer related function call rules

source/val/validate_type.cpp, test/val/val_decoration_test.cpp
Fixes #2354
* Storage image pointer registration allows optional level of arraying
* Added a test
FYI @alegal-arm
=> Allow arrayed storage images for NonWritable decoration

include/spirv-tools/libspirv.h, source/opt/optimizer.cpp, source/spirv_target_env.h
This CL moves the method to parse the SPIRV environment into the public headers. This will allow other applications to re-use the same parsing logic.
=> Make spvParseTargetEnv public

source/opt/block_merge_util.cpp, test/opt/block_merge_test.cpp
Fixes #2374
* Block merging no longer merges unreachable blocks into their
successors
* added a test
Doesn't use `Dominates` because the blocks are unreachable.
=> Don't merge unreachable blocks

BUILD.gn
extensions_enum.inc is included from source/table.h.
So spvtools_core_enums_unified1 target generating the header should be in public_deps of
spvtools target.
See reference for more detail of rule.
https://gn.googlesource.com/gn/+/master/docs/reference.md#var_public_deps
This is for crbug.com/931596
=> Fix BUILD.gn

source/val/validate.cpp, source/val/validate_decorations.cpp, source/val/validate_function.cpp, source/val/validate_type.cpp
This is required to properly handle uses of forward declared ids. Since forward
declared ids were not being properly covered by the validator this uncovered a
bunch of small issues that needed to be resolved to get tests passing again.
This needs to be in its own loop because some of the checks in the later loop depend on all of the usage information being calculated.
Fixes #2373
=> Move usage detection to after all instructions are registered

BUILD.gn
The prior GoogleTest integration was incomplete and produced errors
when building with 'gn check' enabled. Fix this by scoping the test
integration to Chromium.
Fixes Issue #2382 
@dj2 PTAL
=> BUILD.gn: Only build tests in Chromium.

source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp
=>  OpAtomicLoad, OpAtomicStore, OpAtomicExchange can operate on int or float value. Except for Vulkan environment that only operates on int value.

source/opt/eliminate_dead_members_pass.cpp, source/opt/eliminate_dead_members_pass.h, test/opt/eliminate_dead_member_test.cpp
The types of input and output variables must match for the pipeline.  We
cannot see the uses in all of the shader, so dead member
elimination cannot safely change the type of input and output variables.
=> Don't change type of input and output var in dead member elim

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
The code that folds OpDot does not handle half floats correctly.  After
trying to multiple the first components, we get a nullptr because we
don't fold half float values.  This nullptr gets passed to the code that
does the addition, and causes an assert.
Fixes #2405.
=> Fix OpDot folding of half float vectors.

source/val/validate_decorations.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/val/val_decoration_test.cpp
=> It is invalid to apply both Restrict and Aliased to the same <id>

CMakeLists.txt, source/val/validate_function.cpp, test/val/val_id_test.cpp
In relaxed addressing mode, we want to accept non memory objects
because this is a very natural translation of hlsl.  It should be fixed
by legalization by inlining the calls.
A sample hlsl code that generates this code pattern is:
```
struct S {
float fn_1() { return 0.0; }
};
struct T {
S s;
};
float main() : A {
T t;
t.s.fn_1();
return 0.0;
}
➜  dxc cat t.hlsl
struct S {
float fn_1() { return 0.0; }
};
struct T {
S s;
};
float main() : A {
T t;
t.s.fn_1();
return 0.0;
}
```
=> Non memory object as parameters.

source/CMakeLists.txt
On CentOS6.8 with a local build of g++ 6.4.0 (the default g++ version on CentOS6.8 is 4.4.7), the build fails with undefined reference to 'clock_gettime'.
Linking ${SPIRV_TOOLS} and ${SPIRV_TOOLS}-shared against the rt library fixed the issue.
=> Fixed undefined reference to 'clock_gettime' by linking rt library

source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, test/opt/dead_branch_elim_test.cpp
Loop header must have exactly one back edge.  Sometimes the branch
with the back edge can be folded.  However, it should not be folded
if it removes the back edge.
The code to check this simply avoids folding the branch in the
continue block.  That needs to be changed to not fold the back edge,
wherever it is.
At the same time, the branch can be folded if it folds to a branch to
the header, because the back edge will still exist.
Fixes #2391.
=> Handle back edges better in dead branch elim.

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
It should be allowed for the `NonWritable` decoration to be applied to
structure type members.
=> Allow NonWritable to target struct members.

test/val/val_cfg_test.cpp
Test to check case when two loops name the same continue target.
=> Add a test for two back-edges in a continue

source/opt/ccp_pass.cpp, test/opt/ccp_test.cpp
In constant propagation, decoration are transfered from the original
expression to the constant that will replace it.  This can be wrong
because there are no decorations that apply to constants.  We choose to
simply delete the decorations.
Fixes #2441
=> Removing decorations when doing constant propagation.

source/val/validate_function.cpp, test/val/val_storage_test.cpp
DXC changed its policy and now, for variables with Workgroup Storage
Class, DXC passes it directly to functions instead of creating
temporal variables with Function Storage Class.
If relax-logical-pointer is enabled, Validator must consider
variables whose pointer types are the same except Storage Class
as variables with the same type.
Related to #2423
=> Validator: no Storage comparison for pointer param

source/val/validate_function.cpp, test/val/val_function_test.cpp
Fixes #2447
* Allow sub-objects for UniformConstant storage class
* Updated tests
=> Relax function call parameter check

test/val/val_decoration_test.cpp
Fixes two things:
- struct needed layout decorations.  It never had them
- use Block decoration, rather than BufferBlock that was removed in
#2380
=> Repair test for unused storage buffer with descriptor

include/spirv-tools/instrument.hpp, include/spirv-tools/optimizer.hpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, source/opt/instrument_pass.cpp, source/opt/instrument_pass.h, source/opt/optimizer.cpp, test/opt/inst_bindless_check_test.cpp
If SPV_EXT_descriptor_indexing is enabled, add check that for every
descriptor-based reference, the descriptor is initialized. Initialization
data is stored in the debug input buffer, added to the length information
already there. This feature must be separately enabled on the pass
creation routine.
=> Bindless Validation: Descriptor Initialization Check

source/val/validate_image.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_image_test.cpp
Changing the stored value for a sampled image consumer to be the
instruction instead of result ID, since not all instructions have
result IDs. Using result IDs led to a potential crash when using
OpReturnValue, which doesn't have a result ID. OpReturnValue is not a
legal consumer, but the validator needs to look at the instruction to
determine this, thus storing the pointer to the instruction, instead
of trying to fetch the pointer using the instruction.
Issue #1528 covers fixing the check.
Fixes #2463
=> Convert sampled consumers to being Instructions instead of IDs

source/reduce/reducer.cpp, source/reduce/reducer.h, test/reduce/reducer_test.cpp, test/reduce/validation_during_reduction_test.cpp, tools/reduce/reduce.cpp
Fix #2396 
* Change Reducer::Run to *not* immediately copy the input binary.
* Check that initial shader is valid.
* Fix RemoveOpnameAndRemoveUnreferenced test; turns out the original shader is invalid, but we never notice because we don't check this and the reduced shader is valid; fix original shader. Assert reduction status is kComplete.
* Always check return value from `Reducer::Run`.
=> Add some val options to reduce

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/reduce/reducer.cpp, source/reduce/reducer.h, source/reduce/reduction_pass.cpp, source/reduce/reduction_pass.h, source/spirv_reducer_options.cpp, source/spirv_reducer_options.h, test/reduce/reduce_test_util.cpp, test/reduce/reduce_test_util.h, test/reduce/reducer_test.cpp, test/reduce/remove_unreferenced_instruction_test.cpp, test/reduce/validation_during_reduction_test.cpp, tools/reduce/reduce.cpp
Fix #2475. Fix #2476. 
* Improve reducer algorithm: shrink granularity, remove an early return, no lazy initialization, notify pass if binary is interesting, add comments.
* Add fail-on-validation-error option to fail a reduction if an invalid state is reached; useful for tests.
* Set fail-on-validation-error in tests.
* Improve some documentation comments.
* Add Reducer::AddDefaultReductionPasses so tests (and other library consumers) can add the default reduction passes.
* Add CLIMessageConsumer in test_reduce so we can see messages for tricky tests.
* Remove test RemoveUnreferencedInstructionReductionPassTest_ApplyReduction because it was indirectly testing the reduction algorithm, not the RemoveUnreferencedInstruction pass.
* Tweak tests where needed.
=> Improve reducer algorithm and other changes

source/reduce/structured_loop_to_selection_reduction_opportunity.cpp, test/reduce/structured_loop_to_selection_test.cpp
Fix #2457.
`StructuredLoopToSelectionReductionOpportunity::FixNonDominatedIdUses` considers every instruction in the function being modified and tries to fix dominance by checking the dominance of all uses. Unfortunately, some of these "uses" can be OpDecorate instructions that are outside of blocks, which causes a segfault.
=> reduce: fix loop to selection dominance query

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, source/opt/pass_manager.cpp, source/opt/pass_manager.h, tools/opt/opt.cpp
* New command-line option to opt: --validate-after-all
* Pass manager will validate after each pass it runs
Errors look like:
```
error: line 109: ID 54[%54] defined in block 43[%43] does not dominate its use in block 68[%68]
%68 = OpLabel
error: line 0: Validation failed after pass merge-return
```
=> Add option to validate after each pass

source/opt/struct_cfg_analysis.cpp, test/opt/struct_cfg_analysis_test.cpp
Fixes #2451
* Structured cfg analysis now handles functions with no basic blocks
* Added a test
=> Handle function decls in Structured CFG analysis

source/opt/basic_block.cpp, source/opt/basic_block.h, source/reduce/structured_loop_to_selection_reduction_opportunity.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity_finder.cpp, test/reduce/structured_loop_to_selection_test.cpp
* Fix #2478. Note that the fix is to just not try to simplify such loops, but we plan to add additional loop simplification passes soon that will simplify such loops. 
* Also added `BasicBlock::MergeBlockId()` and `BasicBlock::ContinueBlockId()`. 
* Some minor changes to `structured_loop_to_selection_reduction_opportunity.cpp`. 
* Added test.
=> reduce: fix loop to selection pass for loops with combined header/continue block

source/val/validate_cfg.cpp, test/opt/block_merge_test.cpp, test/opt/inline_test.cpp, test/val/val_cfg_test.cpp, test/val/val_id_test.cpp, test/val/val_validation_state_test.cpp
* Adds a validator check that ensures no block reachable from the entry
block is terminated by OpUnreachable
* Updated tests
* Added new tests
This came about from #2456. Adds a better error than what the validator caught for that case.
=> Validate that OpUnreacahble is not statically reachable

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
Fixes #2455
* Properly maintains instruction to block mapping for newly created phi
instructions in merge return
* adds a test
Unfortunately I was unable to reduce the testcase.
=> Maintain inst to block mapping in merge return

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
Fixes #2453
* Enable addition of OpPhi instructions when the loop has multiple
predecessors of the merge due to a break
* This can result in some values no longer dominating their uses
* Track return blocks in structured flow to produce OpPhis that have
multiple undef and non-undef arguments
* New tests to catch the bug
=> Fix merge return in the face of breaks

source/val/construct.cpp, test/val/val_cfg_test.cpp
Fixes #2488
* Validator doesn't identify back-edge of the loop, so the merge is
never set
* Construct::blocks() has safe uses of `merge` so the assert can be
removed
* Added a test
=> Remove merge assert in block calculation

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/common_uniform_elim_pass.cpp, source/opt/instruction.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/common_uniform_elim_test.cpp, test/opt/local_access_chain_convert_test.cpp, test/opt/local_single_block_elim.cpp, test/opt/local_single_store_elim_test.cpp, test/opt/local_ssa_elim_test.cpp
* Check var ptr capability for common uniform.
* Check var ptr capability in access chain convert.
Since we want this pass to run even if there are variable pointer on
storage buffers, we had to remove asserts that assumed there were no
variable pointers.  The functions with the asserts will now work, it
becomes the responsibility of the callers to deal with the output as
appropriate.
* Single block elimination and variable pointers.
It seems like the code in local single block elimination is able to
handle cases with variable pointers already.  This is because the
function `HasOnlySupportedRefs` ensures that variables that feed a
variable pointer are not candidates.
* Single store elimination and variable pointers.
It seems like the code in local single stroe elimination is able to …
=> Handle variable pointer in some optimizations

BUILD.gn
A .h file was specified as .hpp file, causing `gn gen path/ --check` to
fail.
=> Fix webgpu header file name in BUILD.gn

source/opt/ir_loader.cpp, source/opt/optimizer.cpp
Currently, if spirv-opt encounters an unknown instruction, it will drop it on the floor. This behavior can lead to crashes since the output might very well be invalid SPIR-V (see #2190 for an example). This turns the silent invalid output into an error -- still not a perfect outcome but a bit nicer than a hard-to-debug crash.
In addition, this *also* might have been caught by the optimize pass returning SuccessWithoutChange, but the high-level optimizer checks the output binary and silently fixes things up if the pass returned incorrectly. This is indicative of a bug in a pass, so I added an additional warning line to help debug this as well.
=> spirv-opt: Behave a bit better in the face of unknown instructions

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, test/opt/optimizer_test.cpp, tools/opt/opt.cpp
Renames the existing flag '--webgpu-mode' to '--vulkan-to-webgpu' for
the Vulkan->WebGPU operation, and adds a new flag '--webgpu-to-vulkan'
for the WebGPU->Vulkan operation.
Currently '--webgpu-to-vulkan' doesn't have any passes associated with
it, but further patches will implement them.
Fixes #2495
=> Add WebGPU->Vulkan and Vulkan->WebGPU flags in spirv-opt

source/opt/optimizer.cpp
When -Wformat-security is enabled, we are getting an error.  I do not
claim to fully understand when the warning is triggered or not, but this
one can be avoided by calling "Log" instead of "Logf" because the
formating string is not needed.
=> Fix use of Logf to avoid format security warning

CMakeLists.txt, kokoro/scripts/linux/build.sh
The option "SPIRV_USE_SANITIZER=address" does not work as stated in our
documentation because the link step fails for the tools.  We have to add
-fsanitize to the link flags so the correct libraries are added on the
link step.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2482.
=> Add -fsantize to link flags.

source/val/validate_image.cpp, test/val/val_image_test.cpp
Fixes #2470
* Only require the *WithoutFormat capabilities for Unknown image reads
and writes in the Vulkan environment
* update tests and add new vulkan specific tests
=> Gate formatless checks on Vulkan env

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/legalize_vector_shuffle_pass.cpp, source/opt/legalize_vector_shuffle_pass.h, source/opt/optimizer.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/legalize_vector_shuffle_test.cpp, test/opt/optimizer_test.cpp
In WebGPU, the component operand 0xFFFFFFFF is forbidden, but in
Vulkan it is used to indicate a value is undefined. When converting to
WebGPU, 0xFFFFFFFF needs to converted to a legal value, though the
specific one does not matter, since it was used to indicate an
undefined entry in the original code. Choosing to use 0, since the
operands are required to be on [0, N-1], so 0 is guaranteed to always
be valid.
Fixes #2349
=> Add pass to legalize OpVectorShuffle for WebGPU

source/reduce/CMakeLists.txt, source/reduce/conditional_branch_to_simple_conditional_branch_opportunity_finder.cpp, source/reduce/conditional_branch_to_simple_conditional_branch_opportunity_finder.h, source/reduce/conditional_branch_to_simple_conditional_branch_reduction_opportunity.cpp, source/reduce/conditional_branch_to_simple_conditional_branch_reduction_opportunity.h, source/reduce/reducer.cpp, source/reduce/reduction_util.cpp, source/reduce/reduction_util.h, source/reduce/simple_conditional_branch_to_branch_opportunity_finder.cpp, source/reduce/simple_conditional_branch_to_branch_opportunity_finder.h, source/reduce/simple_conditional_branch_to_branch_reduction_opportunity.cpp, source/reduce/simple_conditional_branch_to_branch_reduction_opportunity.h, test/reduce/CMakeLists.txt, test/reduce/conditional_branch_to_simple_conditional_branch_test.cpp, test/reduce/simple_conditional_branch_to_branch_test.cpp
* Fix #2320. `conditional_branch_to_simple_conditional_branch` reduction pass changes conditional branches so both targets point to the same block id (creating a "simple" conditional branch).
* Fix #2501. `simple_conditional_branch_to_branch` reduction pass changes "simple" conditional branches to branches. 
* Fix #2503. `conditional_branch_to_simple_conditional_branch` proper handling of back-edges.
=> reduce: Add two branch reduction passes

source/val/validate_memory_semantics.cpp, test/val/val_atomics_test.cpp
Recent change to the spec restricted the valid values for Memory
Semnatics in OpAtomics* in the WebGPU env. Implementing enforcing
these changes.
Fixes #2499
=> Change validation of memory semantics for OpAtomics* in WebGPU

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
* Remove the check that blocks terminated by OpUnreachable are not
statically reachable in the CFG
* Updated tests
Addresses SPIR internal issue 457
=> Remove unreachable block validation

source/val/validate.cpp
These are not called/referenced by anything, and are marked as being
unused. They were brought to my attention by a coverity based bug
report.
Fixes #2527
=> Remove legacy utility functions

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
Fixes #2533
* Stop checking layouts once the offset gets back to a 16 byte alignment
=> Reduce runtime of array layout checks

README.md
=> Fix spirv-headers link in the README.

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h
There was a bit shift done on 32-bit values, but they should have been
done on 64-bit values.  This is fixed.  At the same time, uses of size_t
are repalaced by uint64_t to ensure these values are 64-bit.
A test case cannot be created because the code that was change is not
run at the moment since we do not split up vectors or matricies.  I do
not want to delete the code because I like to experitment with it every
once in a while.
Fixes #2528.
=> Fix undefined bit shift in sroa.

source/val/validate_mode_setting.cpp
=> Remove stale comment

source/opt/copy_prop_arrays.cpp, source/opt/copy_prop_arrays.h, source/opt/fix_storage_class.cpp, source/opt/fix_storage_class.h, source/opt/pass.cpp, source/opt/pass.h, test/opt/fix_storage_class_test.cpp
Add functionality to fix-storage-class so that it can fix up mismatched
data types for pointers as well.
Fixes bugs in when fixing up storage class.
Move GenerateCopy to the Pass class to be reused.
The spirv-opt change for #2535.
=> Fix up type mismatches.

utils/check_symbol_exports.py
The 'is' operator is not meant to be used for comparisons. It currently working is an implementation detail of CPython.
CPython 3.8 has added a SyntaxWarning for this.
=> Fix use of 'is' operator for comparison

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/pass_fixture.h
Fixes #2551
* Add support for 1.4 entry point interface lists
* only input and output variables are automatically live
* can clean up interfaces after DCE
* added tests
* allow opt tests to specify a target environment
=> ADCE support for SPIR-V 1.4 entry points

test/val/val_fixtures.h
This should fix memory leaks discovered by ASAN.  
I committed tests which first exercises this method, i.e. ValidateImage_SignExtendV13Bad
=> spvtest::Validate::CompileFailure: Don't leak the diagnostic

source/opt/private_to_local_pass.cpp, source/val/validate_decorations.cpp, test/opt/private_to_local_test.cpp, test/val/val_interfaces_test.cpp
Fixes #2555
* Fix a bug in validation where interfaces were considered non-unique
between different entry points targeting the same function
* added a test
* Update private to local pass to remove localized private variables
from entry point interfaces
* added tests
=> Update priv-to-local for SPIR-V 1.4

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/spirv_validator_options.cpp, source/spirv_validator_options.h, source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp, tools/val/val.cpp
Add a command-line option to enable validating SPIR-V for
implementations that support VK_KHR_uniform_buffer_standard_layout.
=> VK_KHR_uniform_buffer_standard_layout validation

source/opt/pass.cpp
Found internally with clang-tidy.
=> Fix clang-tidy warning about definition/declaration mismatch.

source/opcode.cpp, source/operand.cpp, source/table.h, source/val/validate_instruction.cpp, test/val/val_atomics_test.cpp, test/val/val_decoration_test.cpp, utils/generate_grammar_tables.py
Grammar tables now include lastVersion entry. This is used to perform version checks. The assembler remains quite liberal about allowing things past their last version if there is an enabling capability, but validation fails.
Changes to NonWritable tests were for ease of extension.
=> Use last version

source/opt/instruction.cpp, test/opt/fold_test.cpp
Fixes #2558
* Mark floating point instructions as non-foldable if any
SPV_KHR_float_controls capabilities are present
* tests
=> Do not fold floating point if float controls used

source/opt/instrument_pass.cpp
Pre-existing builtins may be declared int, so load with its pointee type
and cast to uint if needed. Fixes #2572
=> Instrument: Fix load type of pre-existing builtin

source/opt/instrument_pass.cpp, test/opt/inst_bindless_check_test.cpp
When the input and output buffer ids are added as variables, also add them as interfaces to all entry points.
=> Update instrumentation passes to handle 1.4 interfaces

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/spirv_validator_options.cpp, source/spirv_validator_options.h, source/val/validate_composites.cpp, source/val/validate_function.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_function_test.cpp, test/val/val_storage_test.cpp, tools/opt/opt.cpp, tools/reduce/reduce.cpp, tools/val/val.cpp
DXC will be generating code where the function parameters will be a more
generic type that the actual parameter.  They should be the same except
for the actual parameter will have extra decorations.
We want to accept this code with an options so that spirv-opt can then
inline and fix the type mismatch.  We will accept this under a new
options `--before-hlsl-legalization`.
The new option will also imply `relax-logical-pointer` so that HLSL
frontends will need to use just the one more generic option.
=> Make pointers to isomorphic type interchangeable with option.

source/opt/constants.cpp, source/opt/ir_context.h, source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
There is a case where sroa is not handling id overflow gracefully.  It
is handled and an error message is output when the ids overflow.
Fixes https://crbug.com/961030.
=> Handle id overflow in sroa better.

source/opt/upgrade_memory_model.cpp, source/opt/upgrade_memory_model.h, test/opt/upgrade_memory_model_test.cpp
Fixes #2552
* Upgrade memory model now supports two memory access operands for
OpCopyMemory*
* in all cases the pass will first generate two operands by either
adding them or copying
* updates accounts for multiple operands
* tests
=> Mem model spv 1.4

source/val/construct.cpp, source/val/construct.h, source/val/validate_cfg.cpp, source/val/validation_state.h, test/val/val_cfg_test.cpp
Fixes #2213, #2450
This change validate exits from a construct. Valid exits are described in the comment for `IsStructuredExit()`.
=> Validate construct exits

source/val/validate_image.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_opencl_test.cpp
It is currently not possible to use an Image Format that is
not Unknown without requiring a capability forbidden by the
OpenCL environment. As such the validation of Image Format
currently leans on capability validation entirely.
Fixes #2592.
=> Validate OpenCL environment rules for OpTypeImage

source/opt/constants.cpp, source/opt/constants.h, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/opt/fold_spec_constant_op_and_composite_pass.h, test/opt/fold_spec_const_op_composite_test.cpp
In order to try to reduce code duplication and to be able
to fold more cases, we want to use the instruction folder
when folding an OpSpecConstantOp with constant operands.
A couple other changes are need to make this work.  First
GetDefiningInstruction| in the constant manager is able
to handle |type_id| being logically equivalent to another
type, so we updated the interface, and removed the assert.
Some tests were also updated because we not generate
better code because constants are not duplicated as much
as before.
No need for new tests.  The functionality of the instruction folder is
already tested.  There are tests check that the instruction folder is
being used correctly for OpCompositeExtract and OpVectorShuffle in the
existing test cases.
Fixes #2585.
=> Using the instruction folder to fold OpSpecConstantOp

source/val/construct.cpp, source/val/construct.h, test/val/val_cfg_test.cpp
Fixes #2604
* Allow selection constructs to branch to the nearest selection merge
whose header is terminated by an OpSwitch (i.e. break from a switch)
* Cleanup break and continue checks generally
* add tests
FYI @johnkslang, @alegal-arm
=> Allows breaks selection breaks to switches

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
Fixes #2588
* Add a check that the merge block of OpLoopMerge may not be the block
that contains the OpLoopMerge
* add a test
=> Disallow merge targeting block with OpLoopMerge

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
The validator didn't accept CrossWorkgroup, Workgroup or Function as valid storage classes for vloadn and vstoren even though the  OpenCL Extended Instruction Set Specification allows them (https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.ExtendedInstructionSet.100.html#_a_id_vector_a_vector_data_load_and_store_instructions)
=> Update vloadn and vstoren validation to match the OpenCL Extended Instruction Set Specification

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp, test/val/val_code_generator.cpp
- Allow arrays of out per-primitive builtins for mesh shaders - PrimitiveID, Layer, ViewportIndex.
- We already allow arrays of per-vertex builtins such as Position, PointSize, etc. (see use of similar function ValidateOptionalArrayedF32 for reference).
=> Allow arrays of out per-primitive builtins for mesh shaders

test/link/CMakeLists.txt, test/link/linker_fixture.h, test/link/type_match_test.cpp
This adds a number of tests that check that all types will match to identically written clones during linking, including nearly every Type and some combinations (e.g. Functions of Arrays of Floats). Intent is for use with https://github.com/KhronosGroup/SPIRV-Tools/pull/2580, however that PR focuses on issues with TypeArray whereas these tests are (more) comprehensive and test more subtle (and possibly incorrect) cases.
A number of these tests fail (and are disabled to pass CI checks), many are fixed by the aforementioned PR. Some additional tests involving TypeForwardPointer cause assertion failures, although the cases they describe are more rare.
=> linker: Add tests for various type comparisons

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/CMakeLists.txt, source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/protobufs/spirvfuzz_protobufs.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/pseudo_random_generator.cpp, source/fuzz/pseudo_random_generator.h, source/fuzz/random_generator.cpp, source/fuzz/random_generator.h, source/spirv_fuzzer_options.cpp, source/spirv_fuzzer_options.h, utils/check_symbol_exports.py
This consists of a Fuzzer class that will transform a module with respect to (a) facts about the module provided via a FactManager class, and (b) a source of random numbers and parameters to control the transformation process provided via a FuzzerContext class.  Transformations will be applied via classes that implement a FuzzerPass interface, and both facts and transformations will be represented via protobuf messages.  Currently there are no concrete facts, transformations nor fuzzer passes; these will follow.
=> Added a library for spirv-fuzz

tools/CMakeLists.txt, tools/fuzz/fuzz.cpp
The current tool can parse basic command-line argument, but generates
a binary identical to the input binary, since no transformations are
yet implemented.
=> Add spirv-fuzz tool.

source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/dead_branch_elim_test.cpp, test/opt/struct_cfg_analysis_test.cpp
There was a recent decision made to allow branches to the merge node of
a switch even if the switch is not the first enclosing construct.  They
can be generated by glslang from break statements in switches.
Dead branch elimination seems to be the only optimization that will
break because of this change, so I will update that optimizations.
The change made are:
- Track switches in structured cfg analysis.
- In Dead branch elimination:
- Look for nested breaks that will require a switch instruction.
- Rewrite, but don't delete, switchs that are required even if it
could be replaced by an unconditional branch.
- When looking for the first break, consider the merge of a switch
as well.
See #2612.
=> Handle nested breaks from switches.

source/link/linker.cpp, source/opt/remove_duplicates_pass.cpp, source/opt/remove_duplicates_pass.h, source/opt/type_manager.cpp, source/opt/type_manager.h, source/opt/types.cpp, source/opt/types.h, test/link/type_match_test.cpp, test/opt/type_manager_test.cpp, test/opt/types_test.cpp
This is an attempt to fix #2442 by re-implementing type comparisons for `OpTypeArray`. This new comparison checks that the values of the constants are the same, or if those are specialised constants, that they refer to the same `SpecId`.
=> Linker: Better type comparison for OpTypeArray and OpTypeForwardPointer

tools/io.h
The close for the file handles was missing in the error cases.
Fixes #2641
=> Close opened file handles.

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_pass_add_useful_constructs.cpp, source/fuzz/fuzzer_pass_add_useful_constructs.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_constant_boolean.cpp, source/fuzz/transformation_add_constant_boolean.h, source/fuzz/transformation_add_constant_scalar.cpp, source/fuzz/transformation_add_constant_scalar.h, source/fuzz/transformation_add_type_boolean.cpp, source/fuzz/transformation_add_type_boolean.h, source/fuzz/transformation_add_type_float.cpp, source/fuzz/transformation_add_type_float.h, source/fuzz/transformation_add_type_int.cpp, source/fuzz/transformation_add_type_int.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_constant_boolean_test.cpp, test/fuzz/transformation_add_constant_scalar_test.cpp, test/fuzz/transformation_add_type_boolean_test.cpp, test/fuzz/transformation_add_type_float_test.cpp, test/fuzz/transformation_add_type_int_test.cpp
This new pass adds some basic ingredients to a module on which future passes are likely to depend, such as boolean constants and some specfic integer and floating-point values.  This is not a fuzzer pass in the true sense in that it does not employ randomization, but it makes sense to define it as a fuzzer pass since it is the first of a number of transformations passes that the fuzzer will run on a module.
=> Add fuzzer pass that adds useful constructs to a module

source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h, test/opt/type_manager_test.cpp, test/opt/types_test.cpp
In the OpSpecConstantOp array length case, consider the lengths
equal if they have the same result id.
Preserve the previous behaviour for other cases:
- when it's an OpSpecConstant, only the SpecId decorations are compared.
- when it's an OpConstant, the literal bit values are compared.
Fixes #2649
=> Optimizer: Handle array type with OpSpecConstantOp length

source/fuzz/fuzzer_pass_split_blocks.cpp, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_test.cpp
There turned out to be a bug in the 'split blocks' transformation due
to blocks being split while they were being iterated over.  This
change fixes that issue, and adds tests that were able to expose the
issue by running the fuzzer on some example shaders.
=> Fix bug in 'split blocks', and add tests for fuzzer.

.appveyor.yml, source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
Also add a Builtin test generator variant that takes
capabilities and extensions.
Tests
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV Builtins are
accepted as Inputs in Vertex, Fragment, TessControl, TessEval, Geometry,
and Compute.
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV Builtins are
accepted as Inputs in MeshNV and TaskNV shaders.
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV Builtins are
accepted as Inputs in the 6 ray tracing stages
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV Builtins are
NOT accepted as Outputs.
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV Builtins are
NOT accepted as non-scalar integers (f32, uvec3)
- verify that the SMCountNV, SMIDNV, WarpsPerSMNV, and WarpIDNV …
=> Add builtin validation for SPV_NV_shader_sm_builtins

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_context.h, source/fuzz/id_use_descriptor.cpp, source/fuzz/id_use_descriptor.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.cpp, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_replace_boolean_constant_with_constant_binary_test.cpp
Add transformation to replace a boolean constant with a numeric comparison.
The transformation can, for example, replace "true" with "12.0 > 6.0", if constants for those floating-point values are available.
This introduces a new 'id use descriptor' structure, which provides a way to describe a particular use of an id, and which will be heavily used in future transformations.  Describing an id use is trivial if the use occurs in an instruction that itself generates an id, but is less straightforward if the id of interest is used by an instruction such as OpStore that does not have a result id.  The 'id use descriptor' structure caters for such cases.
=> Fuzzer transformation replace boolean constant

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/uniform_buffer_element_descriptor.cpp, source/fuzz/uniform_buffer_element_descriptor.h, test/fuzz/CMakeLists.txt, test/fuzz/fact_manager_test.cpp
Adds a new (and first) kind of fact to the fact manager, which is that
a specific uniform value is guaranteed to be equal to a specific
constant.  The point of this is that such information (if known to be
true by some external source) can be used by spirv-fuzz to transform
the module in interesting ways that a static compiler cannot reverse
via compile-time analysis.
This change introduces protobuf messages for the fact, and adds
capabilities to the fact manager to store this kind of fact and
provide information about it.
=> Add constant == uniform facts.

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
Fixes #2611
* Validates builtins in the Vulkan environment:
* NumSubgroups
* SubgroupId
* SubgroupEqMask
* SubgroupGeMask
* SubgroupGtMask
* SubgroupLeMask
* SubgroupLtMask
* SubgroupLocalInvocationId
* SubgroupSize
=> Add validation for Subgroup builtins

source/fuzz/CMakeLists.txt, source/fuzz/replayer.cpp, source/fuzz/replayer.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_replayer_test.cpp, tools/fuzz/fuzz.cpp
The replayer takes an existing sequence of transformations and applies them to a module.  Replaying a sequence of transformations that were obtained via fuzzing should lead to an identical module to the module that was fuzzed.  Tests have been added to check for this.
=> Add replayer tool for spirv-fuzz.

source/val/validate_atomics.cpp, source/val/validate_memory_semantics.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp
* Can only be used with Vulkan memory model
* Can only be used with atomics
* Bit setting must match for compare exchange opcodes
* Updated memory semantics checks to allow constant instructions
generally with CooperativeMatrixNV
@dneto0 and @zoddicus I left it disallowed for WebGPU. Should this be changed? 
FYI @jeffbolznv
=> Validate Volatile memory semantics bit

source/opt/upgrade_memory_model.cpp, source/opt/upgrade_memory_model.h, test/opt/upgrade_memory_model_test.cpp
* If an atomic is decorated with volatile add the volatile bit to its
memory semantics
Fixed some comments and refactored a method too.
=> Handle volatile memory semantics in upgrade

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_useful_constructs.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/replayer.cpp, source/fuzz/transformation_add_type_pointer.cpp, source/fuzz/transformation_add_type_pointer.h, source/fuzz/transformation_replace_constant_with_uniform.cpp, source/fuzz/transformation_replace_constant_with_uniform.h, test/fuzz/CMakeLists.txt, test/fuzz/fact_manager_test.cpp, test/fuzz/fuzzer_pass_add_useful_constructs_test.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_add_type_pointer_test.cpp, test/fuzz/transformation_replace_constant_with_uniform_test.cpp
Adds a new transformation that can replace a constant with a uniform known to have the same value, and adds a fuzzer pass that (a) replaces a boolean with a comparison of literals (e.g. replacing "true" with "42 > 24"), and then (b) obfuscates the literals appearing in this comparison by replacing them with identically-valued uniforms, if available.
The fuzzer_replayer test file has also been updated to allow initial facts to be provided, and to do error checking of the status results returned by the fuzzer and replayer components.
=> Add fuzzer pass to obfuscate constants.

DEPS
https://github.com/KhronosGroup/SPIRV-Headers/compare/8b911bd2ba37...de99d4d834ae
$ git log 8b911bd2b..de99d4d83 --date=short --no-merges --format='%ad %ae %s'
2019-06-12 dneto Add Volatile to Memory Semantics, for SPV_KHR_vulkan_memory_model
2019-06-10 ehsannas Add grammar and symbols for UserTypeGOOGLE extension to unified1.
2019-06-07 cepheus Add missing "version" : "None" to a bunch of reserved enumerants.
2019-06-07 cepheus Add more detail about reserving tokens to the README.
2019-06-07 cepheus Restore numerical order in enumerants.
2019-05-18 mchiasson Update CMakeLists.txt
2019-05-16 mchiasson updated as per code review
2019-05-11 mchiasson cmake development configuration package Fixes #104
Created with:
roll-dep external/spirv-headers
Fixes #2680
=> Roll external/spirv-headers/ 8b911bd2b..de99d4d83 (8 commits)
