source/fuzz/fact_manager.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_constant_with_uniform.cpp, source/fuzz/uniform_buffer_element_descriptor.cpp, source/fuzz/uniform_buffer_element_descriptor.h, test/fuzz/CMakeLists.txt, test/fuzz/fact_manager_test.cpp, test/fuzz/fuzzer_pass_add_useful_constructs_test.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_replace_constant_with_uniform_test.cpp, test/fuzz/uniform_buffer_element_descriptor_test.cpp
Previously uniform facts were expressed with resepect to the id of a
uniform variable.  Describing them with respect to a descriptor set
and binding is more convenient from the point of view of expressing
facts about a shader without requiring analysis of its SPIR-V.
=> Represent uniform facts via descriptor set and binding.

source/spirv_target_env.cpp, source/spirv_target_env.h, tools/as/as.cpp, tools/link/linker.cpp, tools/opt/opt.cpp, tools/val/val.cpp
Several tools take a --target-env option to specify the SPIR-V
environment to use. They all use spvParseTargetEnv to parse
the user-specified string and select the appropriate spv_target_env
but all tools list only _some_ of the valid values in their help
text.
This change makes the help text construction automatic from the
full list of valid values, establishing a single source of truth
for the values printed in the help text. The new utility function
added allows its user to specify padding and wrapping constraints
so the produced strings fits well in the various help texts.
Signed-off-by: Kévin Petit <kpet@free.fr>
=> Add all accepted target environments to the tools' help texts

DEPS, README.md, utils/git-sync-deps, utils/roll_deps.sh
This adds in a script for updating DEPS and another for pulling in the
specified versions in the DEPS file.
DEPS entries that are not part of the documented build processs are
removed. Using the documented cmake process with them made for a very
sad state of one's checkout. If this removal breaks workflows we can
revist this, since the state is saved in git.
DEPS are rolled forward, so that this is taking use to a known good
state. These look like scary big rolls, but in reality the bots and
most people are running near HEAD for external/, so this integration
should already have been tested.
Summary of DEPS roll:
+ Rolling 3 dependencies
+ Roll external/effcee/ 04b624799..b83b58d17 (14 commits)
+ Roll external/googletest/ 98a0d007d..2f42d769a (576 commits)
+ Roll external/re2/ …
=> Add infrastructure for maintaining and using DEPS

source/spirv_target_env.cpp
#2687 introduced a global static map, which isn't allowed by the style guide and caused an issue in DXC.
This change replaces it with an array of pairs.
Signed-off-by: Kévin Petit <kpet@free.fr>
=> Replace global static map with an array of pairs

source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, tools/fuzz/fuzz.cpp
Fixes #2621.
Instead of aborting when an invalid input fact is provided, the tool
now warns about the invalid fact and then ignores it.  This is
convenient for example if facts are specified about uniforms with
descriptor sets and bindings that happen to not be present in the
input binary.
=> Warn when input facts are invalid.

source/opt/ir_context.cpp, test/opt/inst_bindless_check_test.cpp
When working on descriptor indexing validation for compute shaders, the
gl_GlobalInvocationID builtin was being loaded as uint which would cause
compute shaders instrumented by the bindless check pass to have:
%83 = OpLoad %uint %gl_GlobalInvocationID
%84 = OpCompositeExtract %uint %83 0
%85 = OpCompositeExtract %uint %83 1
%86 = OpCompositeExtract %uint %83 2
which results in validation failures:
error: line 127: Reached non-composite type while indexes still remain
to be traversed.
%84 = OpCompositeExtract %uint %83 0
for trying to extract a uint from a uint.
=> Update type for loaded GlobalInvocationID in pass instrumentation

BUILD.gn
In order for the Fuchsia source tree to update its
version of SPIRV-Tools to a newer upstream, the
BUILD.gn needs to be slightly altered to take care
of the fact that it can be used with a different
GN //build set of rules and configs than the
Chromium one.
This is done by using |build_with_chromium|, already
defined by //build_overrides/build.gni, to guard
Chromium-specific statements.
+ Add a target to generate spirv-opt which is used by
Fuchsia to optimize shaders at build time for some of
its graphics libraries.
=> Fix BUILD.gn for Fuchsia platform build.

source/spirv_reducer_options.cpp, source/spirv_reducer_options.h
Avoids polluting the global namespace with a constant, and moves constructor to .cpp file as is done for spirv-reduce's options.
=> Refactor reducer options

source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_test.cpp
It is illegal to inline an OpKill instruction into a continue construct because the continue header will no longer dominate the backedge.
This commit adds a check for this, and does not inline.
If we still want to be able to inline a function that contains an OpKill, we can add a new pass that will wrap OpKill instructions into its own function with just the single instruction.
I do not believe that this is a common case right now, so I will not do that yet.
Fixes #2433.
=> Do not inline OpKill Instructions

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
Inlining does not inline functions that have a single return that is in a loop.  This is because the return cannot be replaced by a branch outside of the loop easily.  Merge return knows how to rewrite the function so the return is replaced by a branch.
Fixes #2038.
=> Perform merge return with single return in loop.

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h, source/spirv_fuzzer_options.cpp, source/spirv_fuzzer_options.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzz_test_util.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, tools/fuzz/fuzz.cpp
Adds to spirv-fuzz the option to shrink a sequence of transformations that lead to an interesting binary to be generated, to find a smaller sub-sequence of transformations that still lead to an interesting (but hopefully simpler) binary being generated.  The notion of what counts as "interesting" comes from a user-provided script, the "interestingness function", similar to the way the spirv-reduce tool works.  The shrinking process will give up after a maximum number of steps, which can be configured on the command line.
Tests for the combination of fuzzing and shrinking are included, using a variety of interestingness functions.
=> Shrinker for spirv-fuzz

source/val/validate_composites.cpp, source/val/validate_constants.cpp, source/val/validate_conversion.cpp, source/val/validate_memory.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_composites_test.cpp, test/val/val_constants_test.cpp, test/val/val_conversion_test.cpp, test/val/val_data_test.cpp, test/val/val_decoration_test.cpp, test/val/val_memory_test.cpp
Fixes #2669 
* Validates use cases for 8- and 16-bit types when only storage capabilities are present
* OpVariable - specific capability check for storage class
* OpLoad - only scalar vector and matrix (and pointers)
* OpStore - only scalar vector and matrix (and pointers)
* Conversions - width-only conversions
* Constants - only pointer null
* Composites - none
* Unified some conversions tests to cover more cases
* Some new helper functions in ValidationState_t to identify the right types and use cases
=> Validate usage of 8- and 16-bit types with only storage capabilities

source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/simplification_pass.cpp, source/opt/value_number_table.cpp, test/opt/decoration_manager_test.cpp, test/opt/simplification_test.cpp, test/opt/value_table_test.cpp
There are a couple spots where we are not looking at decorations when we should.
1. Value numbering is suppose to assign a different value number to ids if they have different decorations.  However that is not being done for OpCopyObject and OpPhi.
1. Instruction simplification is propagating OpCopyObject instruction without checking for decorations.  It should only do that if no decorations are being lost.
Add a new function to the decoration manager to check if the decorations of one id are a subset of the decorations of another.
Fixes #2715.
=> Handle decorations better in some optimizations

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/ir_context.h, source/opt/optimizer.cpp, source/spirv_optimizer_options.cpp, source/spirv_optimizer_options.h, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/pass_fixture.h, tools/opt/opt.cpp
Continuing from https://github.com/KhronosGroup/SPIRV-Tools/pull/2678, a more complete implementation of flags to preserve all bindings and/or specialisation constants within a SPIR-V module, which can be useful/necessary for reflection or for cross-compilation into other shader languages (e.g. for Metal argument buffers).
@s-perron I've implemented this as an optimiser option rather than a flag specifically for AggressiveDCE. At the moment, I think AggressiveDCE is the only pass that _can_ remove unused bindings/spec-constants; however, if future passes started to do the same I'd imagine we'd want a single flag to control it. Does that sound okay?
I've also enabled the flags by default for HLSL legalisation, since some tools (e.g. `dxc` perform legalisation by default on HLSL source even …
=> Add —preserve-bindings and —preserve-spec-constants

source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, test/opt/dead_branch_elim_test.cpp
Dead branch elimination needs to know about the constructs that a block is contained it when determining what to do with its merge instruction.  We currently fold branches in block as we see them, which is parent constructs before their children.  This causes the struct cfg analysis to crash because it tries to get the parent construct for a block after the parent has been folded.
This can be fixed by folding the branch of the children before the parents.
Fixes #2667.
=> Change the order branches are simplified in dead branch elim

BUILD.gn
This adds all the command-line tools from the CMakeLists.txt
file to the BUILD.gn used by Chromium and Fuchsia.
+ Add a convenient "all_spirv_tools" GN target to rebuild
all command-line tools at once.
+ "gn format" pass to fix a few minor issues in the file.
Tested on Chromium with the following procedure:
1) Have a clean Chromium checkout
2) # Update to upstream spirv-headers (otherwise spirv-tools build fails)
cd $CHROMIUM_SRC/third_party/spirv-headers/src &&
git remote add upstream https://github.com/KhronosGroup/SPIRV-Headers.git &&
git fetch upstream &&
git checkout upstream/master
3) # Update to upstream spirv-tools (Chromium is tracking older revision)
cd $CHROMIUM_SRC/third_party/SPIRV-Tools/src &&
git remote add upstream https://github.com/KhronosGroup/SPIRV-Tools.git &&
git …
=> BUILD.gn: Add targets to build all command-line tools

BUILD.gn
This makes SPIRV-Tools produce no GN check errors when used in Dawn and
ANGLE
PTAL @zoddicus !
=> BUILD.gn: Add deps and move files for `gn check`

include/spirv-tools/instrument.hpp, source/opt/instrument_pass.cpp, source/opt/ir_context.cpp, test/opt/inst_bindless_check_test.cpp
Adds the ray tracing stages (ray gen, intersection, any hit, closest hit,
miss, and callable) to the allowed stages in pass instrumentation and add
debug records for these stages to output the global launch id. This will allow
supporting descriptor indexing checks for ray tracing shaders in Vulkan
validation layers.
More information for ray tracing shaders:
- https://github.com/KhronosGroup/GLSL/blob/master/extensions/nv/GLSL_NV_ray_tracing.txt
Vulkan validation layer changes that can be enabled after this change:
- https://github.com/jmacnak-nv/Vulkan-ValidationLayers/commit/499230d720606d1c62dffd885ef3a89ed89ee818
- https://github.com/jmacnak-nv/Vulkan-ValidationLayers/commit/28c71a2d70ab3abf21de042df5fcb91043f5d257
- https://github.com/jmacnak-nv/Vulkan-ValidationLayers/commit/358be9aa4 …
=> Allow ray tracing shaders in InstBindlessCheckPass

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
The merge return pass seems to assume that the only new edges in the cfg
are from return block to merge blocks.  However, it is possible that a
merge block branches to a merge block when it did not before.
This change add a new variable to track all of the new edges.  It also
renames some other variables and cleans us the code to make it a bit
easier to read.
Fixes #2702.
=> Fix bug in merge return

source/val/validate_type.cpp, test/val/val_id_test.cpp
This change corresponds to a pending change to the Vulkan SPIR-V environment spec.
=> For Vulkan, disallow structures containing opaque types

source/val/validate_derivatives.cpp, source/val/validate_image.cpp, test/val/val_derivatives_test.cpp, test/val/val_image_test.cpp
Also update existing derivative check to be based on the execution mode
instead of just the extension being present.
More info about extension:
- https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_compute_shader_derivatives.asciidoc
=> Allow LOD ops in compute shaders with derivative group execution modes

source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp
This change refactors all storage class validation for atomics
to reflect the similar refactoring in the specification.
It is currently not possible to write a test for the check
rejecting Generic in an OpenCL 1.2 environment as the required
GenericPointer capability isn't allowed there. I've decided
to keep the check nonetheless to guard against the capability
becoming available without the rules for atomics being updated.
The ID changes in existing tests aren't ideal but introducing
names drags in a substantial refactoring of this file.
Contributes to #2595.
=> Validate storage class OpenCL environment rules for atomics

source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
Previously was dependent on presense of descriptor_indexing extension
in SPIR-V, but this missed some cases. Tests updated to refect this new
policy.
=> Bindless Instrument: Make init check depend solely on input_init_enabled

source/val/function.cpp, test/val/val_cfg_test.cpp
Fixes #2743
* Continue depth calculation should take precedence over merge calculation
=> Fix block depth rule priority

source/opt/ssa_rewrite_pass.cpp, source/opt/ssa_rewrite_pass.h, test/opt/local_ssa_elim_test.cpp
When a phi candidate is marked as trivial, we are suppose to update all
of its uses to the reference the value that it is being folded to.
However, the code updates the uses misses `defs_at_block_`.  So at a
later time, the id for the trivial phi can reemerge.
Fixes #2744
=> SSA rewriter: Don't use trivial phis

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
In merge return, we need to know the original dominator for a block in order to
traverse code from the original dominator to the new dominator and add
appropriate Phi nodes.  The current code gets this wrong because the dominator
tree is build as needed.  The first time we get the immediate dominator for a
function we just built the dominator tree and it takes into account that a
block has been split.  The second time it does not.
This inconsistency needs to be fixed.  We do that by recording the original
dominator for all blocks at the start of the pass.
If we were to record just the basic block, that could change if the block is
split.  We want to traverse the code in the body of the original dominator,
whatever block it ends up in.  To make this easy to track, we not save the …
=> Record correct dominators in merge return

source/opt/aggressive_dead_code_elim_pass.cpp, source/val/validate_annotation.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/val/val_id_test.cpp
When there is an OpDecorateId instruction that is live,
the ids that is references must be kept live.  This change
adds them to the worklist.
I've also updated a validator check to allow OpDecorateId
to be able to apply to decoration groups.
Fixes #1759.
=> Process OpDecorateId in ADCE

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_add_dead_continues.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_add_dead_continue_test.cpp
Similar to the existing 'add dead breaks' pass, this adds a pass to
add dead continues to blocks in loops where such a transformation is
viable.  Various functionality common to this new pass and 'add dead
breaks' has been factored into 'fuzzer_util', and some small
improvements to 'add dead breaks' that were identified while reviewing
that code again have been applied.
Fixes #2719.
=> Transformation and fuzzer pass to add dead continues

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
Merge return expects unreachable merge block to look a certain way, and
unreachable continue blocks to look a certain way.  What if an
unreachable block is both a merge and a continue?  The continue is
suppose to take precedent, but merge-return implements it with the merge
taking precedent.  This change flips that around.
Fixes #2746
=> Fix check for unreachable blocks in merge-return

test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp
The recently added fuzzer_replayer and fuzzer_shrinker tests were
rather heavyweight and were leading to CI timeouts.  This change
reduces the runtime of those tests by having them do fewer iterations.
=> Limit fuzzer tests so that they take less time to run

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
When SROA tries to do a replacement for an OpAccessChain that is exactly
one element out of bounds, the code was trying to access its internal
array of replacements and segfaulting.
This protects the code from doing this, and it additionally fixes the
way SROA works by not returning failure when it refuses to do a
replacement.  Instead of failing the optimization pass, SROA will now
simply refuse to do the replacement and keep going.
=> Fix #2609 - Handle out-of-bounds scalar replacements.

source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/simplification_pass.cpp, test/opt/simplification_test.cpp
Fixes #2764
* Don't replace all uses when simplifying instructions, instead only
update non-debug, non-decoration uses
* added a test
Decorations shouldn't be pulled into generators when simplifying instructions.
=> Don't move debug or decorations when folding

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
This fixes #2608.
The original test case had an out-of-bounds reference that ended up
folding into OpCompositeExtract that was indexing right outside the
constant composite.
The returned constant would then cause a segfault during constant
propagation.
=> Protect against out-of-bounds references when folding OpCompositeExtract

source/opt/types.cpp, source/opt/types.h
This makes it symmetric with the result type of ...->element_type which
returns a const Type.
So now we can write code like this:
analysis::Vector v = ...
analysis::Vector(v->element_type(), 2);
=> Element type is const for analysis::Vector,Matrix,RuntimeArray

source/opt/constants.cpp, source/opt/constants.h, source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
Fixes #2768
* In scalar replacement, interpret access chain indexes as signed counts
* Use Constant::GetSignExtendedValue and Constant::GetZeroExtendedValue
where appropriate
* new tests
Previously, sroa didn't handle 8 or 16 bit index constants.
=> Treat access chain indexes as signed in SROA

source/opt/graphics_robust_access_pass.h
This fixes a clang compiler warning about extra semicolons that blocks ANGLE's integration.
=> Remove extra ';' after member function definition.

source/fuzz/CMakeLists.txt, source/fuzz/data_descriptor.cpp, source/fuzz/data_descriptor.h, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_copy_object.cpp, source/fuzz/transformation_copy_object.h, source/fuzz/transformation_split_block.cpp, source/fuzz/transformation_split_block.h, source/fuzz/uniform_buffer_element_descriptor.cpp, source/fuzz/uniform_buffer_element_descriptor.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_copy_object_test.cpp
This transformation can introduce an instruction that uses
OpCopyObject to make a copy of some other result id.  This change
introduces the transformation, but does not yet introduce a fuzzer
pass to actually apply it.
=> Add 'copy object' transformation

CMakeLists.txt
This will catch instances on the bots where PRs introduce unneeded
semi-colons, which are going to cause downstream users problems.
Fixes #2781
=> Add -fextra-semi to Clang builds

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
This also fixes ADCE to not remove possibly needed OpTypeForwardPointer.
The bug, its fix and the corresponding test have a circular dependency
with the extension, so they are packaged together.
=> Add SPV_EXT_physical_storage_buffer to opt whitelists

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/desc_sroa.cpp, source/opt/desc_sroa.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/optimizer.cpp, source/opt/passes.h, source/util/string_utils.h, test/assembly_context_test.cpp, test/binary_parse_test.cpp, test/comment_test.cpp, test/ext_inst.debuginfo_test.cpp, test/ext_inst.opencl_test.cpp, test/opt/CMakeLists.txt, test/opt/decoration_manager_test.cpp, test/opt/desc_sroa_test.cpp, test/text_to_binary.annotation_test.cpp, test/text_to_binary.debug_test.cpp, test/text_to_binary.extension_test.cpp, test/text_to_binary.mode_setting_test.cpp, test/unit_spirv.cpp, test/unit_spirv.h, tools/opt/opt.cpp
Creates a pass that will replace a descriptor array with individual variables.  See #2740 for details.
Fixes #2740.
=> Add descriptor array scalar replacement

test/link/type_match_test.cpp, test/opt/types_test.cpp
Later versions of clang seem to pick up more useless semi-colons.  I've removed them.
=> Remove useless semi-colons

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/ir_builder.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/types.cpp, source/opt/types.h, source/opt/wrap_opkill.cpp, source/opt/wrap_opkill.h, test/opt/CMakeLists.txt, test/opt/wrap_opkill_test.cpp, test/tools/opt/flags.py
We are no able to inline OpKill instructions into a continue construct.
See #2433.  However, we have to be able to inline to correctly do
legalization.  This commit creates a pass that will wrap OpKill
instructions into a function of its own.  That way we are able to inline
the rest of the code.
The follow up to this will be to not inline any function that contains
an OpKill.
Fixes #2726
=> Replace OpKill With function call.

source/val/validate_constants.cpp, test/val/val_constants_test.cpp, test/val/val_id_test.cpp
Fixes #2793
* Don't special case matrix validation compared to other composites
* just check the constituents are constants or undefs
* later checking validates the column type
* new test
=> Fix validation of constant matrices

source/opt/desc_sroa.cpp
Including source/util/string_utils.h always uses
"source/util/string_utils.h" instead of
<source/util/string_utils.h>.
=> Change the way to include header

CHANGES
My local python reports that CHANGES uses a non-ascii code
character and fail in running utils/update_build_version.py.
=> Use ascii code based characters

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
The `remquo` builtin was validated as if the last argument was supposed to be to pointer to a float instead of a pointer to a 32-bit integer, which doesn't match the OpenCL Extended Instruction Set Specification (https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.ExtendedInstructionSet.100.html#remquo).
Move `remquo` specific checks to the same case as `frexp` and `lgamma_r` which require a pointer to a 32-bit integer as the last argument and update the tests.
=> Update remquo validation to match the OpenCL Extended Instruction Set Specification

Android.mk, BUILD.gn, include/spirv-tools/instrument.hpp, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/inst_buff_addr_check_pass.cpp, source/opt/inst_buff_addr_check_pass.h, source/opt/instrument_pass.cpp, source/opt/instrument_pass.h, source/opt/optimizer.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/inst_buff_addr_check_test.cpp
Adds new pass to instrument shaders for GPU-assisted validation of shaders referencing through
physical storage buffer address. This pass is only intended to be called from the validation layer.
A command line option is added for developer convenience and is not documented.
=> Instrument: Add support for Buffer Device Address extension

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/pass_fixture.h, test/opt/scalar_replacement_test.cpp
If we run out of ids when creating a new variable, sroa does not recognize
the error, and continues doing work.  This leads to segmentation faults.
Fixes https://crbug/969655
=> More handle overflow in sroa

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
Now we need to handle id overflow when we overflow while replacing uses of the variable.  While looking at this code, I noticed an error in the way we handle access chains that cannot be replaced because of overflow.  Name it will make some change, and then give up by returning SuccessWithoutChange.  But it was changed.
This is fixed up by returning Failure if we notice the error at the time of rewriting the users.  This is for both id overflow or out-of-bounds accesses.
Code is added to "CheckUses" to remove variables that have out-of-bounds accesses from the candidate list, so we don't even try to rewrite its uses.
Fixes https://crbug.com/995032
=> Even more id overflow in sroa

source/reduce/CMakeLists.txt, source/reduce/reducer.cpp, source/reduce/remove_relaxed_precision_decoration_opportunity_finder.cpp, source/reduce/remove_relaxed_precision_decoration_opportunity_finder.h, source/reduce/remove_unreferenced_instruction_reduction_opportunity_finder.cpp, test/reduce/CMakeLists.txt, test/reduce/remove_relaxed_precision_decoration_test.cpp
Adds a reduction pass that removes OpDecorate and OpMemberDecorate
instructions that annotate instructions and members with
RelaxedPrecision.  As well as being useful in its own right, removing
such references allows other passes to remove further instructions.
=> Extend reducer to remove relaxed precision decorations

BUILD.gn
New files missing from BUILD.gn caused build failures in Chromium and
ANGLE:
remove_relaxed_precision_decoration_opportunity_finder.cpp
remove_relaxed_precision_decoration_opportunity_finder.h
=> Add missing files to BUILD.gn

source/opt/optimizer.cpp
If they are not aliased, the function will often print the message:
"Binary unexpectedly changed despite optimizer saying there was no change"
Which is (usually) totally bogus.
Fixes #2798
=> spvtools::Optimizer - don't assume original_binary and optimized_binary are aliased

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/amd_ext_to_khr.cpp, source/opt/amd_ext_to_khr.h, source/opt/instrument_pass.cpp, source/opt/ir_builder.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/module.h, source/opt/optimizer.cpp, source/opt/pass.h, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/amd_ext_to_khr.cpp, tools/opt/opt.cpp
Add the first steps to removing the AMD extension VK_AMD_shader_ballot.
Splitting up to make the PRs smaller.
Adding utilities to add capabilities and change the version of the
module.
Replaces the instructions:
OpGroupIAddNonUniformAMD = 5000
OpGroupFAddNonUniformAMD = 5001
OpGroupFMinNonUniformAMD = 5002
OpGroupUMinNonUniformAMD = 5003
OpGroupSMinNonUniformAMD = 5004
OpGroupFMaxNonUniformAMD = 5005
OpGroupUMaxNonUniformAMD = 5006
OpGroupSMaxNonUniformAMD = 5007
and extentend instructions
WriteInvocationAMD = 3
MbcntAMD = 4
Part of #2814
=> Amd ext to khr

BUILD.gn
spriv-opt was missing a dependency on the AMD ballot extension that was
needed because it uses a header in the AMD ext to KHR ext pass.
=> Fix gn check

source/opt/aggressive_dead_code_elim_pass.cpp
Also add an assertion that these `modified` is true if to_kill_ has a non-zero size to catch this sort of issue in the pass.
Fixes: #2824
=> AggressiveDCEPass: Set modified to true when appending to to_kill_

source/fuzz/data_descriptor.h, source/fuzz/fact_manager.h, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_dead_breaks.h, source/fuzz/fuzzer_pass_add_dead_continues.h, source/fuzz/fuzzer_pass_add_useful_constructs.h, source/fuzz/fuzzer_pass_obfuscate_constants.h, source/fuzz/fuzzer_pass_permute_blocks.h, source/fuzz/fuzzer_pass_split_blocks.h, source/fuzz/uniform_buffer_element_descriptor.h
The end comments for the #ifndef ... #endif macros in various header
files containd a stray #define.
=> Fix end comments in header files

BUILD.gn
Should prevent invalid header usage warnings in dependent targets.
See http://anglebug.com/3876 for context.
@dj2 PTAL
=> GN: Make SPIRV-Tools target use public_deps.

BUILD.gn
This fixes a GN header check in the Chromium integration.
@dj2  PTAL
=> GN: Add Chromium GoogleTest deps.

source/CMakeLists.txt, source/fuzz/CMakeLists.txt, source/link/CMakeLists.txt, source/opt/CMakeLists.txt, source/reduce/CMakeLists.txt
This allows the targets to be used in other cmake projects. See the following for more details:
https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages
https://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html
=> Export SPIRV-Tools targets on installation

include/spirv-tools/optimizer.hpp, test/fuzzers/spvtools_opt_vulkantowebgpu_fuzzer.cpp, test/fuzzers/spvtools_opt_webgputovulkan_fuzzer.cpp, test/opt/optimizer_test.cpp, tools/opt/opt.cpp
=> For WebGPU<->Vulkan optimization, set correct execution environment

source/val/validation_state.h
As far as I know, it is legal to have multiple decoration adding the
same decoration to the same id.  The validator registers all of these
decoration as if they were distinct decorations.  This can cause poor
memory usage and performance in some cases.
This fix is to make sure that duplicates are not registers.
I keep the type of the decoration list as an std::vector because I
expect it to be small enough in most cases that the linear search will
still be faster that using some type of map.
No tests are added because we do not have a mechanism to test memory
usage in our unit tests.
Fixes #2837.  The total memory usage drop to 14,236KB.
=> Don't register duplicate decoration in validator.

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_break.h, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, test/fuzz/transformation_add_dead_break_test.cpp, test/fuzz/transformation_add_dead_continue_test.cpp
The implementation of these passes had overlooked the fact that adding
a new edge to a control flow graph can change dominance information.
Adding a dead break/continue risks causing uses to no longer be
dominated by their definitions.  This change introduces various tests
to expose such scenarios, and augments the preconditions for these
transformations with checks to guard against the situation.
=> Fix add-dead-break and add-dead-continue passes to respect dominance

source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/fuzzer_pass_permute_blocks.cpp, source/fuzz/fuzzer_pass_split_blocks.cpp
Before this change there was quite a lot of duplication in the code
being used to choose random percentages, and some of it was incorrect
so that a percentage chance of (100-N)% instead of N% was being used.
Also there was a lot of duplicate code to choose a random index into a
vector.  This change eliminates that duplication (fixing up the
percentage problem), and gets rid of direct access to the random
number generator being used for fuzzing, so that all randomization
requests must go through the FuzzerContext class, discouraging future
ad-hoc uses of the random number generator.
=> Rework management of probabilities in spirv-fuzz

source/text.cpp, test/assembly_format_test.cpp, test/c_interface_test.cpp, test/opt/ccp_test.cpp, test/opt/copy_prop_array_test.cpp, test/opt/optimizer_test.cpp, test/opt/upgrade_memory_model_test.cpp, test/text_to_binary.constant_test.cpp, test/text_to_binary.control_flow_test.cpp, test/val/val_adjacency_test.cpp, test/val/val_atomics_test.cpp, test/val/val_id_test.cpp, test/val/val_image_test.cpp, test/val/val_limits_test.cpp
Fix tests that violated this rule.
Fixes #2257
=> Assembler: Can't set an ID in instruction without result ID

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_copy_objects.cpp, source/fuzz/fuzzer_pass_copy_objects.h, source/fuzz/transformation.cpp, source/fuzz/transformation_copy_object.cpp, source/fuzz/transformation_copy_object.h
A new fuzzer pass that randomly introduces OpCopyObject instructions
that make copies of ids, and uses the fact manager to record the fact
that an id %id is synonymous with an id generated by an OpCopyObject
applied to %id.  (A future pass will exploit such synonym facts.)
=> Add fuzzer pass to copy objects

source/val/validate_decorations.cpp, source/val/validate_memory.cpp, test/val/val_decoration_test.cpp, test/val/val_memory_test.cpp
* Vulkan specific checks
* storage buffer variables must be structs or arrays of structs
* storage buffer struct must be Block decorated
* uniform struct must be Block or BufferBlock decorated
* new tests
Also tested against CTS.
=> Extra resource interface validation

BUILD.gn
Most auto-generated files included by the SPIRV-Tools sources
do not have a proper newline at the end of file, creating a
hundred of compiler warnings, and even some build failures
when BUILD.gn is used for the Fuchsia build.
This fixes the issue by disabling the warning entirely.
=> Fix Fuchsia build.

source/val/validate_conversion.cpp, test/val/val_conversion_test.cpp
In SPIR-V 1.5 or in the presence of SPV_KHR_physical_storage_buffer allow bitcast between pointers and 32-bit integer vectors.
New tests
=> Relaxed bitcast with pointers

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.h, source/fuzz/id_use_descriptor.cpp, source/fuzz/id_use_descriptor.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h, test/fuzz/fuzzer_shrinker_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
If the fuzzer's fact manager knows that ids A and B are synonymous, it
can replace a use of A with a use of B, so long as various conditions
hold (e.g. the definition of B must dominate the use of A, and it is
not legal to replace a use of an OpConstant in a struct's access chain
with a synonym that is not an OpConstant).
This change adds a fuzzer pass to sprinke such synonym replacements
through the module.
=> Add fuzzer pass to replace ids with synonyms

source/fuzz/CMakeLists.txt
spirv-fuzz generates protobuf sources in a 'protobuf' directory.  When
building with Unix Makefiles, compilation would fail due to to this
directory not existing.  This change causes the directory to be
created when the build is prepared.
=> Fix CMake issue related to spirv-fuzz

Android.mk
This is required to fix the NDK build.
=> Android.mk: Add dependency from optimizer file to amd-shader-ballot-insts.inc

source/opt/copy_prop_arrays.cpp, test/opt/copy_prop_array_test.cpp
Many of the places in copy propagate arrays assumes that integer constant will be defined by an OpConstant instruction.  That is not always true.  We fix these spots by allowing for an OpConstantNull.
Fixes #2869.
=> Handle OpConstantNull in copy-prop-arrays.

test/fuzz/CMakeLists.txt
spirv-fuzz has useful tests that run the fuzzer and shrinker, to give
the whole tool a good shake up, effectively "fuzzing the fuzzer".  The
problems that this detects are sensitive to the source of randomness
that is used, which can change from test platform to test platform.
It is thus not a good idea to run these tests by default during
continuous integration - they may end up failing due to environtal
factors, making it look like an unrelated change has broken the fuzzer
when really the fuzzer has revealed an already-existing bug in itself.
This change makes the tests disabled by default; they can enabled
during dedicated testing of the fuzzer.
=> Disable long-running fuzzer tests by default

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h, source/spirv_fuzzer_options.cpp, source/spirv_fuzzer_options.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, tools/fuzz/fuzz.cpp
To aid in debugging issues in spirv-fuzz, this change adds an option whereby the SPIR-V module is validated after each transformation is applied during replay.  This can assist in finding a transformation that erroneously makes the module invalid, so that said transformation can be debugged.
=> Allow validation during spirv-fuzz replay

test/fuzz/CMakeLists.txt
A previous change that disabled long-running tests by default failed
to enable short-running tests when long-running tests are enabled.
This change fixes that problem.
=> Fix to CMakeLists for spirv-fuzz tests

source/opt/ir_builder.h, source/opt/wrap_opkill.cpp, source/opt/wrap_opkill.h, test/opt/wrap_opkill_test.cpp
The warp-opkill pass is generating incorrect code.  It is placing an
OpUnreachable at the end of a basic block, when the block can be
reached.  We can't reach the end of the block, but we can reach the end.
Instead we will add a return instruction.
Fixes #2875.
=> Use OpReturn* in wrap-opkill

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/transformation_move_block_down.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, test/fuzz/transformation_split_block_test.cpp
This change to spirv-fuzz uses ideas from "Swarm Testing" (Groce et al. 2012), so that a random subset of fuzzer passes are enabled.  These passes are then applied repeatedly in a randomized fashion, with the aggression with which they are applied being randomly chosen per pass.
There is plenty of scope for refining the probabilities introduce in this change; this is just meant to be a reasonable first effort.
=> Employ the "swarm testing" idea in spirv-fuzz

tools/sva/src/parser.js, tools/sva/src/parser_test.js
This CL adds a test for OpCopyMemory and adds the needed IdMemorySemantics and
IdScope in order to extract the parameters.
=> Add OpCopyMemory test to SVA.

source/opt/folding_rules.cpp, source/opt/scalar_replacement_pass.cpp, test/opt/fold_test.cpp, test/opt/scalar_replacement_test.cpp
It is possible that OpCompositeExtract instructions will not have any
indexes.  This is not handled well by scalar replacement and instruction
folding.
Fixes https://crbug.com/1006435
=> Handle extract with no indexes

source/fuzz/transformation_replace_boolean_constant_with_constant_binary.cpp, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.h, test/fuzz/transformation_replace_boolean_constant_with_constant_binary_test.cpp
Before this change, spirv-fuzz would replace a constant boolean
argument to an OpPhi with the result of a binary operation, inserting
the instruction to compute the binary operation right before the
OpPhi, leading to an invalid module.  This change conservatively
disallows replacing OpPhi arguments.  Issue #2902 notes that there is
scope for being less conservative.
Fixes #2897.
=> spirv-fuzz: do not replace boolean constant argument to OpPhi instruction

source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Before this change, spirv-fuzz would replace a pointer argument to a
function call with a synonym, which is problematic when the synonym is
not a memory object declaration, since function call arguments are
required to be memory object declarations.  This change adds a check
to ensure that such a replacement is not made.
Fixes #2896.
=> spirv-fuzz: do not replace a pointer argument to a function call with a synonym

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, test/fuzz/transformation_add_dead_continue_test.cpp
Issues #2898 and #2900 identify some cases where adding a dead
continue would lead to an invalid module, and these turned out to be
due to the lack of sensible dominance information when a continue
target is unreachable.  This change requires that the header of a loop
dominates the loop's continue target if a dead continue is to be
added.
Furthermore, issue #2905 identified a shortcoming in the algorithm
being used to identify when it is OK, from a dominance point of view,
to add a new break/continue edge to a control flow graph.  This change
replaces that algorithm with a simpler and more obviously correct
algorithm (that incidentally does not require the new edge to be a
break/continue edge in particular).
Fixes #2898.
Fixes #2900.
Fixes #2905.
=> spirv-fuzz: Fixes to preconditions for adding dead break/continue edges

source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
This change introduces a robust check for whether an index in an
access chain is indexing into a struct, in which case the index needs
to be an OpConstant and cannot be replaced with a synonym.
Fixes #2906.
=> spirv-fuzz: do not replace struct indices with synonyms

source/opt/wrap_opkill.cpp, test/opt/wrap_opkill_test.cpp
New code in wrap-opkill does not handle id overflow correctly.  We fix that up.
Fixes https://crbug.com/1007144
=> Handle id overflow in wrap-opkill

source/val/validate_id.cpp, test/val/val_data_test.cpp, test/val/val_id_test.cpp
Fixes https://crbug.com/1008130
* Restore a missing check that the only valid forward references in
structs are previously declared forward pointers
=> Only allow previously declared forward refs in structs

source/fuzz/transformation_move_block_down.cpp
The performance of the fuzzer was unacceptable in the 'permute blocks'
transformation, due to dominator analysis being repeatedly invalidated
and recomputed.  This change preserves the dominator analysis,
together with the CFG analysis, when a block is moved down.
=> spirv-fuzz: preserve some analyses when permuting blocks

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, test/fuzz/transformation_add_dead_break_test.cpp
Because dominance information becomes a bit unreliable when blocks are
unreachable, this change makes it so that the 'dead break'
transformation will not introduce a break to an unreachable block.
Fixes #2907.
=> spirv-fuzz: do not allow a dead break to target an unreachable block

source/val/validate_instruction.cpp, source/val/validate_memory.cpp, source/val/validate_misc.cpp, source/val/validate_mode_setting.cpp, source/val/validate_type.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_cfg_test.cpp, test/val/val_opencl_test.cpp, test/val/val_storage_test.cpp, test/val/val_webgpu_test.cpp
* move checks to more appropriate locations
* remove some duplicated checks
* New function to check valid storage classes
* updated tests
A couple of memory model tests are no longer testable, but the location is still more appropriate.
=> Refactor the InstructionPass

source/opt/ir_loader.cpp, source/opt/module.cpp, source/opt/module.h, source/opt/strip_debug_info_pass.cpp, test/opt/module_test.cpp, test/opt/strip_debug_info_test.cpp
There is nothing in the spir-v spec that says the last
instructions in a module cannot be OpLine or OpNoLine.
However, the code that parses the module will simply drop
these instructions.
We add code that will preserve these instructions.
Strip-debug-info is updated to remove these instructions.
Fixes https://crbug.com/1000689.
=> Record trailing line dbg instructions

source/opt/cfg.h, source/opt/ir_context.h, source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/struct_cfg_analysis_test.cpp
Add the ability to identify which blocks are in the continue construct for a
loop, and to get functions that are called from those blocks, directly or
indirectly.
Part of https://github.com/KhronosGroup/SPIRV-Tools/issues/2912.
=> Add continue construct analysis to struct cfg analysis

tools/fuzz/fuzz.cpp
And relax naming requirements of input and output files.
=> fuzz: add shrinker-temp-file-prefix

source/val/validate_constants.cpp, source/val/validate_memory.cpp, test/opt/inst_buff_addr_check_test.cpp, test/val/val_constants_test.cpp, test/val/val_memory_test.cpp
* Physical storage buffer cannot be used with OpConstantNull,
OpPtrEqual, OpPtrNotEqual or OpPtrDiff
* new tests
* see also #2929
=> Validate physical storage buffer restrictions

tools/fuzz/fuzz.cpp, tools/reduce/reduce.cpp
* reduce: add -o. 
* reduce: add --temp-file-prefix. 
* reduce: add interestingness test args. 
* Detect bad args with one dash e.g. -a. 
* reduce: fix validator args. 
* Add = to args that require it. 
* More consistent naming/style across fuzz/reduce. 
* Change some 0 exit codes to 1.
=> reduce/fuzz: improve command line args

source/val/validate_misc.cpp, test/val/val_misc_test.cpp
Add checks for SPV_KHR_shader_clock
1) Check that the Result Type must be a 64-bit unsigned integer type or a vector of two-components of 32-bit unsigned integer.
2) Check for a valid execution scope.
=> Add SPV_KHR_shader_clock validation

source/fuzz/CMakeLists.txt, source/fuzz/force_render_red.cpp, source/fuzz/force_render_red.h, tools/fuzz/fuzz.cpp
Adds a spirv-fuzz option for converting a SPIR-V shader into a shader
that renders red, whilst containing the body of the original shader.
This is for aiding in compiler crash bug reporting.
=> spirv-fuzz: option to convert shader into a form that renders red

source/opt/inline_pass.cpp, source/opt/inline_pass.h, source/opt/wrap_opkill.cpp, test/opt/inline_test.cpp, test/opt/wrap_opkill_test.cpp
We want to handle OpKill better.  The wrap opkill causes lots of extra
code to be generated, even when they are not needed to avoid the main
problem: OpKill cannot be found directly in a continue construct.
This change will be more selective on which functions the OpKill will be
wrapped and inlining will avoid inlining.
Fixes #2912
=> Handle OpKill better

source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h, test/opt/type_manager_test.cpp
spirv-opt was failing during constant specialization of OpTypeCooperativeMatrix (see Vulkan-ValidationLayers #1166).
=> Enable OpTypeCooperativeMatrix specialization

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_useful_constructs.cpp, source/fuzz/fuzzer_pass_adjust_selection_controls.cpp, source/fuzz/fuzzer_pass_adjust_selection_controls.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_set_selection_control.cpp, source/fuzz/transformation_set_selection_control.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_set_selection_control_test.cpp
A new pass that allows the fuzzer to change the 'selection control'
operand of OpSelectionControl instructions.
Fixes #2937.
=> spirv-fuzz: Add fuzzer pass to change selection controls

source/fuzz/fuzzer_util.cpp, test/fuzz/transformation_add_dead_continue_test.cpp
Issue #2919 identifies a problem in spirv-fuzz's ability to determine
when it is safe to add a new control flow edge without breaking
dominance rules.  This change adds a (currently disabled) test to
expose the issue, and a comment to document that the current solution
is incomplete.
=> spirv-fuzz: add disabled test to document known issue

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_adjust_loop_controls.cpp, source/fuzz/fuzzer_pass_adjust_loop_controls.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_set_loop_control.cpp, source/fuzz/transformation_set_loop_control.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, test/fuzz/transformation_set_loop_control_test.cpp
A new pass that allows the fuzzer to change the 'loop control' operand
(and associated literal operands) of OpLoopMerge instructions.
Fixes #2938.
Fixes #2943.
=> spirv-fuzz: Add fuzzer pass to change loop controls

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_adjust_function_controls.cpp, source/fuzz/fuzzer_pass_adjust_function_controls.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_set_function_control.cpp, source/fuzz/transformation_set_function_control.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_set_function_control_test.cpp
A new pass that allows the fuzzer to change the 'function control'
operand of OpFunction instructions.
Fixes #2939.
=> spirv-fuzz: Add fuzzer pass to change function controls

source/fuzz/CMakeLists.txt, source/fuzz/force_render_red.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/id_use_descriptor.cpp, source/fuzz/id_use_descriptor.h, source/fuzz/instruction_descriptor.cpp, source/fuzz/instruction_descriptor.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.cpp, source/fuzz/transformation_replace_constant_with_uniform.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_boolean_constant_with_constant_binary_test.cpp, test/fuzz/transformation_replace_constant_with_uniform_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
A refactoring that separates the identification of an instruction from
the identification of a use in an instruction, to enable the former to
be used independently of the latter.
=> spirv-fuzz: Rework id descriptors

source/val/validate_cfg.cpp, test/opt/if_conversion_test.cpp, test/val/val_cfg_test.cpp
Validate that all selections are structured (i.e. are preceeded by a merge instruction) where necessary.
Checks that switches and conditional branches are preceeded by a merge instruction if two or more  unique targets have not yet been encountered in a reverse post order traversal. This intentional does not flag code like:
```
%b0 = OpLabel
OpSelectionMerge %b3 None
OpBranchConditional %c1 %b1 %b2
%b1 = OpLabel
OpBranchConditional %c2 %b2 %b3 ; not an error
%b2 = OpLabel
OpBranch %b3
%b3 = OpLabel
```
Updated a few offending unit tests. Tested against CTS.
=> Validate that selections are structured

source/fuzz/fuzzer_pass_split_blocks.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_split_block.cpp, source/fuzz/transformation_split_block.h, test/fuzz/transformation_split_block_test.cpp
This change refactors the 'split blocks' transformation so that an
instruction is identified via a base, opcode, and number of those
opcodes to be skipped when searching from the base, as opposed to the
previous design which used a base and offset.
=> spirv-fuzz: Refactor 'split blocks' to identify instructions differently

source/val/validate_derivatives.cpp, test/val/val_derivatives_test.cpp
* Add a check that derivative functions only operate on scalar or vector
32-bit floating point values
* Added tests to disallow half derivatives
=> Check that derivatives operate on 32-bit values

source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
We have a check that ensures that the optimizer did not change the
binary when it says that it did not.  However, when the binary is
converted back to a binary, we made a decision to remove OpNop
instructions.  This means that any spv file that contains a NOP
originally will fail this check.
To get around this, we convert the module to a second binary that keeps
the OpNop instructions.  That binary is compared against the original.
Fixes https://crbug.com/1010191
=> Keep NOPs when comparing with original binary

utils/update_build_version.py
Thanks for implementing `SOURCE_DATE_EPOCH`. However, I think that the timestamp you then generate using `isoformat` varies with the build user's timezone. This should make it use UTC instead.
=> Ensure timestamp does not vary with timezone.

source/fuzz/fuzzer_pass_construct_composites.cpp, test/fuzz/fuzzer_replayer_test.cpp
Support for matrix composites had been omitted in a previous PR; this
change adds the support that was missing.
Fixes #2971.
=> spirv-fuzz: add missing functionality for matrix composites

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_adjust_memory_operands_masks.cpp, source/fuzz/fuzzer_pass_adjust_memory_operands_masks.h, source/fuzz/instruction_descriptor.cpp, source/fuzz/instruction_descriptor.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_set_memory_operands_mask.cpp, source/fuzz/transformation_set_memory_operands_mask.h, test/fuzz/CMakeLists.txt, test/fuzz/instruction_descriptor_test.cpp, test/fuzz/transformation_set_memory_operands_mask_test.cpp
A new pass that gives spirv-fuzz the ability to adjust the memory
operand masks associated with memory access instructions (such as
OpLoad and OpCopy Memory).
Fixes #2940.
=> spirv-fuzz: fuzzer pass to adjust memory access operands

source/fuzz/CMakeLists.txt, source/fuzz/equivalence_relation.h, test/fuzz/CMakeLists.txt, test/fuzz/equivalence_relation_test.cpp
Adds a templated class for representing an equivalence relation on a
value data type.  This will be used by spirv-fuzz for representing
sets of distinct pieces of data in a shader that are known to have
equal values.
=> spirv-fuzz: add class to represent equivalence relation

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_composite_construct.h, source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/CMakeLists.txt, test/fuzz/transformation_composite_construct_test.cpp
Class TransformationConstructComposite has been renamed to
TransformationCompositeConstruct, to correspond to the name of the
SPIR-V instruction (as is done with e.g. TransformationCopyObject).
Running tests revealed an issue related to checking dominance in
TransformationReplaceIdWithSynonym, which is also fixed here.
=> spirv-fuzz: rename class, and fix bug related to dominance

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_composite_extract.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_composite_extract_test.cpp
At present, TransformationReplaceIdWithSynonym both extracts elements
from composite objects and replaces uses of ids with synonyms.  This
new TransformationCompositeExtract class will allow that
transformation to be broken into smaller transformations.
=> spirv-fuzz: Transformation to extract from a composite object

source/opt/graphics_robust_access_pass.cpp, source/opt/graphics_robust_access_pass.h, test/opt/graphics_robust_access_test.cpp
One remains: the fact that the image-texel-pointer modification
is mostly dead code. But that's intentional for now.
=> Fix some clang-tidy issues in graphics_robust_access_pass

test/fuzzers/spvtools_dis_fuzzer.cpp
=> Reset pointers before iterating in fuzzer to avoid double free

source/fuzz/data_descriptor.cpp, source/fuzz/data_descriptor.h, source/fuzz/equivalence_relation.h, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_copy_object.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/equivalence_relation_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_copy_object_test.cpp
This change fixes a bug in EquivalenceRelation, changes the interface
of EquivalenceRelation to avoid exposing (potentially
nondeterministic) unordered sets, and changes the interface of
FactManager to allow querying data synonyms directly.  These interface
changes have required a lot of corresponding changes to client code
and tests.
=> spirv-fuzz: improvements to representation of data synonym facts

source/fuzz/equivalence_relation.h, test/fuzz/equivalence_relation_test.cpp
An equivalence relation is computed by traversing the tree of values
rooted at the class's representative.  Children were represented by
unordered sets, meaning that the order of values in an equivalence
class could be nondeterministic.  This change makes things
deterministic by representing children using a vector.
The path compression optimization employed in the implementation of
the underlying union-find data structure has the potential to change
the order in which elements appear in an equivalence class by changing
the structure of the tree, so the guarantee of determinism is limited
to being a deterministic function of the manner in which the
equivalence relation is updated and inspected.
=> spirv-fuzz: make equivalence classes deterministic

source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_copy_object_test.cpp
When a data synonym fact about two composites is added, data synonym
facts between all sub-components of the composites are also added.
Furthermore, when data synonym facts been all sub-components of two
composites are known, a data synonym fact relating the two composites
is added.  Identification of this case is done in a lazy manner, when
questions about data synonym facts are asked.
The change introduces helper methods to get the size of an array type
and the number of elements of a struct type, and fixes
TransformationCompositeExtract to invalidate analyses appropriately.
=> spirv-fuzz: better computation of data synonym facts

README.md
This change provides some information about spirv-fuzz in the
top-level SPIRV-Tools README.  A typo elsewhere in the README is also
fixed.
=> Add basic documentation about spirv-fuzz

source/fuzz/CMakeLists.txt, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_vector_shuffle.cpp, source/fuzz/transformation_vector_shuffle.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_vector_shuffle_test.cpp
Inroduces a new transformation that adds a vector shuffle instruction
to the module, with associated facts about how the result vector of
the shuffle relates to the input vectors.
A fuzzer pass to add such transformations is not yet in place.
=> spirv-fuzz: vector shuffle transformation

source/fuzz/fact_manager.cpp
This breaks builds on some Mac systems. Not sure why the bots miss it.
=> Remove semicolon

utils/update_build_version.py
The U qualifier (universal line endings) has no effect
in Python3. Remove its use to avoid a Python warning.
=> Python 3: remove deprecated U qualifier on 'open'

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/id_use_descriptor.cpp, source/fuzz/instruction_descriptor.cpp, source/fuzz/instruction_descriptor.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, test/fuzz/CMakeLists.txt, test/fuzz/data_synonym_transformation_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Prior to this change, TransformationReplaceIdWithSynonym was designed
to be able to replace an id with some synonymous data descriptor,
possibly necessitating extracting from a composite into a fresh id in
order to get at the synonymous data.  This change simplifies things so
that TransformationReplaceIdWithSynonym just allows one id to be
replaced by another id.  It is the responsibility of the associated
fuzzer pass - FuzzerPassApplyIdSynonyms - to perform the extraction
operations, using e.g. TransformationCompositeExtract.
=> spirv-fuzz: simplify transformation for replacing an id with a synonym

utils/vscode/src/grammar/grammar.go
The linter wants the comment on an exported constant to
begin with the name of the constant.
=> Try to fix go linter: exported constant comment

source/val/validate_decorations.cpp, test/opt/eliminate_dead_member_test.cpp, test/opt/graphics_robust_access_test.cpp, test/val/val_decoration_test.cpp, test/val/val_memory_test.cpp
Fixes #3027
* Disallow array stride 0
* Check array stride against element size
* Fix up tests
* Add new tests
Tested against Vulkan CTS.
=> Validate array stride does not cause overlap

source/opt/upgrade_memory_model.cpp, test/opt/upgrade_memory_model_test.cpp
Fixes #2992
* Accessing aggregate subtype used the wrong operand
* Added a test
=> Fix operand access of composite in upgrade memory model

source/fuzz/id_use_descriptor.cpp
Fixes
spirv-tools/source/fuzz/id_use_descriptor.cpp:58:46: error: ‘*((void*)& in_operand +32)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
in_operand_index);
^
=> Avoid uninit warning in GCC

source/opt/ir_context.cpp, source/opt/wrap_opkill.h
Wrap-opkill will create a new function, invalidating the id-to-func map.
The preserved analyses for the pass have been updated to reflect that.
Also adding consistency check for the id-to-func map.  With this new
check, old tests identify this problem.  No new tests are needed.
Fixes #3038
=> Kill the id-to-func map after wrap-opkill

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/spirv_fuzzer_options.cpp, source/spirv_fuzzer_options.h, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, tools/fuzz/fuzz.cpp
Adds an option to run the validator on the SPIR-V binary after each
fuzzer pass has been applied, to help identify when the fuzzer has
made the module invalid.  Also adds a helper method to allow dumping
of the sequence of transformations that have been applied to a JSON
file.
=> spirv-fuzz: Improve debugging facilities

source/opt/block_merge_util.cpp, source/opt/inline_pass.cpp, source/val/basic_block.h, source/val/function.cpp, source/val/validate_cfg.cpp, test/fuzz/transformation_add_dead_continue_test.cpp, test/fuzz/transformation_copy_object_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/block_merge_test.cpp, test/opt/dead_branch_elim_test.cpp, test/opt/inline_test.cpp, test/opt/local_ssa_elim_test.cpp, test/opt/loop_optimizations/fusion_legal.cpp, test/opt/pass_merge_return_test.cpp, test/reduce/reducer_test.cpp, test/reduce/validation_during_reduction_test.cpp, test/val/val_cfg_test.cpp
Validate the spec rule:
> when a construct contains another header block, it also contains that header’s corresponding merge block if that merge block is reachable in the CFG
Fixes #3031 
Identified problems in block merging and inlining. Block merging will no longer merge a continue target. Inlining a single block loop will not modify the continue target. Had to fix up many invalid tests.
=> Validate nested constructs

test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp
This change fixes some tests that turned out to be invalid; recent
improvements to the validator in #3068 exposed them as such.
=> spirv-fuzz: Fix invalid tests

include/spirv-tools/optimizer.hpp, source/opt/graphics_robust_access_pass.cpp, source/opt/graphics_robust_access_pass.h, source/val/basic_block.h, test/opt/graphics_robust_access_test.cpp
Access chain indices are always interpreted as signed integers.
So use signed clamp instead of unsigned clamp.  We must also
clamp to the max signed int for the index type.
Fixes #3072
=> graphics robust access: use signed clamp

source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
continuing #3063 
fixing #3052
=> Remove stripping debug info when converting Vulkan to WebGPU in optimizer

source/val/validate_type.cpp, test/val/val_id_test.cpp
Khronos SPIR-V internal issue 524
=> WebGPU: Array size at most max signed int + 1

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_break.h, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, test/fuzz/transformation_add_dead_continue_test.cpp
The passes that add dead breaks and continues suffer from the
challenge that a new control flow graph edge can change dominance
information, leading to the potenital for definitions to no longer
dominate their uses.  The attempt at guarding against this was known
to be incomplete.  This change calls on the SPIR-V validator to do the
necessary checking: in deciding whether adding such an edge would be
legitimate, we clone the module, add the edge, and use the validator
to check whether the transformed clone is valid.
This strategy is heavy-weight, and should be used sparingly, but seems
like a good option when the validity of transformations is intricate,
to avoid reimplementing swathes of validation logic in the fuzzer.
Fixes #2919.
=> spirv-fuzz: Use validator to check break/continue dominance conditions

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
An OpCompositeConstruct of an empty struct will be folded to a constant
under normal circumstances.  However, if the id limit has been reached
and the constant cannot be generated, then other folding rules will be
tried.
These rules do not handle the case of an empty struct.  We add allow it
to be handled.
Fixes http://crbug/1030194
=> Don't crash when folding construct of empty struct

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_constant_composite.cpp, source/fuzz/transformation_add_constant_composite.h, source/fuzz/transformation_add_global_undef.cpp, source/fuzz/transformation_add_global_undef.h, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, source/fuzz/transformation_add_type_array.cpp, source/fuzz/transformation_add_type_array.h, source/fuzz/transformation_add_type_function.cpp, source/fuzz/transformation_add_type_function.h, source/fuzz/transformation_add_type_matrix.cpp, source/fuzz/transformation_add_type_matrix.h, source/fuzz/transformation_add_type_struct.cpp, source/fuzz/transformation_add_type_struct.h, source/fuzz/transformation_add_type_vector.cpp, source/fuzz/transformation_add_type_vector.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_constant_composite_test.cpp, test/fuzz/transformation_add_global_undef_test.cpp, test/fuzz/transformation_add_global_variable_test.cpp, test/fuzz/transformation_add_type_array_test.cpp, test/fuzz/transformation_add_type_function_test.cpp, test/fuzz/transformation_add_type_matrix_test.cpp, test/fuzz/transformation_add_type_struct_test.cpp, test/fuzz/transformation_add_type_vector_test.cpp
This change adds several transformations that allow types, constants,
undefined values and global variables to be added to a module.
=> spirv-fuzz: Transformations to add types, constants and variables

source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, test/fuzz/transformation_add_global_variable_test.cpp
In the context of SPIR-V 1.4 or higher, global variables cannot be
used by an instruction unless they are listed in the interface of all
entry points that might invoke the instruction.  This change
conservatively adds new global variables to the interfaces of all
entry points (if the SPIR-V version is 1.4 or higher).
Issue #3111 notes that a more rigorous approach to entry point
interfaces could be taken in spirv-fuzz, which would allow being less
conservative here.
=> spirv-fuzz: Always add new globals to entry point interfaces

test/opt/pass_fixture.h
=> Avoid pessimizing std::move

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, source/fuzz/fuzzer_util.h, source/fuzz/instruction_message.cpp, source/fuzz/instruction_message.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, tools/fuzz/fuzz.cpp
This change adds a fuzzer pass that allows code from other SPIR-V
modules to be donated into the module under transformation.  It also
changes the command-line options of the tools so that, in fuzzing
mode, a file must be specified that contains the names of available
donor modules.
=> spirv-fuzz: Add fuzzer pass to perform module donation

BUILD.gn, utils/generate_grammar_tables.py
The utils/generate_grammar_tables.py vendor-operand-kind-prefix
can now take a value of "...nil..." to signify the empty string.
That's needed because GN doesn't quote empty string arguments
correctly down into its action commands.
Fixes #3120
=> Fix GN build for OpenCL.DebugInfo.100 update

source/link/linker.cpp, test/link/matching_imports_to_exports_test.cpp
There seems to be no reason to keep the original variable/function/parameter decorations around for import symbols, as the corresponding exports should either match them or should override them. At least that's my understanding, but if there are any exceptions to that please let me know.
Also, with this change the generated module won't have stale decoration and name instructions referring to ids which no longer exist after linking.
=> Remove names and decorations of imported symbols

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_dead_blocks.cpp, source/fuzz/fuzzer_pass_add_dead_blocks.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_dead_block.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, source/fuzz/transformation_split_block.cpp, source/fuzz/transformation_split_block.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzz_test_util.cpp, test/fuzz/transformation_add_dead_block_test.cpp, test/fuzz/transformation_split_block_test.cpp
This adds a new kind of fact to the fact manager that knows whether a
block is dead - i.e. guaranteed to be statically unreachable - and a
new transformation for adding a selection construct to a CFG that
conditionally branches to a fresh, dead block, such that the branch
will never be dynamically taken.  Transformations that may create new
blocks ('split block' and 'outline function') are updated to propagate
dead block facts to newly-created blocks where appropriate.  A fuzzer
pass randomly adds dead blocks to the module.
Future transformations will be able to exploit the fact that such
blocks are known to be dead.
=> spirv-fuzz: add dead blocks

source/opt/block_merge_util.cpp, source/opt/instruction.h, test/opt/block_merge_test.cpp
As explained in #3118, spirv-opt merge-blocks pass causes a
spirv-val error when an OpBranch has an OpLine in front of it.
OpLoopMerge
OpBranch ; Will be killed by merge-blocks pass
OpLabel  ; Will be killed by merge-blocks pass
OpLine   ; will be placed between OpLoopMerge and OpBranch - error!
OpBranch
To fix this issue, this commit moves line info of OpBranch to
OpLoopMerge.
Fixes #3118
=> Fix OpLine bug of merge-blocks pass

source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation.cpp, source/fuzz/transformation.h, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/transformation_outline_function_test.cpp
This change refactors some code for walking access chain indexes to
make it mirror the structure of other code (to improve readability in
the first instance and potentially enable a future refactoring to
extract common code), and fixes a problem related to module donation
and function types.
=> spirv-fuzz: Refactoring and type-related fixes

DEPS
$ git log af64a9e82..dc77030ac --date=short --no-merges --format='%ad %ae %s'
2020-01-20 dneto Fix the license to match LICENSE
2020-01-20 syoussefi Add BUILD.gn
2019-11-20 Tobias.Hector Off-by-one errors
2019-11-20 Tobias.Hector Reserve a new block of 64 opcodes
Created with:
roll-dep external/spirv-headers
=> Roll external/spirv-headers/ af64a9e82..dc77030ac (4 commits)

include/spirv-tools/libspirv.h, source/spirv_target_env.cpp, test/target_env_test.cpp
This new API lets clients request a minimal spv_target_env value
that supports a given Vulkan and SPIR-V version, by a generic
numbering scheme (as already defined by Vulkan and SPIR-V specs).
This breaks a formal source dependency from Glslang to SPIRV-Tools.
When a new API is rolled out, such as Vulkan 1.2, Glslang currently
needs to reference a specific SPIRV-Tools enum by name.
=> Add spvParseVulkanEnv

source/val/construct.cpp, source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
Fixes #3139
* If the header of the construct is also a merge block, jump to the
associated header instead of the immediate dominator
* new test
=> Fix structured exit validation

source/opt/dead_branch_elim_pass.cpp, source/opt/dead_branch_elim_pass.h, test/opt/dead_branch_elim_test.cpp
We must treat a branch to the merge node of a switch that is in the
header of a construct as a nested construced.  The original merge
instruction is still needed in that case.
=> Dead branch elim fix

source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, source/fuzz/fuzzer_util.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_function.h, source/fuzz/transformation_outline_function.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/transformation_add_dead_break_test.cpp, test/fuzz/transformation_add_function_test.cpp, test/fuzz/transformation_outline_function_test.cpp
This change allows the generator to (optionally and at random) make
the functions of a module "livesafe" during donation.  This involves
introducing a loop limiter variable to each function and gating the
number of total loop iterations for the function using that variable.
It also involves eliminating OpKill and OpUnreachable instructions
(changing them to OpReturn/OpReturnValue), and clamping access chain
indices so that they are always in-bounds.
=> spirv-fuzz: Make functions "livesafe" during donation

source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, test/fuzz/transformation_add_function_test.cpp, test/fuzz/transformation_add_global_variable_test.cpp, test/fuzz/transformation_outline_function_test.cpp
This change adds a new kind of fact to the fact manager, which records
when a variable (or pointer parameter) refers to an arbitrary value,
so that anything can be stored to it, without affecting the observable
behaviour of the module, and nothing can be guaranteed about values
loaded from it.  Donated modules are the current source of such
variables, and other transformations, such as outlining, have been
adapted to propagate these facts appropriately.
=> spirv-fuzz: Arbitrary variable facts

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
This change adds support for folding of sin/cos/tan/asin/acos/atan,
exp/log/exp2/log2, sqrt, atan2 and pow.
The mechanism allows to use any C function to implement folding in the
future; for now I limited the actual additions to the most commonly used
intrinsics in the shaders.
Unary folder had to be tweaked to work with extended instructions - for
extended instructions, constants.size() == 2 and constants[0] ==
nullptr. This adjustment is similar to the one binary folder already
performs.
Fixes #1390.
=> Implement constant folding for many transcendentals

source/opt/amd_ext_to_khr.cpp, test/opt/amd_ext_to_khr.cpp
This adds support for replacing TimeAMD with OpReadClockKHR.  The scope
for OpReadClockKHR is fixed to be a subgroup because TimeAMD operates
only on subgroup.
Part of #2814
=> Handle TimeAMD in AmdExtensionToKhrPass.

source/fuzz/fuzzer_util.cpp, source/fuzz/transformation_copy_object.h, test/fuzz/transformation_copy_object_test.cpp
If the fuzzer object-copies a pointer we would like to be able to
perform loads from the copy (and stores to it, if its value is known
not to matter).  Undefined and null pointers present a problem here,
so this change disallows copying them.
=> spirv-fuzz: Disallow copying of null and undefined pointers

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_composite_types.cpp, source/fuzz/fuzzer_pass_add_composite_types.h, source/fuzz/transformation_add_type_matrix.h, source/fuzz/transformation_add_type_vector.h, utils/check_copyright.py
Adds a fuzzer pass that randomly adds vector and matrix types not
already present in the module, and randomly adds structs with random
field types and arrays with random base types and sizes.  Other passes
will be able to create variables and ids using these types.
=> spirv-fuzz: Fuzzer pass to add composite types

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_global_variables.cpp, source/fuzz/fuzzer_pass_add_global_variables.h, source/fuzz/fuzzer_pass_add_local_variables.cpp, source/fuzz/fuzzer_pass_add_local_variables.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_local_variable.cpp, source/fuzz/transformation_add_local_variable.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_local_variable_test.cpp
Adds two new fuzzer passes to add variables to a module: one that adds
Private storage class global variables, another that adds Function
storage class local variables.
=> spirv-fuzz: Fuzzer passes to add local and global variables

source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_load.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/transformation_add_global_variable_test.cpp
This change ensures that global and local variables donated from other
modules are always initialized at their declaration in the module
being transformed.  This is to help limit issues related to undefined
behaviour that might arise due to accessing uninitialized memory.
The change also introduces some helper functions in fuzzer_util to
make it easier to find the pointee types of pointer types.
=> spirv-fuzz: Ensure that donated variables are always initialized

source/fuzz/CMakeLists.txt, source/fuzz/call_graph.cpp, source/fuzz/call_graph.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_pass_add_function_calls.h, source/fuzz/fuzzer_pass_add_loads.cpp, source/fuzz/fuzzer_pass_add_stores.cpp, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_pass_copy_objects.cpp, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_function_call.cpp, source/fuzz/transformation_function_call.h, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.cpp, source/fuzz/transformation_replace_constant_with_uniform.cpp, test/fuzz/CMakeLists.txt, test/fuzz/transformation_function_call_test.cpp, test/fuzz/transformation_replace_boolean_constant_with_constant_binary_test.cpp, test/fuzz/transformation_replace_constant_with_uniform_test.cpp
Adds a fuzzer pass that inserts function calls into the module at
random.  Calls from dead blocks can be arbitrary (so long as they do
not introduce recursion), while calls from other blocks can only be to
livesafe functions.
The change fixes some oversights in transformations to replace
constants with uniforms and to obfuscate constants which testing of
this fuzzer pass identified.
=> spirv-fuzz: Fuzzer pass to add function calls

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_add_access_chains.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_access_chain.cpp, source/fuzz/transformation_access_chain.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_access_chain_test.cpp
This change adds a fuzzer pass that sprinkles access chain
instructions into a module at random.  This allows other passes to
have a richer set of pointers available to them, in particular the
passes that add loads and stores.
=> spirv-fuzz: Fuzzer pass that adds access chains

source/fuzz/fuzzer_pass_donate_modules.cpp
This fixes a bug where the type id of a type instruction, rather than
its result id, was being used.  It also favours using zero as the
return value when replacing an OpKill or OpUnreachable with a return
instruction, and adds a check that the donor module is valid when
doing module donation.
Fixes #3187.
=> spirvfuzz: Fix type-related bug, change undef to zero, and add assert

source/val/validate_image.cpp, test/val/val_image_test.cpp
According to SPV_AMD_shader_image_load_store_lod spec, Lod operand is
valid with OpImageRead, OpImageWrite, or OpImageSparseRead if the
extension is enabled.
=> spirv-val: Add support for SPV_AMD_shader_image_load_store_lod

utils/vscode/src/schema/schema.go, utils/vscode/src/schema/schema.go.tmpl
These were declared in the `Opcode` struct type, but were never assigned.
They're not actually used by the language server, but I reused this go schema package for a local experiment and found they were missing.
=> vscode: Add missing fields to schema.Opcode

include/spirv-tools/libspirv.h, source/opcode.cpp, source/opcode.h
=> Make spvOpcodeString part of the public API

source/opcode.cpp
This is preventing me from building SPIRV-Tools with SPIRV_WERROR on Fedora 31 (GCC 9.2.1).
=> Fix ignored const qualifier warning in static_cast

source/val/validate.cpp, source/val/validation_state.cpp
Part of https://bugs.chromium.org/p/chromium/issues/detail?id=1039697
=> Fix Wrange-loop-analysis warnings in SPIRV-Tools.

Android.mk, BUILD.gn, build_defs.bzl, source/CMakeLists.txt, utils/generate_language_headers.py
Some build systems such as Android blueprints require that the inputs
and outputs of generator scripts are all provided as arguments.  These
two arguments to generate_language_headers.py are combined to form the
output path in the script.  This change simply lets the user provide the
whole output path as an argument.
I wasn't able to test to bazel build files locally.
=> Combine extinst-name and extinst-output-base into one arg.

source/val/validate_extensions.cpp, source/val/validate_id.cpp, test/val/val_ext_inst_test.cpp
Add validation rules for DebugCompilationUnit, DebugSource,
DebugTypeBasic, DebugTypeVector, DebugTypeArray, DebugTypedef,
DebugTypeFunction, DebugTypeEnum, DebugTypeComposite,
DebugTypeMember, DebugTypeInheritance, DebugFunction,
DebugFunctionDeclaration, DebugLexicalBlock, DebugScope,
DebugLocalVariable, DebugDeclare, DebugExpression.
=> Add validation rules for OpenCL.DebugInfo.100 extension

utils/generate_registry_tables.py
Required for compatibility with (some?) Python3 installations.
=> Avoid use of Python distutils.dir_util

source/fuzz/fuzzer_pass_add_no_contraction_decorations.cpp, source/fuzz/fuzzer_pass_adjust_function_controls.cpp, source/fuzz/fuzzer_pass_adjust_loop_controls.cpp, source/fuzz/fuzzer_pass_adjust_memory_operands_masks.cpp, source/fuzz/fuzzer_pass_adjust_selection_controls.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
In this PR, the duplicated scope of  `FuzzerPass::ApplyTransformation` was replaced by its call.
=> spirv-fuzz: Refactor FuzzerPass::ApplyTransformation code duplication

source/fuzz/CMakeLists.txt, source/fuzz/equivalence_relation.h, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/fuzzer_pass_add_equation_instructions.h, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_equation_instruction.cpp, source/fuzz/transformation_equation_instruction.h, test/fuzz/CMakeLists.txt, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp
This introduces a new fuzzer pass to add instructions to the module
that define equations, and support in the fact manager for recording
equation facts and deducing synonym facts from equation facts.
Initially the only equations that are supported involve OpIAdd,
OpISub, OpSNegate and OpLogicalNot, but there is scope for adding
support for equations over various other operators.
=> spirv-fuzz: Fuzzer pass to add equation instructions

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_pass_swap_commutable_operands.cpp, source/fuzz/fuzzer_pass_swap_commutable_operands.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_swap_commutable_operands.cpp, source/fuzz/transformation_swap_commutable_operands.h, source/opcode.cpp, source/opcode.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_swap_commutable_operands_test.cpp, utils/check_copyright.py
In this PR, the classes that represent the swap commutable operands transformation and the fuzzer pass were implemented.
=> spirv-fuzz: Add swap commutable operands transformation

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_pass_add_loads.cpp, source/fuzz/fuzzer_pass_add_stores.cpp, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_pass_copy_objects.cpp
Changes FuzzerPass::MaybeAddTransformationBeforeEachInstruction to
FuzzerPass::ForEachInstructionWithInstructionDescriptor.
Fixes #3184.
=> spirv-fuzz: Use better function name

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_toggle_access_chain_instruction.cpp, source/fuzz/fuzzer_pass_toggle_access_chain_instruction.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_toggle_access_chain_instruction.cpp, source/fuzz/transformation_toggle_access_chain_instruction.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_toggle_access_chain_instruction_test.cpp
In this PR, the classes that represent the toggle access chain instruction transformation and fuzzer pass were implemented. This transformation toggles the instructions `OpAccessChain` and `OpInBoundsAccessChain` between them.
=> spirv-fuzz: Add toggle access chain instruction transformation

DEPS
https://github.com/KhronosGroup/SPIRV-Headers/compare/30ef660ce2e6...a17e17e36da4
$ git log 30ef660ce..a17e17e36 --date=short --no-merges --format='%ad %ae %s'
2020-03-13 jmadill Add missing header to BUILD.gn.
Created with:
roll-dep external/spirv-headers
@johnkslang @zoddicus PTAL
=> Roll external/spirv-headers/ 30ef660ce..a17e17e36 (1 commit)

source/opt/instruction.h, test/opt/instruction_test.cpp
It only works when the operand is a literal string.
=> Add opt::Operand::AsCString and AsString

source/opt/function.cpp, source/opt/function.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_loader.cpp, source/opt/ir_loader.h, source/opt/module.cpp, source/opt/module.h, source/opt/optimizer.cpp, test/opt/ir_loader_test.cpp
This commit adds data structures for rich debug info and lets ir_loader
and module correctly load/dump IR instructions.
- For debug instructions other than `DebugScope`, `DebugNoScope`,
`DebugDeclare`, `DebugValue`, we already added
`InstructionList ext_inst_debuginfo_` in `Module` class.
- For `DebugScope`/`DebugNoScope`, this commit adds
`struct DebugScope` in `Instruction` class.
- When ir_loader processes `DebugScope`/`DebugNoScope`, we update
`last_dbg_scope_` of ir_loader to update the last `DebugScope`
information. When ir_loader processes a terminator instruction or merge
instruction, it sets `last_dbg_scope_` as `DebugNoScope` because it is the
end of the scope. When module dumps IR, if the next `DebugScope` is new
scope information, it generates a `DebugScope` instruction. If …
=> Add data structures for DebugScope, DebugNoScope, DebugDeclare, DebugValue

source/opt/instruction.cpp, test/opt/instruction_test.cpp, test/opt/local_redundancy_elimination_test.cpp
Fixes #3252
* Image and buffer queries did not account for optional level of
arrayness on the variable
* new tests
=> Fix identification of Vulkan images and buffers

source/opt/wrap_opkill.cpp, test/opt/wrap_opkill_test.cpp
Fixes #3268
* Set the parent of the basic block for the wrapper function
* Add a test
=> Set wrapped kill basic block's parent

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, tools/fuzz/fuzz.cpp
Allows several validator options to be passed to the fuzzer, to be
used when validation is invoked during fuzzing.
=> spirv-fuzz: Add validator options

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
Fixes an issue where an id use in a non-regular context, e.g. as a
scope parameter to an atomic instruction, would be replaced with a
synonym.
=> spirv-fuzz: Only replace regular ids with synonyms

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_global_variables.cpp, source/fuzz/fuzzer_pass_add_local_variables.cpp
To avoid problems where global and local variables of opaque or
runtime-sized types are added to a module, this change introduces the
notion of a 'basic type' -- a type made up from floats, ints, bools,
or vectors, matrices, structs and fixed-size arrays of basic types.
Added variables have to be of basic type.
=> spirv-fuzz: Limit adding of new variables to 'basic' types

source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_pass_construct_composites.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_construct_composites_test.cpp
The fuzzer pass that constructs composites had an issue where it would
regard isomorphic but distinct structs (similarly arrays) as being
interchangeable when constructing composites.  This change fixes the
problem by relying less on the type manager.
=> spirv-fuzz: Handle isomorphic types property in composite construction

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_constant_null.cpp, source/fuzz/transformation_add_constant_null.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/transformation_add_constant_null_test.cpp
Adds a transformation for adding OpConstantNull to a module, for
appropriate data types.
=> spirv-fuzz: Transformation to add OpConstantNull

source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_pass_add_global_variables.cpp, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/transformation_add_global_variable_test.cpp
(1) Runtime arrays are turned into fixed-size arrays, by turning
OpTypeRuntimeArray into OpTypeArray and uses of OpArrayLength into
uses of the constant used for the length of the fixed-size array.
(2) Atomic instructions are not donated, and uses of their results are
replaced with uses of constants of the result type.
=> spirv-fuzz: Improve support for compute shaders in donation

source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, test/fuzz/fuzzer_pass_donate_modules_test.cpp
This change increases the extent to which arbitrary SPIR-V can be used
by the fuzzer pass that donates modules.  It handles the case where
various ingredients (such as types, variables and particular
instructions) cannot be donated by omitting them, and then either
omitting their dependencies or replacing their dependencies with
alternative instructions.
The change pays particular attention to allowing code that manipulates
image types to be handled (by skipping anything image-specific).
=> spirv-fuzz: Handle more general SPIR-V in donation

source/fuzz/equivalence_relation.h, source/fuzz/fact_manager.cpp, test/fuzz/equivalence_relation_test.cpp, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp
The management of equation facts suffered from two problems:
(1) The processing of an equation fact required the data descriptors
used in the equation to be in canonical form.  However, during
fact processing it can be deduced that certain data descriptors
are equivalent, causing their equivalence classes to be merged,
and that could cause previously canonical data descriptors to no
longer be canonical.
(2) Related to this, if id equations were known about a canonical data
descriptor dd1, and other id equations known about a different
canonical data descriptor dd2, the equation facts about these data
descriptors were not being merged in the event that dd1 and dd2
were deduced to be equivalent.
This changes solves (1) by not requiring equation facts to be in
canonical form while processing …
=> spirv-fuzz: Improve the handling of equation facts

CMakeLists.txt
clang-cl does not handle precompiled headers with the same setup as MSVC very well. So fixing the macro in CMake to skip adding precompiled headers when building with clang-cl makes it possible to succeed with that build.
To configure a build with clang-cl I used
```sh
cmake .. -G"Visual Studio 16 2019" -T ClangCL
```
=> Fix pch macro to ignore clang-cl

source/opt/eliminate_dead_members_pass.cpp, test/opt/eliminate_dead_member_test.cpp
- Rewrite composite insert and extract operations on SpecConstnatOp.
- Leaves assert for Access chain instructions, which are only allowed
for kernels.
- Other operations do not require any extra code will no longer cause an
assert.
Fixes #3284.
Fixes #3282.
=> Handle more cases in dead member elim

source/opt/struct_cfg_analysis.cpp, test/opt/struct_cfg_analysis_test.cpp, test/opt/wrap_opkill_test.cpp
Loop headers must be marked as in the continue if the loop header is
also the continue target.
Fixes #3264
=> Struct CFG analysus and single block loop

external/CMakeLists.txt
This allows enclosing projects to use SPIRV-Headers_SOURCE_DIR
to set up in header includes.
=> If SPIRV-Headers is in our tree, include it as subproject

source/opt/instruction.cpp, test/opt/value_table_test.cpp
There are some cases where a variable that is declared as a sampled
image could be read only.  That is when the image type has sampled == 1.
Fixes #3288
=> Sampled images as read-only storage

source/fuzz/fuzzer_util.cpp, source/fuzz/transformation_split_block.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_copy_object_test.cpp, test/fuzz/transformation_split_block_test.cpp
The SPIR-V data rules say that all uses of an OpSampledImage
instruction must be in the same block as the instruction, and highly
restrict those instructions that can consume the result id of an
OpSampledImage.
This adapts the transformations that split blocks and create synonyms
to avoid separating an OpSampledImage use from its definition, and to
avoid synonym-creation instructions such as OpCopyObject consuming an
OpSampledImage result id.
=> spirv-fuzz: Respect rules for OpSampledImage

source/fuzz/fuzzer_pass_donate_modules.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp
Demotes the image storage class to Private during donation.  Also
fixes an issue where instructions that depended on non-donated global
values would not be handled properly.
=> spirv-fuzz: Handle image storage class in donation

source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Provides support for runtime arrays in the code that traverses
composite types when checking applicability of transformations that
replace ids with synonyms.
=> spirv-fuzz: Handle OpRuntimeArray when replacing ids with synonyms

source/fuzz/transformation_outline_function.cpp, test/fuzz/transformation_outline_function_test.cpp
The function outliner uses a struct to return ids that a region
generates and that are used outside that region.  If these ids have
pointer type this would result in a struct with pointer members, which
leads to illegal loading from non-logical pointers if logical
addressing is used.  This change bans that outlining possibility.
=> spirv-fuzz: Do not outline regions that produce pointer outputs

source/opt/graphics_robust_access_pass.cpp, source/opt/ir_context.cpp
@dneto0 Are you okay with this change or should we just delete the code in the robust buffer access code?  This is the alternative solution to https://github.com/KhronosGroup/SPIRV-Tools/pull/3303.
=> Remove unreachable code.

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_compute_data_synonym_fact_closure.cpp, source/fuzz/transformation_compute_data_synonym_fact_closure.h, source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/CMakeLists.txt, test/fuzz/data_synonym_transformation_test.cpp, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_compute_data_synonym_fact_closure_test.cpp, test/fuzz/transformation_copy_object_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp, test/fuzz/transformation_vector_shuffle_test.cpp
The fact manager maintains an equivalence relation on data descriptors
that tracks when one data descriptor could be used in place of
another.  An algorithm to compute the closure of such facts allows
deducing new synonym facts from existing facts.  E.g., for two 2D
vectors u and v it is known that u.x is synonymous with v.x and u.y is
synonymous with v.y, it can be deduced that u and v are synonymous.
The closure computation algorithm is very expensive if we get large
equivalence relations.
This change addresses this in three ways:
- The size of equivalence relations is reduced by limiting the extent
to which the components of a composite are recursively noted as
being equivalent, so that when we have large synonymous arrays we do
not record all array elements as being pairwise …
=> spirv-fuzz: Make handling of synonym facts more efficient

README.md
fix issue - #3307 
typo fix: in README.md in Assembler tool- exectuable->executable
=> typo fix: in README.md exectuable->executable

tools/opt/opt.cpp
This change increases the set of validator options that can be passed
to spirv-opt, to match those options that spirv-reduce and spirv-fuzz
accept.  This is useful to still allow some validation, at the start
of and during optimisation, for SPIR-V modules that the strict
validator would reject.
=> Allow various validation options to be passed to spirv-opt

source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
The Sample argument of OpImageTexelPointer is sometimes required to be
a zero constant.  It thus cannot be replaced with a synonym in
general.  This change avoids replacing this argument with a synonym.
=> spirv-fuzz: Do not replace the Sample argument in OpImageTexelPointer

source/fuzz/shrinker.cpp
Fixes an issue where the shrinker's validator options were not
actually being passed to the validator.
=> spirv-fuzz: Pass on validator options during shrinking

utils/vscode/src/parser/parser.go, utils/vscode/src/schema/schema.go
Also update the schema with new definitions.
=> vscode: Handle '|' chains on BitEnum / ValueEnum

source/fuzz/transformation_outline_function.cpp, test/fuzz/transformation_outline_function_test.cpp
The outliner would outline regions ending with a loop header, making
the block containing the call to the outlined function serve as the
loop header.  This, however, is incorrect in general, since the whole
outlined function -- rather than just the exit block for the region --
would end up getting called every time the loop would iterate.
This change restricts the outliner so that the last block in a region
cannot be a loop header.
=> spirv-fuzz: Do not outline regions that end with a loop header

source/opt/ir_loader.cpp, test/opt/ir_loader_test.cpp
Many high-level languages like HLSL and GLSL generate termination
instructions such as return and branch from the actual part of the
high-level language code like return and if statements. This commit lets
IrLoader set `DebugScope` for termination instructions.
=> Set DebugScope for termination instructions

kokoro/scripts/linux/build.sh, source/opt/function.h
When moving blocks around, we ended up with a nullptr for a basic block,
and it was left in the list for a little bit.  However, in that time, it
would end up being dereferenced while traversing the function.
To fix this, we delete it right away.  This was found in an asan build
that runs our current tests.  No new tests are needed, but I did add
extra check asan checks for our asan bot.
=> Delete nullptr in function bb list immediately

source/opt/code_sink.cpp, source/opt/instruction.cpp, source/opt/instruction.h, test/opt/instruction_test.cpp
Generalizes the IsReadOnlyVariable() method, and related methods, so
that they can be used to ask whether pointer result ids are read-only.
Fixes #3324.
=> Generalize IsReadOnlyVariable() to apply to pointers

source/fuzz/fuzzer_pass_add_stores.cpp, source/fuzz/transformation_store.cpp, source/fuzz/transformation_store.h, test/fuzz/transformation_store_test.cpp
Adds checks for PushConstant and UniformConstant storage classes (in
addition to the existing check for Input storage class).
=> spirv-fuzz: Do not allow adding stores to read-only pointers

source/opt/function.h, source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
We will remove the code in inlining to handle a return in the middle of
a function.  To inline those functions, we need to run merge return to
move the return to the end of the function.
=> Do merge return if the return is not at the end of the function.

source/fuzz/fuzzer_pass.h
A template method turned out not to be necessary.
=> spirv-fuzz: Get rid of unnecessary template method

source/reduce/CMakeLists.txt, source/reduce/pch_source_reduce.h, source/reduce/reducer.cpp, source/reduce/remove_instruction_reduction_opportunity.cpp, source/reduce/remove_unused_instruction_reduction_opportunity_finder.cpp, source/reduce/remove_unused_instruction_reduction_opportunity_finder.h, test/reduce/CMakeLists.txt, test/reduce/reducer_test.cpp, test/reduce/remove_unused_instruction_test.cpp
Adds a reduction opportunity to get rid of a resource variable (such
as a uniform or image) that is unreferenced except by descriptor set,
binding, readonly or writeonly decorations, getting rid of said
decorations at the same time.
=> spirv-reduce: Add the capability to remove unused uniforms and similar

source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_opaque_test.cpp, test/opt/inline_test.cpp
In the function inlining pass, a lamda function contains
lots of logic and it is too complicated. This commit breaks
it down into small functions to be more readable.
=> [spirv-opt] refactor inlining pass

source/opt/mem_pass.cpp, test/opt/local_ssa_elim_test.cpp
ssa-rewrite fails in `MemPass::GetPtr()` when the SPIR-V code contains
`OpLoad` for the result id of `OpConstantNull` because of the out of
index access for an operand to get the base address. This commit fixes
it.
Fixes #3344
=> Handle OpConstantNull in ssa-rewrite

source/opt/instruction.cpp, test/opt/ccp_test.cpp, test/opt/fold_test.cpp
When CCP is evaluating an instruction, it was trying to fold a
comparison with 64 bit integers.  This was causing a fold failure later
since the folder still cannot deal with 64 bit integers.
Fixes #3343.
=> Reject folding comparisons with unfoldable types.

source/val/validate_function.cpp, test/val/val_decoration_test.cpp
Fix spirv-val failure on a module with multiple function and OpDecorationGroup.
See issue https://github.com/KhronosGroup/SPIRV-Tools/issues/3159 for more details.
=> Fix validation failure on OpDecorationGroup

source/val/validate_image.cpp, test/val/val_image_test.cpp
ImageGatherBiasLodAMD makes it possible to use the Bias and Lod image
operands with OpImageGather and OpImageSparseGather. This commit makes
sure the validator checks for that capability before reporting errors
and adds a few positive tests.
=> Add validation support for ImageGatherBiasLodAMD

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
=> spirv-val: allow DebugInfoNone for DebugTypeComposite.Size

DEPS
Roll external/effcee/ cd25ec17e..5af957bbf (3 commits)
https://github.com/google/effcee/compare/cd25ec17e938...5af957bbfc7d
$ git log cd25ec17e..5af957bbf --date=short --no-merges --format='%ad %ae %s'
2019-12-20 raj.khem Respect CMAKE_INSTALL_LIBDIR in installed CMake files
2019-10-30 dneto Travis-CI: macOS: Run brew update first
2019-10-30 dneto Add namespace to make_unique to avoid potential collisions
Roll external/googletest/ f2fb48c3b..011959aaf (233 commits)
https://github.com/google/googletest/compare/f2fb48c3b3d7...011959aafddc
$ git log f2fb48c3b..011959aaf --date=short --no-merges --format='%ad %ae %s'
2020-05-13 absl-team Googletest export
2020-05-13 absl-team Googletest export
2020-05-11 absl-team Googletest export
2020-05-08 martin Remove an explicit include of debugapi.h …
=> Rolling 4 dependencies

test/opt/pass_merge_return_test.cpp
Merge-return pass already properly preserves OpenCL.DebugInfo.100
information. This commit adds unit tests to check the preservation.
=> Add tests for merge-return debug info preservation

external/CMakeLists.txt
The googletest root CMakeLists.txt now sets a GOOGLETEST_VERSION variable, which is needed by the subprojects. We previously included only a subproject, which now fails. Use add_subdirectory(external/googletest EXCLUDE_FROM_ALL) to add the root CMakeLists.txt file, which by default builds GMock and GTest, as required. We already use EXCLUDE_FROM_ALL, which should shield us from e.g. building their tests, installing their targets, etc. If this causes issues, we can change the googletest CMakeLists.txt file to only mess with compiler settings, add tests, etc. if it is the root project being built.
=> Fix googletest inclusion

source/fuzz/fuzzer_pass_adjust_memory_operands_masks.cpp
This change replaces the instruction function `GetSingleWordOperand`
with `GetSingleWordInOperand`. Debugging spirv-fuzz, `GetSingleWordOperand`
was returning the result id of an OpLoad instruction with memory operands.
=> spirv-fuzz: Fix instruction function use

source/fuzz/fuzzer_pass_push_ids_through_variables.cpp
This change fixes an assertion failure related to the push
id through variable transformation. In the fuzzer pass class
it was missing the `IdIsAvailableBeforeInstruction` condition
that is checked in the `IsApplicable` function.
=> spirv-fuzz: Fix assertion failure related to transformation applicability

test/opt/ccp_test.cpp
For constant propagation, the ccp pass already replaces the result id of
a value with a result id of the corresponding constant value. As a part
of the replacement, it correctly updates the operands of
DebugValue/DebugDeclare as well. Since we do not have to any addition
work other than the ccp pass itself, this commit just adds unit tests to
check the debug information preservation.
=> Debug info preservation in ccp pass

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, source/opcode.cpp, source/opcode.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements a transformation that replaces
a linear algebra instruction with its mathematical definition.
=> spirv-fuzz: Add replace linear algebra instruction transformation

test/opt/dead_branch_elim_test.cpp, test/opt/ir_context_test.cpp
The DeadBranchElimPass class already handles the OpenCL.DebugInfo.100
instructions correctly. This commit just adds a unit test to make sure
it preserves the information properly.
=> Debug info preservation in dead branch elimination

source/opt/desc_sroa.cpp, source/opt/desc_sroa.h, source/opt/ir_context.h, test/opt/desc_sroa_test.cpp
This doesn't cover cases where we have the following pattern:
```
%31 = OpAccessChain %_ptr_UniformConstant_S %globalS %int_0 %int_0
%32 = OpLoad %S %31
%33 = OpCompositeExtract %_arr_type_2d_image_uint_2 %32 0
%34 = OpCompositeExtract %type_2d_image %33 0
%35 = OpCompositeExtract %type_2d_image %33 1
%36 = OpCompositeExtract %_arr_T_uint_2 %32 1
%37 = OpCompositeExtract %T %36 0
%38 = OpCompositeExtract %_arr_type_sampler_uint_3 %37 0
%39 = OpCompositeExtract %type_sampler %38 1
%40 = OpCompositeExtract %T %36 1
%41 = OpCompositeExtract %_arr_type_sampler_uint_3 %40 0
%42 = OpCompositeExtract %type_sampler %41 2
%43 = OpSampledImage %type_sampled_image %34 %39
%44 = OpImageSampleImplicitLod %v4float %43 %14 None
```
This pattern could be seen if a global structure of resources is passed …
=> Updated desc_sroa to support flattening structures

utils/roll_deps.sh
This in anticipation of some repos changing their default branch name. This is based off to the change I made in https://github.com/google/shaderc/pull/1086
=> Add support for different default branches in roll-deps

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_permute_phi_operands.cpp, source/fuzz/fuzzer_pass_permute_phi_operands.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_permute_function_parameters.cpp, source/fuzz/transformation_permute_phi_operands.cpp, source/fuzz/transformation_permute_phi_operands.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_permute_function_parameters_test.cpp, test/fuzz/transformation_permute_phi_operands_test.cpp
=> spirv-fuzz: Permute OpPhi instruction operands

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h
Adds a `GetParameters` function to `fuzzerutil`.
=> spirv-fuzz: Add GetParameters

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_parameters.cpp, source/fuzz/fuzzer_pass_add_parameters.h, source/fuzz/fuzzer_pass_permute_function_parameters.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_parameters.cpp, source/fuzz/transformation_add_parameters.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_parameters_test.cpp
=> spirv-fuzz: Implement FuzzerPassAddParameters

source/val/validate_decorations.cpp, source/val/validate_interfaces.cpp, test/val/val_builtins_test.cpp, test/val/val_capability_test.cpp, test/val/val_decoration_test.cpp, test/val/val_interfaces_test.cpp
Validate that location, component and index decorations do not cause an overlap in any interface.
Checks:
* location can only be applied to variables or structure members
* variable that require a location have one
* index can only be on fragment outputs
* no conflicting location, component, index assignments
* utility functions calculate the consumed locations and components
Tests include common corners such as a scalar being packed after 3-component 64-bit vector. 
Tested against CTS.
=> Validate location assignments

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/ir_context.cpp, test/opt/ir_context_test.cpp, test/opt/local_ssa_elim_test.cpp
For many spirv-opt passes such as simplify-instructions pass, we have to
correctly clear the OpenCL.DebugInfo.100 debug information for
KillInst() and ReplaceAllUses(). If we keep some debug information that
disappeared because of KillInst() and ReplaceAllUses(), adding new
DebugValue instructions will generate incorrect information. This CL
update DebugInfoManager and IRContext to correctly clear debug
information.
=> Clear debug information for kill and replacement

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements the `OpMatrixTimesScalar` case for the
=> spirv-fuzz: Implement the OpMatrixTimesScalar linear algebra case

source/name_mapper.cpp, test/name_mapper_test.cpp
GLSL: https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)
SPIR-V: `BaseInstance` [Builtin](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_builtin_a_builtin) decoration
=> Add gl_BaseInstance to the name mapper.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp
When there are multiple entries and the shader has a variable with
WorkGroup storage class, those multiple entry functions store values to
the variable. Since ADCE pass uses def-use chains to propagate the work
list, some of instructions in the work list are not actually a part of
the currently processed function. As a result, it adds instructions in
other functions and put them in `live_insts_`. However, it does not
have the control flow information for those instructions in other
functions i.e., `block2headerBranch_` and `header2nextHeaderBranch_`.
It skips handling those instructions because they are already in
`live_insts_` and does not check their control flow information e.g.,
`block2headerBranch_` and `header2nextHeaderBranch_`, which results
in skipping some branches. Even though …
=> Fix ADCE pass bug for mulitple entries

source/opt/copy_prop_arrays.cpp, source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/instruction.h, source/opt/pass.h, source/opt/ssa_rewrite_pass.cpp, test/opt/copy_prop_array_test.cpp
When the pass replaces the local variable `OpVariable` ids to their
corresponding pointers, we have to update operands of DebugValue or
DebugDeclare instructions that are the local variable ids.
Fixes #3429
=> Debug info preservation in copy-prop-array pass

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements the `OpVectorTimesMatrix` case for the
=> spirv-fuzz: Implement the OpVectorTimesMatrix linear algebra case

source/opt/copy_prop_arrays.cpp, source/opt/debug_info_manager.cpp, source/opt/instruction.h, source/opt/reduce_load_size.cpp, test/opt/reduce_load_size_test.cpp
The decision to reduce the load must be not affected by debug
instructions. For example, even when a DebugValue references a
result id of a loaded composite value, this change lets the
reduce-load-size pass reduce the load if the full composite value is not
used anywhere other than the DebugValue.
=> Preserve OpenCL.100.DebugInfo in reduce-load-size pass

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements the `OpMatrixTimesVector` case for the
=> spirv-fuzz: Implement the OpMatrixTimesVector linear algebra case

source/opt/vector_dce.cpp, source/opt/vector_dce.h, test/opt/vector_dce_test.cpp
This commit lets the vector DCE pass preserve the OpenCL.DebugInfo.100
information properly. When the vector DCE pass determines the liveness
of instructions, the debug instructions must not affect the decision. In
addition, when it kills some instructions, it has to kill DebugValue
instructions that use the killed instructions. When it updates some
composite values to meaningful values (not undef), it has to remove
DebugValue because the value information becomes incorrect.
=> Preserve debug info in vector DCE pass

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/local_single_store_elim_pass.cpp, source/opt/local_single_store_elim_pass.h, test/opt/local_single_store_elim_test.cpp
This pass basically follows the same process as ssa-rewrite: it adds a DebugValue after each Store and removes the DebugDeclare or DebugValue Deref. It only does this if all instructions that are dependent on the Store are Loads and are replaced.
=> Preserve OpenCL.DebugInfo.100 through elim-local-single-store

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h
Removes unused functions from `fuzzerutil`.
=> spirv-fuzz: Remove unused functions

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements the `OpMatrixTimesMatrix` case for the
=> spirv-fuzz: Implement the OpMatrixTimesMatrix linear algebra case

source/opt/debug_info_manager.cpp, test/opt/debug_info_manager_test.cpp
DebugInfoManager::KillDebugDeclares() must erase the variable id
from |var_id_to_dbg_decl_| after killing its DebugDeclare
instructions.
=> Rewrite KillDebugDeclares()

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/fuzz/protobufs/spirvfuzz_protobufs.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/spirv_fuzzer_options.cpp, source/spirv_fuzzer_options.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/replayer_test.cpp, tools/fuzz/fuzz.cpp
This change adds a --replay-range argument to spirv-fuzz that
facilitates applying only a prefix of transformations.
=> spirv-fuzz: Add replay range option

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_replace_id_with_synonym.cpp
This fuzzer pass:
- For each zero-like constant, either finds the existing definition of the corresponding toggled one (OpConstantNull becomes zero-valued scalar OpConstant or vice versa) or creates a new one if it doesn't exist and records that the two are synonyms
- For each use of these constants, probabilistically decides whether to change it with the corresponding toggled constant id
(as described in #3486 )
Only uses inside blocks of instructions are considered and not, for example, in instructions declaring other constants.
=> spirv-fuzz: Fuzzer pass to interchange zero-like constants

source/val/basic_block.cpp, source/val/basic_block.h, source/val/function.cpp, source/val/function.h, source/val/validate.cpp, source/val/validate.h, source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
Fixes #3529
* Make BasicBlock::reachable() only consider static reachability
* Fix reachability calculation to be independent of block order
* add tests
Also tested against CTS.
=> Fix reachability in the validator

source/fuzz/transformation_access_chain.cpp, test/fuzz/transformation_access_chain_test.cpp
… if it is invalid (with null or undefined pointer).
In this case, assert false instead of returning false so that the fuzzer fails.
(See issue #3185 )
=> Assert false in IsApplicable method of TransformationAccessChain

source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_dead_blocks.cpp, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.cpp, source/fuzz/fuzzer_pass_merge_blocks.cpp, source/fuzz/fuzzer_pass_outline_functions.cpp, source/fuzz/fuzzer_pass_permute_blocks.cpp, source/fuzz/fuzzer_pass_split_blocks.cpp
This function can be used to apply a transformation only if it is applicable and use it wherever this pattern is used (see issue #3530 ).
=> spirv-fuzz: Implement MaybeApplyTransformation helper function in fuzzer_pass.h

source/fuzz/transformation_invert_comparison_operator.cpp
=> spirv-fuzz: Added support for floating-point comparisons to TransformationInvertComparisonOperator

source/val/validate_mode_setting.cpp, test/val/val_webgpu_test.cpp
Now that WebGPU ingests WGSL instead of SPIR-V,
there is no need to be so strict about the memory model.
Allow any memory model that is already allowed by Vulkan 1.0,
either directly or via an existing.
=> Permit Simple and GLSL450 memory model in WEBGPU_0

source/val/validate_interfaces.cpp, test/val/val_interfaces_test.cpp
Fixes http://crbug.com/1102149
* Switch from boolean vectors to unordered sets for location storage
Ideally the validator would know the right Vulkan limits, but that isn't feasible in the current setup.
=> Store location values sparsely

source/fuzz/fuzzer_pass_merge_blocks.cpp
This PR makes the code in fuzzer_pass_merge_blocks.cpp simpler by
using the RemoveAtRandomIndex function from FuzzerContext
See related comment in #3540
=> spirv-fuzz: refactor to use RemoveAtRandomIndex

source/fuzz/transformation_record_synonymous_constants.cpp, source/fuzz/transformation_record_synonymous_constants.h, test/fuzz/transformation_record_synonymous_constants_test.cpp
Implemented AreEquivalentConstants method to check equivalency of constants, changing IsApplicable method of TransformationRecordSynonymousConstants to allow recording equivalence of composite constants; added some tests to check this.
Tests with arrays and matrices still need to be added.
Related issue: #3533
=> spirv-fuzz: Extend TransformationRecordSynonymousConstants to allow composite constants

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/debug_info_manager.h, test/opt/aggressive_dead_code_elim_test.cpp
Essentially, it marks all DebugInfo instructions in functions (and their operands) as live. It treats DebugDeclare and DebugValue with Deref as loads and so marks Stores of their variables as live.
It marks each DebugGlobalVariables as live except for its variable. After closure, it rechecks if the variable is live. If not, the DebugGlobalVariable instruction's variable operand is set to DebugInfoNone, per the DebugInfo spec.
=> Preserve OpenCL.DebugInfo.100 through elim-dead-code-aggressive

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
We cannot create an OpPhi for pointers, so we have to regenerate these
instructions instead.
Fixes #3030
Fixes #3266
=> Sink pointer instructions in merge return

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_permute_function_parameters.cpp, source/fuzz/transformation_replace_parameter_with_global.cpp, source/fuzz/transformation_replace_params_with_struct.cpp, test/fuzz/transformation_permute_function_parameters_test.cpp, test/fuzz/transformation_replace_parameter_with_global_test.cpp, test/fuzz/transformation_replace_params_with_struct_test.cpp
=> spirv-fuzz: Create a helper in fuzzerutil to reuse function type

source/fuzz/shrinker.cpp, test/fuzz/fuzzer_shrinker_test.cpp
Fixes an issue with the shrinker, where the message consumer set for
the shrinker was not being passed on to the replay object that the
shrinker creates.  This meant that messages generated during replay
would cause an exception to be thrown.
=> spirv-fuzz: Set message consumer in replayer when shrinking

source/fuzz/fuzzer_pass_outline_functions.cpp
This PR modifies FuzzerPassOutlineFunctions so that it tries to split
a block starting with OpPhi instructions, so that it is more likely
that the selected blocks can be outlined using
TransformationOutlineFunction.
Fixes #3094 .
=> spirv-fuzz: Split blocks starting with OpPhi before trying to outline

source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_add_access_chains.h, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_access_chain.cpp, source/fuzz/transformation_access_chain.h, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_function.h, test/fuzz/transformation_access_chain_test.cpp
This PR generalises TransformationAddAccessChain so that dynamic
indices for non-struct composites (with clamping to ensure that
accesses are in-bound) are allowed.
The transformation will add instructions to clamp any index to
a non-struct composite, regardless of whether it is a constant
or not.
Fixes #3179
=> spirv-fuzz: Generalise transformation access chain

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_record_synonymous_constants.cpp, source/fuzz/transformation_record_synonymous_constants.h, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, test/fuzz/transformation_record_synonymous_constants_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Right now, TransformationRecordSynonymousConstants requires the type
ids of two candidate constants to be exactly the same.
This PR adds an exception for integer constants, which can be
considered equivalent even if their signedness is different.
This applies to both integers and vector constants.
The IsApplicable method of ReplaceIdWithSynonym is also updated so
that, in the case of two integer constants which don't have the same
type, they can only be swapped in particular instructions (those
that don't take the signedness into consideration).
Fixes #3536  .
=> spirv-fuzz: Relax type checking for int contants

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/private_to_local_pass.cpp, source/opt/private_to_local_pass.h, test/opt/private_to_local_test.cpp
1. A debug instruction must not have any impact on the private-to-local
optimization.
2. DebugGlobalVariable for the OpVariable optimized by private-to-local
must be converted to a DebugLocalVariable because we want to run
the ssa-rewrite to propagate DebugValue properly, which correctly
delivers the updates of local variables to the debugger.
=> Preserve OpenCL.DebugInfo.100 through private-to-local pass

tools/sva/yarn.lock
Manually apply #3558 because the bot cannot sign the CLA.
=> build(deps): bump lodash from 4.17.15 to 4.17.19 in /tools/sva

source/opt/constants.cpp, source/opt/constants.h, source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/instruction.h, source/opt/local_single_store_elim_pass.cpp, source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, source/opt/ssa_rewrite_pass.cpp, source/opt/wrap_opkill.cpp, test/opt/ir_context_test.cpp, test/opt/scalar_replacement_test.cpp
Preserve OpenCL.DebugInfo.100 and line information in scalar
replacement pass.
1. Set the debug scope and line information for the new replacement
instructions.
2. Replace DebugDeclare and DebugValue if their OpVariable or value
operands are replaced by scalars.
- If the initial aggregate has DebugValue, we clone a DebugValue
for each scalar and add one more index for the scalar to 'Indexes'
operand of the cloned DebugValue as we add an index to 'Indexes'
operand of OpAccessChain.
- If the initial aggregate has DebugDeclare, we create a DebugValue
with Deref operation for each scalar and add an index for the scalar
to 'Indexes' operand.
- For example,
```
struct S { int a; int b;}
S foo; // before scalar replacement
int foo_a; // after scalar replacement
int foo_b;
DebugDeclare %dbg_foo …
```
=> Preserve debug info in scalar replacement pass

include/spirv-tools/libspirv.h, source/operand.cpp, test/operand_test.cpp
Deprecates the SPV_OPERAND_TYPE_FIRST_* and SPV_OPERAND_TYPE_LAST_*
macros.
The "variable" and "optional" operand types are only for internal use.
Export spvOperandIsConcrete instead, as that should cover intended
external uses.
Test that each operand type is classified either as one of:
- a sentinel value
- a concrete operand type
- an optional operand type (which includes variable-expansion types)
Test that each concrete and optional non-variable operand type
has a name for use internally when generating messages.
=> Avoid operand type range checks

external/CMakeLists.txt, source/CMakeLists.txt, source/fuzz/CMakeLists.txt, source/link/CMakeLists.txt, source/opt/CMakeLists.txt, source/reduce/CMakeLists.txt, test/CMakeLists.txt, test/val/CMakeLists.txt, tools/CMakeLists.txt
Rename the `${SPIRV_TOOLS}` target to `${SPIRV_TOOLS}-static` and alias `${SPIRV_TOOLS}` to either `${SPIRV_TOOLS}-static` or `${SPIRV_TOOLS}-shared` depending on `BUILD_SHARED_LIBS`.
Re-point all internal uses of `${SPIRV_TOOLS}` to `${SPIRV_TOOLS}-static`.
`${SPIRV_TOOLS}-static` target output is explicitly renamed to just `${SPIRV_TOOLS}` to ensure the binary name does not change from current behavior.
Build the `SPIRV-Tools-*` libraries as static, as this is what they always were.
Force the external targets `gmock` and `effcee` to be built statically. These either do not support being built as shared libraries, or require special flags.
Issue: #3482
=> CMake: Enable building with BUILD_SHARED_LIBS=1

test/tools/spirv_test_framework.py
Python issues a SyntaxWarning for the use of `is` with literals, since it does not make any formal guarantees about the small-number optimization.  This PR fixes these warnings.
```
2: /home/rdb/local/src/SPIRV-Tools/test/tools/spirv_test_framework.py:149: SyntaxWarning: "is" with a literal. Did you mean "=="?
2:   if sys.version_info[0] is 2:
2: /home/rdb/local/src/SPIRV-Tools/test/tools/spirv_test_framework.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
2:   elif sys.version_info[0] is 3:
2: /home/rdb/local/src/SPIRV-Tools/test/tools/spirv_test_framework.py:159: SyntaxWarning: "is" with a literal. Did you mean "=="?
2:   if sys.version_info[0] is 2:
2: /home/rdb/local/src/SPIRV-Tools/test/tools/spirv_test_framework.py:161: SyntaxWarning: "is" with a literal. Did you mean …
```
=> Fix SyntaxWarning in Python 3.8

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
This PR implements the `OpTranspose` case for the
=> spirv-fuzz: Implement the OpTranspose linear algebra case

source/fuzz/transformation_set_loop_control.cpp, source/fuzz/transformation_split_block.cpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/loop_peeling.cpp, source/opt/optimizer.cpp, source/reduce/operand_to_dominating_id_reduction_opportunity_finder.cpp, test/binary_parse_test.cpp, test/fuzz/transformation_add_dead_break_test.cpp, test/fuzz/transformation_add_dead_continue_test.cpp, test/opcode_table_get_test.cpp, test/opt/graphics_robust_access_test.cpp, utils/vscode/src/parser/parser.go
In line with:
https://source.android.com/setup/contribute/respectful-code
this change uses the terms 'coherence' and 'coherence check' where
'sanity' and 'sanity check' were previously used.
=> Avoid use of 'sanity' and 'sanity check' in the code base

source/fuzz/fact_manager.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.h, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, test/fuzz/transformation_replace_id_with_synonym_test.cpp
=> spirv-fuzz: Relax type constraints in DataSynonym facts

source/fuzz/fact_manager.cpp, test/fuzz/fact_manager_test.cpp
Splits #3523 in two parts. This part implements functionality to compute corollary facts from `OpBitcast` equation facts.
=> spirv-fuzz: Compute corollary facts from OpBitcast

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/instruction.h, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/loop_unroller.cpp, test/opt/debug_info_manager_test.cpp, test/opt/loop_optimizations/unroll_simple.cpp
When we copy the loop body to unroll it, we have to copy its
instructions but DebugDeclare or DebugValue used for the declaration
i.e., DebugValue with Deref must not be copied and only the first block
can contain those instructions.
=> Debug info preservation in loop-unroll pass

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_interchange_integer_operands.cpp, source/fuzz/fuzzer_pass_interchange_integer_operands.h, source/fuzz/fuzzer_pass_interchange_signedness_of_integer_operands.cpp, source/fuzz/fuzzer_pass_interchange_signedness_of_integer_operands.h, source/fuzz/fuzzer_pass_interchange_zero_like_constants.h
This PR introduces FuzzerPassInterchangeIntegerOperands, which:
- finds all integer vectors or constants
- finds or creates the corresponding constants with opposite
signedness
- records such constants as synonyms of the first ones
- replaces the usages of the original constants with the new ones
if allowed
Fixes #2677 .
=> spirv-fuzz: Pass to replace int operands with ints of opposite signedness

source/fuzz/CMakeLists.txt, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_loop_preheader.cpp, source/fuzz/transformation_add_loop_preheader.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_loop_preheader_test.cpp
This PR introduces TransformationAddLoopPreheader, which, given
a loop header and enough fresh ids, adds a loop preheader, updating
all the references so that this new block is the only out-of-loop
predecessor of the header, which branches unconditionally to the
header.
See the discussion in #3095 .
=> spirv-fuzz: Transformation to add loop preheader

source/fuzz/transformation_replace_params_with_struct.cpp, source/fuzz/transformation_replace_params_with_struct.h, test/fuzz/transformation_replace_params_with_struct_test.cpp
=> spirv-fuzz: Remove OpFunctionCall operands in correct order

source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_function.h, test/fuzz/fuzzer_pass_donate_modules_test.cpp
=> spirv-fuzz: Handle OpPhis in livesafe functions

source/opt/instruction.cpp, source/opt/instruction.h
This PR makes some improvements to the source code of the Instruction class,
choosing better names for variables and avoiding unnecessary function calls.
=> spirv-opt: Improve the code of the Instruction class

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
The updated OpenCL.DebugInfo.100 spec says that we can use
variable for "Component Count" operand of DebugTypeArray i.e.,
DebugLocalVariable or DebugGlobalVariable. This commit updates spirv-val
based on the spec update.
=> OpenCL.DebugInfo.100 DebugTypeArray with variable size

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp
This PR changes the way the fuzzer pass iterates over the module instructions.
It avoids iterating over non-relevant instructions for the replace linear algebra transformation.
=> spirv-fuzz: iterate over blocks in replace linear algebra pass

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_replace_adds_subs_muls_with_carrying_extended.cpp, source/fuzz/fuzzer_pass_replace_adds_subs_muls_with_carrying_extended.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_add_sub_mul_with_carrying_extended.cpp, source/fuzz/transformation_replace_add_sub_mul_with_carrying_extended.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_replace_add_sub_mul_with_carrying_extended_test.cpp
Replaces OpIAdd with OpIAddCarry, OpISub with OpISubBorrow, OpIMul with
OpUMulExtended or OpSMulExtended and stores the result into a fresh_id
representing a structure. Extracts the first element of the result into
the original result_id. This value is the same as the result of the
original instruction.
Fixes #3577
=> spirv-fuzz: TransformationReplaceAddSubMulWithCarryingExtended

DEPS
Roll external/googletest/ a781fe29b..3af06fe16 (12 commits)
https://github.com/google/googletest/compare/a781fe29bcf7...3af06fe1664d
$ git log a781fe29b..3af06fe16 --date=short --no-merges --format='%ad %ae %s'
2020-08-05 absl-team Googletest export
2020-08-03 absl-team Googletest export
2020-08-03 absl-team Googletest export
2020-08-05 zumix.cpp fix endif comment
2020-08-02 zumix.cpp fix tests
2020-07-29 franciscogthiesen Removing tiny-dnn from "Who is using.."
2020-07-28 absl-team Googletest export
2020-07-29 zumix.cpp fix GTEST_REMOVE_LEGACY_TEST_CASEAPI_ typo
2020-07-28 absl-team Googletest export
2020-07-26 ofats Googletest export
2020-07-19 jasjuang fix clang tidy modernize-use-equals-default warnings
2020-07-02 siliconearth Fix test failing when simple regex is used
Created with: …
=> Roll 2 dependencies

source/opcode.cpp, source/opcode.h
This PR implements the `spvOpcodeIsAccessChain` function
that checks if the given opcode represents an access chain
instruction.
=> spirv-opt: Add spvOpcodeIsAccessChain

source/fuzz/id_use_descriptor.cpp
`spvtools::fuzz::MakeIdUseDescriptorFromUse` asserts if the id use type is
`SPV_OPERAND_TYPE_ID`. The problem is that not all id types are covered by
this condition. The bug was found because the first operand of an `OpControlBarrier`
instruction has `SPV_OPERAND_TYPE_SCOPE_ID` as type. Therefore, to cover
all cases the `spvIsInIdType` function is used.
Fixes #3665.
=> spirv-fuzz: Fix in operand type assertion

source/val/validate_interfaces.cpp, test/val/val_interfaces_test.cpp
Fixes #3653
* Only validate locations for fragment, vertex, geometry and
tessellation shaders
=> Only validate locations for appropriate execution models

source/opt/dead_insert_elim_pass.cpp, test/opt/dead_insert_elim_test.cpp
When we determine the liveness of an insert, we have to ignore the debug
instruction (it must not have any impact on the decision).
=> Preserve debug info in dead-insert-elim pass

source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/fuzzer_pass_add_equation_instructions.h
=> spirv-fuzz: Fix width in FuzzerPassAddEquationInstructions

source/fuzz/fuzzer_pass_interchange_signedness_of_integer_operands.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.cpp, source/opt/constants.cpp
`FuzzerPassInterchangeSignednessOfIntegerOperands` and `FuzzerPassInterchangeZeroLikeConstants` both included specialization constants when trying to find integer constants with known values. However, this is incorrect behavior because we do not know the value of specialization constants. Furthermore, ConstantManager does not support them, and this led to crashes where we assumed we could look up specialization constants via the ConstantManager.
This change fixes both passes to ignore specialization constants.
Fixes #3663.
=> spirv-fuzz: Ignore specialization constants

source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
`TransformationReplaceIdWithSynonym` is careful to avoid replacing id uses that index into a struct with synonyms because the indices must only be `OpConstant` instructions. However, the check only considered `OpAccessChain` instructions, even though the same restriction applies to `OpInBoundsAccessChain`, `OpPtrAccessChain`, etc. 
This change extends the check to include all access chain instructions.
Fixes #3671.
=> spirv-fuzz: consider additional access chain instructions

source/fuzz/transformation_add_type_float.cpp, source/fuzz/transformation_add_type_int.cpp, test/fuzz/transformation_add_type_float_test.cpp, test/fuzz/transformation_add_type_int_test.cpp
`TransformationAddTypeFloat` and `TransformationAddTypeInt` did not check whether the required capabilities were present when adding 16-bit, 64-bit, and 8-bit types.
This change adds these checks in the `IsApplicable` method of each transformation.
Fixes #3669.
=> spirv-fuzz: Check integer and float width capabilities

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/eliminate_dead_functions_util.cpp, source/opt/function.cpp, source/opt/function.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/ir_loader.cpp, source/opt/module.cpp, test/opt/eliminate_dead_functions_test.cpp, test/opt/function_test.cpp, test/opt/module_test.cpp, test/opt/strip_reflect_info_test.cpp
This does not aim to be complete support for non-semantic instructions in the optimizer. It is enough to handle basics properly and meet the needs of https://github.com/kpet/clvk/pull/250. In the future, `KillInst()` should probably call `KillNonSemanticInfo()` automatically.
* No longer blindly add global non-semantic info instructions to global
types and values
* functions now have a list of non-semantic instructions that succeed
them in the global scope
* global non-semantic instructions go in global types and values if
they appear before any function, otherwise they are attached to the
immediate function predecessor in the module
* changed ADCE to use the function removal utility
* Modified EliminateFunction to have special handling for non-semantic
instructions in the global scope
* …
=> Improve non-semantic instruction handling in the optimizer

source/fuzz/fuzzer_pass_propagate_instructions_up.cpp, source/fuzz/transformation_propagate_instruction_up.cpp, test/fuzz/transformation_propagate_instruction_up_test.cpp
A basic block may have multiple identical predecessors as follows:
```
%1 = OpLabel
OpSelectionMerge %2 None
OpBranchConditional %true %2 %2
%2 = OpLabel
...
```
This case wasn't supported before.
=> spirv-fuzz: Support identical predecessors in TransformationPropagateInstructionUp

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_loop_preheaders.cpp, source/fuzz/fuzzer_pass_add_loop_preheaders.h
This PR introduces FuzzerPassAddLoopPreheaders, which:
- Finds existing loop headers
- If they have no simple preheader (where simple means that the
preheader itself is not a loop header), randomly decides whether
to add one.
Fixes #3621 .
=> spirv-fuzz: Fuzzer pass to randomly apply loop preheaders

source/fuzz/transformation_replace_copy_object_with_store_load.cpp, source/fuzz/transformation_replace_load_store_with_copy_memory.cpp, test/fuzz/transformation_add_relaxed_decoration_test.cpp, test/fuzz/transformation_replace_copy_object_with_store_load_test.cpp, test/fuzz/transformation_replace_load_store_with_copy_memory_test.cpp
I have significantly improved code coverage in tests for my transformations:
1. TransformationAddRelaxedDecoration
2. TransformationReplaceCopyMemoryWithLoadStore
3. TransformationReplaceCopyObjectWithStoreLoad
4. TransformationReplaceLoadStoreWithCopyMemory
5. TransformationReplaceAddSubMulWithCarryingExtended
=> spirv-fuzz: Improve code coverage of tests

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
Some OpenCL.DebugInfo.100 instructions such as DebugGlobalVariable
and DebugLocalVariable have the Type operand. This commit allows them to
use DebugTypeTemplate for the Type operand.
=> Allow DebugTypeTemplate for Type operand

source/fuzz/transformation_add_dead_block.cpp, test/fuzz/transformation_add_dead_block_test.cpp
`TransformationAddDeadBlock` did not check whether the existing block
(that will become a selection header) dominates its successor block (that
will become its merge block).
This change adds the check.
Fixes #3690.
=> spirv-fuzz: Check header dominance when adding dead block

source/cfa.h
Clang 10 has `-Wrange-loop-analysis` included in `-Wall` (since removed in https://reviews.llvm.org/D73434). If `-Werror` is also specified, this will cause compilation to fail.
=> Fix -Wrange-loop-analysis warning

source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h
The `FuzzerPassDonateModules` was not checking if the function to donate had
a block with `OpKill` or `OpUnreachable` as its termination instruction.
Fixes #3709.
=> spirv-fuzz: Check termination instructions when donating modules

source/opt/function.cpp, source/opt/function.h, test/opt/function_test.cpp
This PR implements the `opt::Function::HasEarlyReturn` function that checks
if the given `opt::Function` object has a return block other than the exit block.
=> spirv-opt: Implement opt::Function::HasEarlyReturn function

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp
In the existing code, ADCE pass does not check DebugScope of an
instruction when it checks the users of each instruction, which results
in removing OpenCL.Debug.100 instructions that are only used by
DebugScope. This commit lets ADCE pass add DebugScope of an instruction
to the live instruction set when the instruction is added to the live
instruction set.
=> Let ADCE pass check DebugScope

source/opt/ccp_pass.cpp, source/opt/ccp_pass.h, test/opt/ccp_test.cpp, test/opt/pass_fixture.h
This fixes #3636.
When CCP is simulating statements, it will sometimes successfully fold
an instruction, which laters switches to varying.  The initial fold of
the instruction may generate a new constant K.
The problem we were running into is when K never gets propagated to the
IR.  Its definition will still exist, so CCP should mark the IR modified
in this case.
In fixing this bug, I noticed that an existing test was suffering from
the same bug.  The change also makes PassTest::SinglePassRunAndMatch()
return the result from the pass, so that we can check that the pass
marks the IR modified in this case.
=> CCP should mark IR changed if it created new constants.

source/opt/inline_pass.cpp, test/opt/inline_opaque_test.cpp, test/opt/inline_test.cpp
It is possible that the result of a void function call is used.  In case
it is used, we need something that still defines its id after inlining.
We add an undef for that purpose.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/3704
=> Add undef for inlined void function

source/opt/ssa_rewrite_pass.cpp, test/opt/local_ssa_elim_test.cpp
Previously, the removal of DebugDeclares was predicated on the module "changing". In this case, "changing" actually meant loads being removed. This omitted the case where a variable had all its loads removed by a previous pass but still needed its DebugDeclare to be replaced with DebugValues by SSA-rewrite. The test case included in this PR gives further details.
This commit now has SSA-rewrite do  the DebugDeclare removal unconditionally. It appears that the purpose of the previous condition was just one of optimization, so it seems that its removal will not cause a functional problem. It is imagined that few functions will not require SSA-Rewrite, so few functions will suffer compile-time degradation from this change, and for those that do, the degradation will likely be nearly …
=> Fix SSA-rewrite to remove DebugDeclare for variables without loads

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager/constant_uniform_facts.cpp, source/fuzz/fact_manager/constant_uniform_facts.h, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.h, source/fuzz/fact_manager/dead_block_facts.cpp, source/fuzz/fact_manager/dead_block_facts.h, source/fuzz/fact_manager/fact_manager.cpp, source/fuzz/fact_manager/fact_manager.h, source/fuzz/fact_manager/irrelevant_value_facts.cpp, source/fuzz/fact_manager/irrelevant_value_facts.h, source/fuzz/fact_manager/livesafe_function_facts.cpp, source/fuzz/fact_manager/livesafe_function_facts.h, source/fuzz/force_render_red.cpp, source/fuzz/fuzzer.cpp, source/fuzz/replayer.cpp, source/fuzz/transformation_context.h, source/fuzz/transformation_replace_constant_with_uniform.h, test/fuzz/fact_manager_test.cpp
Part of #3698.
This splits various components of the fact manager into multiple files.
=> spirv-fuzz: Split the fact manager into multiple files

source/opt/instruction.cpp
This problem was seen as part of https://github.com/KhronosGroup/SPIRV-Tools/issues/3743 although it does not fix this issue, so the issue will stay open.
Essentially, the logic for outputting DebugNoScope was printing an InlinedAt operand when "available", which is not valid. This prevents this from happening.
The extra operand at the end of DebugNoScope created the appearance of an instruction with zero words which confused validation.
=> Fix DebugNoScope to not output InlinedAt operand.

source/fuzz/CMakeLists.txt, source/fuzz/counter_overflow_id_source.cpp, source/fuzz/counter_overflow_id_source.h, source/fuzz/overflow_id_source.cpp, source/fuzz/overflow_id_source.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/fuzz/transformation_context.cpp, source/fuzz/transformation_context.h, source/fuzz/transformation_outline_function.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/replayer_test.cpp, test/fuzz/transformation_outline_function_test.cpp, tools/fuzz/fuzz.cpp
This change adds the notion of "overflow ids", which can be used
during shrinking to facilitate applying transformations that would
otherwise have become inapplicable due to earlier transformations
being removed.
=> spirv-fuzz: Overflow ids

source/opt/compact_ids_pass.cpp, source/opt/instruction.h, test/opt/compact_ids_test.cpp
We have to update OpenCL.DebugInfo.100 DebugScope for instructions if we
change its lexical scope or DebugInlinedAt.
=> Handle DebugScope in compact-ids pass

source/opt/debug_info_manager.cpp, test/opt/debug_info_manager_test.cpp
This fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/3743
The debug info manager was attempting to register functions that had been optimized away by inlining. They all have a function id of DebugInfoNone which caused a problem with the DebugFunction map which keys on the function id, resulting in conflict.
The solution is to not register functions which map to DebugInfoNone.
=> Do not register DebugFunction for functions optimized away by inlining.

source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fuzzer_util.cpp, test/fuzz/transformation_add_synonym_test.cpp
=> spirv-fuzz: Do not make synonyms of void result ids

source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/struct_cfg_analysis_test.cpp
This PR adds the LoopNestingDepth function to StructuredCFGAnalysis.
This function, given a block id, returns the loop nesting depth of
such block within its function (the number of loop constructs
containing it).
=> spirv-opt: Add function to compute loop nesting depth of a block in StructuredCFGAnalysis

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_opphi_synonyms.cpp, source/fuzz/fuzzer_pass_add_opphi_synonyms.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_opphi_synonym.cpp, source/fuzz/transformation_add_opphi_synonym.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_add_opphi_synonyms_test.cpp, test/fuzz/transformation_add_opphi_synonym_test.cpp
A transformation that adds new OpPhi instructions to blocks with >=1
predecessors, so that its value depends on previously-defined ids of
the right type, which are all synonymous. This instruction is also
recorded as synonymous to the others.
The related fuzzer pass still needs to be implemented.
Fixes #3592 .
=> spirv-fuzz: Create synonym via OpPhi and existing synonyms

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h
There's no real need for Fuzzer, Replayer and Shrinker to use the
opaque pointer design pattern.  This change removes it, paving the way
for making some upcoming changes to Fuzzer easier.
=> spirv-fuzz: Remove opaque pointer design pattern

source/fuzz/call_graph.cpp, source/fuzz/call_graph.h, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_donate_modules.h, test/fuzz/CMakeLists.txt, test/fuzz/call_graph_test.cpp
This PR extends CallGraph with functions to:
- return a list of functions in lexicographical order, with respect to
function calls
- the maximum loop nesting depth that a function can be called from
(computed interprocedurally, e.g. if foo() calls bar() at depth 2
and bar() calls baz() at depth 1, the maximum depth of baz() will
be 3).
=> spirv-fuzz: Compute interprocedural loop nesting depth of blocks

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager/fact_manager.cpp, source/fuzz/fact_manager/fact_manager.h, source/fuzz/fact_manager/irrelevant_value_facts.cpp, source/fuzz/fact_manager/irrelevant_value_facts.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp, source/fuzz/fuzzer_pass_replace_irrelevant_ids.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_id_with_synonym.h, source/fuzz/transformation_replace_irrelevant_id.cpp, source/fuzz/transformation_replace_irrelevant_id.h, test/fuzz/CMakeLists.txt, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_replace_irrelevant_id_test.cpp
A transformation that replaces the use of an irrelevant id with
another id of the same type.
The related fuzzer pass, for every use of an irrelevant id,
checks whether the id can be replaced in that use by another
id of the same type and randomly decides whether to replace
it.
Fixes #3503 .
=> spirv-fuzz: Transformation to replace the use of an irrelevant id

source/fuzz/fuzzer_pass_add_opphi_synonyms.cpp, test/fuzz/fuzzer_pass_add_opphi_synonyms_test.cpp
FuzzerPassAddOpPhiSynonyms::GetIdEquivalenceClasses considers every id
with type among Bool, Integer, Float, Vector, Matrix, Array, Struct,
Pointer (if VariablePointers is enabled) to find sets of potential
synonyms.
However, some instructions with these types cannot be used in an OpPhi:
- OpFunction cannot be used as a value
- OpUndef should not be used, because it yields an undefined value for
each use
Fixes #3761 .
=> spirv-fuzz: Fix GetIdEquivalenceClasses

source/val/validate_builtins.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_builtins_test.cpp
The Vulkan 1.2.152 headers/spec now include Valid Usage IDs (VUID)
for every BuiltIn. This change adds labeling to help aid tracking
the coverage gap in Vulkan targeted validation. This is done with
a script in the Validation Layers that parses the source for VUID
strings, both that there is an implementation and a test for it.
There are 2 main changes:
1. A VUID string is added where applicable. It is wrapped in a function
that at runtimes checks if Vulkan is the target so that other targets
will not be effected as the output error only changes for Vulkan and
the overhead only occurs if there is an error at all.
2. For unit test, a new parameter value was added to allow make sure
that for each VUID there is a matching test. There are cases where the
same unit test checks multiple VUs via …
=> spirv-val: Add Vulkan VUID labels to BuiltIn

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_replace_opselects_with_conditional_branches.cpp, source/fuzz/fuzzer_pass_replace_opselects_with_conditional_branches.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_opselect_with_conditional_branch.cpp, source/fuzz/transformation_replace_opselect_with_conditional_branch.h, source/fuzz/transformation_split_block.cpp, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_construct_composites_test.cpp, test/fuzz/transformation_replace_opselect_with_conditional_branch_test.cpp
This transformation takes an OpSelect instruction and replaces it with
a conditional branch, selecting the correct value using an OpPhi
instruction.
Fixes part of the issue #3544 .
=> spirv-fuzz: Transformation to convert OpSelect to conditional branch

source/opt/struct_cfg_analysis.cpp, source/opt/struct_cfg_analysis.h, test/opt/struct_cfg_analysis_test.cpp
This PR adds the NestingDepth function to StructuredCFGAnalysis.
This function, given a block id, returns the number of merge
constructs containing it.
This is needed by spirv-fuzz, but it makes sense to add it to
StructuredCFGAnalaysis, which contains related functionalities.
=> spirv-opt: Add function to compute nesting depth of a block

CMakeLists.txt, README.md, external/CMakeLists.txt, kokoro/scripts/linux/build.sh, kokoro/scripts/macos/build.sh, kokoro/scripts/windows/build.bat, source/fuzz/CMakeLists.txt, source/fuzz/protobufs/spirvfuzz_protobufs.h
This change improves spirv-fuzz CMake code to be more compatible with other projects that might want to include spirv-fuzz as a sub-project.
* Add a CMake option for building spirv-fuzz. 
* We now check if protobuf targets are already available. 
* We no longer specify `-DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_USE_UNALIGNED=0`; a newer version of protobuf does not require this. Note that we probably should have specified this for protobuf targets as well, but this is no longer needed. 
* Updated protobuf version in Kokoro scripts and README.md.
=> Improve spirv-fuzz CMake code

source/fuzz/CMakeLists.txt
Add CMake option SPIRV_FUZZ_PROTOC_COMMAND for overriding the protoc command. This is needed when cross-compiling, such as when building for Android.
=> spirv-fuzz: Add SPIRV_FUZZ_PROTOC_COMMAND

source/fuzz/fuzzer_pass_add_composite_inserts.h, source/fuzz/fuzzer_pass_add_relaxed_decorations.h, source/fuzz/fuzzer_pass_replace_adds_subs_muls_with_carrying_extended.h, source/fuzz/fuzzer_pass_replace_copy_memories_with_loads_stores.h, source/fuzz/fuzzer_pass_replace_copy_objects_with_stores_loads.h, source/fuzz/fuzzer_pass_replace_loads_stores_with_copy_memories.h, source/fuzz/transformation_add_relaxed_decoration.h, source/fuzz/transformation_composite_insert.h, source/fuzz/transformation_replace_add_sub_mul_with_carrying_extended.h, source/fuzz/transformation_replace_copy_memory_with_load_store.h, source/fuzz/transformation_replace_copy_object_with_store_load.h, source/fuzz/transformation_replace_load_store_with_copy_memory.h
I have corrected header guards in my transformations and fuzzer passes: I have replaced "SPIRV_TOOLS_..." with "SOURCE_FUZZ_..."
=> spirv-fuzz: Fix header guards in transformations/fuzzer passes

source/reduce/conditional_branch_to_simple_conditional_branch_opportunity_finder.cpp, source/reduce/conditional_branch_to_simple_conditional_branch_reduction_opportunity.cpp, source/reduce/merge_blocks_reduction_opportunity.cpp, source/reduce/merge_blocks_reduction_opportunity_finder.cpp, source/reduce/operand_to_const_reduction_opportunity_finder.cpp, source/reduce/operand_to_dominating_id_reduction_opportunity_finder.cpp, source/reduce/operand_to_undef_reduction_opportunity_finder.cpp, source/reduce/reduction_util.cpp, source/reduce/reduction_util.h, source/reduce/remove_block_reduction_opportunity.cpp, source/reduce/remove_block_reduction_opportunity_finder.cpp, source/reduce/remove_selection_reduction_opportunity_finder.cpp, source/reduce/simple_conditional_branch_to_branch_opportunity_finder.cpp, source/reduce/simple_conditional_branch_to_branch_reduction_opportunity.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.h, source/reduce/structured_loop_to_selection_reduction_opportunity_finder.cpp
Avoids the use of "using" in favour of explicit qualification, to be
consistent with spirv-fuzz.  Fixes indentation in a TODO comment.
Addresses and removes two existing TODO comments by moving some helper
functionality into reduction_util.
Related issue: #2184.
=> spirv-reduce: Refactoring

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_duplicate_regions_with_selections.cpp, source/fuzz/fuzzer_pass_duplicate_regions_with_selections.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_duplicate_region_with_selection.cpp, source/fuzz/transformation_duplicate_region_with_selection.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
Adds a transformation that inserts a conditional statement with a
boolean expression of arbitrary value and duplicates a given
single-entry, single-exit region, so that it is present in each
conditional branch and will be executed regardless of which branch will
be taken.
Fixes #3614
=> spirv-fuzz: Add TransformationDuplicateRegionWithSelection

source/opt/ccp_pass.cpp, test/opt/ccp_test.cpp
In #3636, I missed that the instruction folder may create more than a
single constant per call.  Since CCP was only checking whether one
constant had been created after folding, it was wrongly thinking that
the IR had not changed.
Fixes #3738.
=> Properly mark IR changed if instruction folder creates more than one constant

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
This adds more Vulkan built-ins that are targeted at extensions core to Vulkan 1.2 (SPIR-V 1.5)
=> spirv-val: Add BaseInstance, BaseVertex, DrawIndex, and ViewIndex

source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fuzzer_util.cpp, test/fuzz/fact_manager_test.cpp
Fixes #3741.
This PR fixes two bugs:
1. Segfault in https://github.com/KhronosGroup/SPIRV-Tools/blob/4c239bd81bf79337e4a0cfe1c9da9caf1b25108a/source/fuzz/fuzzer_util.cpp#L574-L576 when `result_id` doesn't exist in the module. The bug is triggered in https://github.com/KhronosGroup/SPIRV-Tools/blob/4c239bd81bf79337e4a0cfe1c9da9caf1b25108a/source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp#L290 when `representative->object()` doesn't exist in the module. This can happen in certain cases if we apply `TransformationMergeBlocks` first.
2. Segfault in either https://github.com/KhronosGroup/SPIRV-Tools/blob/4c239bd81bf79337e4a0cfe1c9da9caf1b25108a/source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp#L769 or https://github.com/KhronosGroup/SPIRV-Tools/blob/4c239bd81bf79337e …
=> spirv-fuzz: Handle invalid ids in fact manager

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_bit_instruction_synonyms.cpp, source/fuzz/fuzzer_pass_add_bit_instruction_synonyms.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_bit_instruction_synonym.cpp, source/fuzz/transformation_add_bit_instruction_synonym.h, source/opcode.cpp, source/opcode.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_bit_instruction_synonym_test.cpp
This PR implements part of the add bit instruction synonym transformation.
For now, the implementation covers the `OpBitwiseOr`, `OpBitwiseXor` and
`OpBitwiseAnd` cases.
=> spirv-fuzz: Add bit instruction synonym transformation

source/fuzz/pseudo_random_generator.cpp, source/fuzz/pseudo_random_generator.h, source/fuzz/random_generator.h
This PR extends the RandomGenerator interface and fixes the
PseudoRandomGenerator class. It:
- Fixes a problem that made the RandomUint32 of PseudoRandomGenerator
segfault.
- Adds the RandomUint64 function to RandomGenerator and
PseudoRandomGenerator.
Fixes #3805 .
=> spirv-fuzz: Improvements to random number generation

source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp
=> spirv-fuzz: Use an irrelevant id for the unused components

source/fuzz/transformation_duplicate_region_with_selection.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
Introduces two changes:
1. duplicated_exit_region refers to a correct block, regardless of the order of the blocks in the enclosing function.
2. Exclude the case where the continue target is the exit block.
=> spirv-fuzz: Fix TransformationDuplicateRegionWithSelection

source/fuzz/fuzzer_pass_add_no_contraction_decorations.h, source/fuzz/fuzzer_pass_add_opphi_synonyms.h, source/fuzz/fuzzer_pass_adjust_function_controls.h, source/fuzz/fuzzer_pass_adjust_loop_controls.h, source/fuzz/fuzzer_pass_adjust_selection_controls.h, source/fuzz/fuzzer_pass_apply_id_synonyms.h, source/fuzz/fuzzer_pass_interchange_signedness_of_integer_operands.h, source/fuzz/fuzzer_pass_interchange_zero_like_constants.h, source/fuzz/fuzzer_pass_obfuscate_constants.h, source/fuzz/fuzzer_pass_permute_blocks.h, source/fuzz/fuzzer_pass_replace_irrelevant_ids.h, source/fuzz/fuzzer_pass_replace_opselects_with_conditional_branches.h, source/fuzz/fuzzer_pass_split_blocks.h
Adds missing "H_" to several header guard macros.
=> Fix header guard macros

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, test/fuzz/replayer_test.cpp, tools/fuzz/fuzz.cpp
In preparation for some upcoming work on the shrinker, this PR changes
the interfaces of Fuzzer, Replayer and Shrinker so that all data
relevant to each class is provided on construction, meaning that the
"Run" method can become a zero-argument method that returns a status,
transformed binary and sequence of applied transformations via a
struct.
This makes greater use of fields, so that -- especially in Fuzzer --
there is a lot less parameter passing.
=> spirv-fuzz: Refactor fuzzer, replayer and shrinker

source/cfa.h
Fixed a minor language building snafu with Apple's XCode12 and updated compiler tools. XCode12 is needed for the new MoltenVK (which brings in this library) libraries.
=> Fix compiler error on macOS with XCode12

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_loops_to_create_int_constant_synonyms.cpp, source/fuzz/fuzzer_pass_add_loops_to_create_int_constant_synonyms.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/pass_management/repeated_pass_instances.h, source/fuzz/pass_management/repeated_pass_recommender_standard.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_loop_to_create_int_constant_synonym.cpp, source/fuzz/transformation_add_loop_to_create_int_constant_synonym.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_loop_to_create_int_constant_synonym_test.cpp
This transformation, given a constant integer (scalar or vector) C,
constants I and S of compatible type and scalar 32-bit integer constant
N, such that C = I - S*N, adds a loop which subtracts S from I, N
times, creating a synonym for C.
The related fuzzer pass randomly chooses constants to which to add
synonyms using this transformation, and the location where they should
be added.
Fixes #3616 .
=> spirv-fuzz: Create synonym of int constant using a loop

source/binary.cpp, test/binary_header_get_test.cpp, test/link/binary_version_test.cpp
=> Validate SPIRV Version number when parsing binary header

docs/syntax.md
Fixes apparently missing word:
> an OpCode or a is emitted
=> Docs: Add missing backticks around <result-id>

source/fuzz/replayer.cpp, source/fuzz/replayer.h, source/fuzz/shrinker.cpp, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/replayer_test.cpp, tools/fuzz/fuzz.cpp
Before this change, the replayer would return a SPIR-V binary.  This
did not allow further transforming the resulting module: it would need
to be re-parsed, and the transformation context arising from the
replayed transformations was not available.  This change makes it so
that after replay an IR context and transformation context are
returned instead; the IR context can subsequently be turned into a
binary if desired.
This change paves the way for an upcoming PR to integrate spirv-reduce
with the spirv-fuzz shrinker.
=> spirv-fuzz: Return IR and transformation context after replay

source/fuzz/fuzzer_pass_add_bit_instruction_synonyms.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_bit_instruction_synonym.cpp, source/fuzz/transformation_add_bit_instruction_synonym.h, test/fuzz/transformation_add_bit_instruction_synonym_test.cpp
This PR implements the `OpNot` instruction for the
add bit instruction synonym transformation. In addition,
some code improvements have been made.
=> spirv-fuzz: Support OpNot bit instruction case

source/fuzz/fuzzer_pass_duplicate_regions_with_selections.cpp, source/fuzz/transformation_duplicate_region_with_selection.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
The following changes are introduced:
1. Entry block might have more than one predecessor, even if it is not a selection/loop merge block. However Apply method asserts that there is only one predecessor. Now, IsApplicable method ensures that there is only one predecessor.
2. In fuzzer pass we exclude both loop headers and selection headers as potential exit blocks.
Fixes #3827
=> spirv-fuzz: Fix bug in TransformationDuplicateRegionWithSelection

source/val/validate.cpp
Fix a use-after-move (potential) bug found by the
"bugprone-use-after-move" clang-tidy check.
This is part of a Chromium-related effort (see
https://crbug.com/1122844).
=> Fix use-after-move in val/validate.cpp

include/spirv-tools/libspirv.h, source/disassemble.cpp, tools/dis/dis.cpp
This CL adds some extra new lines and context comments into the
spirv-dis output format. This CL adds:
- Blank line and '; Annotations' before decorations
- Blank line and '; Debug Information' before debug instructions
- Blank line and '; Types, variables and constants' before type section
- Blank line and '; Function <name>' before each function.
Issue #788
=> [spirv-dis] Add some context comments to disassembly.

source/fuzz/transformation_add_constant_composite.cpp, source/fuzz/transformation_add_constant_composite.h, test/fuzz/transformation_add_constant_composite_test.cpp
=> spirv-fuzz: Do not add constants for Block-decorated structs

source/fuzz/CMakeLists.txt, source/fuzz/added_function_reducer.cpp, source/fuzz/added_function_reducer.h, source/fuzz/instruction_message.cpp, source/fuzz/instruction_message.h, source/fuzz/shrinker.cpp, source/fuzz/shrinker.h, source/fuzz/transformation_add_function.h, test/fuzz/CMakeLists.txt, test/fuzz/shrinker_test.cpp
This extends shrinking so that spirv-reduce is employed to simplify
the functions that are added by TransformationAddFunction.
=> spirv-fuzz: Integrate spirv-reduce with shrinker

source/fuzz/transformation_inline_function.cpp, source/fuzz/transformation_inline_function.h, test/fuzz/transformation_inline_function_test.cpp
=> spirv-fuzz: Use overflow ids when inlining functions

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_constant_composite.cpp, source/fuzz/transformation_add_constant_composite.h, source/fuzz/transformation_add_copy_memory.cpp, source/fuzz/transformation_add_copy_memory.h, test/fuzz/transformation_add_copy_memory_test.cpp
=> spirv-fuzz: Avoid using block-decorated structs in transformations

source/fuzz/transformation_duplicate_region_with_selection.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
=> spirv-fuzz: Use overflow ids when duplicating regions

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_propagate_instructions_down.cpp, source/fuzz/fuzzer_pass_propagate_instructions_down.h, source/fuzz/pass_management/repeated_pass_instances.h, source/fuzz/pass_management/repeated_pass_recommender_standard.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_propagate_instruction_down.cpp, source/fuzz/transformation_propagate_instruction_down.h, test/fuzz/CMakeLists.txt, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h, test/fuzz/transformation_propagate_instruction_down_test.cpp
=> spirv-fuzz: TransformationPropagateInstructionDown

source/val/validate_layout.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_layout_test.cpp, test/val/val_state_test.cpp
Currently the validator, when checking an instruction is in the correct
section, always advances the current section. This means if we have an
instruction from a previous section we'll end up reporting it as invalid
in a function definition. This error is confusing.
This CL updates the validator to check if the given opcode is from a
previous layout section before advancing the current section. If it is
from a previous layout section an error is emitted.
=> Update val to handle reversed instruction sections.

source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp
=> spirv-fuzz: Do not replace irrelevant ids that are not in blocks

source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_loop_to_create_int_constant_synonym.cpp, test/fuzz/transformation_add_loop_to_create_int_constant_synonym_test.cpp
=> spirv-fuzz: Fix to transformation that adds a synonym via a loop

source/fuzz/force_render_red.cpp, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/transformation_merge_function_returns.cpp, test/fuzz/fuzz_test_util.cpp, test/fuzz/fuzz_test_util.h
The validity check during fuzzing and in unit tests is strengthened to
require that every block has its enclosing function as its parent.
TransformationMergeFunctionReturns is fixed so that it ensures parents
are set appropriately.
Fixes #3907.
=> spirv-fuzz: Avoid creating blocks without parents

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, test/opt/local_single_store_elim_test.cpp
`DebugInfoManager::AddDebugValueIfVarDeclIsVisible()` adds
OpenCL.DebugInfo.100 DebugValue from DebugDeclare only when the
DebugDeclare is visible to the given scope. It helps us correctly
handle a reference variable e.g.,
```
{ // scope #1.
int foo = /* init */;
{ // scope #2.
int& bar = foo;
...
```
in the above code, we must not propagate DebugValue of `int& bar` for
store instructions in the `scope #1` because it is alive only in
the `scope #2`.
We have an exception: If the given DebugDeclare is used for a function
parameter, `DebugInfoManager::AddDebugValueIfVarDeclIsVisible()` has
to always add DebugValue instruction regardless
of the scope. It is because the initializer (store instruction) for
the function parameter can be out of the function parameter's scope
(the function) in …
=> Add DebugValue for function param regardless of scope

source/fuzz/transformation_flatten_conditional_branch.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Do not allow sampled image load when flattening conditionals

source/fuzz/fuzzer_pass_add_parameters.cpp, source/fuzz/transformation_add_parameter.cpp, source/fuzz/transformation_add_parameter.h
=> spirv-fuzz: Do not allow Block-decorated structs when adding parameters

source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, test/fuzz/transformation_outline_function_test.cpp
=> spirv-fuzz: Avoid void struct member when outlining functions

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
=> spirv-val: Fix validation of OpPhi instructions

source/fuzz/fuzzer_pass_flatten_conditional_branches.cpp, source/fuzz/fuzzer_pass_flatten_conditional_branches.h, source/fuzz/fuzzer_pass_replace_opselects_with_conditional_branches.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_flatten_conditional_branch.h, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Use component-wise selectors when flattening conditional branches

source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp, source/fuzz/transformation_replace_irrelevant_id.cpp, source/fuzz/transformation_replace_irrelevant_id.h, test/fuzz/transformation_replace_irrelevant_id_test.cpp
=> spirv-fuzz: Skip OpFunction when replacing irrelevant ids

source/fuzz/fuzzer_pass_duplicate_regions_with_selections.cpp, source/fuzz/transformation_duplicate_region_with_selection.cpp, source/fuzz/transformation_merge_function_returns.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_compute_data_synonym_fact_closure_test.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
Also incorporates a few style fixes.
Fixes #3940.
=> spirv-fuzz: Fix to TransformationDuplicateRegionWithSelection

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, test/fuzz/transformation_replace_params_with_struct_test.cpp
=> spirv-fuzz: Avoid the type manager when looking for struct types

source/fuzz/fuzzer_pass_add_opphi_synonyms.cpp
=> spirv-fuzz: Skip dead blocks in FuzzerPassAddOpPhiSynonyms

source/fuzz/fuzzer_pass_add_loops_to_create_int_constant_synonyms.cpp
=> spirv-fuzz: Avoid irrelevant constants in synonym-creating loops

source/fuzz/fuzzer_pass_merge_function_returns.cpp, source/fuzz/fuzzer_pass_merge_function_returns.h
=> spirv-fuzz: Skip early terminator wrappers when merging returns

source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp
=> spirv-fuzz: Handle more types when extending OpPhi instructions

source/fuzz/fuzzer_pass_flatten_conditional_branches.cpp, source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_flatten_conditional_branch.h, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Don't flatten conditional if condition is irrelevant

source/fuzz/fuzzer_pass_add_function_calls.cpp
=> spirv-fuzz: Pass OpUndef in function call if needed

source/fuzz/transformation_propagate_instruction_up.cpp, test/fuzz/transformation_propagate_instruction_up_test.cpp
=> spirv-fuzz: Skip OpTypeSampledImage when propagating up

source/fuzz/fuzzer_pass_add_loops_to_create_int_constant_synonyms.cpp
=> spirv-fuzz: Do not add synonym-creating loops in dead blocks

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_replace_irrelevant_id.cpp, test/fuzz/transformation_replace_irrelevant_id_test.cpp
=> spirv-fuzz: Don't replace irrelevant indices in OpAccessChain

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_expand_vector_reductions.cpp, source/fuzz/fuzzer_pass_expand_vector_reductions.h, source/fuzz/pass_management/repeated_pass_instances.h, source/fuzz/pass_management/repeated_pass_recommender_standard.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_expand_vector_reduction.cpp, source/fuzz/transformation_expand_vector_reduction.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_expand_vector_reduction_test.cpp
The following implementations are introduced:
1. Transformation and fuzzer pass for expanding vector reduction.
2. Unit tests to cover the instructions with different vector sizes.
Fixes #3768.
=> spirv-fuzz: Add expand vector reduction transformation

source/opt/ccp_pass.cpp, source/opt/ccp_pass.h, test/opt/ccp_test.cpp
The previous attempts at fixing this issue relied on marking the IR
changed only when CCP was able to fold an instruction during
propagation (https://github.com/KhronosGroup/SPIRV-Tools/pull/3799,
https://github.com/KhronosGroup/SPIRV-Tools/pull/3732).
Those fixes missed the case described in
https://github.com/KhronosGroup/SPIRV-Tools/issues/3991.  In this case,
the folder never actually succeeds in folding the instruction, but it
does create constants in the process.
Fixed with this change.
=> Simplify logic to decide whether CCP modified the IR

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
This patch adds support for the `ViewportIndex` and `Layer` built-ins when their corresponding capabilities are present. Previously, the validator would produce a false positive when encountering them without seeing the old `ShaderViewportIndexLayerEXT` capability.
I also have a pull request for [glslang](https://github.com/KhronosGroup/glslang/pull/2432) which adds support for emitting these new capabilities when targeting SPIR-V 1.5
=> spirv-val: Allow the ViewportIndex and Layer built-ins on SPIR-V 1.5

source/cfa.h
Avoid triggering a warning from newer Clang, which turns into an error
on macOS.
=> Avoid copying a ref in a loop

CMakeLists.txt, source/CMakeLists.txt, source/fuzz/CMakeLists.txt, source/link/CMakeLists.txt, source/opt/CMakeLists.txt, source/reduce/CMakeLists.txt, test/CMakeLists.txt, test/val/CMakeLists.txt, tools/CMakeLists.txt
If enabled the following targets will be created:
* `${SPIRV_TOOLS}-static` - `STATIC` library. Has full public symbol visibility.
* `${SPIRV_TOOLS}-shared` - `SHARED` library. Has default-hidden symbol visibility.
* `${SPIRV_TOOLS}`        - will alias to one of above, based on `BUILD_SHARED_LIBS`.
If disabled the following targets will be created:
* `${SPIRV_TOOLS}`        - either `STATIC` or `SHARED` based on the new `SPIRV_TOOLS_LIBRARY_TYPE` flag. Has full public symbol visibility.
* `${SPIRV_TOOLS}-shared` - `SHARED` library. Has default-hidden symbol visibility.
Defaults to `ON`, matching existing build behavior.
This flag can be used by package maintainers to ensure that all libraries are build as shared objects.
This is a temporary solution to getting package maintainers up and …
=> CMake: Add SPIRV_TOOLS_BUILD_STATIC flag

source/opt/function.h, source/opt/inline_pass.cpp, test/opt/inline_test.cpp
This commit add an option for optimizer to not inline functions with DontInline control flag, so that the [noinline] attribute in HLSL will be useful in DXC SPIR-V generation.
This is part of work of github.com/microsoft/DirectXShaderCompiler/issues/3158
=> spirv-opt: Add option to prevent functions from being inlined if they have DontInline flag

BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/empty_pass.h, source/opt/optimizer.cpp, source/opt/passes.h
Removing PropagateLineInfoPass and RedundantLineInfoElimPass from
56d0f5035 makes unit tests of many open source projects fail.
It will happen before submitting this glslang PR
https://github.com/KhronosGroup/glslang/pull/2440. This commit will be
git-reverted after merging the glslang PR.
=> Temporarily add EmptyPass to prevent glslang from failing

source/fuzz/fuzzer_pass_flatten_conditional_branches.cpp, source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_flatten_conditional_branch.h, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Fix bugs in TransformationFlattenConditionalBranch

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_bit_instruction_synonyms.cpp
Adds some functions that allow a fuzzer pass to check whether it is
spiralling out of control and exit early.  The fuzzer pass for adding
bit instruction synonyms now uses this.  Also make many methods in
FuzzerContext const.
=> spirv-fuzz: Add support for reining in rogue fuzzer passes

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/pass_management/repeated_pass_manager_random_with_recommendations.cpp
Fixes a bug in the "random with recommendations" strategy, and tweaks
various probabilities to aim for more interesting fuzzer pass
combinations.
=> spirv-fuzz: Fixes to pass management

source/opt/ssa_rewrite_pass.cpp, test/opt/local_ssa_elim_test.cpp
This fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/3873.
In the presence of variable pointers, the reaching definition may be
another pointer.  For example, the following fragment:
```
%2 = OpVariable %_ptr_Input_float Input
%11 = OpVariable %_ptr_Function__ptr_Input_float Function
OpStore %11 %2
%12 = OpLoad %_ptr_Input_float %11
%13 = OpLoad %float %12
```
corresponds to the pseudo-code:
```
layout(location = 0) in flat float *%2
float %13;
float *%12;
float **%11;
*%11 = %2;
%12 = *%11;
%13 = *%12;
```
which ultimately, should correspond to:
```
%13 = *%2;
```
During rewriting, the pointer `%12` is found to be replaceable by `%2`.
However, when processing the load `%13 = *%12`, the type of `%12`'s reaching
definition is another float pointer (`%2`), instead of a float value. …
=> Fix SSA re-writing in the presence of variable pointers

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/local_single_store_elim_pass.cpp, source/opt/local_single_store_elim_pass.h, test/opt/local_single_store_elim_test.cpp
The front-end language compiler would simply emit DebugDeclare for
a variable when it is declared, which is effective through the variable's
scope. Since DebugDeclare only maps an OpVariable to a local variable,
the information can be removed when an optimization pass uses the
loaded value of the variable. DebugValue can be used to specify the
value of a variable. For each value update or phi instruction of a variable,
we can add DebugValue to help debugger inspect the variable at any
point of the program execution.
For example,
float a = 3;
... (complicated cfg) ...
foo(a); // <-- variable inspection: debugger can find DebugValue of `float a` in the nearest dominant
For the code with complicated CFG e.g., for-loop, if-statement, we
need help of ssa-rewrite to analyze the effective value …
=> Add DebugValue for invisible store in single_store_elim

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
Adds labeling for 
VUID-Layer-Layer-04275
VUID-Layer-Layer-04274
VUID-ViewportIndex-ViewportIndex-04406
VUID-ViewportIndex-ViewportIndex-04407
Also adds missing MeshNV stage from check which is in the spec
=> spirv-val: Label Layer and ViewportIndex VUIDs

source/val/validation_state.cpp, test/val/val_builtins_test.cpp
in #3943 the new tests should have failed since it was missing the switch case in `validation_state.cpp`, but didn't due to the `AnyVUID()` check not handling case with trailing whitespace. 
```
Values("VUID-PrimitiveShadingRateKHR-PrimitiveShadingRateKHR-04485 ")
```
Added trimming to handle it as easily might happen again in future and rather the above example to still work when writing tests to make it easier
cc @Tobski
=> spirv-val: Fix SPV_KHR_fragment_shading_rate VUID label

source/val/validate_builtins.cpp
Don't pass a constructed string as an argument to
ValidateNotCalledwithExecutionModel. That method is captured via
std::bind and it ends up using lots of stack space.
Instead, pass in:
- a Vulkan validation unique ID as an integer instead,
(with -1 meaning no VUID), and
- the const char* for the explanator text.
=> Use less stack space when validating Vulkan builtins

source/fuzz/force_render_red.cpp, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_early_terminator_wrapper.cpp, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_inline_function.cpp, source/fuzz/transformation_merge_function_returns.cpp, source/fuzz/transformation_outline_function.cpp, source/opt/basic_block.cpp, source/opt/eliminate_dead_members_pass.cpp, source/opt/function.cpp, source/opt/function.h, source/opt/inst_buff_addr_check_pass.cpp, source/opt/instrument_pass.cpp, source/opt/loop_peeling.cpp, source/opt/merge_return_pass.cpp, source/opt/wrap_opkill.cpp
Ensures that the parent of a block is set in Function::AddBasicBlock.
Removes various now unnecessary calls to BasicBlock::SetParent.
Fixes #3912.
=> spirv-opt: Set parent when adding basic block

source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/eliminate_dead_members_pass.cpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
Matrix stride decoration is not on matrix type but is a member decoration
on the enclosing struct type. Also correctly apply matrix stride depending
on row or column major.
=> Fix buffer oob instrumentation for matrix refs

source/opt/build_module.cpp, source/opt/build_module.h, source/opt/ir_loader.cpp, source/opt/ir_loader.h, test/opt/ir_loader_test.cpp
=> BuildModule: optionally avoid adding new OpLine instructions

include/spirv-tools/instrument.hpp, include/spirv-tools/optimizer.hpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, source/opt/optimizer.cpp, test/opt/inst_bindless_check_test.cpp
This instruments ImageRead, ImageWrite and ImageFetch when applied to
texel buffers.
Also add new (but not yet generated) buffer OOB error codes differentiated
for VUID classification.
=> Add texel buffer out-of-bounds checking instrumentation

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp, test/val/val_code_generator.cpp
Add validation for ray tracing builtins
- Remove existing InstanceId testing that was combined with VertexId in awkward ways.
- Rather than adding a new set of functions for each ray tracing builtin, add
an error table that maps the builtin ID to the 3 common VUIDs for each builtin
(I could see this being extended for other builtins in the future).
- add F32 matrix validation function
- augment existing PrimitiveId validation to verify Input storage class for the
RT stages this is accepted in, and correct the list of stages that it is actually
accepted in (only Intersection / Any Hit / Closest Hit)
Add testing for ray tracing builtins
- remove existing InstanceId testing as it was tangled in with VertexId in now weird ways
and combine it with the new tests
- add testing for ray tracing …
=> Add validation support for the ray tracing built-in variables

source/opt/eliminate_dead_members_pass.cpp, test/opt/eliminate_dead_member_test.cpp
The eliminate dead member pass is written assuming that the index to an
OpAccessChain will be a 32-bit integer or 64-bit integer.  That is
changed to work for any width 64-bits or less.
Fixes https://crbug.com/1151727
=> Handle 8-bit index in elim dead member

source/opt/aggressive_dead_code_elim_pass.cpp
When support for `KHR_ray_query` and `KHR_ray_tracing` [landed in SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools/commit/5a97e3a391677ff9baae8ccdf5c03c4d403d848b), it missed adding ray_query to acceptable extensions for DCE.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/3287
=> Do run DCE if SPV_KHR_ray_query is used.

source/opt/aggressive_dead_code_elim_pass.cpp
Similar to [1] DCE should be ran when this extension is enabled to prevent unused bindings from showing up (in particular atomic counters attached to buffers).
[1]: https://github.com/KhronosGroup/SPIRV-Tools/pull/4047
=> opt: Run DCE when SPV_KHR_shader_clock is used

source/operand.cpp, source/val/validate_id.cpp, test/val/val_data_test.cpp
Fixes #4042
* Allow types to have forward declarations as long as that declaration
is an OpTypeForwardPointer
This brings the validator in line with the clarification made in SPIR-V 1.5 revision 2.
=> Allow forward pointer to be used in types generally

source/val/validate_image.cpp, test/val/val_image_test.cpp
The StorageImageMultisampled capability is required when declaring
an image type with with Multisampled==1 and it's a storage image (Sampled == 2)
Fixes #4061
=> validate StorageImageMultisampled capability

utils/git-sync-deps
This scripts fails to run in Python 2.
For systems that have both Python 2 and 3 installed, 
depending on your PATH the existing code may or 
may not run. Explictly using Python 3 to avoid this.
=> Force using Python 3 git-sync-deps

source/val/validate_image.cpp, test/val/val_image_test.cpp
- if MS=1, then Sample image operand is required
- Sampling operations are not permitted when MS=1
Fixes #4057, #4058
=> validation: tighter validation of multisampled images

source/val/validate_image.cpp, test/val/val_image_test.cpp, test/val/val_opencl_test.cpp
Vulkan: must be 4-element vector
WebGPU: must be 4-element vector
OpenCL:
- must be scalar float for depth image
- must be 4-element vector otherwise
=> validation: validate return type of OpImageRead

source/fuzz/transformation_duplicate_region_with_selection.cpp, source/fuzz/transformation_duplicate_region_with_selection.h, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
Avoid generating OpPhi on void types, and allow the transformation to
take place on regions that produce pointer and sampled image result
ids if such ids are not used after the region.
Fixes #3787.
=> spirv-fuzz: Fix OpPhi handling in DuplicateRegionWithSelection

source/val/validate_mode_setting.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp, test/val/val_fixtures.h, test/val/val_id_test.cpp
Adds `VUID-StandaloneSpirv-None-04633`
Now that most of the Built-ins are done, the next goal is to add VUID labels to all the Vulkan Spec's SPIR-V Standalone validation rules
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap46.html#spirvenv-module-validation
This will make it easy to see the gaps missing in `spirv-val` which I can then add
=> spirv-val: Add first StandAlone VUID 04633

source/val/validate_non_uniform.cpp, source/val/validation_state.cpp, test/val/val_non_uniform_test.cpp
`VUID-StandaloneSpirv-OpGroupNonUniformBallotBitCount-04685`
> If OpGroupNonUniformBallotBitCount is used, the group operation must be limited to Reduce, InclusiveScan, or ExclusiveScan
=> spirv-val: Add Vulkan Group Operation VUID

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
`VUID-StandaloneSpirv-OpImageTexelPointer-04658`
> If an OpImageTexelPointer is used in an atomic operation, the image type of the image parameter to OpImageTexelPointer must have an image format of R64i, R64ui, R32f, R32i, or R32ui
=> spirv-val: Add Vulkan ImageTexelPointer format check

source/val/validate_type.cpp, source/val/validation_state.cpp, test/val/val_data_test.cpp
`VUID-StandaloneSpirv-OpTypeForwardPointer-04711`
> OpTypeForwardPointer must have a storage class of PhysicalStorageBuffer
=> spirv-val: Add Vulkan ForwardPointer VUID

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
Fix to match the Vulkan `VUID-StandaloneSpirv-OpTypeImage-04656`
> OpTypeImage must declare a scalar 32-bit float, 64-bit integer, or 32-bit integer type for the “Sampled Type” (RelaxedPrecision can be applied to a sampling instruction and to the variable holding the result of a sampling instruction)
Added more test coverage of various types as well
=> spirv-val: Fix Vulkan image sampled check

source/val/validate_decorations.cpp, source/val/validation_state.cpp, test/val/val_decoration_test.cpp
`VUID-StandaloneSpirv-FPRoundingMode-04675`
> Only the round-to-nearest-even and the round-towards-zero rounding modes can be used for the FPRoundingMode decoration
=> spirv-val: Add Vulkan FP Mode VUID

source/opt/desc_sroa.cpp, source/opt/desc_sroa.h, test/opt/desc_sroa_test.cpp
When there is an array of strutured buffers, desc sroa will only split
the array, but not a struct type in the structured buffer.  However,
the calcualtion of the number of binding a struct requires does not take
this into consideration.  This commit will fix that.
=> Fix binding number calculation in desc sroa

source/val/validate_annotation.cpp, source/val/validation_state.cpp, test/val/val_decoration_test.cpp
Copied same style as the WebGPU `IsValidWebGPUDecoration()`
`VUID-StandaloneSpirv-GLSLShared-04669`
> The GLSLShared and GLSLPacked decorations must not be used
=> spirv-val: Add Vulkan decoration VUID

source/val/validate_image.cpp, source/val/validate_memory.cpp, source/val/validate_memory_semantics.cpp, source/val/validate_misc.cpp, source/val/validate_mode_setting.cpp, source/val/validate_scopes.cpp, source/val/validation_state.cpp, test/val/val_barriers_test.cpp, test/val/val_image_test.cpp, test/val/val_memory_test.cpp, test/val/val_misc_test.cpp, test/val/val_modes_test.cpp, test/val/val_non_uniform_test.cpp
Groupped into single commit/PR to as this is just some more labeling of VUID where spirv-val already had coverage. Added some tests to force the Vulkan Env path for some tests
=> spirv-val: Label standalone Vulkan VUID

test/val/val_decoration_test.cpp
=> use std::string::empty() to test for emptiness

include/spirv-tools/instrument.hpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
This allows the GPU-AV layer to differentiate between errors with
uniform buffers versus storage buffers and map these to the relevant
VUIDs.
=> Generate differentiated error codes for buffer oob checking

include/spirv-tools/instrument.hpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
Reverts KhronosGroup/SPIRV-Tools#4097
Breaks the validation layers which depend on the removed `kInstErrorBindlessBuffOOB`.
=> Revert "Generate differentiated error codes for buffer oob checking"

source/link/linker.cpp, tools/link/linker.cpp
* Error out if an option is not recognized by spirv-link instead of silently ignoring it.
* Improve the output of the usage function of spirv-link.
* Change the output default of spirv-link from the standard output to "spv.out" to match the other tools.
* Change the default environment of spirv-link from spv1.0 to spv1.5 to match the other tools.
* Change the targets reported by `spirv-link --version` to just list the currently selected environment.
* A few improvements to the code of spirv-link and error reporting of the linker.
=> Linker usability improvements

source/opt/ir_loader.cpp, source/opt/module.h, source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
This bug was reported by https://bugs.chromium.org/p/chromium/issues/detail?id=1149065
(Chromium ClusterFuzzer)
The commit 56d0f50357a192602216bfc4873e714905323e35 propagates the
extra line instruction to all instructions that are applied in order to
properly preserve the line information through the optimization. As a
result, it contains additional line instructions that actually do not
exist in the input SPIR-V. It results in the mismatch between the input
and the output SPIR-V when spirv-opt does not conduct any optimization.
This commit adds `bool is_extra_line_` to `class Instruction` of
spirv-opt to determine weather the line instruction exists in the input
or it is just added for the extra line tracking. When spirv-opt dumps
the binary, it always outputs the line instruction if it …
=> Output the same line instructions when no optimization is done

source/val/validate_atomics.cpp, source/val/validation_state.cpp, test/val/val_atomics_test.cpp
`VUID-StandaloneSpirv-None-04686`
> The Pointer operand of all atomic instructions must have a Storage Class limited to Uniform, Workgroup, Image, StorageBuffer
=> spirv-val: Vulkan atomic storage class

source/val/validate_mode_setting.cpp, source/val/validation_state.cpp
I tried writing a negative test, but the issue is the only invalid addressing models currently are Physical32/64 which both need the `Addresses` capability and it will hit that error first
Adding for future-proofing if a Non-Vulkan API adds a new addressing model
Also covers `VUID-StandaloneSpirv-None-04635`
=> spirv-val: Add Vulkan Addressing Model check

android_test/jni/Application.mk, kokoro/android/build.sh, kokoro/linux-clang-asan/build.sh, kokoro/linux-clang-debug/build.sh, kokoro/linux-clang-release-bazel/build.sh, kokoro/linux-clang-release/build.sh, kokoro/linux-gcc-debug/build.sh, kokoro/linux-gcc-release/build.sh, kokoro/ndk-build/build.sh, kokoro/scripts/linux/build-docker.sh, kokoro/scripts/linux/build.sh, kokoro/shaderc-smoketest/build.sh, source/opt/instruction.h, utils/check_copyright.py
Required updating the NDK SDK and build scripts, as well as the check_copyright for handling 2021.
=> Migrate all Kokoro build scripts over to use the docker VM image

include/spirv-tools/libspirv.h, source/binary.cpp, source/disassemble.cpp, source/operand.cpp
This patch supports new Intel extensions added via
https://github.com/KhronosGroup/SPIRV-Headers/pull/176
SPV_INTEL_fooat_controls2 requires extra support to add
two new operand types:
SPV_OPERAND_TYPE_FPDENORM_MODE
SPV_OPERAND_TYPE_FPOPERATION_MODE
=> Support pending Intel extensions

build_overrides/build.gni
The linux_use_bundled_binutils_override flag is obsolete, see https://crbug.com/1164276.
=> Remove obsolete GN config

source/val/validate_memory_semantics.cpp, source/val/validation_state.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp
VUID-StandaloneSpirv-OpAtomicStore-04730
VUID-StandaloneSpirv-OpAtomicLoad-04731
VUID-StandaloneSpirv-OpMemoryBarrier-04732
VUID-StandaloneSpirv-OpMemoryBarrier-04733
=> spirv-val: Label Vulkan atomic semantics VUIDs

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
Validate that workgroup variables can now have an initializer that is restricted to OpConstantNull.
=> Validate VK_KHR_zero_initialize_workgroup_memory

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/local_single_store_elim_pass.cpp, source/opt/scalar_replacement_pass.cpp, source/opt/ssa_rewrite_pass.cpp, test/opt/debug_info_manager_test.cpp, test/opt/local_single_store_elim_test.cpp, test/opt/local_ssa_elim_test.cpp
The existing spirv-opt `DebugInfoManager::AddDebugValueForDecl()` sets
the scope and line info of the new added DebugValue using the scope and
line of DebugDeclare. This is wrong because only a single DebugDeclare
must exist within a scope while we have to add multiple DebugValues for all the
places where the variable's value is updated. Therefore, we have to set
the scope and line of DebugValue based on the places of the variable
updates.
This bug makes
https://github.com/google/amber/blob/main/tests/cases/debugger_hlsl_shadowed_vars.amber
fail. This commit fixes the bug.
=> Set correct scope and line info for DebugValue

source/opt/convert_to_half_pass.cpp, source/opt/convert_to_half_pass.h, source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, test/opt/convert_relaxed_to_half_test.cpp
If the convert-to-half pass does not change the body of the function,
but removes decorations, it returns that nothing changed.  This is
incorrect, and will be fixed.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4117
=> Mark module as modified if convert-to-half removes decorations.

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
VUID-StandaloneSpirv-OpImageQuerySizeLod-04659
=> spirv-val: label tests for VUID 04659

include/spirv-tools/instrument.hpp, source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
This allows the GPU-AV layer to differentiate between errors with
uniform buffers versus storage buffers and map these to the relevant
VUIDs.
This is a resubmit of a previously reverted commit. The revert was
done as someone erroneously attempted to build the latest validation
layers with a TOT spirv-tools. The validation layers must be built with
their known-good glslang and its known-good spirv-tools and spirv-headers.
=> Resubmit: Generate differentiated error codes for buffer oob checking

source/opt/fix_storage_class.cpp, source/opt/pass.cpp, test/opt/fix_storage_class_test.cpp
This change is needed by this DirectXShaderCompiler pull request: https://github.com/microsoft/DirectXShaderCompiler/pull/3395
Since the DirectXShaderCompiler change linked above adds the ImageFormat only for global texture/buffer variables, they need to be propagated by the legalization pass to all variables and function parameters where the global resource is assigned.
However, the generated SPIR-V will initially have mismatches in the formats, and this change in Pass::GenerateCopy allows the source and destination to have
separate image formats. Legalization seems to generate valid SPIR-V in this case so allowing the type mismatch between source and destination in case of image types seems to be OK. Not sure if this is the cleanest/proper way to do it though, but not being very …
=> spirv-opt: Allow image type mismatch in GenerateCopy

utils/vscode/README.md, utils/vscode/go.mod, utils/vscode/go.sum, utils/vscode/install.bat, utils/vscode/spirv.json, utils/vscode/src/langsvr.go, utils/vscode/src/lsp/protocol/log.go, utils/vscode/src/lsp/protocol/protocol.go, utils/vscode/src/lsp/protocol/span.go, utils/vscode/src/lsp/protocol/tsclient.go, utils/vscode/src/lsp/protocol/tsserver.go, utils/vscode/src/parser/parser.go, utils/vscode/src/schema/schema.go, utils/vscode/src/tools/gen-grammar.go
Fix URL to the OpenCL.DebugInfo.100 grammar file, which moved from SPIRV-Tools to SPIRV-Headers.
Add a `go.mod` and `go.sum` file.
Go has now fully migrated to using modules, and relative imports no longer work.
Fixup all the relative imports to use a fully qualified path based on the module name.
Fix the `.exe` executable extension on windows.
Update the generated grammar files.
Update the README.md with more information.
=> Fixes for the vscode language server extension

tools/as/as.cpp, tools/cfg/cfg.cpp, tools/dis/dis.cpp, tools/fuzz/fuzz.cpp, tools/io.h, tools/link/linker.cpp, tools/opt/opt.cpp, tools/reduce/reduce.cpp, tools/val/val.cpp
The first implementation to try to change stdin to binary mode is not
portable.  Using freopen has a lot of implementation defined behavior,
and the code relied on that working.
Looking into the MSVC documentation, I do not see a portable way of
doing this.  I've implemented a Windows specific method and do nothing
for other systems.  In general, UNIX based systems do make a distinction
between text and binary files, so nothing needs to be done for them.
Fixes #2518
=> Use standard function to get stdin to binary mode.

source/val/validate_cfg.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/block_merge_test.cpp, test/opt/dead_branch_elim_test.cpp, test/val/val_cfg_test.cpp, test/val/val_limits_test.cpp
Fixes #4153
* OpSwitch is required to be preceeded by OpSelectionMerge
* Update newly invalid tests
=> Require an OpSelectionMerge before an OpSwitch

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/pass_management/repeated_pass_manager.cpp, source/fuzz/pass_management/repeated_pass_manager.h, test/fuzz/fuzzer_pass_add_opphi_synonyms_test.cpp, test/fuzz/fuzzer_pass_construct_composites_test.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/fuzzer_pass_outline_functions_test.cpp, test/fuzz/fuzzer_pass_test.cpp, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/fuzzer_shrinker_test.cpp, test/fuzz/shrinker_test.cpp, tools/fuzz/fuzz.cpp
This PR adds the ability to call `Fuzzer::Run` multiple times in a single lifetime of the `Fuzzer`.
@afd for info.
=> spirv-fuzz: Add persistent state to the fuzzer

source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp
While adding Vulkan Validation support for runtime checking of 64-bit atomics, I realized that spirv-val was using the result type to check width, which doesn't work because of `OpAtomicStore` lack of result
=> spirv-val: Vulkan 64-bit OpAtomicStore check

source/fuzz/force_render_red.cpp, source/fuzz/force_render_red.h, tools/fuzz/fuzz.cpp
The fuzzer library depended on CLIMessageConsumer, due to its explicit
use in a function. This change removes that dependency so that,
instead, a message consumer parameter is passed.
=> spirv-fuzz: Avoid unnecessary dependency

BUILD.gn
@ben-clayton PTAL this trivial fix (and also, whooops)
=> BUILD.gn: fix typo for 'cflags'

source/opt/iterator.h, source/val/basic_block.h
This helper class was deprecated in C++17 and some compilers start
warning about it. Replaces usages of std::iterator with manual type
aliases.
=> Remove usage of std::iterator.

source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_replace_id_with_synonym.cpp, source/fuzz/transformation_swap_conditional_branch_operands.cpp
The performance of spirv-fuzz is sometimes poor due to analyses being
conservatively invalidated. This can lead to quadratic time algorithms
when a fuzzer pass applies O(N) transformations, and where every
transformation e.g. depends on def-use analysis and invalidates
def-use analysis (because building def-use analysis is O(N)).
This change avoids invalidating analyses for certain transformations.
=> spirv-fuzz: Avoid invalidating analyses

source/val/validate.cpp, source/val/validation_state.cpp, test/val/val_validation_state_test.cpp
Adds label for `VUID-StandaloneSpirv-None-04634`
>  The static function-call graph for an entry point must not contain cycles; that is, static recursion is not allowed
=> spirv-val: Label VUID 04634

source/val/validate_atomics.cpp, source/val/validate_barriers.cpp, source/val/validate_memory_semantics.cpp, source/val/validate_memory_semantics.h, source/val/validation_state.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp
Adds validation for `VUID-StandaloneSpirv-None-04641`
>  If the Scope for memory is Invocation, then memory semantics must be None
=> spirv-val: Add Vulkan Invocation Sematics check

source/opt/scalar_replacement_pass.cpp, source/opt/scalar_replacement_pass.h, test/opt/scalar_replacement_test.cpp
We have to conduct the scalar replacement for an aggregate with an image
type even when it has OpImageTexelPointer users.
=> Accept OpImageTexelPointer user in scalar-replacement

source/fuzz/transformation_permute_phi_operands.cpp
Amends def-use information rather than invalidating all analyses in
TransformationPermutePhiOperands.
=> spirv-fuzz: Make PermutePhiOperands more efficient

source/val/validate_scopes.cpp, source/val/validation_state.cpp, test/val/val_barriers_test.cpp, test/val/val_decoration_test.cpp
With https://github.com/KhronosGroup/SPIRV-Headers/pull/198 merged, this should be correct
`VUID-StandaloneSpirv-None-04636`
> Scope for execution must be limited to Workgroup or Subgroup
`VUID-StandaloneSpirv-None-04637`
> If the Scope for execution is Workgroup, then it must only be used in the task, mesh, tessellation control, or compute execution models
`VUID-StandaloneSpirv-OpControlBarrier-04682`
> If OpControlBarrier is used in ray generation, intersection, any-hit, closest hit, miss, fragment, vertex, tessellation evaluation, or geometry shaders, the execution Scope must be Subgroup
=> spirv-val: Add Vulkan Execution Scope checks

source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp, test/val/val_image_test.cpp
I still have more refactoring for the atomic validation pass coming, but decided to break this up as its own PR to make sure the change to the tests are correct.
Also note that all uses of `Int64ImageEXT` are already being validated in the `ValidateTypeImage` pass and test coverage seemed good.
=> spirv-val: Fix Int64Atomics check

source/val/validate_type.cpp, source/val/validation_state.cpp, test/val/val_id_test.cpp
VUID-StandaloneSpirv-None-04667
Structure types must not contain opaque types
=> spirv-val: Label VUID 04667

source/val/validate_memory.cpp, source/val/validate_type.cpp, source/val/validation_state.cpp, test/val/val_misc_test.cpp
VUID-StandaloneSpirv-None-04643
Storage Class must be limited to UniformConstant, Input, Uniform, Output, Workgroup, Private, Function, PushConstant, Image, StorageBuffer, RayPayloadKHR, IncomingRayPayloadKHR, HitAttributeKHR, CallableDataKHR, IncomingCallableDataKHR, ShaderRecordBufferKHR, or PhysicalStorageBuffer
I also think this actually closes #1504 (granted it could have been probably before this PR)
=> spirv-val: Label VUID 04643

source/val/validate_atomics.cpp, test/val/val_atomics_test.cpp
- Created helper functions to handle the result type case logic
-  This allows the `result_type` logic to be much cleaner and convey what it is trying to do
- Some of the original error message used `int` and some used `integer` and was causing tests to fail... just made it consistent for the file
- The `OpAtomicCompareExchange` tests seemed to have copy-paste errors from `OpAtomicExchange` tests and was allowing float results so had to modify basically all of them to keep the same error message to be used
=> spirv-val: Refactor of atomic pass

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_constant_boolean.cpp, source/fuzz/transformation_add_constant_boolean.h, source/fuzz/transformation_add_constant_composite.cpp, source/fuzz/transformation_add_constant_composite.h, source/fuzz/transformation_add_constant_null.cpp, source/fuzz/transformation_add_constant_null.h, source/fuzz/transformation_add_constant_scalar.cpp, source/fuzz/transformation_add_constant_scalar.h, source/fuzz/transformation_add_global_undef.cpp, source/fuzz/transformation_add_global_undef.h, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, source/fuzz/transformation_add_local_variable.cpp, source/fuzz/transformation_add_local_variable.h, test/fuzz/transformation_add_constant_boolean_test.cpp, test/fuzz/transformation_add_constant_composite_test.cpp, test/fuzz/transformation_add_constant_null_test.cpp, test/fuzz/transformation_add_constant_scalar_test.cpp, test/fuzz/transformation_add_global_undef_test.cpp, test/fuzz/transformation_add_global_variable_test.cpp, test/fuzz/transformation_add_local_variable_test.cpp
Avoids invalidating all analyses in transformations that add
constants, OpUndef and global and local variables.
=> spirv-fuzz: Avoid invalidating analyses in various transformations

test/fuzz/transformation_add_type_array_test.cpp, test/fuzz/transformation_add_type_boolean_test.cpp, test/fuzz/transformation_add_type_float_test.cpp, test/fuzz/transformation_add_type_int_test.cpp, test/fuzz/transformation_add_type_matrix_test.cpp, test/fuzz/transformation_add_type_pointer_test.cpp, test/fuzz/transformation_add_type_struct_test.cpp, test/fuzz/transformation_add_type_vector_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp, test/fuzz/transformation_permute_phi_operands_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp, test/fuzz/transformation_set_loop_control_test.cpp, test/fuzz/transformation_swap_conditional_branch_operands_test.cpp
To help ensure that optimizations that do less cautious invalidation
of analyses are implemented correctly, this change adds checks to the
tests of various transformations to ensure that analyses such as
def-use are up to date.
=> spirv-fuzz: Improve transformation test oracles

source/CMakeLists.txt
Required to support latest Xcode
Fixes #4109
=> Make spirv-tools-build-version a common dependency

source/fuzz/transformation_access_chain.cpp, source/fuzz/transformation_add_copy_memory.cpp, source/fuzz/transformation_add_synonym.cpp, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_composite_insert.cpp, source/fuzz/transformation_equation_instruction.cpp, source/fuzz/transformation_load.cpp, source/fuzz/transformation_mutate_pointer.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_replace_constant_with_uniform.cpp, source/fuzz/transformation_replace_copy_object_with_store_load.cpp, source/fuzz/transformation_replace_irrelevant_id.cpp, source/fuzz/transformation_store.cpp, source/fuzz/transformation_vector_shuffle.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp
Avoids blanket invalidation of analyses in several transformations,
instead updating the def-use manager and instruction to block mapping.
=> spirv-fuzz: Optimize transformations

source/fuzz/fuzzer_pass_add_dead_blocks.cpp
Profiling has shown that adding large numbers of dead block
transformations can be expensive because each on requires dominator
analysis information, and each one invalidates this information. There
is currently no obvious mechanism for incrementally updating the
dominator analysis. This change restricts the number of these
transformations that a single fuzzer pass will apply, to restrict this
performance bottleneck.
=> spirv-fuzz: Do not add too many dead blocks

source/fuzz/transformation_split_block.cpp
It is easy to avoid the need to invalidate the def-use analysis and
instruction to block mapping when splitting blocks, and profiling has
revealed that invalidation of def-use in particular is expensive when
splitting many blocks. This change avoids these invalidations.
=> spirv-fuzz: Avoid invalidating analyses when splitting blocks

source/fuzz/fuzzer_pass_add_composite_types.cpp, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_pass_construct_composites.h, source/fuzz/transformation_add_type_array.cpp, source/fuzz/transformation_add_type_array.h, source/fuzz/transformation_add_type_struct.cpp, source/fuzz/transformation_add_type_struct.h
FuzzerPassConstructComposites is adapted to use AvailableInstructions
to manage available instructions, and to use zero constants when
trying to construct a composite for which not all fields can otherwise
be constructed.
=> spirv-fuzz: Efficiency improvements to fuzzer pass

kokoro/check-format/build.sh
Also add the `--fail` flag so that `kokoro/check-format/build.sh` fails when it cannot download the `clang-format-diff.py` script.
=> Fix clang-format-diff.py URL

BUILD.gn
UWP doesn't support system(), so skip building spirv-reduce on it
similarly to iOS.
=> Fix UWP build

source/fuzz/fuzzer_pass_donate_modules.cpp
There are some edge cases where adding livesafe functions does not
succeed, due to loop limiter edges breaking SPIR-V dominance rules. As
these edge cases are rare it does not seem worth implementing complex
additional logic to handle all cases. This change accepts that trying
to add a function in a livesafe manner may not succeed.
=> spirv-fuzz: Accept limitations in AddFunction

test/val/val_builtins_test.cpp
re-ran clang-format and happy with change... it shouldn't have broken a string in for a newline with `-` connecting it in first place, but not going to lose sleep over it though
=> spriv-val: Fix clang-format bug for VUID string

utils/check_copyright.py
There are a few places where `is` is used when `==` should be used.
Part of #4250
=> Fix warning in python script.

source/opt/loop_unroller.cpp, test/opt/loop_optimizations/unroll_simple.cpp
When unrolling the following loop:
```
%const0 = OpConstant ...
%const1 = OpConstant ...
...
%LoopHeader = OpLabel
%phi0 = OpPhi %float %const0 %PreHeader %phi1 %Latch
%phi1 = OpPhi %float %const1 %PreHeader %x    %Latch
...
%LoopBody = OpLabel
%x = OpFSub %float %phi1 %phi0
...
```
the loop-unroll pass sets the value of `%phi0` as `%phi1` for the second
copy of the loop body. For example, the second copy of
`%x = OpFSub %float %phi1 %phi0` will be
`%y = OpFSub %float %x %phi1`.
Since all phi instructions for inductions will be removed after the
loop unrolling, `%phi1` will be a dead dangling phi. This CL keeps the
phi value from the previous loop iteration to map instruction operands
to the phi value instead of using phi.
For example, the second copy of `%x = OpFSub %float %phi1 %phi0` …
=> Fix dangling phi bug from loop-unroll

source/reduce/change_operand_to_undef_reduction_opportunity.cpp
Fixes #4252.
Also, I've noticed that if you add `CheckValid` to unit tests to all the places it's missing from (e.g. when the initial binary is constructed, after every `TryToApply` etc), a bunch of tests fail. I also have doubts about whether `CheckValid` ensures that the module is well-formed (i.e. all analyses are correct) - maybe `fuzzerutil::IsValidAndWellFormed` can help with that?
Either way, I think refactoring tests (if at all) is better left for a separate PR.
=> spirv-reduce: Invalidate DefUse analysis

source/CMakeLists.txt
Fixes the following linker errors when building Android binaries using cmake (e.g., using `android.toolchain.cmake`) rather than  ndk-build/Android.mk/etc.:
```
ld: error: undefined symbol: AHardwareBuffer_describe
...
ld: error: undefined symbol: __android_log_print
```
=> build: Fix Android CMake build

utils/check_symbol_exports.py
The symbol export test does not check weak symbols, even though they are
possibly exported.  It also does not allow functions in the standard
namespace even though it allows symbols on other namespaces.
I've modified the check to look at the name of weakly defined function,
and I've allowed functions in the standard namespace.
Fixes #4250.
=> Fix export symbol test.

test/operand_capabilities_test.cpp
Private storage class is now also enabled by VectorComputeINTEL
This should fix the CI bots
=> val test: Update capability dependency

source/fuzz/fuzzer_pass_merge_function_returns.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_merge_function_returns.cpp, source/fuzz/transformation_merge_function_returns.h, test/fuzz/transformation_merge_function_returns_test.cpp
Fixes #4278.
Some minor code cleanup is incorporated.
=> spirv-fuzz: Respect control flow rules when merging returns

source/val/construct.cpp, test/val/val_cfg_test.cpp
Fixes https://crbug.com/tint/793
* When a loop has an empty loop construct, the loop construct and
continue construct share the same header so don't disallow the loop
header for the continue construct
=> Fix continue construct for single block loops

source/reduce/change_operand_reduction_opportunity.cpp, source/reduce/remove_block_reduction_opportunity.cpp, source/reduce/remove_block_reduction_opportunity.h, source/reduce/remove_block_reduction_opportunity_finder.cpp, source/reduce/remove_function_reduction_opportunity.cpp, source/reduce/remove_struct_member_reduction_opportunity.cpp, source/reduce/simple_conditional_branch_to_branch_reduction_opportunity.cpp
Some reduction opportunities don't invalidate all analyses. This PR fixes the situation (although we might invalidate more analyses than required).
=> spirv-reduce: Invalidate analyses in some reduction opportunities

test/fuzz/fuzz_test_util.cpp
The Transformation class tests did not cover the (trivial) ToMessage
methods of each transformation, nor the constructors that take a
protobuf message. This lac of coverage makes it hard to see which more
interesting pieces of code are not covered when looking at coverage
percentages. This change adapts the helper function for applying a
transformation and checking fresh ids so that it turns a
transformation into a protobuf message and back, thus covering
ToMessage and the protobuf constructor for every transformation. The
runtime overhead of doing this is very small.
=> spirv-fuzz: Cover protobuf message creation in tests

test/fuzz/transformation_add_constant_scalar_test.cpp
This PR will solve #4287 by enhancing the test to get 100% of lines covered.
Results `100%` instead of `98%`.
=> Enhance test to improve lines covered

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/transformation_composite_insert.cpp
Sometimes, you need to change these functions during debugging (e.g., figure out why the transformation is inapplicable). When that happens, you need to recompile the whole fuzzer just because these functions are in the header file. This PR fixes the situation.
=> spirv-fuzz: Move ApplyTransformation to .cpp file

source/fuzz/transformation_permute_phi_operands.cpp, test/fuzz/transformation_permute_phi_operands_test.cpp
The def-use manager was being incorrectly updated in
TransformationPermutePhiOperands, and this was causing future
transformations to go wrong during fuzzing. This change updates the
def-use manager in a correct manner, and adds a test exposing the
previous bug.
Fixes #4300.
=> spirv-fuzz: Fix def-use update in PermutePhiOperands

source/fuzz/transformation_outline_function.cpp, test/fuzz/transformation_outline_function_test.cpp
This change prevents TransformationOutlineFunction from outlining a
region of blocks if some block in the region has an unreachable
predecessor. This avoids a bug whereby the region would be outlined,
and the unreachable predecessors would be left behind, referring to
blocks that are no longer in the function.
Fixes #4298.
=> spirv-fuzz: Fix OutlineFunction in presence of unreachable blocks

source/opt/folding_rules.cpp
This call returns nullptr to indicate errors.
Fixes https://crbug.com/1213365
=> Check that valid bitcasted constant was returned

include/spirv-tools/instrument.hpp
To allow for extending GPU-AV error codes outside of spirv-tools.
=> Add kInstErrorMax to instrument.hpp

source/val/validate_image.cpp, test/val/val_image_test.cpp
PR #4118 (d71ac38b8e) let spirv-val report a validation error when we
use offset for an OpImage* instruction instead of ConstantOffset. Since
some compilers like DXC rely on spirv-opt for function inlining or loop
unrolling, the spirv-val change broke some working shaders when the
shader developers disable the optimization (spirv-opt).
For example, DXC recently got this issue from a few users e.g.,
https://github.com/microsoft/DirectXShaderCompiler/issues/3807
Since this error is reported only when the spirv-opt is disabled, it
looks like the exact case that we have to skip spirv-val when
`--before-legalize-hlsl` is given. Moreover, avoiding the error using
`--before-legalize-hlsl` on DXC is exactly what FXC and DXC's DXIL
do (they do not report the error if the offset becomes a constant …
=> No error report for variable image offset when before-legal-hlsl is on

include/spirv-tools/libspirv.h, source/binary.cpp, source/disassemble.cpp, source/operand.cpp
See https://github.com/KhronosGroup/SPIRV-Headers/pull/177
Assembly, disassembly should work, but are untested.
=> Support Intel extensions for fixed point and hls-float

source/opt/aggressive_dead_code_elim_pass.cpp
Fixes #4296
Related similar PRs: #4047 #4049
I don't know if this omission was intentional or not, and so I filed #4296, and seems like I should file a PR instead, so here we are.
=> Add SPV_KHR_vulkan_memory_model to aggressive_dead_code_elim

source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_atomics_test.cpp, test/val/val_storage_test.cpp
Closes https://github.com/KhronosGroup/SPIRV-Tools/issues/3069
Adds
> VUID-StandaloneSpirv-None-04644
If the Storage Class is Output, then it must not be used in the RayGenerationKHR, IntersectionKHR, AnyHitKHR, ClosestHitKHR, MissKHR, or CallableKHR execution models
and 
> VUID-StandaloneSpirv-None-04645
If the Storage Class is Workgroup, then it must only be used in the task, mesh, or compute execution models
=> spirv-val: Vulkan Storage Class for Execution Model

source/val/validation_state.cpp, test/val/val_storage_test.cpp
Based on https://github.com/KhronosGroup/SPIRV-Tools/pull/4212 but the Vulkan spec now has `GLCompute` but realize the message was never updated
=> spirv-val: Add GLCompute to VUID 04644 message

source/reduce/CMakeLists.txt, source/reduce/structured_loop_to_selection_reduction_opportunity.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.h, source/reduce/structured_loop_to_selection_reduction_opportunity_finder.cpp
Cleans up a CMakeLists.txt file and the header guard for a reduction
opportunity, and gets rid of an unnecessary parent function field that
can be derived from an existing block field.
=> spirv-reduce: Clean up a few things

source/fuzz/available_instructions.cpp, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass_propagate_instructions_down.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_propagate_instruction_down.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/opt/block_merge_util.cpp, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/loop_descriptor.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.cpp
There was a lot of code in the codebase that would get the dominator
analysis for a function and then use it to check whether a block is
reachable. In the fuzzer, a utility method had been introduced to make
this more concise, but it was not being used consistently.
This change moves the utility method to IRContext, so that it can be
used throughout the codebase, and refactors all existing checks for
block reachability to use the utility method.
=> Add IsReachable function to IRContext

source/fuzz/fuzzer_pass_push_ids_through_variables.cpp
In the extreme case where there are no basic types,
FuzzerPassPushIdsThroughVariables could trigger a bounds error. This
change fixes this problem.
=> spirv-fuzz: Avoid out of bounds access

Android.mk, BUILD.bazel, BUILD.gn, build_defs.bzl, include/spirv-tools/libspirv.h, source/CMakeLists.txt, source/ext_inst.cpp, source/extinst.nonsemantic.vulkan.debuginfo.100.grammar.json
This is legacy code before this extension was ratified. A follow-up PR will include from SPIRV-Headers instead.
=> Add non-semantic vulkan extended instruction set

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
This change will fix https://github.com/microsoft/DirectXShaderCompiler/issues/3871
=> spirv-opt: support SPV_EXT_shader_image_int64

BUILD.gn
Should fix the failing GN header check where the reduce header
was not visible to the fuzzer target.
Also reformats the GN file using 'gn format'.
@pkasting fyi, will unblock http://crbug.com/1228274
=> Add missing fuzzer header dependency.

source/fuzz/fuzzer_util.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Fixes #4346. 
This PR is responsible for avoiding the replacement of constant operands with another one not constant. Particularly with atomic operations.
Rule: "All used for Scope and Memory Semantics in shader capability must be of an `OpConstant`."
In this shader:
https://github.com/KhronosGroup/SPIRV-Tools/blob/8cc8b6562be9de063a22ddf7f75d11c641779e36/test/fuzz/transformation_replace_id_with_synonym_test.cpp#L1820-L1857
When we trying to do something like this:
https://github.com/KhronosGroup/SPIRV-Tools/blob/8cc8b6562be9de063a22ddf7f75d11c641779e36/test/fuzz/transformation_replace_id_with_synonym_test.cpp#L1878 
Or, 
https://github.com/KhronosGroup/SPIRV-Tools/blob/8cc8b6562be9de063a22ddf7f75d11c641779e36/test/fuzz/transformation_replace_id_with_synonym_test.cpp#L1883
That's …
=> spirv-fuzz: Don't allow to use of a non-constant operands

CMakeLists.txt
According https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html,
> -fsanitize=vptr: Use of an object whose vptr indicates that it is of the wrong dynamic type, or that its lifetime has not begun or has ended. Incompatible with -fno-rtti.
The fix is similar to https://github.com/KhronosGroup/glslang/pull/2084 to glslang.
=> Fix build errors when UBSan's vptr check is enabled

source/fuzz/transformation_replace_id_with_synonym.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Fixes #4345. 
This PR is responsible for supporting atomic operations opcode and checks it's in operands signedness neutrality.
Original shader 
https://github.com/KhronosGroup/SPIRV-Tools/blob/8cc8b6562be9de063a22ddf7f75d11c641779e36/test/fuzz/transformation_replace_id_with_synonym_test.cpp#L1911-L1948
After applying transformation
https://github.com/KhronosGroup/SPIRV-Tools/blob/8cc8b6562be9de063a22ddf7f75d11c641779e36/test/fuzz/transformation_replace_id_with_synonym_test.cpp#L1992-L2029
That's the Important changes from original shader ` %21 = OpAtomicLoad %6 %14 %15 %20`, and this transformed  shader ` %21 = OpAtomicLoad %6 %14 %100 %101`.
=> spirv-fuzz: Support atomic operations opcode

DEPS, test/binary_to_text_test.cpp, test/val/val_modes_test.cpp
The grammar was recently fixed to have the right number of operands. See https://github.com/KhronosGroup/SPIRV-Headers/pull/229
=> Fix local size hint id tests

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_constant_null.cpp, source/fuzz/transformation_add_global_undef.cpp, source/fuzz/transformation_add_global_undef.h, source/reduce/reducer.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp, test/fuzz/fuzzerutil_test.cpp, test/fuzz/transformation_access_chain_test.cpp, test/fuzz/transformation_add_copy_memory_test.cpp, test/fuzz/transformation_add_synonym_test.cpp, test/fuzz/transformation_load_test.cpp, test/fuzz/transformation_mutate_pointer_test.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp, test/fuzz/transformation_store_test.cpp
Adaps the transformations that add OpConstantUndef and OpConstantNull
to a module so that pointer undefs are not allowed, and null pointers
are only allowed if suitable capabilities are present.
Fixes #4357.
=> spirv-fuzz: Tighten checks on null and undef pointers
