- source/fuzz/fuzzer_pass_wrap_vector_synonym.cpp
- source/fuzz/fuzzer_util.cpp
- source/fuzz/fuzzer_util.h
- source/fuzz/transformation_wrap_vector_synonym.cpp
The fuzzer pass was passing the type of a scalar where a vector type
was required, and was not checking whether synonyms could be made for
the operands to the scalar instruction.
> spirv-fuzz: Fix vector wrapping fuzzer pass

- source/fuzz/fuzzer_util.cpp
- source/fuzz/transformation_duplicate_region_with_selection.cpp
Adds an additional validity check to ensure that every instruction's
context pointer matches the enclosing IR context. Avoids a redundant
copy constructor call in TransformationDuplicateRegionWithSelection
that was leading to a bad IR context for some instructions.
Related: #4387, #4388.
Fixes #4393.
> spirv-fuzz: Fix problem with instruction context

- source/opt/instruction.cpp
> spirv-opt: Initialize context in `opt::Instruction`'s move constructor

- BUILD.gn
Tint reaches out into SPIRV-Tools BUILD.gn file for some targets:
- Adds spvtools_include_gen_dirs so that Tint can add $target_gen_dir
and find autogenerated files.
- Adds spvtools_language_headers that Tint can reference so it
automatically picks up new language headers that are added.
> BUILD.gn: introduce finer grained internal targets for Tint

- BUILD.gn
Some generated headers are exposed by headers in the spvtools_opt
target, but its GN dependency on them is private. This can result in
build flake, since the headers don't need to be generated before
compiling any spvtools_opt dependents.
This fixes the build flake by correctly expressing these as public
dependencies.
> Fix public deps on generated headers

- source/fuzz/fuzzer_pass_add_vector_shuffle_instructions.cpp
- source/fuzz/fuzzer_pass_construct_composites.cpp
- source/fuzz/fuzzer_pass_expand_vector_reductions.cpp
- source/fuzz/fuzzer_pass_push_ids_through_variables.cpp
- source/fuzz/fuzzer_pass_wrap_vector_synonym.cpp
- source/fuzz/fuzzer_util.cpp
- source/fuzz/fuzzer_util.h
- source/fuzz/transformation_add_synonym.cpp
- source/fuzz/transformation_composite_construct.cpp
- source/fuzz/transformation_composite_extract.cpp
- source/fuzz/transformation_composite_insert.cpp
- source/fuzz/transformation_expand_vector_reduction.cpp
- source/fuzz/transformation_push_id_through_variable.cpp
- source/fuzz/transformation_vector_shuffle.cpp
- source/fuzz/transformation_wrap_vector_synonym.cpp
The instruction parameter of CanMakeSynonymOf is an input parameter
that should never be null, so a const reference is a more appropriate
type than a const pointer.
> spirv-fuzz: Use reference in CanMakeSynonymOf

- Android.mk
- BUILD.gn
- source/opt/CMakeLists.txt
- source/opt/control_dependence.cpp
- source/opt/control_dependence.h
- test/opt/CMakeLists.txt
- test/opt/control_dependence.cpp
Control dependence analysis constructs a control dependence graph, representing the conditions for a block's execution relative to the results of other blocks with conditional branches, etc.
This is an analysis pass that will be useful for the linter and potentially also useful in opt. Currently it is unused except for the added unit tests.
> Add control dependence analysis to opt

- test/opt/control_dependence.cpp
In particular, adds tests for DoesBlockExist, ForEachBlockLabel, and WhileEachBlockLabel, which were pointed out in the previous PR (#4380).
> spirv-opt: Add more tests to control dependence 

- source/fuzz/fuzzer_pass_add_global_variables.cpp
The fuzzer pass that adds global variables requires some basic
types. This change makes the fuzzer pass exit gracefully when none are
available.
Fixes #4408.
> spirv-fuzz: Quit fuzzer pass when no types are available

- source/opt/control_dependence.h
- test/opt/control_dependence.cpp
Suggested by Jakub as 'DoesBlockExist' was confusing.
> spirv-opt: Rename ControlDependenceAnalysis::DoesBlockExist to HasBlock

- test/fuzz/fuzzer_replayer_test.cpp
Testing on ClusterFuzz has revealed that the fuzzer sometimes goes
wrong when a shader is very simple - e.g., there have been bugs where
a fuzzer pass has assumed that at least one basic type exists in the
module. This change adds an almost empty SPIR-V example to the shaders
used for testing, to help catch such cases locally.
> spirv-fuzz: Add minimal SPIR-V example to test shaders

- source/val/validate_extensions.cpp
- test/val/val_ext_inst_test.cpp
Fixes #4411
* Some GLSL.std.450 validation didn't handle an operand without a type
> Fix validator crash

- source/fuzz/fuzzer.cpp
- source/fuzz/fuzzer.h
Introducing a new mandatory parameter makes it very difficult to roll
Chromium to a new version of SPIRV-Tools, as this project is used by
several third-party projects, and an atomic update of all projects
is very hard to coordinate.
> Fuzzer: Default the new constructor parameter

- source/fuzz/protobufs/spirvfuzz_protobufs.h
The protobuf generated code triggers this clang-12 warning, which some
projects may treat as an error.
> fuzzers: Disable suggest-destructor-override warning

- README.md
* Releases are unrelated to SPIRV-Headers releases
* SPIRV-Headers should always be taken from the DEPS file
> Add a section releases to the README

- BUILD.bazel
- build_defs.bzl
- include/spirv-tools/linter.hpp
- source/CMakeLists.txt
- source/lint/CMakeLists.txt
- source/lint/linter.cpp
- test/CMakeLists.txt
- test/lint/CMakeLists.txt
- test/lint/placeholder_test.cpp
- tools/CMakeLists.txt
- tools/lint/lint.cpp
This PR adds a new executable spirv-lint with a simple "Hello, world!" program, along with its associated library and a dummy unit test.
For now, only adds to CMake and Bazel; other build systems will be added in a future PR.
Issue: #3196
> Add new target for spirv-lint

- Android.mk
- BUILD.gn
- source/opt/CMakeLists.txt
- source/opt/dataflow.cpp
- source/opt/dataflow.h
- test/opt/CMakeLists.txt
- test/opt/dataflow.cpp
This PR adds a generic dataflow analysis framework to SPIRV-opt, with the intent of being used in SPIRV-lint. This may also be useful for SPIRV-opt, as existing ad-hoc analyses can be rewritten to use a common framework, but this is not the target of this PR.
> spirv-opt: Add dataflow analysis framework

- source/val/validate_interfaces.cpp
Fixes #4464
* Add a limit to only check up to 4096 locations to prevent excessive
memory consumption
* still fully validates all reasonable inputs
> Limit location validation

- tools/io.h
When a tool (tested with spirv-dis and spirv-as) runs on a file that
does not exist, it notifies the user and tries to close the stream that
was never successfully opened.
> Fix SIGSEGV when reading from a non-existent file

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
Negating an unsigned constant results in its two's complement which is
still interpreted as unsigned. For example -2u becomes 4294967294u.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4456
> Don't fold unsigned divides of an constant and a negation

- source/opt/const_folding_rules.cpp
Only the first two operands were tested for constness, missing the third
one. Since the FoldFPBinaryOp() at the end of FoldClamp1() returns null
when not both of its operands are constant, this doesn't change any
behavior, but it avoids some needless work.
Also the comment for FoldClamp2() was fixed.
> Fix early-out for Clamp constant folding

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/opt/eliminate_dead_member_test.cpp
- test/val/val_composites_test.cpp
- test/val/val_memory_test.cpp
Fixes #4472
* Disallow loading a runtime-sized array or a composite containing one
* Refactor type traversal into a separate function used by both runtime
array checks and sized int/float checks
* Update invalid tests
> Disallow loading a runtime-sized array

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/convert_to_sampled_image_pass.cpp
- source/opt/convert_to_sampled_image_pass.h
- source/opt/optimizer.cpp
- source/opt/passes.h
- test/opt/CMakeLists.txt
- test/opt/convert_to_sampled_image_test.cpp
- tools/opt/opt.cpp
convert-to-sampled-image pass converts images and/or samplers with
given pairs of descriptor set and binding to sampled image.
If a pair of an image and a sampler have the same pair of descriptor
set and binding that is one of the given pairs, they will be
converted to a sampled image. In addition, if only an image has the
descriptor set and binding that is one of the given pairs, it will
be converted to a sampled image as well.
For example, when we have
```
%a = OpLoad %type_2d_image %texture
%b = OpLoad %type_sampler %sampler
%combined = OpSampledImage %type_sampled_image %a %b
%value = OpImageSampleExplicitLod %v4float %combined ...
```
1. If `%texture` and `%sampler` have the same descriptor set and binding
```
%combine_texture_and_sampler = OpVaraible %ptr_type_sampled_image_Uniform …
```
> Add spirv-opt convert-to-sampled-image pass

- BUILD.gn
These are popping up in a Chromium test integration.
Fixes #4475
@alan-baker PTAL
> GN: Suppress unreachable code warnings.

- source/val/validate_interfaces.cpp
- test/val/val_interfaces_test.cpp
Fixes #4403
* Pre-1.4 modules could have duplicate interface entries
* Don't double count variables for locations
> Don't double count variables for location validation

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Fixes #4454
* Use MatrixStride from member decorations instead of from matrix
decorations
Tested against Vulkan CTS.
> Fix matrix stride validation

- BUILD.bazel
- tools/lint/lint.cpp
Mostly copied from spirv-opt. Simply reads in a single input file.
Issue: #3196
> spirv-lint: add basic CLI argument handling

- source/val/validate_builtins.cpp
- test/val/val_builtins_test.cpp
>  VUID-WorkgroupSize-WorkgroupSize-04425
>
> The WorkgroupSize decoration must be used only within the GLCompute, MeshNV, or TaskNV Execution Model
This was missing the mesh stages and causing issues in Validation Layers for me
> spirv-val: Fix WorkgroupSize VUID 04425

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
ADCE does not handle exported functions.  This was an explicit decision
because we did not believe that the linkage attribute could be used in
shaders, but it can now.  This change has been made.
While fixing this error, I noticed that the OpName for labels is
sometimes removed because the label instructions are not marked
explicitly marked as live.  This has able been fixed.
> Handle exported functions in ADCE

- CMakeLists.txt
- test/fuzzers/CMakeLists.txt
With OSS-Fuzz, the build system should not directly set options such as
-fsanitize=fuzzer. Instead, these are set by OSS-Fuzz, and
linker options are provided via the LIB_FUZZER_OPTIONS environment
variable. This change allows the fuzzers to be build stand-alone,
outside of OSS-Fuzz, in the way that was already supported, as well as
inside OSS-Fuzz, when the LIB_FUZZER_OPTIONS environment variable is
set.
> Adjust build for fuzzer targets to support OSS-Fuzz

- source/val/validation_state.h
The validation state contained feature bits for scalar block layout and
workgroup memory scalar block layout which were never used (the
command-line option is used in every case).
> Remove environment features that are never used

- source/binary.cpp
Fixes an issue where an arbitrary word was cast to SpvOp, leading to
undefined behaviour if the value of the word fell outside the range of
SpvOp values.
Fixes #4504.
> spirv-val: Fix ubsan error

- kokoro/linux-clang-ubsan/build.sh
- kokoro/linux-clang-ubsan/continuous.cfg
- kokoro/linux-clang-ubsan/presubmit.cfg
- kokoro/scripts/linux/build-docker.sh
Adds a kokoro configuration for UBSan, to allow this sanitizer to be
used during continuous integration.
> Add UBSan kokoro configuration

- source/val/function.cpp
- test/val/val_cfg_test.cpp
Fixes #4515
* Sets block depth to 0 if it encountered multiple times and leaves
finding the real error for other code
> Fix infinite loop in GetBlockDepth

- source/opt/vector_dce.cpp
- source/opt/vector_dce.h
- test/opt/vector_dce_test.cpp
It is possible that other optimization will propagate
a value into an OpCompositeExtract or OpVectorShuffle
instruction that is larger than the vector size.
Vector DCE has to be able to handle it.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4513.
> Handle out-of-bounds accesses in VDCE

- DEPS
https://github.com/google/googletest/compare/b7d472f1225c...955c7f837efa
$ git log b7d472f12..955c7f837 --date=short --no-merges --format='%ad %ae %s'
2021-08-20 absl-team Googletest export
2021-08-20 absl-team Googletest export
2021-08-19 invalid_ms_user Simplify example code with c++11
2021-08-12 absl-team Googletest export
2021-08-10 dmauro Googletest export
2021-08-09 dmauro Googletest export
2021-08-06 absl-team Internal change
2021-08-06 victordk13 Format test properties in xml printer
2021-08-05 iamberkeyavas typo fix gmock_cook_book
2021-08-03 absl-team Googletest export
2021-08-03 absl-team Googletest export
2021-08-02 absl-team Googletest export
2021-07-29 absl-team Googletest export
2021-07-29 otnaiud Typo, double "the"
2021-07-28 absl-team Internal change
2021-07-24 slowy.arfy …
> Roll external/googletest/ b7d472f12..955c7f837 (111 commits)

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
In SPIR-V, integers use 2s complement representation, so that signed
integer overflow and underflow is well defined. However, the constant
folder was causing overflow / underflow at the C++ level. This change
avoids such overflows by performing constant folding for IAdd, ISub and
IMul in the context of unsigned values, which works because signedness
is irrelevant according to the SPIR-V semantics for these instructions.
Fixes #4510.
> spirv-opt: Avoid integer overflow during constant folding

- include/spirv-tools/optimizer.hpp
- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/aggressive_dead_code_elim_pass.h
- source/opt/optimizer.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
This mode is needed by GPU-assisted validation instrumentation which
needs to do ADCE but cannot change the shader entry point interface.
> Add preserve_interface mode to aggressive_dead_code_elim

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
When folding a OpCompositeExtract that is fed by an
OpCompositeConstruct, we handle and out of bounds
index, but only in the case where the result of the
OpCompostiteConstruct is a struct.  This change
refactors that folding rule and then improves it to
handle an out-of-bounds access when the result of the
OpCompositeConstruct is a vector.
Fixes #4514
> Fix extract with out-of-bounds index

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/block_merge_util.cpp
- source/opt/compact_ids_pass.cpp
- source/opt/debug_info_manager.cpp
- source/opt/def_use_manager.cpp
- source/opt/feature_manager.cpp
- source/opt/feature_manager.h
- source/opt/if_conversion.cpp
- source/opt/inline_pass.cpp
- source/opt/instruction.cpp
- source/opt/instruction.h
- source/opt/ir_context.cpp
- source/opt/ir_context.h
- source/opt/ir_loader.cpp
- source/opt/loop_unroller.cpp
- source/opt/module.cpp
- source/opt/pass.cpp
- source/opt/reflect.h
- source/opt/replace_invalid_opc.cpp
- source/opt/scalar_replacement_pass.cpp
- source/opt/scalar_replacement_pass.h
- source/val/validate_layout.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
- test/opt/loop_optimizations/unroll_simple.cpp
Debug[No]Line instructions are tracked and optimized using the same mechanism
that tracks and optimizes Op[No]Line.
Also:
- Fix missing DebugScope at top of block.
- Allow scalar replacement of access chain in DebugDeclare
> Handle NonSemantic.Shader Debug[No]Line

- source/fuzz/protobufs/spirvfuzz_protobufs.h
Suppresses a warning emitted by some versions of clang when compiling
protobufs.
> Suppress protobuf warning

- source/val/validate_derivatives.cpp
- test/val/val_derivatives_test.cpp
Fixes #4550
* Do not assume that an entry point has any associated execution modes
when checking derivative requirements
> Do not assume there are execution modes

- source/opt/eliminate_dead_members_pass.cpp
- source/opt/instruction.cpp
- source/opt/instruction.h
- test/opt/eliminate_dead_member_test.cpp
This PR fixes the **eliminate_dead_members_pass** for structured buffers which UnrealEngine heavily relies on to significantly reduce the `$Globals` constant buffer.
However, we cannot remove any fields from a structured buffer (i.e. SSBO in GLSL) since `layout(offset)` qualifiers cannot be applied to structure fields, so the `ArrayStride` decoration is not sufficient in SPIR-V to translate a `StructuredBuffer` to an SSBO in GLSL.
Here is an HLSL example:
```hlsl
struct S {
float4 A;
float4 B;
};
ConstantBuffer<S> Buf1;
StructuredBuffer<S> Buf2;
float4 PSMain() : SV_TARGET {
return Buf1.A + Buf2[0].B;
}
```
We can use the following commands to translate that into SPIR-V with optimization for size (to trigger the eliminate_dead_members_pass):
```
$ dxc -E PSMain -T ps_6_0 -spirv -Fo …
```
> spirv-opt: Don't eliminate dead members from StructuredBuffer

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/aggressive_dead_code_elim_pass.h
- source/opt/mem_pass.cpp
Split the code that processes the work list into multiple functions.
Move the code to remove the dead instructions in a function to its own function.
> More ADCE refactoring

- source/opt/constants.cpp
- test/opt/inline_test.cpp
Inlining needs to create a constant for DebugInlinedAt for NonSemantic.Shader.DebugInfo
> Fix ConstantManager to not run AnalyzeInstDefUse if DefUse not valid

- include/spirv-tools/libspirv.h
- source/spirv_target_env.cpp
To allow querying the range of target environments (to ensure that a
target environment value is within the valid range of the associated
enum), this change adds a maximum value to the spv_target_env
enumeration.
Fixes #4558.
> Include a maximum value for spv_target_env

- source/opt/block_merge_util.cpp
- test/opt/block_merge_test.cpp
Fixes DefUse assertions and invalid DebugScope instruction
between OpLoopMerge and OpBranch for included test shader.
> Fix merge-block assertions with debugInfo

- source/opt/reflect.h
- test/opt/ir_loader_test.cpp
According to spec this opcode is a constant instruction - that's it
can appear outside of function bodies.
> Enable OpConstFunctionPointerINTEL outside function

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Fixes #4561
* When checking for offsets, don't accept 0xffffffff
> Consider 0xffffffff offset as missing

- source/opt/debug_info_manager.cpp
- test/opt/debug_info_manager_test.cpp
- test/opt/inline_test.cpp
Using the ConstantManager attempts to regenerate the DefUseManager
which is not valid during inlining.
> Generate constants directly in CreateDebugInlinedAt

- source/opt/set_spec_constant_default_value_pass.cpp
- test/opt/set_spec_const_default_value_test.cpp
When setting default value for spec constants, for numeric bit types smaller
than 32 bits, follow the SPIR-V rules for narrow literals:
- signed integers are sign-extended
- otherwise, upper bits are zero.
Followup to #4588
> opt: set upper bits of spec constant according to spec

- CMakeLists.txt
Found a possible link error if we compile spirv-tools by using VS2019 and link with VS2017 for another project, unresolved symbols as _CxxFrameHandler4 and __GSHandlerCheck_EH4 will be thrown. As Visual Studio updated its c++ exceptions libs.
https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/
Could we make this option controllable?
> Make cxx exceptions controllable 

- source/CMakeLists.txt
> In generated cmake config file for SPIRV-Tools only access cmake target, if present

- source/val/validate_cfg.cpp
In #3404 a logical && was replaced with a bitwise & to ensure that
both side-effecting arguments were evaluated. However, this leads to
warnings from some compilers (leading to the OSS-Fuzz build breaking,
in particular).
This change reworks the relevant code so that both arguments to the
logical && are evaluated into temporaries.
> Avoid bitwise and in boolean expression

- source/opt/ir_builder.h
- source/opt/merge_return_pass.cpp
- source/opt/merge_return_pass.h
- test/opt/pass_merge_return_test.cpp
If the ids overflow when creating an integer constant in the ir_builder, there will be a nullptr dereference.  This is happening from inside merge return.
We need to propagate the error up, and make sure it is handled appropriately.
Fixes #4538
> Handle overflowing id in merge return

- .github/workflows/wasm.yml
The JS-Tools/npm-publish flow requires a `token` attribute, even
in dry-run mode.
There is no token, so remove the step for now.
> Remove publish-to-npm step for Wasm build

- source/opt/desc_sroa.cpp
- source/opt/desc_sroa.h
- test/opt/desc_sroa_test.cpp
If a struct/array of resources has `OpMemberDecorate` instructions,
the desc-sroa pass must correctly create `OpDecorate` instructions
when it creates variables for its elements. For example, desc-sroa
has to convert
```
OpMemberDecorate %struct 0 RelaxedPrecision
...
%struct = %resource0 %resource1
```
to
```
OpDecorate %resource0_var RelaxedPrecision
...
%resource0_var = OpVariable ..
```
This will fix https://github.com/microsoft/DirectXShaderCompiler/issues/4047
> spirv-opt: create OpDecorate for OpMemberDecorate in desc-sroa

- source/val/validate_annotation.cpp
- source/val/validate_builtins.cpp
- source/val/validation_state.cpp
- test/opt/inline_test.cpp
- test/opt/upgrade_memory_model_test.cpp
- test/val/CMakeLists.txt
- test/val/val_annotation_test.cpp
- test/val/val_builtins_test.cpp
- test/val/val_capability_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_id_test.cpp
- test/val/val_interfaces_test.cpp
- test/val/val_layout_test.cpp
- test/val/val_memory_test.cpp
Fixes #4469
* Checks that decorations only usable with structure members are not
used by OpDecorate or OpDecorateId
* Checks that decorations not allowed on structure members are not used
with OpMemberDecorate
* Checks decoration targets for most core decorations
* Performs some Vulkan specific validation on decorations
VK-GL-CTS Issue: 3063
This PR breaks some Vulkan CTS tests that are invalid.
> Improve decoration validation

- README.md
- utils/roll_deps.sh
-  Mention that `depot_tools` are required and link to that repo.
-  Make `roll_deps.sh` exit on error. The script passes `shellcheck`
with this change.
-  Reword instruction in the README.
> Clarify how to update DEPS

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
* https://github.com/KhronosGroup/Vulkan-Docs/issues/666 clearly
specified that interfaces do not require an input if there is an
associated output
* ADCE can now remove unused input variables (though they are kept if
the preserve interfaces option is used)
FYI @sindney and @zeux
> Allow ADCE to remove dead inputs

- source/val/validate_annotation.cpp
Fixes compile failure due to pedantic warning:
`error: default argument specified for lambda parameter [-Werror=pedantic]`
> Remove default arguments from lambda

- source/opt/desc_sroa.cpp
- source/opt/desc_sroa.h
- test/opt/desc_sroa_test.cpp
Along with OpDecorate, also clone the OpDecorateString instructions for
variables created in the descriptor scalar replacement pass.
Fixes microsoft/DirectXShaderCompiler#3705
> Copy OpDecorateStrings in DescriptorScalarReplacementPass

- source/util/hex_float.h
Ensures that when an attempt to read a floating-point value from an
input stream fails, the recieving variable for the read does not end up
uninitialised.
Fixes OSS-Fuzz:40432
Fixes #4644
> Avoid uninitialised read when parsing hex float

- source/link/linker.cpp
- source/opt/module.cpp
- source/opt/module.h
For consistency with SPIR-V disassembly which outputs Schema for this
field.
> Use schema instead of reserved in header description

- source/opt/def_use_manager.cpp
Speedup: 5% less time on a real-world compilation batch
(nearly 10k parallel compilations, on 8 hardware threads)
(Durations: Before: 156.5s, After: 147.4s)
> Avoid an extra map lookup

- kokoro/scripts/linux/build.sh
With a change in the VM, the kokoro asan run is failing because it does
not have the correct permissions.  Adding the ptrace capability will
hopefully fix that.
> Fix kokoro asan run

- include/spirv-tools/optimizer.hpp
- source/opt/optimizer.cpp
The change in
commit 4ac8e5e541ea992dc6f44a4d4eb065a8fe0888ec
Author: Greg Fischer <greg@lunarg.com>
Date:   Wed Sep 15 12:38:34 2021 -0600
Add preserve_interface mode to aggressive_dead_code_elim (#4520)
Broke the C++ ABI for spirv-tools shared libraries on Linux, for not a great reason.
Restore the previous ABI.
> optimizer: restore previous ABI.

- test/fuzzers/spvtools_as_fuzzer.cpp
Makes the logic in the as fuzzer target closer to the logic of the
spirv-as tool.
Fixes #4643
> Simplify the as fuzzer target

- source/disassemble.cpp
- source/disassemble.h
The upcoming spirv-diff tool also outputs disassembly, although in a
per-instruction basis.  This change refactors the disassembler code to
support such a use case.
> Refactor the disassembler code for reuse

- source/val/validate_decorations.cpp
- test/val/val_builtins_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_interfaces_test.cpp
For a shader input/output interface variable of structure type:
If the structure has BuiltIn members, then the structure type
must be Block decorated.
Otherwise, the variable, or the struct members must have locations,
but nothing can have both a location be a BuiltIn.
Implements validation needed to reject the example in
https://github.com/KhronosGroup/SPIRV-Registry/issues/134
> val: interface struct with builtins must be Block

- source/text.cpp
Ensures that instruction's opcode is set to something default when
parsing the module with --preserve-numeric-ids enabled. This avoids
uninitialized accesses and knock-on buffer overflows.
Fixes #4672.
> Avoid uninitialized access to instruction opcode

- test/fuzzers/spvtools_opt_fuzzer_common.cpp
- test/fuzzers/spvtools_opt_fuzzer_common.h
The test harness for the opt fuzzer was failing to consider that the
input might use a very large id bound, despite no id approaching this
bound actually being used in the module. This change modifies the test
harness to use the module's id bound, rather than looking through the
module for large ids.
Fixes: oss-fuzz:42386
> Fix opt fuzzer test harness

- source/opt/types.cpp
The comment in `Array::GetExtraHashWords` is misleading because getting
the hash words is split up between the generic `Type::GetHashWords` and
the type specific `Type::GetExtraHashWords`.  While `IsSameImpl` is
self-contained.  Removing the comment since it is misleading and no
comment is really needed.
Fixes #3248
> Remove misleading comment.

- source/opt/pass_manager.cpp
1. Output disassembly messages and a warning in case disassembly fails.
2. Use the specified target environment during disassembly rather than a hardcoded value.
This takes the output of `spirv-opt --print-all -Os -o out.spv in.spv` from
```
; IR before pass wrap-opkill
; IR before pass eliminate-dead-branches
; IR before pass merge-return
; IR before pass inline-entry-points-exhaustive
```
to
```
error: line 143: Invalid opcode: 400
warning: line 0: Disassembly failed before pass wrap-opkill
error: line 143: Invalid opcode: 400
warning: line 0: Disassembly failed before pass eliminate-dead-branches
error: line 143: Invalid opcode: 400
warning: line 0: Disassembly failed before pass merge-return
error: line 143: Invalid opcode: 400
warning: line 0: Disassembly failed before pass …
```
> Improvements to disassembly within PassManager

- source/link/linker.cpp
- test/link/binary_version_test.cpp
- test/link/entry_points_test.cpp
- test/link/global_values_amount_test.cpp
- test/link/ids_limit_test.cpp
- test/link/matching_imports_to_exports_test.cpp
- test/link/memory_model_test.cpp
- test/link/partial_linkage_test.cpp
- test/link/type_match_test.cpp
- test/link/unique_ids_test.cpp
- tools/link/linker.cpp
* Require a memory model in each input module.
* Error out when merging input modules using different SPIR-V versions, whereas before the linker would allow that scenario and use the highest version for the linked module.  (#4135)
* Replace an error with a warning when going universal limits, as some implementations might accept higher limits.
* Only check for universal limits right before emitting the linked binary as, for example, passes like type de-duplication might reduce the amount of IDs present.
* The tests benefited from some code factorisation and tweaks regarding what was considered as `EXPECT_*` versus `ASSERT_*`.
* Avoid having the ID count overflow when merging binaries.
* Use existing macros instead of hardcoded values.
* In spirv-link, do not write to disk if linking …
> Linker improvements

- source/link/linker.cpp
- test/link/ids_limit_test.cpp
Also rework the code slightly to first compute the new ID bound and validate it, and only then, offset all existing IDs.
This makes those two steps clearer, and avoids potentially overflowing the IDs within a module (even if that would have been caught later on).
Fixes: c3849565 ("Linker improvements (#4679)")
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4684
> linker: Address conversion error introduced in earlier rework

- source/util/small_vector.h
C++20 automatically adds reversed versions of operator overloads for
consideration; in this particular instance this results in infinite
recursion, which has now been pointed out elsewhere as a known issue
when migrating to C++20. Here we just disable one of the overloads in
C++20 mode and let the auto-reversing take care of it for us.
> Avoid infinite recursion in comparison operators on SmallVector

- utils/roll_deps.sh
Two deps changes branch names, and roll_deps.sh must be updated.
We also don't want the script to fail just because one of the deps is
already up-to-date.  Set `+e` before rolling the deps.
> Fix roll_deps.sh

- source/opt/type_manager.cpp
- source/opt/types.h
- test/opt/type_manager_test.cpp
The handling of the RayQueryKHR type is not complete in the type
manager.  The tests were not picking this up.  I've added a test to make
sure that the `GenerateAllTypes` function actually does generate all of
the types.  Once it is added there other tests should pick up on the
other parts that were missing.
> Complete handling of RayQueryKHR type

- source/opt/scalar_replacement_pass.cpp
- source/opt/scalar_replacement_pass.h
- test/opt/scalar_replacement_test.cpp
Scalar replacement generates a null when there value for a member will
not be used.  The null is used to make sure things are
deterministic in case there is an error.
However, some type cannot be null, so we will change that to use undef.
To keep the code simpler we will always use the undef.
Fixes #3996
> Have scalar replacement use undef instead of null

- test/diff/CMakeLists.txt
This disables spirv-diff tests temporarily, since they are currently failing on Windows builds.
This is a workaround for #4696.  @ShabbyX is looking at a real fix.
> Disable spirv-diff tests.

- utils/check_copyright.py
The copyright check has hardcoded the years that can appear in the
copyright check.  This means is has to be constantly updated as new
years or range of years are needed.
This avoid this.  It taks the current year from the systems time, and
will now accept any individual year from 2014 to the current year or
range of years in those two.
There are also some corner cases around New Year's Eve, which I do not
think are a big deal.
If someone's local machine has the wrong date, the check could fail.  I
view that as their problem.
> Generalize the copyright check

- source/val/validate_extensions.cpp
- test/val/val_ext_inst_debug_test.cpp
Rev 7 of NonSemantic.Shader.DebugInfo.100 was updated to allow zero
component count for for DebugTypeArray to represent runtime array.
> [spirv-val] Allow 0 Component Count for DebugTypeArray for Shader

- source/opt/constants.cpp
This is 3/N, for full context please see PR#4075.
Profiling revealed ConstantManager::GetOperandConstants was a surprisingly large source of allocations.  Since we know the exact size of the returned std::vector, we can reserve the capacity up-front.
> Avoid unnecessary reallocations in GetOperandConstants

- source/opcode.cpp
This causes a strange artifact in a `spirv-dis --comment` because `OpModuleProcessed` wasn't in the `spvOpcodeIsDebug` and it is labeled as `"class"  : "Debug"` in the grammar file
> Add OpModuleProcessed to debug opcode

- tools/sva/yarn.lock
Manually applying https://github.com/KhronosGroup/SPIRV-Tools/pull/4710
because the bot cannot sign the cla.
> Bump pathval from 1.1.0 to 1.1.1 in /tools/sva

- source/opt/copy_prop_arrays.cpp
- source/opt/copy_prop_arrays.h
- source/opt/replace_desc_array_access_using_var_index.cpp
- test/opt/replace_desc_array_access_using_var_index_test.cpp
When copy propagating, OpDecorate instructions can be copied as is. For
array flattening, they should be ignored.
> Handle propagation of arrays with decorations

- source/opt/ir_loader.cpp
- test/opt/freeze_spec_const_test.cpp
Needed for Vulkan1.3 adding `LocalSizeId` support
Came across when trying to add proper `LocalSizeId`/`SpecConstant` support for the Vulkan-Validation Layers (cc @ncesario-lunarg)
> spirv-opt: Add OpExecutionModeId support

- BUILD.gn
- source/CMakeLists.txt
- source/opt/types.cpp
- source/opt/types.h
- source/util/hash_combine.h
- source/util/small_vector.h
- test/util/CMakeLists.txt
- test/util/hash_combine_test.cpp
- test/util/small_vector_test.cpp
Hello - this is 2/N, please see PR#4705 for context
This change is the result of seeing Type::HashValue was ~7.5% of our runtime when compiling shaders.  These changes get it down to < .5%.
First, we compute the hash incrementally instead of gathering the "words" into a std::vector, inserting them into a u32string, and then hashing that string.  This avoids two series of [re]allocations, and avoids making three total passes over the hashed data.
Next, instead of using a std::unordered_set to avoid processing duplicates, we use a std::vector -- the unordered_set requires an alloc/free when inserting/removing, and has a larger constant-factor than a linear search through a small, dense, cache coherent vector.  I've never seen the vector contain more than a few items.
Last, swap out the …
> Optimize Type::HashValue

- source/val/validate_extensions.cpp
- test/val/val_ext_inst_debug_test.cpp
Ran into this missing validation while implementing NonSemanticShaderDebugInfo in glslang.
> spirv-val: Validate DebugTypeMatrix

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_memory_test.cpp
Add a label for `VUID-StandaloneSpirv-OpVariable-04734` as well as refactored error message and the logic be consistent in wrapping `spvIsVulkanEnv()` as the top check
> spirv-val: Label Vulkan VUID 04734

- source/opt/ir_context.cpp
- source/opt/ir_context.h
- source/opt/merge_return_pass.cpp
- test/opt/ir_context_test.cpp
In BuildInvalidAnalyses, we state that it will only rebuild the invalid
analyses.  However, the code will rebuild all analyses that have been
requested, even if they were already valid.
We fix that, and add a couple tests.  The tests cannot check every
analysis because there are no visible differences for all of the
analyses.  We test two of them as representatives.  Note that the new
code is generic, so this should be good enough.
Fixes #3635
> Don't rebuilt valid analyses.

- source/val/validate_annotation.cpp
- source/val/validation_state.cpp
- test/val/val_annotation_test.cpp
Add label for `VUID-StandaloneSpirv-DescriptorSet-06491`
also getting another explicit VUID for the 
```
case SpvDecorationLocation:
case SpvDecorationComponent:
```
check and flipped logic around while muxing in this function
> spirv-val: Label VUID 06491

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/optimizer.cpp
- source/opt/passes.h
- source/opt/remove_dontinline_pass.cpp
- source/opt/remove_dontinline_pass.h
- test/opt/CMakeLists.txt
- test/opt/remove_dontinline_test.cpp
Swift shader needs a way to inline all functions, even those marked as
DontInline.  See https://github.com/KhronosGroup/SPIRV-Tools/pull/4471.
This implements the suggestion I made in the PR.  We add a pass that
will remove the DontInline function control, so that the inlining passes
will inline them.
SwiftShader will still have to modify their code to add this pass before
the other passes are run.
> Add pass to remove DontInline function control

- BUILD.bazel
- build_defs.bzl
- kokoro/windows-msvc-2015-release-bazel/build.bat
Before this commit, the bazel build setup would not work on windows.
This is due to the fact, that genrule tries to use bash, which fails.
One fix would be to use bazel-skylib's run_binary.
This however does not work (easily) since genrules is more complex.
To (temporarily) fix the windows build, I added the `cmd_bat` property to every genrule.
This seems more like a hack, because it basically repeat commands,
but for now it at least builds on windows.
I don't know if this is strictly necessary, since there is very little documentation of how to build this repo with bazel.
> Fixed Bazel Windows build

- source/opt/ccp_pass.cpp
- test/opt/ccp_test.cpp
CCP does not want to fold an instruction unless it folds to a constant.
There is an asser to check for this.  The question if a spec constant
counts as a constant.  The constant folder considers a spec constant a
constand, but CCP does not.  I've fixed the assert in CCP to match what
the folder does.  It should not require any new changes to CCP.
> Generalize assert in ccp

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
When folding a vector shuffle feeding a vector shuffle, we do not
propagate an 0xFFFFFFFF, which has a special meaning, correctly.  We
adjust the value making it lose it meaning as an undefined value.
Fixes #4581
> Better handling of 0xFFFFFFFF when folding vector shuffle

- source/opt/compact_ids_pass.cpp
- test/opt/compact_ids_test.cpp
If the body of the module does not have any ids change, compact ids will
not change the id bound.  This can cause problems because the id bound
could be much higher than the largest id in that is used.  It should be
reset any time it is not the larger id used +1.
Fixes #4604
> Reset the id bound on the module in compact ids

- source/val/validate_memory.cpp
- test/val/val_memory_test.cpp
~~(WIP until confirmed that the Vulkan Spec is not incorrect here)~~
In the spec for Uniform and Storage buffers it says
> Variables identified with the Uniform storage class are used to access transparent buffer backed resources. Such variables must be:
> typed as OpTypeStruct, or an array of this type,
but for PushConstant it just says
> typed as OpTypeStruct,
(note I need to fix in glslang as well incase CI breaks from it)
> spirv-val: Disallow array of push constants

- source/val/validate_image.cpp
- source/val/validation_state.cpp
- test/val/val_image_test.cpp
Adds `VUID-StandaloneSpirv-OpTypeImage-06214` which makes sure `SubpassData` dim images have arrays of 0
> spirv-val: Add Vulkan Image VUID 06214

- source/val/validate_image.cpp
- source/val/validation_state.cpp
- test/val/val_image_test.cpp
Add `VUID-StandaloneSpirv-OpImage-04777`
> OpImage*Dref* must not consume an image whose Dim is 3D
> spirv-val: Add Vulkan Dref not allowed 3D dim VUID

- source/val/validate_image.cpp
Have some other Vulkan changes related to images, but pulled this out as a separate PR
- `ValidateImageCommon` seemed to be a random function used only sometimes that I just broke into 2 dedicated functions
- grouped the checks in `ValidateTypeImage` to be Universal, CL, then Vulkan checks
- grouped CL and Vulkan checks together where it makes sense inside given functions
> spirv-val: Small Cleanup of validate image

- source/opt/dead_branch_elim_pass.cpp
- source/opt/private_to_local_pass.cpp
Clang added -Wunqualified-std-cast-call in
https://reviews.llvm.org/D119670, which warns on unqualified std::move
and std::forward calls. This change qualifies these calls to allow the
project to build on HEAD Clang -Werror.
> Qualify std::move.

- source/assembly_grammar.cpp
- source/operand.cpp
- source/text.cpp
- test/val/val_fixtures.h
- test/val/val_image_test.cpp
I was getting `SPV_ERROR_INVALID_TEXT` with `Invalid image operand 'ZeroExtend'` as an error message. It was not helpful to realize I was missing the version, so changed it so a case like this will return `SPV_ERROR_WRONG_VERSION` as a better indicator of why my spvasm was wrong
> spirv-val: Add better error code for invalid operand

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/eliminate_dead_input_components_pass.cpp
- source/opt/eliminate_dead_input_components_pass.h
- source/opt/inst_bindless_check_pass.cpp
- source/opt/interp_fixup_pass.cpp
- source/opt/optimizer.cpp
- source/opt/pass.h
- source/opt/passes.h
- source/opt/types.cpp
- source/opt/types.h
- test/opt/CMakeLists.txt
- test/opt/eliminate_dead_input_components_test.cpp
- tools/opt/opt.cpp
This adds the --eliminate-dead-input-components pass which currently
removes trailing unused components from input arrays.
Fixes #4532
> spirv-opt: Eliminate Dead Input Components Pass

- BUILD.gn
GN does not allow multiple build files to declare the same executables,
so for SwiftShader to be able to use its own internal copy of SPIRV-
Tools libraries it needs to exclude the executable targets.
This is achieved by checking if the current path is //third-party/
SPIRV-Tools/.
Bug: b/158002593
> BUILD.gn: Enable independent builds within the Chromium tree

- source/val/validate_atomics.cpp
- source/val/validate_decorations.cpp
- source/val/validate_function.cpp
- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_capability_test.cpp
- test/val/val_conversion_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_logicals_test.cpp
- test/val/val_memory_test.cpp
- Adds label for `VUID-StandaloneSpirv-PhysicalStorageBuffer64-04708`
- Adds tests for using `OpCopyMemory` with PSB (had store and load ops)
- Remove a redundant call to `CheckMemoryAccess` for copy ops because it calls `ValidateCopyMemoryMemoryAccess` right after anyway
- Removed the `EXT` suffix for `SPV_KHR_physical_storage_buffer` items to make it consistent everywhere in code base
> spirv-val: Label and add test for PSB Aligned

- source/val/validation_state.cpp
In case comparisons between types of different widths in a loop condition caused the loop to behave unexpectedly.
> Use types have same widths in loop condition.

- source/val/validate_cfg.cpp
- source/val/validate_function.cpp
- source/val/validate_logicals.cpp
- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_memory_test.cpp
Was going to add a missing Vulkan VariablePointers check and was really thrown off with the use of the `variable_pointers` and `variable_pointers_storage_buffer` feature boolean as it was just redoing the work `HasCapability` and besides the "can it be Workgroup StorageClass" all the checks just want both anyway
~~Also `OpPtrEqual` and `OpPtrNotEqual` I noticed when cleaning this up were being checked for a capability that they don't need in `ValidatePtrComparison`  ... but also looking at internal issue `#682` it seems maybe the spec got updated wrong and is missing the `VariablePointersStorageBuffer` requirement~~
> spirv-val: Clean up VariablePointers logic

- source/val/validate_annotation.cpp
- source/val/validate_decorations.cpp
- source/val/validate_image.cpp
- source/val/validation_state.cpp
- test/val/val_annotation_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_image_test.cpp
Add new VUID labels for the following
- VUID-StandaloneSpirv-OpTypeSampledImage-06671
- VUID-StandaloneSpirv-Location-06672
- VUID-StandaloneSpirv-OpEntryPoint-06674
- VUID-StandaloneSpirv-PushConstant-06675
- VUID-StandaloneSpirv-Uniform-06676
- VUID-StandaloneSpirv-UniformConstant-06677
- VUID-StandaloneSpirv-InputAttachmentIndex-06678
Removed the "section" part as it is not accurate due to the many variations of the spec, but also with a VUID there is no need to go finding the random spec language that enforces these errors
> spirv-val: Add more Vulkan VUID labels

- source/opt/spread_volatile_semantics.cpp
- source/opt/spread_volatile_semantics.h
- test/opt/spread_volatile_semantics_test.cpp
spread-volatile-semantics pass spreads Volatile semantics for builtin
variables used by certain execution models based on
VUID-StandaloneSpirv-VulkanMemoryModel-04678 and
VUID-StandaloneSpirv-VulkanMemoryModel-04679 (See "Standalone SPIR-V
Validation" section of Vulkan spec "Appendix A: Vulkan Environment for
SPIR-V"). Therefore, shaders without execution model (e.g., used only
for linkage) are not the target of the pass. This commit lets the pass
just return SuccessWithoutChange in that case.
> Handle shaders without execution model in spread-volatile-semantics

- source/text.cpp
- test/c_interface_test.cpp
- test/text_to_binary.annotation_test.cpp
- test/text_to_binary.barrier_test.cpp
- test/text_to_binary.control_flow_test.cpp
- test/text_to_binary.device_side_enqueue_test.cpp
- test/text_to_binary.image_test.cpp
- test/text_to_binary.memory_test.cpp
- test/text_to_binary.mode_setting_test.cpp
- test/text_to_binary.pipe_storage_test.cpp
- test/text_to_binary.subgroup_dispatch_test.cpp
- test/text_to_binary.type_declaration_test.cpp
I find myself dealing with `spirv-as` failing and just giving me a line number which is not always helpful when the disassembled spirv is not available in a convenient way to make use of that information. This adds the opcode when possible on failure to help more quickly find the error
> spirv-as: Add opcode name when possible

- source/util/ilist.h
sentinel_count is not used in non-assert builds.
Recent clang improvements to -Wunused-but-set-variable trigger a warning on this.
Fixes #4772.
> Suppress -Wunused-but-set-variable on variable

- source/opt/loop_descriptor.cpp
- source/opt/loop_descriptor.h
- test/opt/loop_optimizations/unroll_simple.cpp
These loop are infinite loop, so there is no reason to unroll the loop.
Fixes #4711.
> Don't try to unroll loop with step count 0.

- source/link/linker.cpp
- test/link/entry_points_test.cpp
- test/link/linker_fixture.h
By resolving extern symbols Entry Points might access variables they hadn't declared before.
Side note: we might want to rename `RemoveUnusedInterfaceVariablesPass` as it's not removing variables, but instead recomputing them.
> linker: Recalculate interface variables

- DEPS
- source/val/validate_builtins.cpp
Add SpvBuiltInSubgroupLtMask to a switch so spirv-tools can compile with
the latest headers.
> Add SpvBuiltInSubgroupLtMask to a switch

- source/opcode.cpp
- source/val/validate_non_uniform.cpp
- test/text_to_binary.extension_test.cpp
- test/val/CMakeLists.txt
- test/val/val_extension_spv_khr_subgroup_rotate.cpp
- Update SPIR-V Headers to pick up the definitions
- Add assembler/disassembler support
- Add validator support
Change-Id: Iffcedd5d5e636a0e128a5906ffe634dd85727de1
> Add support for SPV_KHR_subgroup_rotate

- source/opt/replace_desc_array_access_using_var_index.cpp
- source/opt/replace_desc_array_access_using_var_index.h
- test/opt/replace_desc_array_access_using_var_index_test.cpp
Previously, a chain of `OpAccessChain` instructions would not be handled correctly by the `replace_desc_array_access_using_var_index` pass, which is required to legalize variable-index accesses to flattened resource arrays. The pass works by transforming each variable index access into a switch-case block where each case block references a constant index instead.
Consider this code in HLSL:
```
struct TestStruct
{
uint unused;
uint val;
};
ConstantBuffer<TestStruct> TestResources[2];
TestStruct test = TestResources[chosenIndex];
test.val; 
```
which becomes in SPIR-V:
```
%75 = OpAccessChain %85 %3 %90
%94 = OpAccessChain %93 %75 %6
%95 = OpLoad %5 %94
```
The `replace_desc_array_access_using_var_index` pass does not handle this case correctly, as it looks for final users of the first …
> Handle chains of OpAccessChain in flattened resources' variable index replacement

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
Fold chains of insert into construct
If a chain of OpCompositeInsert instruction write to every element of a
composite object, then we can replace it with an OpCompositeConstruct.
Fold a construct fed by extracts to a single extract
We already fold an OpCompositeConstruct when it is simlpy reconstructing
an object that was decomposed by a series of OpCompositeExtract
instructions.  However, we do not do that if that object is an element
of a larger object.
I have updated the rule, so that if the original object is a an element
of a larger object, then the OpCompositeConstruct is replaced with a
single OpCompositeExtract from the larger object.
Fixes #4371.
> Add more folding for composite instructions

- source/val/validate_annotation.cpp
- source/val/validate_interfaces.cpp
- source/val/validation_state.cpp
- test/val/val_decoration_test.cpp
Add remaining validation for `SPV_KHR_fragment_shader_barycentric` for the `PerVertexKHR` decoration
Adds VUID `VUID-StandaloneSpirv-PerVertexKHR-06777` and `VUID-StandaloneSpirv-Input-06778`
tracker: https://github.com/KhronosGroup/Vulkan-Docs/issues/1863
cc @stu-s
> spirv-val: Add PerVertexKHR

- source/val/decoration.h
- source/val/validate_annotation.cpp
- source/val/validate_decorations.cpp
- source/val/validate_memory.cpp
- source/val/validation_state.h
- test/val/val_decoration_test.cpp
A std::set is used instead of std::vector, where the elements are
ordered by member index first.  Decorations for fields are now looked up
by going over the range of decorations for the member only, instead of
the whole set.
In an ANGLE test that generates a struct with 4096 members, validation
goes down from ~140ms to ~90ms.  On debug builds, the difference is more
pronounced, going down from ~2.5s to ~600ms.
> spirv-val: Optimize struct field decoration lookup

- DEPS
- source/val/validate_mode_setting.cpp
- test/val/val_modes_test.cpp
- Update SPIR-V headers.
- Add validator support.
- Add validator tests.
> spirv-val: Add support for SPV_AMD_shader_early_and_late_fragment_tests

- source/opt/scalar_replacement_pass.h
sprintf is marked as deprecated with Xcode 14.
> Fix usage of sprintf.

- source/opt/local_access_chain_convert_pass.cpp
- source/opt/local_access_chain_convert_pass.h
- source/opt/types.cpp
- source/opt/types.h
- test/opt/local_access_chain_convert_test.cpp
- test/opt/types_test.cpp
An access chain could have a constant index that is an out of bounds
access.  This is valid spir-v, even if it can cause problems at runtime.
However, it is not valid to have an OpCompositeExtract with an out of
bounds access.  This means we have to stop local-access-chain-convert
from making that change.
Fixes #4605
> Avoid replacing access chain with OOB access

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_memory_test.cpp
`VUID-StandaloneSpirv-Uniform-06807` and `VUID-StandaloneSpirv-PushConstant-06808` were added in the 1.3.217 spec so they could be labeled here
> spirv-val: Label 06807 and 06808 VUID

- source/opt/folding_rules.cpp
The Reciprocal function expects a divide-by-0 to return nan,and then Reciprocal will return 0.
Since the divide-by-0 is actually undefined, we will identify this case early, and return 0.
No new tests are needed because we already tests folding divide-by-0.
Fixes #4715
> Avoid undefined divide-by-0

- source/opt/loop_unroller.cpp
Current implementation crashes running pass configuration like this:
```cpp
opt.RegisterPerformancePasses()
.RegisterPass(spvtools::CreateStripDebugInfoPass())
.RegisterPass(spvtools::CreateStripReflectInfoPass())
// A pass I wrote to specialize loop ranges and it calls `LoopUtils::PartiallyUnroll`.
.RegisterPass(spvtools::CreateMyPass())
.RegisterPerformancePasses() // <- Crashed in a `DeadBranchElimPass` here
;
```
and the assertion failure reads:
```
Assertion failed: (block_to_move->GetParent() == ip->GetParent() && "Both blocks have to be in the same function."), function MoveBasicBlockToAfter, file function.h, line 234.
```
with the following stacktrace:
```
__pthread_kill (@__pthread_kill:5)
pthread_kill (@pthread_kill:75)
abort (@abort:44)
__assert_rtn (@err:3) …
```
> Fixed crash unrolling loops with residual iterations

- source/opt/if_conversion.cpp
- test/opt/if_conversion_test.cpp
If the predecessor blocks are the same, then there is only 1 value for the
OpPhi.  The simplition pass will simplify it, and it causes problems for
if-conversion.  In these cases, if-conversion can just punt.
Fixes #3554.
> Avoid if-conversion if both predecessors are the same

- source/cfa.h
- source/opt/cfg.cpp
- source/opt/cfg.h
- source/opt/dominator_tree.cpp
- source/opt/loop_descriptor.cpp
- source/val/validate_cfg.cpp
- test/opt/cfg_test.cpp
We currently build the structured order for all nodes reachable from the
loop header when unrolling a loop.  However, unrolling only needs the
nodes in the loop and possibly the merge node.
To avoid needless computation, I have implemented a search that will
stop at the merge node.
Fixes #4827
> Build struct order only for the section needed when unrolling.

- source/disassemble.cpp
- source/disassemble.h
- source/libspirv.cpp
- test/binary_to_text_test.cpp
When the `SPV_BINARY_TO_TEXT_OPTION_PRINT` option is specified, `spvtext` will not be created: https://github.com/KhronosGroup/SPIRV-Tools/blob/37d2396cabe56b29d37551ea55d0d745d5748ded/source/disassemble.cpp#L116-L132
The attempt to afterwards dereference into its members (`spvtext->str` and `spvtext->length`) then results in segmentation fault:
https://github.com/KhronosGroup/SPIRV-Tools/blob/37d2396cabe56b29d37551ea55d0d745d5748ded/source/libspirv.cpp#L103
This PR adds a check on `spvtext`.
> Fix segfault in `SpirvTools::Disassemble` when printing

- source/opt/inline_pass.cpp
- source/opt/inline_pass.h
- source/val/basic_block.cpp
- source/val/basic_block.h
- source/val/construct.cpp
- source/val/function.cpp
- source/val/function.h
- source/val/validate_cfg.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
- test/opt/dead_branch_elim_test.cpp
- test/opt/inline_test.cpp
- test/opt/pass_merge_return_test.cpp
- test/val/val_cfg_test.cpp
- test/val/val_fixtures.h
* Structural dominance introduced in SPIR-V 1.6 rev2
* Changes the structured cfg validation to use structural dominance
* structural dominance is based on a cfg where merge and continue
declarations are counted as graph edges
* Basic blocks now track structural predecessors and structural
successors
* Add validation for entry into a loop
* Fixed an issue with inlining a single block loop
* The continue target needs to be moved to the latch block
* Simplify the calculation of structured exits
* no longer requires block depth
* Update many invalid tests
> Use structural dominance to validate cfg

- source/val/construct.cpp
* ANGLE builds with -Werror,-Wunreachable-code-loop-increment which had
a problem with grabbing the first construct in a loop
* Change the code to just use begin instead
> Fix unreachable loop increment

- BUILD.bazel
- build_defs.bzl
I was running into issues building with Bazel on my Mac using a Linux [RBE](https://bazel.build/docs/remote-execution) worker. The reason was that Bazel was uploading the [Host platform](https://bazel.build/docs/platforms)'s (Mac) Python executables and not the Execution Platform (Linux)'s Python executables. Thus, I was seeing an error like:
`OSError: [Errno 8] Exec format error`
The [tools](https://bazel.build/reference/be/general#genrule.tools) attribute of genrules corresponds to the Host platform, but this is largely incorrect when using RBE. [exec_tools](https://bazel.build/reference/be/general#genrule.exec_tools) matches the execution platform, which is what is desired here. If building without RBE, the Host and Execution platform will be the same, and the difference between …
> Use exec_tools instead of tools for better RBE compatibility

- source/opt/instruction.cpp
- test/opt/instruction_test.cpp
If the `instruction` operand in an extended instruction instruction is
too large, it causes undefined behaviour when that value is cast to the
enum for the corresponding set.  This is done with the
NonSemanticDebug100 instruction set.  We need to avoid the undefined
behaviour.
Fixes #4727
> Avoid undefined behaviour when getting debug opcode

- source/opt/reduce_load_size.cpp
- test/opt/reduce_load_size_test.cpp
Array do not have to have a size that is known at compile time.  It
could be a spec constant.  In these cases, we should treat the array
like it is arbitrary long.  Internally, we will treat it like it is an
array of size UINT32_MAX.
Fixes https://crbug.com/oss-fuzz/47397.
> Reduce load size does not work for array with spec const size

- source/opt/scalar_replacement_pass.h
The fuzzer cretes code with very large array, and scalar replacement
times out.  Adding a limit on the size of the composites that will be
split when fuzzing.
Fixes https://crbug.com/oss-fuzz/48630
> Add limit for scalar replacment when fuzzing

- source/val/validate_cfg.cpp
- test/val/val_cfg_test.cpp
The updated rules in SPIR-V 1.6 Rev2 use structural dominance,
so update the messages to match
> Update validator diagnostics with "structurally dominated"

- source/val/basic_block.cpp
- source/val/basic_block.h
- source/val/validate_cfg.cpp
- test/reduce/structured_loop_to_selection_test.cpp
- test/val/val_cfg_test.cpp
Fixes https://crbug.com/oss-fuzz/48578
* Adds structural reachability to basic blocks
* calculated in same manner as reachability, but using structural
successors
* Change structured CFG validation to use structural reachability
instead of reachability
* Fix some invalid reducer cases
> Use structural reachability in CFG checks

- source/val/validate_decorations.cpp
- source/val/validation_state.cpp
- test/val/val_builtins_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_interfaces_test.cpp
the successor of https://github.com/KhronosGroup/SPIRV-Tools/pull/4293/ and closes https://github.com/KhronosGroup/SPIRV-Tools/issues/3154 and https://github.com/KhronosGroup/SPIRV-Tools/issues/3066
This adds the following:
- VUID-StandaloneSpirv-Flat-04744
- VUID-StandaloneSpirv-Flat-06201
- VUID-StandaloneSpirv-Flat-06202
> spirv-val: Add Vulkan decoration interface

- source/opt/interface_var_sroa.cpp
Fix code that is traversing def-use user structure at the same time
that it is changing it. This is dicey at best and error prone at worst.
This was uncovered making a change to the id_to_user representation.
> Fix small bug traversing users in interface_var_sroa

- source/val/validate_conversion.cpp
- source/val/validate_misc.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_conversion_test.cpp
Adds `OpConvertUToAccelerationStructureKHR` check found in both `SPV_KHR_ray_query` and `SPV_KHR_ray_tracing`
task list https://github.com/KhronosGroup/Vulkan-Docs/issues/1402
> spirv-val: Add OpConvertUToAccelerationStructureKHR

- source/val/validate.cpp
- source/val/validate_cfg.cpp
- source/val/validate_decorations.cpp
- source/val/validate_image.cpp
- source/val/validate_instruction.cpp
- source/val/validate_layout.cpp
- source/val/validate_logicals.cpp
- source/val/validate_type.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_decoration_test.cpp
- test/val/val_id_test.cpp
- test/val/val_image_test.cpp
- test/val/val_layout_test.cpp
- test/val/val_logicals_test.cpp
@alan-baker kindly let me know where should I add test cases for this extension?
Note: Previous PR https://github.com/KhronosGroup/SPIRV-Tools/pull/4597 was closed. I have addressed all the comments except adding test cases.
> Implement SPV_NV_bindless_texture related changes

- Android.mk
- BUILD.gn
- source/CMakeLists.txt
- source/val/validate.cpp
- source/val/validate.h
- source/val/validate_ray_query.cpp
- test/val/CMakeLists.txt
- test/val/val_ray_query.cpp
Adds basic validation for all `OpRayQuery*` instructions operands/result types
Might not work with CI if it hards code `./test/val/val_stuvw` as name has been updated to `val_rstuvw`
task list https://github.com/KhronosGroup/Vulkan-Docs/issues/1402 (cc @dgkoch in case I beat someone to this and prevent them from duplicating work, but didn't see an open issue on this)
> spirv-val: Add SPV_KHR_ray_query

- source/text_handler.cpp
- test/text_advance_test.cpp
Excessive whitespace can lead to stack overflow during parsing as each
character of skipped whitespace involves a recursive call. An
iterative solution avoids this.
Fixes #4729.
> spirv-as: Avoid recursion when skipping whitespace

- source/val/validate_scopes.cpp
- test/val/val_barriers_test.cpp
The VUID reads as
> VUID-StandaloneSpirv-None-04638
Scope for memory must be limited to Device, QueueFamily, Workgroup, ShaderCallKHR, Subgroup, or Invocation
And there is a runtime VUID the Vulkan Validation Layers use to check for `QueueFamily`
> VUID-RuntimeSpirv-vulkanMemoryModel-06266
If [vulkanMemoryModel](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-vulkanMemoryModel) is not enabled, QueueFamily memory scope must not be used
so I was going to add `QueueFamily` to `spirv-val` (since it was missing) then realized the logic for the check seems more complex than needed.
I realize `ShaderCallKHR` is really not possible in Vulkan 1.0, but below the change we check for the proper execution model so it will still be validated correctly (but with a more …
> spirv-val: Fix Vulkan memory scope

- source/util/hex_float.h
- test/hex_float_test.cpp
When an exponent is so large that it would overflow the int
type in the parser, saturate the exponent.
This allows extremely large exponents, and saturates
to infinity when the exponent is positive, and zero when the exponent
is negative.
Fixes #4721.
> spirv-as: Avoid overflow when parsing exponents on hex floats

- source/val/validate_decorations.cpp
- test/opt/inst_bindless_check_test.cpp
- test/val/val_decoration_test.cpp
* Uniform block layout rules for matrices should use extended layouts by
default
> Update structure layout validation

- source/opt/merge_return_pass.h
A recent libc++ roll in Chrome warned of a deprecated copy. We're
still looking if this is a bug in libc++ or a valid warning, but
removing the redundant line is a safe workaround or fix in either
case.
See discussion in https://crrev.com/c/3791771
@alan-baker PTAL
> Remove default copy constructor in header.

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Fixes #4875
* Require that matrices in laid out structs have RowMajor or ColMajor
set as per SPIR-V section 2.16.2 (shader validation)
> Require ColMajor or RowMajor for matrices

- source/val/validate_scopes.cpp
- source/val/validation_state.cpp
- test/val/val_barriers_test.cpp
Vulkan 1.2.223 spec added `VUID-StandaloneSpirv-None-06997`
> spirv-val: Label VUID 06997

- source/diff/diff.cpp
These asserts are not valid for string literals, which may
contain several words:
assert(a_operand.words.size() == 1);
assert(b_operand.words.size() == 1);
It looks like they only make sense for the default case, which
assumes that both operands contain a single word.
Running a debug version of spirv-diff on any shader containing
a string literal will hit the original asserts.
> spirv-diff: Fix asserts in ComparePreambleInstructions()

- source/opt/local_access_chain_convert_pass.cpp
- source/opt/local_access_chain_convert_pass.h
- test/opt/local_access_chain_convert_test.cpp
An access chain instruction interpretes its index operands as signed.
The composite insert and extract instruction interpret their index
operands as unsigned, so it is not possible to represent a negative
number.
This commit adds a check to the local-access-chain-convert pass to check
for a negative number in the access chain and to not do the conversion.
Fixes #4856
> Local access chain convert: check for negative indexes

- source/opt/pass_manager.cpp
Disassembler was called with non-default params, loosing FRIENDLY_NAMES.
This commit changes the call options to allow the spirv-opt to show
friendly names instead of raw-ids. Might be more helpful when reading
the SPIRV-opt output.
Fixes #4882
Signed-off-by: Nathan Gauër <brioche@google.com>
> Allow spirv-opt print-all to show pretty IDs

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
When folding a vector shuffle with an undef literal, it is possible that the
literal is adjusted so that it will then be interpreted as an index into
the input operands.  This is fixed by special casing that case, and not
adjusting those operands.
Fixes #4859
> Fix shuffle feeding shuffle with undef literal

- source/opt/copy_prop_arrays.cpp
- source/opt/copy_prop_arrays.h
- test/opt/copy_prop_array_test.cpp
The Array copy propagation was interpreting OpEntryPoint as a store, and therefore not propagating arrays passed into the shader.
Fixes microsoft/DirectXShaderCompiler#4444
> Fix array copy propagation

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/debug_info_manager.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
Specifically, DebugSourceContinued, DebugCompilationUnit, and
DebugEntryPoint. These instructions are top-level instructions
which do not or may not have a user except for the tool and so
should not be eliminated.
> Fix ADCE to not eliminate top level DebugInfo instructions

- source/opt/copy_prop_arrays.cpp
- source/opt/copy_prop_arrays.h
- test/opt/copy_prop_array_test.cpp
Copy-propagate-arrays optimization pass would create unused constants,
even if the optimization not completed.
This was caused by the way we handled OpAccessChain squashing: we
only referenced constants, and had to create them upfront.
For now, I couldn't find a path to reproduce this. (Might have one involving RuntimeArrays, but couldn't generate one).
This however will be more visible once #4887 is fixed since we would need to abort while computing the final OpAccessChain.
Signed-off-by: Nathan Gauër <brioche@google.com>
> spirv-opt: fix copy-propagate-arrays index opti on structs.

- source/opt/eliminate_dead_input_components_pass.cpp
- source/opt/eliminate_dead_input_components_pass.h
- test/opt/eliminate_dead_input_components_test.cpp
Will eliminate all trailing members of input struct that are not
referenced.
> Add structs to eliminate dead input components

- source/val/validate_image.cpp
- test/val/val_image_test.cpp
The spirv specs in 1.5.3 added
> #573: Clarify the type read/written is scalar or vector in OpImageRead, OpImageWrite, and OpImageSparseRead.
so safe to remove the `#if 0` and todo comment in `OpImageWrite` for the `Texel` type check
> spirv-val: Remove ImageWrite Texel todo

- source/opt/compact_ids_pass.cpp
This is because the DebugInfo manager requires valid SPIR-V
which is not always true during this pass.
> Disable DebugInfoMgr during the entire CompactIds pass

- test/opt/inst_bindless_check_test.cpp
- test/opt/inst_buff_addr_check_test.cpp
- test/opt/inst_debug_printf_test.cpp
Reduce the amount of repeated boilerplate in the test cases by using pattern matching for common code that is added by these passes.  This will make it easier to keep the tests working when making changes to how these passes work.
> tests: Make InstrumentPass tests use SinglePassRunAndMatch<> and stateful pattern matching

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_storage_test.cpp
Adds validation to make sure all the ray tracing `Storage Class` are using the correct execution model. Also `HitAttributeKHR` and `ShaderRecordBufferKHR` have read/write limitations. There is already validation for the "cannot have initializers" marked as `VUID-StandaloneSpirv-OpVariable-04651`
(tasklist https://github.com/KhronosGroup/Vulkan-Docs/issues/1402)
> spirv-val: Add SPV_KHR_ray_tracing storage class

- source/val/validate_annotation.cpp
- source/val/validate_decorations.cpp
- source/val/validation_state.h
Noticed there were 2 functions doing a string lookup and not just using the generated table
> spirv-val: Use lookup table for Decoration string

- source/val/validate_memory.cpp
- test/val/val_id_test.cpp
related to https://github.com/KhronosGroup/SPIRV-Registry/issues/161 trying to understand when a `OpTypeBool` is legal
seems the code before the error message was a bit outdated
edit: I just saw
> Khronos Issue #363: [OpTypeBool](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeBool) can be used in the Input and Output storage classes, but the client APIs still only allow built-in Boolean variables (e.g. FrontFacing), not user variables.
so that would explain/verify this logic
> spirv-val: Better message for using OpTypeBool in input/output

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/aggressive_dead_code_elim_pass.h
This is pretty self explanatory. ADCE was not marking these as live and was subsequently removing an DebugInlinedAt that was needed when the binary was generated at the end.
There is no test because one is not possible. That is because the problem only occurs when an instruction has a different scope than its OpLine (or DebugLine). It is not possible to enter such SPIR-V into spirv-opt. The spirv-opt binary reader overrides the actual input and gives an OpLine the same scope as its instruction. The original issue was created by SSA Rewrite on a very large and complex (and proprietary) shader.
I think it is quite obvious that ADCE needs to mark these as live.
> Fix ADCE to mark scope and inlined_at of line instructions as live.

- source/opt/inst_buff_addr_check_pass.cpp
- source/opt/inst_buff_addr_check_pass.h
- source/opt/instrument_pass.cpp
- source/opt/instrument_pass.h
- test/opt/inst_bindless_check_test.cpp
- test/opt/inst_buff_addr_check_test.cpp
- test/opt/inst_debug_printf_test.cpp
Add name annotations to the generated instrumentation code to
make it easier to understand. Example spirv-cross output:
vec4 _140;
if (0u < inst_bindless_direct_read_4(0u, 0u, 1u, uint(_19)))
{
_140 = texture(textures[nonuniformEXT(_19)], inUV);
}
else
{
inst_bindless_stream_write_4(50u, 1u, uint(_19), 0u);
_140 = vec4(0.0);
}
> Instrument: Add OpNames to generated functions and variables

- source/opt/fold_spec_constant_op_and_composite_pass.cpp
- source/opt/fold_spec_constant_op_and_composite_pass.h
- source/opt/instruction.cpp
- source/opt/instruction.h
While looking into something else for `FoldSpecConstantOpAndCompositePass` it seems that over time things were moved out to `opt/fold.cpp` and `opt/folding_rules.cpp` and these functions are not being used and threw me off while trying to grasp how the pass worked at first.
> spirv-opt: Remove unused fold spec const code

- source/cfa.h
- source/opt/cfg.cpp
- source/opt/dominator_tree.cpp
- source/val/validate_cfg.cpp
Changed a couple small parts of the algorithm to reduce time to build
the dominator trees.  There should be no visible changes.
Add a depth first search algorithm that does not run a function on
backedges.  The check if an edge is a back edge is time consuming, and
pointless if the function run on it is a nop.
> Improve time to build dominators

- test/val/val_builtins_test.cpp
Just adds `vuid` to the `ValidateVulkanCombineBuiltInArrayedVariable` tests for completeness
> spirv-val: Label Builtin Array Test VUIDs

- source/opcode.cpp
Not sure why this is repeated for validation and optimizer, but ...
Fixes spirv-opt error when consuming a task shader:
```
error: line 0: OpLabel inside basic block
```
```
; SPIR-V
; Version: 1.4
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 109
; Schema: 0
OpCapability MeshShadingEXT
OpExtension "SPV_EXT_mesh_shader"
%1 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint TaskEXT %main "main" %vs %gl_LocalInvocationIndex %p
OpExecutionMode %main LocalSize 4 3 2
OpSource GLSL 450
OpSourceExtension "GL_EXT_mesh_shader"
OpName %main "main"
OpName %vs "vs"
OpName %gl_LocalInvocationIndex "gl_LocalInvocationIndex"
OpName %Payload "Payload"
OpMemberName %Payload 0 "v"
OpName %p "p"
OpDecorate %gl_LocalInvocationIndex BuiltIn LocalInvocationIndex …
```
> Also consider EmitMeshTasksEXT terminator in spirv-opt.

- source/opt/debug_info_manager.cpp
- source/opt/debug_info_manager.h
- source/opt/local_single_store_elim_pass.cpp
- source/opt/ssa_rewrite_pass.cpp
- source/opt/ssa_rewrite_pass.h
- test/opt/ir_context_test.cpp
- test/opt/local_single_store_elim_test.cpp
- test/opt/local_ssa_elim_test.cpp
Specificially, this fixes DebugValues coming out of eliminate-local-single-store and eliminate-local-multi-store AKA SSA rewrite.
This is done by bypassing the IsDeclareVisibleToInstr() analysis in the DebugInfoManager and just always generating a DebugValue when calling AddDebugValueIfVarDeclIsVisible() ie. assuming that the associated DebugDeclare is always visible. This is currently done through a force argument to AddDebugValueIfVarDeclIsVisible(), but this method will ultimately be changed to just AddDebugValue() along with other clean-up once this change is approved.
This change was created because several different issues with DebugValues were tracked back to this logic: several cases of missing DebugValues, one case of a DebugValue generated with stale (ie. no longer defined) …
> WIP: Fix missing and incorrect DebugValues

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_id_test.cpp
`VUID-StandaloneSpirv-Input-07290` was added in the Vulkan 1.3.227 spec
> spirv-val: Label VUID 07290

- source/val/validate_decorations.cpp
* getBaseAlignment with roundUp true is called the "extended" by the Vulka spec.
* roundUp also affects matrix alignment, not just struct and array
> spirv-val: Fix comment for checking extended alignments

- source/opt/debug_info_manager.cpp
- source/opt/debug_info_manager.h
- source/opt/local_single_store_elim_pass.cpp
- source/opt/ssa_rewrite_pass.cpp
- source/opt/ssa_rewrite_pass.h
Removed now unused DebugDeclare visibility logic for generating DebugValue.
Also eliminated the phi sort introduced in 272e4b3d0. This should have been removed in the first commit.
> Cleanup code for 272e4b3d0

- source/val/validate_ray_query.cpp
- test/val/val_ray_query_test.cpp
Private arrays of ray queries are legal to use. Several CTS tests check they work properly but were being rejected by spirv-val.
Fixes #4917.
> spirv-val: Make it legal to use arrays of ray queries

- source/val/validate_builtins.cpp
This prevents spurious build failures when new opcodeds are added in SPIRV-Headers.  It moves all the unhandled opcodes to the `default` case.
> Fix builtin validator for unimplemented opcodes.

- source/opcode.cpp
- source/opcode.h
- source/opt/inline_pass.cpp
- source/opt/inline_pass.h
This function is the same as `spvOpcodeIsAbort` except for
OpUnreachable.  The names are so close in meaning that it is hard to
distinguish them.  I've removed `spvOpcodeTerminatesExecution` since it
is used in only a single place.  I've special cased OpUnreachable in
that location.
At the same time, I fixed up some comments related to the use of the
TerminatesExecution and IsAbort functions.
Following up on #4930.
> Remove `spvOpcodeTerminatesExecution`

- source/opt/fold.cpp
- source/opt/fold_spec_constant_op_and_composite_pass.cpp
- test/opt/fold_spec_const_op_composite_test.cpp
This was spotted in the Validation Layers where `OpSpecConstantOp %x CompositeExtract %y 0` was being folded to a constant, but anything that was using it wasn't recognizing it as a constant, the simple fix was to add a `const_mgr->MapInst(new_const_inst);` so the next instruction knew it was a const
> spirv-opt: Fix stacked CompositeExtract constant folds

- source/opt/debug_info_manager.cpp
- test/opt/inline_test.cpp
get_def_use_mgr() is actually not allowed here because we are in the middle of inlining and the module may be inconsistent/invalid and rebuilding the def_use_mgr() can cause problems. Luckily the call to get_def_use_mgr()->GetDef() is unnecessary and this gets rid of it.
> Fix CreatDebugInlinedAt to not invoke def_use_mgr

- source/opt/const_folding_rules.cpp
`FoldIClamp` seems to have been replaced with `FoldClamp1`/`FoldClamp2`/`FoldClamp3`
> spirv-opt: Remove unused folding rule

- include/spirv-tools/libspirv.h
- include/spirv-tools/libspirv.hpp
- source/spirv_validator_options.cpp
- source/spirv_validator_options.h
- source/val/validation_state.cpp
- test/val/val_id_test.cpp
The always-friendly messages make it harder to debug when the
disassembly is later generated without friendly names.
Additionally, the friendly-name-mapper is slow.  Disabling it improves
performance of an ANGLE test that creates numerous shaders by ~5%.
> spirv-val: Add an option to use friendly names or not

- test/val/val_id_test.cpp
Proved to be marginally faster than appending to string.
> spirv-val: Use ostringstream in id validation tests

- source/val/validate_builtins.cpp
- test/val/val_builtins_test.cpp
Change-Id: If1680a823aea9662d44def1ec6fe6ac334c00574
> spirv-val: Add SPV_ARM_core_builtins validation

- source/opt/constants.h
- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
This change adds support for narrow types in the BitCastScalarOrVector folding rule. According to Section 2.2.1 of the SPIR-V spec, types that are narrower than 32 bits are automatically either sign extended, or zero extended depending on the type. With that guaranteed, we should be able to use the first 32-bit word of any narrow type for the folding logic without performing any special conversions.
In order to reduce code duplication, this change moves the GetU32BitValue and GetU64BitValue functions from IntConstant to ScalarConstant. Without this move, we would have needed an identical version of GetU32BitValue on FloatConstant.
> Support Narrow Types in BitCast Folding Rule

- source/val/validate_decorations.cpp
- source/val/validation_state.cpp
- test/val/val_decoration_test.cpp
- test/val/val_interfaces_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/2017
Adds 
VUID-StandaloneSpirv-Component-04920
VUID-StandaloneSpirv-Component-04921
VUID-StandaloneSpirv-Component-04922
VUID-StandaloneSpirv-Component-04923
VUID-StandaloneSpirv-Component-04924
> spirv-val: Add remaining Component decoration validation

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/opt/eliminate_dead_member_test.cpp
- test/val/val_id_test.cpp
- test/val/val_memory_test.cpp
adds `VUID-StandaloneSpirv-Base-04707` and the SPIR-V spec for `Shader` saying
> Each OpPtrAccessChain must have a Base whose type is [decorated](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration) with ArrayStride.
> spirv-val: Add OpPtrAccessChain Base checks

- source/cfa.h
- test/val/val_cfg_test.cpp
Fixes https://crbug.com/oss-fuzz/48553
* Assign a reflexive dominator if no other dominator can be found using forward traversals
* This prevents a null dereference of a pointer in the sorting of the output
> Prevent null pointer from being dereferenced

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_memory_test.cpp
follow up from https://github.com/KhronosGroup/SPIRV-Tools/pull/4965#discussion_r1000524643
These were added in the Vulkan 1.2.232 headers
> spirv-val: Label new Vulkan OpPtrAccessChain VUs

- source/val/validate_decorations.cpp
- test/reduce/validation_during_reduction_test.cpp
- test/val/val_decoration_test.cpp
Fixes #4671
Fixes https://crbug.com/oss-fuzz/43265
* Only validate full layout in a vulkan environment
* Universal validation still checks that the right decorations are present, but the values are only considered for vulkan
* One exception is that invalid overlaps are only checked for vulkan
* This is a pragmatic choice as SPIR-V doesn't define the size of types so the amount of universal checking would be quite limited
* Removed redundant check for GLSLShared and GLSLPacked decorations
* Should never have been validated as part of universal validation
> Only validate full layout in Vulkan environments

- source/opt/block_merge_util.cpp
- test/opt/block_merge_test.cpp
Fixes #4918
* Prevent block merging from producing an invalid case construct by merging a switch target/default with another construct's merge or continue block
* This is to satisfy the structural dominance requirement between the switch header and the case constructs
> Prevent eliminating case constructs in block merging

- source/val/validate_decorations.cpp
- source/val/validation_state.cpp
- test/val/val_decoration_test.cpp
adds `VUID-StandaloneSpirv-Component-07703` label that was added in Vulkan 1.3.233
> spirv-val: Add VUID label for 07703

- source/opt/const_folding_rules.cpp
- test/opt/fold_spec_const_op_composite_test.cpp
Currently doing a `OpSpecConstantOp %x CompositeInsert` would segfault
This change injects the extra needed `OpConstantComposite` in order to properly handle folding `CompositeInsert`
> spirv-opt: Add const folding for CompositeInsert

- include/spirv-tools/optimizer.hpp
- source/opt/eliminate_dead_input_components_pass.cpp
- source/opt/eliminate_dead_input_components_pass.h
- source/opt/optimizer.cpp
- source/opt/type_manager.cpp
- source/opt/type_manager.h
- test/opt/eliminate_dead_input_components_test.cpp
This pass eliminates components of output variables that are not stored to. Currently this just eliminates trailing components of arrays and structs, all of which are dead.
WARNING: This pass is not designed to be a standalone pass as it can cause interface incompatibiliies with the following shader in the pipeline. See the comment in optimizer.hpp for best usage. This pass is currently available only through the API; it is not available in the CLI.
This commit also fixes a bug in CreateDecoration() which is part of the system of generating SPIR-V from the Type manager.
> Add pass to eliminate dead output components

- include/spirv-tools/optimizer.hpp
- source/opt/eliminate_dead_input_components_pass.cpp
- source/opt/eliminate_dead_input_components_pass.h
- source/opt/instrument_pass.cpp
- source/opt/optimizer.cpp
- test/opt/eliminate_dead_input_components_test.cpp
Safe version will only optimize vertex shaders. All other shaders will succeed without change.
Change --eliminate-dead-input-components to use new safe version.
Unsafe version (allowing non-vertex shaders) currently only available through API. Should only be used in combination with other optimizations to keep interfaces consistent. See optimizer.hpp for more details.
> Split EliminateDeadInputComponents into safe and unsafe versions.

- include/spirv-tools/optimizer.hpp
- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/aggressive_dead_code_elim_pass.h
- source/opt/optimizer.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
This can cause interface incompatibility and should only be done if ADCE has been applied to the following shader in the pipeline. For this reason this capability is not available through the CLI but rather only non-default through the API. This functionality is intended as part of a larger cross-shader dead code elimination sequence and not a standalone optimization.
> Add option to ADCE to remove output variables from interface.

- Android.mk
- source/CMakeLists.txt
- source/opcode.cpp
- source/opt/ir_context.cpp
- source/opt/reflect.h
- source/opt/type_manager.cpp
- source/opt/types.cpp
- source/opt/types.h
- source/val/validate.cpp
- source/val/validate.h
- source/val/validate_annotation.cpp
- source/val/validate_extensions.cpp
- source/val/validate_memory.cpp
- source/val/validate_ray_tracing_reorder.cpp
- source/val/validation_state.cpp
- test/opt/type_manager_test.cpp
- test/val/CMakeLists.txt
- test/val/val_ray_tracing_reorder_test.cpp
SPV spec : https://github.com/KhronosGroup/SPIRV-Registry/pull/175
GLSL spec : https://github.com/KhronosGroup/GLSL/pull/196
> Add validation support for SPV_NV_shader_invocation_reorder.

- source/val/validate_ray_tracing_reorder.cpp
This fixes the errors:
validate_ray_tracing_reorder.cpp:25:49: error: 'numeric_limits' is not a member of 'std'
> Fix missing declaration of std::numeric_limits

- source/opt/const_folding_rules.cpp
- source/opt/constants.cpp
- source/opt/constants.h
- source/opt/debug_info_manager.cpp
- source/opt/eliminate_dead_io_components_pass.cpp
- source/opt/interface_var_sroa.cpp
- source/opt/replace_desc_array_access_using_var_index.cpp
- source/opt/scalar_replacement_pass.cpp
- test/opt/fold_spec_const_op_composite_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/5005 
Now when folding `OpCompositeInsert` with a null `composite` it correctly handles it.
The main issue is `class NullConstant : public Constant {}` is not a  `CompositeConstant` because sometimes `OpConstantNull` can be either. For cases where there is a `OpConstantNull %v3float` it will turn it into a `OpConstantComposite %v3float %null %null %null` before continuing with the logic as normal
cc @sugoi1 I hope this fixes everything now
> spirv-opt: Fix OpCompositeInsert with Null Constant

- test/val/val_id_test.cpp
open_quote value becomes npos when it fails to find '\'' and then is used to compute the string length for writing to result. This causes crash in win32 builds of the test.
> Fix for bug #5017

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Fixes #5010
* Unless scalar block layout is enabled, no member can reside at an offset between the end of the previous member that is a struct or array and the next multiple of that alignment
* Tested against Vulkan CTS
> Fix layout validation

- kokoro/windows-msvc-2017-release-bazel/build.bat
- kokoro/windows-msvc-2017-release-bazel/continuous.cfg
- kokoro/windows-msvc-2017-release-bazel/presubmit.cfg
Part 1 of replacing the msvc-2015-release-bazel build. See issue #5022
> First attempt to set up CI-windows-msvc-2017-release-bazel build

- source/opt/instruction.cpp
Reserve space for the entire operand list rather than adding them one a time.
> Optimize allocation of spvtools::opt::Instruction::operands_

- DEPS
- kokoro/scripts/linux/build-docker.sh
- kokoro/scripts/macos/build.sh
- kokoro/scripts/windows/build.bat
- utils/git-sync-deps
Update git-sync-deps to reduce the amount of data downloaded on a first checkout, while being able to checkout the specific commit specified in the DEPS file.
Previously the CI bots would only clone --depth=1.  But that's not enough to check out a specific commit.  So clone either blobless or treeless.  For a CI bot, treeless is preferable, because it downloads the least data.  For interactive use, blobless is better because it prevents redundant downloads of tree data. See
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
Fixes: #5028
> Kokoro CI bots use git-sync-deps to get sources

- tools/CMakeLists.txt
The package is called SPIRV-Tools-tools, which might be a bit confusing, but at lease follows the general naming scheme.
Without this package file it is impossible to detect tools with cmake only, one needs to use pkgconfig only for that.
> Add exported CMake config file for binaries in ./tools/

- utils/check_code_format.sh
- utils/roll_deps.sh
roll_deps.h: SPIRV-Headers uses 'main'
check_code_format.h: SPIRV-Tools uses 'main'
> utils: repos use 'main' as main devlopment branch

- DEPS
- source/val/validate_extensions.cpp
- source/val/validate_memory.cpp
- test/val/val_ext_inst_test.cpp
* Add validation for instructions in versions 2 through 5
* Change the instruction reported for remaining indices on an access chain to the access chain itself for clarity
> Validate version 5 of clspv reflection

- CMakeLists.txt
These policies don't need to be set anymore now that the cmake_minimum_required is 3.17.2
> cmake: Remove old policy code

- CHANGES
- DEPS
This prepares the `main` branch for the upcoming SPIRV-Tools release.  Testing in progress.
> Prepare for v2023.1 release

- source/opt/inst_bindless_check_pass.cpp
- source/opt/inst_buff_addr_check_pass.cpp
- test/opt/inst_bindless_check_test.cpp
- test/opt/inst_buff_addr_check_test.cpp
Avoid using OpConstantNull with types that do not allow it.
Update existing tests for slight changes in code generation.
Add new tests based on the Vulkan Validation layer test case that exposed this problem.
This is a fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4983
> Instrument: Fix bindless checking for BufferDeviceAddress

- CHANGES
Reverts KhronosGroup/SPIRV-Tools#5062
I did not pay attention to the fact that we want these two commits registered separately in the repo.  This way we can mark the end point of the v2023.1 release properly.  Apologies for the carelessness.
> Revert "Finalize v2023.1 release"

- .github/workflows/autoroll.yml
- utils/roll_deps.sh
Adding an autoroll github action.  It will run once a day, and create a PR to
update DEPS if there are new commits.
I updated roll_deps.sh so that it will not return an error if there were not new
commits for a repository.
> Create a github action to update DEPS

- .github/workflows/autoroll.yml
The current bot is having trouble with the CLA. I checked with the Khronos
admin, and this was his reply:
> We already safe list *[bot] which should account for all GitHub bots. If you
have manually named the GitHub Actions bot to GitHub Actions bot, it should be
renamed to GitHub Actions[bot]. This should resolve the issue.
Trying that to see if it works.
> Rename bot in autoroll.yml

- .github/workflows/bazel.yml
The bazel build are set up to run any time there is a push to any branch. This
cause the same workflow to be run twice when a PR is updated.
I'm changing the workflow to trigger on there is a push to "main", for the
continuous test, and leaving the pull_request trigger for the presubmit test.
> Limit when the github action bazel builds run

- CMakeLists.txt
- README.md
Moving from cpp 11 to cpp 17 will allow us to use modern features like filesystem support, optional, any, execution policies and improved templates.
> build: move from c++11 to c++17

- .github/workflows/bazel.yml
- .github/workflows/wasm.yml
- kokoro/check-format/build.sh
- kokoro/macos-clang-debug/build.sh
- kokoro/macos-clang-release-bazel/build.sh
- kokoro/macos-clang-release/build.sh
- kokoro/scripts/linux/build-docker.sh
- kokoro/scripts/macos/build.sh
- source/wasm/build.sh
Kokoro clones repos with a different user used to run the build steps, meaning if some git command must be run at build time, they will fail because of this dubious ownership issue.
This is a known Kororo issue.
Fixing this is required to generate the version file using git history.
Signed-off-by: Nathan Gauër <brioche@google.com>
> kokoro: fix dubious ownership

- source/val/validate_builtins.cpp
- source/val/validation_state.cpp
- test/val/val_builtins_test.cpp
Adds the basic validation of storage class and type for the 4 new builtins from`SPV_EXT_mesh_shader`
> spirv-val: Initial SPV_EXT_mesh_shader builtins

- external/CMakeLists.txt
Align git-sync-deps and CMake to use external/SPIRV-Headers by default
This should help with avoiding mistakes such as the one that happened under #4958.
Change-Id: I922f02e25c507f3412e0e7a99f525fb617b2d426
> Align git-sync-deps and CMake to use external/spirv-headers by default

- BUILD.gn
> BUILD.gn: Make MSVC report the correct __cplusplus value

- include/spirv-tools/libspirv.h
- source/opt/optimizer.cpp
- test/opt/CMakeLists.txt
- test/opt/c_interface_test.cpp
- utils/check_copyright.py
This PR implements a C interface for the Optimizer class. It follows the same pattern established by the existing C interfaces for other classes in SPIRV-Tools.
> Add C Interface for Optimizer

- source/opt/inst_bindless_check_pass.cpp
- source/opt/inst_buff_addr_check_pass.cpp
- source/opt/inst_debug_printf_pass.cpp
- source/opt/instrument_pass.cpp
- source/opt/instrument_pass.h
- test/opt/inst_bindless_check_test.cpp
- test/opt/inst_buff_addr_check_test.cpp
- test/opt/inst_debug_printf_test.cpp
- Make more use of InstructionBuilder instruction helper methods
- Use MakeUnique<>() rather than new
- Add InstrumentPass::GenReadFunctionCall() which optimizes function calls in a loop with constant arguments and no side effects.
This is a prepatory change for future work on the instrumentation code which will add more generated functions.
> instrument: Clean up generation code

- source/val/validate_type.cpp
- test/val/val_decoration_test.cpp
- test/val/val_memory_test.cpp
Partially fixes https://github.com/KhronosGroup/glslang/issues/2439
* When OpTypeStruct is used in Vulkan env and its last member is a RuntimeArray, check if the struct is decorated with Block or BufferBlock, as required by VUID-...-04680.
> Validate decoration of structs with RuntimeArray

- utils/update_build_version.py
When the build is done on a shallow repo, or on a non-git copy, the version script failed. We should not hard fail, but generate a "version" (unknown).
Sample outputs:
with git history:
`"v2023.2-dev", "SPIRV-Tools v2023.2-dev v2022.4-87-g53541064"`
with shallow clone:
`"unknown_version", "SPIRV-Tools unknown_version d8759a140bc65811332d5f91f3b08febadd5a21d"`
not a git repo:
`"unknown_version", "SPIRV-Tools unknown_version unknown_hash, 2023-02-02T16:25:48.077995"`
> build: allow update_build to generate fake version

- source/val/validate_cfg.cpp
- test/fuzz/transformation_add_dead_block_test.cpp
- test/fuzz/transformation_add_dead_break_test.cpp
- test/val/val_cfg_test.cpp
From 2.16.2, for CFG:
```
Selections must be structured. That is, an OpSelectionMerge instruction is required to precede:
an OpSwitch instruction
an OpBranchConditional instruction that has different True Label and False Label operands where neither are declared merge blocks or Continue Targets.
```
> spirv-val: Conditional Branch without an exit is invalid in loop header

- BUILD.bazel
Without this, Mac developers could not build using our remote linux RBE instance.
> Change exec_tools -> tools for local genrule

- include/spirv-tools/libspirv.h
- include/spirv-tools/libspirv.hpp
- source/libspirv.cpp
- test/binary_parse_test.cpp
This commit adds a C++ wrapper above the current spvBinaryParse function. I tried to match it 1:1, except for 2 things:
- std::function<>& are used. No more function pointers, allowing context capture.
- spv_result_t replaced with a boolean, to match other C++ apis.
Callbacks still return a spv_result_t because the underlying implem relies on that. The convertion from spv_result_t to boolean is only done at the boundary.
> libspirv.cpp: adds c++ api for spvBinaryParse

- source/opcode.cpp
- source/opt/instruction.h
- source/opt/reflect.h
Adding a new type instruction required making the same change in two places.
Also remove IsCompileTimeConstantInst that was used in a single place and replace its use by an expression that IMO better conveys the intent.
Change-Id: I49330b74bd34a35db6369c438c053224805c18e0
> Remove duplicate lists of constant and type opcodes

- include/spirv-tools/optimizer.hpp
- source/opt/optimizer.cpp
Breaking the ABI for this API isn't worth it when the fix is so simple.
81ec2aaa0e170afbeaaf3deaccf88f7dc88672d7
Author: Greg Fischer <greg@lunarg.com>
Date:   Wed Nov 23 10:48:58 2022 -0700
Add option to ADCE to remove output variables from interface. (#4994)
in #4994 broke ABI for the library incompatibility.
Just avoid that.
> opt: fix spirv ABI on Linux again.

- .bazelrc
- .github/workflows/bazel.yml
- README.md
- kokoro/macos-clang-release-bazel/build.sh
- kokoro/scripts/linux/build-docker.sh
Before, we did set cxx version to c++17 using COPTS in our bazel files. This was wrong, and part of the dependencies were then built with the default standard version. This was not an issue until we moved to c++17.
Then, we decided to use the bazel --cxxopt=-std=c++17, but this was only valid for nix platforms.
The last option left is to ask the user to specify the standard when building using bazel.
> build: change the way we set cxx version for bazel.

- utils/update_build_version.py
In a Chromium build environment on Windows git is supplied by depot_tools as git.bat. This was causing build errors on Windows that are most easily reproduced with this command:
gn gen out\default && gn clean out\default && ninja -C out\default spirv-as
The errors included:
[12:55:40][ERROR   ] Failed to run "['git', 'tag', '--sort=-v:refname']" in "C:\src\chromium\src\third_party\vulkan-deps\spirv-tools\src": [WinError 2] The system cannot find the file specified
[12:55:40][WARNING ] Could not deduce latest release version from history.
This is because 'git' does not resolve to git.bat unless shell=True is passed to subprocess.Popen. This change passes shell=True but only on Windows which resolves these errors.
> Allow invoking git.bat as git on Windows

- source/opt/eliminate_dead_functions_util.cpp
- test/opt/eliminate_dead_functions_test.cpp
Fixes #5121
* If the non-semantic info instructions depended on other moved instructions the def/use manager would get corrupted.
> Fix removal of dependent non-semantic instructions

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
`GetExtractOperandsForElementOfCompositeConstruct()` states _"Returns the empty vector if |result_index| is out-of-bounds"_, but violates that contract for non-vector result types.
> Fix operand index out of bounds when folding OpCompositeExtract.

- tools/io.h
This commit fixes the following build error when the source code is build with MinGW gcc 12 and compiler switch '-Werror=maybe-uninitialized' is added:
'file.{anonymous}::OutputFile::old_mode_' may be used uninitialized
in this function [-Werror=maybe-uninitialized]
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4935
> Fix MinGW build error (#4935)

- CMakeLists.txt
> Fix using invalid install path for cmake support files with MINGW platform

- utils/generate_changelog.py
This small utility parses the CHANGES file to generate a CHANGELOG that can be used for GitHub releases.
This will be used by the GitHub workflow to make releases automatic.
Given a CHANGES file path, a tag, the script extract the editorialized changelog, and writes it to a given output file.
> build: tool to generate a CHANGELOG from tags

- .github/workflows/autoroll.yml
- .github/workflows/bazel.yml
- .github/workflows/wasm.yml
This PR sets the minimal permission needed for each workflow:
`content = read`, to read the repo, rest to `none`.
`content = write` for the autoroll workflow as it needs to push to a branch to create a PR.
See:
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#contents
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
> Change default permissions for workflows

- source/val/validate_scopes.cpp
- source/val/validation_state.cpp
- test/val/val_barriers_test.cpp
The new 1.3.243 Vulkan spec created a new VU
> VUID-StandaloneSpirv-SubgroupVoteKHR-07951
If none of the SubgroupVoteKHR, GroupNonUniform, or SubgroupBallotKHR capabilities are declared, Scope for memory must not be Subgroup
> spirv-val: Label new Vulkan VUID 07951

- .github/workflows/release.yml
This workflow creates a new draft release with the proper changelog when a given tag is pushed.
If the CHANGES file has no tag for this release, the workflow fails, so this should prevent most accidental tag push.
> git: add release workflow

- BUILD.bazel
- test/tools/CMakeLists.txt
- test/tools/objdump/extract_source_test.cpp
- tools/CMakeLists.txt
- tools/objdump/extract_source.cpp
- tools/objdump/extract_source.h
- tools/objdump/objdump.cpp
This should be rebased on https://github.com/KhronosGroup/SPIRV-Tools/pull/5146 first.
This adds the source extraction logic for this tool.
Next should be entrypoint and compiler commandline extraction.
> Implement source extraction logic for spirv-objdump

- source/opt/ir_context.h
- source/opt/replace_invalid_opc.cpp
- test/opt/ir_context_test.cpp
- test/opt/replace_invalid_opc_test.cpp
The control barrier instruction was allowed in a limiteted set of shader types.
Part of the HLSL legalization, we use to remove the instructions when it was is
a shader in which it was not allowed. As of spv1.3 that restriction is not long
there.
This change modifies replaced invalid opc to no longer remove it.
Fixes #4999.
> Do not remove control barrier after spv1.3

- kokoro/scripts/linux/build.sh
If the build fails, the artifacts must still be chowned
so the CI can pick them up. If they are not, the CI tooling
will fail and go into 'aborted' state, which blocks the logs.
> kokoro: always chown files

- android_test/Android.mk
- source/util/small_vector.h
> Remove use of deprecated std::aligned_storage

- DEPS
- external/CMakeLists.txt
- source/fuzz/protobufs/spirvfuzz_protobufs.h
- utils/check_symbol_exports.py
We need to update because the current version was not buliding with gcc 12.2. I
could not move upda to v22.x because there was an odd use of some defines that
were causing failures.
> Update protobuf to v21.12

- source/val/validate_constants.cpp
- test/val/val_constants_test.cpp
- test/val/val_extension_spv_khr_integer_dot_product_test.cpp
The constituent types much fully match, not just the opcode.
Fixes #3576
> Fix vector OpConstantComposite type validation

- DEPS
- source/val/validate_annotation.cpp
- source/val/validate_function.cpp
- source/val/validate_image.cpp
- source/val/validate_mode_setting.cpp
- source/val/validation_state.cpp
- test/text_to_binary.extension_test.cpp
- test/text_to_binary.type_declaration_test.cpp
- test/val/val_image_test.cpp
- test/val/val_modes_test.cpp
Adds the basic validation corresponding to https://github.com/KhronosGroup/SPIRV-Registry/pull/198 and https://github.com/KhronosGroup/SPIRV-Headers/pull/335
This requires the header PR to land first.
> Add support for SPV_EXT_shader_tile_image

- source/val/validate_image.cpp
* Execution model limitation was never executed and the check actually belongs with other opcodes
CC @y-novikov
> Remove dead code

- source/opt/const_folding_rules.cpp
- test/opt/fold_test.cpp
When some (not all) of the matrix columns are `OpConstantNull`
> opt: Fix null deref in `OpMatrixTimesVector` and `OpVectorTimesMatrix`

- CMakeLists.txt
This change updates CMakeLists.txt to support building for QNX platforms.
> spirv-tools: Add support for QNX

- source/opt/scalar_replacement_pass.cpp
- source/opt/scalar_replacement_pass.h
- source/opt/type_manager.cpp
- source/opt/types.cpp
- source/opt/types.h
- test/opt/scalar_replacement_test.cpp
- test/opt/types_test.cpp
We want to be able to apply scalar replacement on variables that have
the AliasPointer and RestrictPointer decorations.
This exposed a bug that needs to be fixed as well.
Scalar replacement sometimes uses the type manager to get the type id for the
variables it is creating. The variable type is a pointer to a pointee
type. Currently, scalar replacement uses the type manager when only if
the pointee type has to be unique in the module. This is done to try to avoid the case where two type hash to the same
value in the type manager, and it returns the wrong one.
However, this check is not the correct check. Pointer types still have to be
unique in the spir-v module. However, two unique pointer types can hash
to the same value if their pointee types are isomorphic. For example,
```
%s1 = …
```
> Apply scalar replacement on vars with Pointer decorations

- source/opt/convert_to_half_pass.cpp
- source/opt/convert_to_half_pass.h
- test/opt/convert_relaxed_to_half_test.cpp
An initial (and possibly overzealous) attempt at fixing #4814 
This currently just stops conversion to half when it's reading from a struct. This could lead to cases that could be optimised being missed - that would require checking the members of the struct to determine whether they're compatible with half.
> Don't convert struct members to half

- source/val/validate_interfaces.cpp
- source/val/validation_state.cpp
- test/val/val_interfaces_test.cpp
adds VUIDs for
> VUID-StandaloneSpirv-OpEntryPoint-08721
>
> Each OpEntryPoint must not have more than one Input variable assigned the same Component word inside a Location slot, either explicitly or implicitly
and
> VUID-StandaloneSpirv-OpEntryPoint-08722
>
> Each OpEntryPoint must not have more than one Output variable assigned the same Component word inside a Location slot, either explicitly or implicitly
> spirv-val: Label Interface Location/Component VUIDs

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
This PR extends logic in the SPIRV-Tools Optimizer.  When a ConstOffset of 0 would have been generated, offsetting is avoided entirely.
> Removes ConstOffset for 0 offsets

- .gitignore
- DEPS
- external/CMakeLists.txt
The latest version of RE2 requires Abseil. This PR adds Abseil as an
external dependence, and update RE2 to use it.
> Add Abseil as a dep and update RE2

- source/opt/const_folding_rules.cpp
- test/opt/fold_test.cpp
Two folding rules try to cast a constant to a MatrixConstant before
checking if it is a Null constant. This leads to the null pointer being
dereferneced. The solution is to move the check for zero earlier.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5063
> Check if const is zero before getting components.

- README.md
~~The readme say to run `git-sync-deps`. The following lines are redudant
because those repos will already be checked out.~~
I did not update the README after adding Abseil as a dep. This updates to README.
> Add Abseil dep to the README

- tools/sva/package.json
- tools/sva/yarn.lock
Depenabot is not able to update these deps to avoid security issues. I'm
updating all of them manually. This was done by running `yarn upgrade
--latest`. I do not claim to understand the changes to `yarn.lock`.
> Update deps in sva

- source/diff/diff.cpp
- test/diff/diff_files/different_decorations_fragment_autogen.cpp
- test/diff/diff_files/different_decorations_vertex_autogen.cpp
- test/diff/diff_files/different_function_parameter_count_autogen.cpp
- Consider prior type pairings when attempting to pair function parameters by type.
- Pair all parameters that have matching types, not just the first.
- Update diff tests.
Fixes #5218.
> Fix pairing of function parameters.

- source/val/validate_interfaces.cpp
- test/val/val_interfaces_test.cpp
Follow up to https://github.com/KhronosGroup/SPIRV-Tools/pull/5249
* glslang tests that physical storage buffer pointers can be used as
varyings in shaders
* Allow physical storage buffer pointers in IO interfaces as a 64-bit
type
> Allow physical storage buffer pointer in IO

- android_test/jni/Application.mk
- kokoro/scripts/linux/build-docker.sh
Vulkan was introduced in Android API 24.
Test that.
The Android NDK drops support for very old APIs.
> Increase tested Android API level

- source/val/validate_memory.cpp
- test/val/val_id_test.cpp
See https://github.com/KhronosGroup/SPIRV-Registry/issues/72
* OpenGL allowed uniforms to be declared with boolean types, but the validator was overly strict in disallowing it
> Allow OpTypeBool in UniformConstant

- .github/workflows/bazel.yml
In the latest windows images, MSVC is not installed in the default
directory, and bazel is not able to find it.  See
https://github.com/actions/runner-images/issues/7675. Because of that, I
will change the github action so that is uses windows-2019 instead of
latest.
At the same time, I merged the build and test commands for the different
platforms because they are now the same.
> Use windows 2019 to workaround bazel issue

- source/opt/inst_buff_addr_check_pass.cpp
- source/opt/inst_buff_addr_check_pass.h
- test/opt/inst_buff_addr_check_test.cpp
The length of a uvec3 was assumed to be 16 bytes, but it is 12. Sometimes the stride might be 16 bytes though, which is probably the source of the confusion.
Redo structure length to be the offset + length of the last member.
Add tests to cover arrays of uvec3s and uvec3 struct members.
Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5691
> instrument: Fix buffer address length calculations

- source/opt/constants.cpp
- source/opt/fold.cpp
- source/opt/fold.h
- source/opt/instruction.cpp
- source/opt/instruction.h
- test/opt/fold_test.cpp
This PR enables constant folding for vector types (Mentioned in https://github.com/KhronosGroup/SPIRV-Tools/issues/4913).
I ran the test suit and all test succeeded, but I could use some help to write up a new test case. I have this example HLSL code which can be massively reduced with SPIRV-Tools once this constant folding is enabled:
```hlsl
float4 PSMain() : SV_Target {
int4 A = int4(1, 2, 3, 4);
int4 B = int4(5, 6, 7, 8);	
int4 C = A + B;	
if (C.x == 6) { // This condition can be constant folded to true
return 1.0;
} else {
return 0.0;
}
}
```
DXC generates the following SPIR-V with `dxc -E PSMain -T ps_6_6 -spirv -O0 -Fo out.spv in.hlsl` (optimizations disabled):
```
OpCapability Shader
%1 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %PSMain …
```
> Enable vector constant folding

- CMakeLists.txt
- source/CMakeLists.txt
- test/tools/CMakeLists.txt
- test/tools/opt/CMakeLists.txt
From the 3.27 release notes:
The FindPythonInterp and FindPythonLibs modules, which have been deprecated since CMake 3.12, have been removed by policy CMP0148. Port projects to FindPython3, FindPython2, or FindPython.
closes #4145
> cmake: Use modern Python3 CMake support

- BUILD.bazel
- build_defs.bzl
The host transition migration is done so these can now be moved back and `exec_tools` can be removed.
> Migrate `exec_tools` back to `tools`.

- include/spirv-tools/instrument.hpp
- include/spirv-tools/optimizer.hpp
- source/opt/inst_bindless_check_pass.cpp
- source/opt/inst_bindless_check_pass.h
- source/opt/inst_buff_addr_check_pass.cpp
- source/opt/inst_debug_printf_pass.cpp
- source/opt/instrument_pass.cpp
- source/opt/instrument_pass.h
- source/opt/ir_builder.h
- source/opt/optimizer.cpp
- test/opt/inst_bindless_check_test.cpp
- test/opt/inst_buff_addr_check_test.cpp
- test/opt/inst_debug_printf_test.cpp
Simplify what we add to user code by moving most of it into a function that checks both that the descriptor index is in bounds and the initialization state. Move error logging into this function as well.
Remove many options to turn off parts of the instrumentation, because there were far too many permutations to keep working and test properly.
Combine Buffer and TexBuffer error checking. This requires that VVL set the length of TexBuffers in the descriptor input state, rather than relying on the instrumentation code to call OpImageQuerySize. Since the error log includes the descriptor set and binding numbers we can use a single OOB error code rather than having 4 per-type error codes.
Since the error codes are getting renumbered, make them start at 1 rather than 0 so it is easier to …
> instrument: Combine descriptor length and init state checking

- external/CMakeLists.txt
We currently add the abseil in the external/CMakeLists.txt. However, it
is not needed by spirv-tools directly. Instead we set effcee's variable
with the abseil source directory, and let effcee add it.
This will mean that abseil will be checked out only if effcee is
used. We currently get a few reports from people that use to only checkout
spirv-headers, and now get errors because abseil is missing.
> Have effcee add abseil subdirectory

- source/val/validate_decorations.cpp
- test/opt/inst_buff_addr_check_test.cpp
- test/val/val_decoration_test.cpp
Fixes #5282
* These pointers may not orginate from a variable so standard layout validation misses them
* Now checks every instructions that results in a physical storage buffer pointer
* May not start from a Block-decorated struct so that part is fudged with a valid layout
> Validate layouts for PhysicalStorageBuffer pointers

- android_test/Android.mk
SPIRV-Tools should build in c++17, but this file was forgotten.
Fixing the standard version.
> fix ndk build standard to c++17

- Android.mk
- source/wasm/build.sh
Figured I forgot some references. Naive sed this time, so we should be done.
> build: remove last references of c++11

- source/enum_set.h
- source/extensions.h
- source/val/validation_state.cpp
- test/enum_set_test.cpp
The current EnumSet implementation is only efficient for enums with values < than 64. The reason is the first 63 values are stored as a bitmask in a 64 bit unsigned integer, and the other values are stored in a std::set.
For small enums, this is fine (most SPIR-V enums have IDs < than 64), but performance starts to drop with larger enums (Capabilities, opcodes).
Design considerations:
----------------------
This PR changes the internal behavior of the EnumSet to handle enums with arbitrary values while staying performant.
The idea is to extend the 64-bits buckets sparsely:
- each bucket can store 64 value, starting from a multiplier of 64. This could be considered as a hashset with linear probing.
- For small enums, there is a slight memory overhead due to the bucket storage, but lookup …
> NFC: rewrite EnumSet to handle larger enums.

- utils/generate_registry_tables.py
Treat the input file as utf-8, and configure the XML parser to use the utf-8 encoding.
The Chromium build was breaking when trying to parse the XML file as ASCII.
> Treat spir-v.xml as utf-8

- source/assembly_grammar.cpp
- source/enum_set.h
- source/opt/feature_manager.cpp
- source/opt/feature_manager.h
- source/val/validate_capability.cpp
- source/val/validate_instruction.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/enum_set_test.cpp
This commit adds forward iterator, and renames functions to it matches the std::unordered_set/std::set better. This goes against the SPIR-V coding style, but might be better in the long run, especially when this set is used along real STL sets.
(Right now, they are not compatible, and requires 2 syntaxes).
This container could in theory handle bidirectional iterator, but for now, only forward seemed required for our use-cases.
> enumset: STL-ize container

- source/opt/instrument_pass.cpp
- test/opt/inst_bindless_check_test.cpp
This avoids errors like this from instrumenting vertex shaders:
```
error: 165: Expected Constituents to be scalars or vectors of the same type as Result Type components
%195 = OpCompositeConstruct %v4uint %uint_0 %191 %194 %uint_0
```
> instrument: Cast gl_VertexIndex and InstanceIndex to uint

- source/enum_set.h
- source/extensions.cpp
- source/opt/feature_manager.cpp
- source/opt/ir_context.cpp
- source/val/validate_instruction.cpp
- source/val/validation_state.cpp
- test/enum_set_test.cpp
- test/unit_spirv.h
EnumSet now supports iterators, meaning we can remove the custom ForEach.
> NFC: replace EnumSet::ForEach with range-based-for

- include/spirv-tools/libspirv.h
- source/binary.cpp
- source/diff/diff.cpp
- source/disassemble.cpp
- source/operand.cpp
- source/parsed_operand.cpp
- source/text.cpp
In https://github.com/KhronosGroup/SPIRV-Headers/pull/348
We are trying to add a new literal type called LiteralFloat.
This PR aims to add support in SPIR-V Tools to support this new type.
Thanks
> Add support for LiteralFloat type

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/mem_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
When using PhysicalStorageBuffer it is possible for a function to
return a pointer type. This was not being handled correctly in
GetLoadedVariablesFromFunctionCall in the DCE pass.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/5270.
> [spirv-opt] Handle OpFunction in GetPtr

- source/enum_set.h
Caused issues with vs2017, required for std::min.
> NFC: fix missing algorithm include in enumset file

- CMakeLists.txt
Work around a problem in CMake 3.22.1 in setting -std=c++17. Instead -std=c++11 is in effect for targets in test/*, but those targets require C++17.
Fixes: #5340
> Set cmake_policy CMP0128

- kokoro/scripts/linux/build-docker.sh
glslangValidator was renamed to glslang
(https://github.com/KhronosGroup/glslang/pull/3257). Fixing build.
> kokoro: rename glslang

- test/opt/CMakeLists.txt
This apparently is required for debug builds.
Fixes: #5335
> Add /bigobj to test_opt for VS 2017

- source/opt/feature_manager.h
- source/opt/ir_context.cpp
- test/opt/feature_manager_test.cpp
GetCapabilities returned a const*, and GetExtensions did not exist. This commit adds GetExtensions, and changes the return value to be a const&.
This commit also removes the overload to GetCapabilities which returns a mutable set, as it is unused.
> opt: change Get* functions to return const&

- source/enum_set.h
- test/enum_set_test.cpp
Expanding a bit the EnumSet API to have iterator-based insert and constructors (like the STL).
This is also a pre-requisite from the capability-trimming pass as it allows to build a const set from a constexpr std::array easily.
> enumset: add iterator based constructor/insert

- source/opt/const_folding_rules.cpp
- test/opt/fold_test.cpp
The code currently tries to get the value of the floating point constant
to see if it is -0.0. However, we are not able to get the value for
16-bit floating point value, and we hit an assert.
To avoid this, we add an early check for the width to make sure it is
either 32 or 64.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5413.
> Do not crash when folding 16-bit OpFDiv

- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/ir_context.h
- source/opt/passes.h
- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/CMakeLists.txt
- test/opt/trim_capabilities_pass_test.cpp
This commit adds a new optimization which tries to remove unnecessary capabilities from a SPIR-V module.
When compiling a SPIR-V module, you may have some dead-code using features gated by a capability.
DCE will remove this code, but the capability will remain. This means your module would still require some capability, even if it doesn't require it. Calling this pass on your module would remove obsolete capabilities.
This pass wouldn't be enabled by default, and would only be usable from the API (at least for now).
NOTE: this commit only adds the basic skeleton/structure and supports the ShaderClockKHR capability as initial example.
> opt: add capability trimming pass (not default).

- source/opt/convert_to_half_pass.cpp
- source/opt/convert_to_half_pass.h
- test/opt/convert_relaxed_to_half_test.cpp
Fixes image operands not decorated as relaxed from getting marked relaxed and converted to half precision.
Fixes #5044.
FYI @greg-lunarg @jeremy-lunarg.
>  opt: Fix incorrect half float conversion

- Android.mk
- BUILD.gn
PR #5278 added 2 new files, but they were not added to the BUILD.gn file. Fixing this.
Same for the Android.mk.
Fixes #5350
> build: fix missing files in BUILD.gn

- source/opt/inst_bindless_check_pass.cpp
- test/opt/inst_bindless_check_test.cpp
Multiple calls to this function were causing vkCreateGraphicsPipelines to be 3x slower on some drivers. I suspect this was because each call had to be inlined separately which bloated the code and caused more work in the driver's SPIRV -> native instruction compilation.
> instrument: Reduce number of inst_bindless_stream_write_6 calls

- source/opt/optimizer.cpp
This function was unused, so we missed the lack of definition.
Found-out when integrating with DXC.
> opt: fix missing CreateTrimCapabilitiesPass definition

- DEPS
- test/val/val_arithmetics_test.cpp
Test:
MatrixASignedComponentsKHR
MatrixBSignedComponentsKHR
MatrixCSignedComponentsKHR
ResultSignedComponentsKHR
> Update SPIRV-Headers; test some coop matrix enums

- .github/workflows/autoroll.yml
The autoroll workflow is currently failing due to being unable to find some depot_tools executables. This is due to a limitation in Go os/exec which effectively rejects all relative paths in PATH, and is exposed by a recent update to depot_tools
(https://crrev.com/43083529de5802a83f53f1d53d7f5f9615999996).
> Use absolute path to depot_tools

- source/assembly_grammar.cpp
- source/operand.cpp
- test/operand_capabilities_test.cpp
- test/val/val_image_test.cpp
A token is allowed to parse even when it's from the wrong version, or is not enabled by a capability or extension. This allows more modules to parse.
Version/capability/extension checking is fully moved to validation instead.
Fixes: #5364
> Move token version/cap/ext checks from parsing to validation

- include/spirv-tools/libspirv.h
- source/operand.cpp
* SPV_INTEL_global_variable_fpga_decorations
Spec: https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/INTEL/SPV_INTEL_global_variable_fpga_decorations.asciidoc
* SPV_INTEL_global_variable_host_access
Spec: https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/INTEL/SPV_INTEL_global_variable_host_access.asciidoc
This change follows headers change:
https://github.com/KhronosGroup/SPIRV-Headers/pull/356
> Support 2 Intel extensions

- include/spirv-tools/linker.hpp
- source/link/linker.cpp
- test/link/binary_version_test.cpp
- tools/link/linker.cpp
Currently spirv-link fails if all input files don't use the same SPIR-V version. Add an option to instead use the highest input version as the output version. Note that if one of the 'old' input files uses an opcode that is deprecated in the 'new' version, the output spirv will be invalid.
> linker: Add --use-highest-version option

- .github/workflows/scorecard.yml
- README.md
Closes #5369 
Hi, here is the configuration file for scorecard to run. It is also possible to enable the branch protection check to run by providing a fine-grained PAT to the workflow (which is much more safe than a classic PAT).
Also, feel free to wait for the resolution at https://github.com/KhronosGroup/glslang/issues/3299#issuecomment-1672085986 
Let me know if I can help with anything!
> Enable OpenSSF Scorecard and Badge

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
This is part of adding rasterizer ordered views to DXC. `OpBeginInvocationInterlockEXT` and `OpEndInvocationInterlockEXT` require only one of the capabilities `FragmentShaderPixelInterlockEXT`, `FragmentShaderSampleInterlockEXT`, or `FragmentShaderShadingRateInterlockEXT` to be enabled. Which capability is needed will be based on which execution mode is chosen, so this code uses that for the capability and ignores the begin and end opcodes.
> opt: add FragmentShader*InterlockEXT to capability trim pass

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
From the Capability's text in the SPIRV spec:
```
An MS operand in OpTypeImage indicates multisampled, used with an
OpTypeImage having Sampled == 2 and Arrayed == 1.
```
Adding this logic to the capability trimming pass.
> opt: add ImageMSArray capability to trim pass.

- source/opt/decoration_manager.h
The prototype does not match the implementation.
Fixes Typo in declaration DecorationManager::AddMemberDecoration #5392
> Fix `AddMemberDecoration` variable names.

- utils/update_build_version.py
When we are attempting to fetch the version info from the git repository, first check if we're actually in one, otherwise spurious errors messages get printed.
> Check for git repository before git commands

- DEPS
- include/spirv-tools/libspirv.h
- source/operand.cpp
- test/operand_capabilities_test.cpp
Update SPIRV-Headers, add cache control operand kinds
Adds SPV_OPERAND_TYPE_LOAD_CACHE_CONTROL
and  SPV_OPERAND_TYPE_STORE_CACHE_CONTROL,
from SPV_INTEL_cache_controls
Fixes: #5404
Update tests: remove Kernel from constant sampler enum dependencies
This corresponds to header change
https://github.com/KhronosGroup/SPIRV-Headers/pull/378
> Update SPIRV-Headers, add cache control operand kinds

- .github/workflows/autoroll.yml
For some reason the `gh` command to create a pull request with a team as
the reviewer is not working. That command works when I run it locally. I
don't know what the problem is, but I will just stop adding a reviewer.
Then anyone can look at it.
> Remove reviewer from autoroller

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/invocation_interlock_placement_pass.cpp
- source/opt/invocation_interlock_placement_pass.h
- source/opt/optimizer.cpp
- source/opt/passes.h
- test/opt/CMakeLists.txt
- test/opt/invocation_interlock_placement_test.cpp
DXC will be adding support for HLSL's rasterizer ordered views by using the [SPV_EXT_fragment_shader_interlock_extension](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/EXT/SPV_EXT_fragment_shader_interlock.asciidoc). That extension stipulates that if an entry point has an interlock ordering execution mode, it must dynamically execute `OpBeginInvocationInterlockEXT` and `OpEndInvocationInterlockEXT`, in that order, exactly once. This would be difficult to determine in DXC's SPIR-V backend, so instead we will emit these instructions potentially multiple times, and use this legalization pass to ensure that the final SPIR-V follows the specification.
This PR uses data-flow analysis to determine where to place begin and end instructions; in essence, determining whether a …
> Add a new legalization pass to dedupe invocation interlock instructions

- source/opt/inst_bindless_check_pass.cpp
- source/opt/inst_buff_addr_check_pass.cpp
- source/opt/optimizer.cpp
spirv-link requires that memory models match between its input files. Ensure this is the case by always returning SuccessWithChange and always changing the memory model to match the instrumentation code in Vulkan-ValidationLayers.
Also, disable the DCE pass in the --inst-* command line options, since it will only work after linking.
> instrument: Ensure linking works even of nothing is changed

- .github/dependabot.yml
- .github/workflows/autoroll.yml
- .github/workflows/bazel.yml
- .github/workflows/release.yml
- .github/workflows/wasm.yml
Closes #5410
Hi, I've hash pinned the actions (using step security tool) and configured the dependabot to run only on github actions and to group upgrades on a single PR.
> Hash pin workflows and config dependabot

- source/opt/fix_storage_class.cpp
- test/opt/fix_storage_class_test.cpp
The SPIR-V specification allows any scalar integer type as an index. DXC usually emits indexes as 32-bit integer types, however, in some cases it is possible to make it emit 64-bit indexes instead (as in https://github.com/microsoft/DirectXShaderCompiler/issues/5638).
> opt: support 64-bit OpAccessChain index in FixStorageClass

- utils/update_build_version.py
Return False instead of raising an exception when running git commands fail, which allows the script to fallback to alternative options.
Fixes #5469
> Support missing git in update_build_version.py

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
The StorageImageReadWithoutFormat capability is only required when an image type with the format set to Unknown is used with some specific OpImageRead or OpImageSparseRead instructions.
This patch adds the required code to the capability trimming pass to remove the StorageImageReadWithoutFormat capability when not required.
This would fix https://github.com/microsoft/DirectXShaderCompiler/issues/5906 once merged in DXC.
> opt: add StorageImageReadWithoutFormat to cap trim

- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
The PhysicalStorageBufferAddresses capability can now be trimmed. From the spec, it seems any instruction enabled by this required some operand to have the PhysicalStorageBuffer storage class. This means checking the storage class is enough.
Now, because the pass uses the grammar, we don't need to add any new logic.\
Fixes #5425
> opt: add PhysicalStorageBufferAddresses to trim

- utils/update_build_version.py
Python 3.12 on Fedora 39 is producing a deprecation warning about `datetime.utcfromtimestamp`.
See
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp for more details.
> Fix python warning seen on Fedora 39

- tools/io.h
The file mode is only actually respected when flushing the internal I/O buffers to the filesystem. By changing the file mode to text before flushing, the flush still ends up converting line endings, producing invalid output.
> Flush stdout before changing mode back to text

- source/opt/dead_insert_elim_pass.cpp
- test/opt/dead_insert_elim_test.cpp
I observed crashes in DXC that appeared after introducing an early out conditional branch to a HLSL shader that compiles to spirv.
The culprit is a nullptr access violation that occurs in spirv-opt when DXC tries to legalize its generated spirv code. The proposed change fixed the issue for me.
Please have a look and consider taking it in.
> spirv-opt: Fix nullptr argument in MarkInsertChain

- source/val/validate_extensions.cpp
- test/val/val_ext_inst_debug_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/5471
Problem: The base type operand for these instructions can be any DebugType instruction, but currently spirv-val forces it to be a DebugBasicType.
Solution: Change validator code to accept any DebugType instruction.
> spirv-val: Loosen restriction on base type of DebugTypePointer and DebugTypeQualifier

- CMakeLists.txt
- source/CMakeLists.txt
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/4437
> Fix iOS / Android CMake builds

- tools/fuzz/fuzz.cpp
- tools/reduce/reduce.cpp
Android's bionic library blows up on this, contrary to the standard.
If std::system can't find a shell, you already have bigger problems. Don't check specially for that condition. (That's the justification Android uses, and I'm not going to fight it.)
> Remove uses of std::system(nullptr)

- source/opt/instrument_pass.cpp
- test/opt/inst_bindless_check_test.cpp
This is an int and needs to be cast to a unit for inclusion in the stage specific data passed to the instrumentation check function.
> instrument: Fix handling of gl_InvocationID

- source/opt/optimizer.cpp
Certain versions of GCC warn about these variables being potentially uninitialized when used. I believe this is a false-positive, but zero-init'ing them is a safe way to fix this.
> Zero initialize local variables

- external/CMakeLists.txt
To build repository version from sources current cmake require to explicitly clone SPIRV-Headers repository to directory named 'external' with fixed name 'spirv-headers'.
This is a behavior which doesn't support searching global headers and also CMAKE_PREFIX_PATH which makes development in some environments less convenient than it should be.
The commit fixes this issue with keeping previous clone option intact.
> Fix(cmake): CMake doesn't find system installed SPIRV-Headers

- test/scripts/test_compact_ids.py
- utils/check_copyright.py
- utils/check_symbol_exports.py
- utils/fixup_fuzz_result.py
- utils/generate_changelog.py
- utils/generate_grammar_tables.py
- utils/generate_registry_tables.py
- utils/generate_vim_syntax.py
- utils/update_build_version.py
Some Linux images don't ship with a plain 'python'
> Use python3 explicitly.

- source/opt/ir_context.h
- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
Add the VulkanMemoryModelDeviceScope capability to the capability trimming pass. According the the spec, "If the Vulkan memory model is declared and any instruction uses Device scope, the VulkanMemoryModelDeviceScope capability must be declared." Since this case, based on the type of an operand, is not covered by the JSON grammar, it is added explicitly.
> opt: Add VulkanMemoryModelDeviceScope to trim

- DEPS
- source/opcode.cpp
- source/val/validate_mode_setting.cpp
- source/val/validate_non_uniform.cpp
- source/val/validate_scopes.cpp
- test/val/val_modes_test.cpp
- test/val/val_non_uniform_test.cpp
- tools/sva/src/spirv.data.js
1. Add two new execute modes: RequireFullQuadsKHR and QuadDerivativesKHR
2. Add two opCodes: OpGroupNonUniformQuadAllKHR and OpGroupNonUniformQuadAnyKHR
3. Add one Capability: QuadControlKHR
> SPV_KHR_quad_control

- test/CMakeLists.txt
Without this (or similar filtering), the `spirv-tools_expect_unittests` and `spirv-tools_spirv_test_framework_unittests` Python tests at `test/tools/` get defined even when `SPIRV_SKIP_TESTS` is set.
In downstream projects this show up as extra irrelevant tests:
> Skip entire test/ folder if SPIRV_SKIP_TESTS is set.

- source/opt/desc_sroa.cpp
- source/opt/desc_sroa.h
- test/opt/desc_sroa_test.cpp
Add OpEntryPoint to the list of instructions processed by the DescriptorScalarReplacement pass. This is necessary for SPIR-V 1.4 and above where global variables must be included in the interface.
Fixes microsoft/DirectXShaderCompiler#5962
> opt: Add OpEntryPoint to DescriptorScalarReplacement pass

- source/opt/convert_to_half_pass.cpp
- test/opt/convert_relaxed_to_half_test.cpp
When running the `ConvertToHalf` pass, an `OpCompositeExtract` instruction with a `OpTypeStruct` operand should not be demoted to half. This was (partially) fixed in #5201. However, that PR did not address a couple of scenarios:
1. The `OpCompositeExtract` instruction is explicitly decorated with `RelaxedPrecision`.
```
OpDecorate %9 RelaxedPrecision
%v4float = OpTypeVector %float 4
%_struct_6 = OpTypeStruct %v4float
%7 = OpUndef %_struct_6
...
%9 = OpCompositeExtract %float %7 0 3
OpReturn
```
2. The `OpCompositeExtract` instruction's usages are also relaxed (or it has no uses), so it is automatically decorated with `RelaxedPrecision`. See [this block in convert_to_half_pass.cpp](https://github.com/KhronosGroup/SPIRV-Tools/blob/c96fe8b943564fbab3424219d924d21cac2e877a/source/opt/convert_t …
> spirv-opt: Fix OpCompositeExtract relaxation with struct operands

- source/opt/block_merge_util.cpp
- test/opt/block_merge_test.cpp
The extension SPV_KHR_maximal_reconvergence adds more constraints around the merge blocks, and how the control flow can be altered.
The one we address here is explained in the following part of the spec:
>  Note: This means that the instructions in a break block will execute as if
>  they were still diverged according to the loop iteration. This restricts
>  potential transformations an implementation may perform on the IR to match
>  shader author expectations. Similarly, instructions in the loop construct
>  cannot be moved into the continue construct unless it can be proven that
>  invocations are always converged.
Until the optimizer is clever enough to determine if the invocation have already converged, we shall not meld a block which branches to a merge block into it, as it might …
> opt: prevent meld to merge block with MaximalReconvergence

- test/opt/fold_test.cpp
We repeat basicly the same code multiple times in the different types of
folding tests. This add a function that builds the module, finds the
instruction to fold, and folds it. Doing the routine checks at the same
time.
> [NFC] Refactor code to fold instruction in fold tests.

- source/val/validate_interfaces.cpp
- source/val/validation_state.cpp
- test/val/val_interfaces_test.cpp
It was decided in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6344 that `PhysicalStorageBuffer` should not be allowed to be in the `Input`/`Output` as it would greatly complicate the `Location` matching logic and there isn't strong testing (or any spec language) around all the edge cases currently... for those who still want to pass it between stages, the simple workaround is to just pass a `uint64`/`uvec2` between stages 
There is a tracker to fix the very few CTS coverage that might be violating this https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/4896
I assume there will be desire for a glslang change, but first wanted to get the `spirv-val` logic up
> spirv-val: Validate PhysicalStorageBuffer Stage Interface

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/optimizer.cpp
DXC does not do a good job of recognizing which variables need to be
on the entry point for which functions. This is because it does not
want to have to walk the call tree to determine which instructions
are reachable from which entry points.
This is also useful if the same input variable gets used from two
different shader, but the uses in one get optimized away.
Will parially fix
https://github.com/microsoft/DirectXShaderCompiler/issues/4621. Will not
fix code compiled with -fcgl.
> [OPT] Add removed unused interface var pass to legalization passes

- source/val/validate_memory.cpp
- test/val/val_id_test.cpp
- test/val/val_memory_test.cpp
Fixes https://crbug.com/oss-fuzz/66948
* Negative indices are invalid for struct access
* Fix typos
cc @spencer-lunarg
> Fix access chain struct checks

- source/operand.h
Flagged by `-Wredundant-decls`
I'm assuming the declarations in `libspirv.h` are part of the external interface and need to be kept.
Change-Id: I6b138d3322a7a4ee49ee33b0fbcf0ca35dd92261
> Remove redundant function declarations from `source/operand.h`

- source/opt/ir_context.cpp
- source/opt/ir_context.h
All tests treat kAnalysisEnd like STL end iterators, which means its value must be greater than that of the last valid Analysis.
Change-Id: Ibfaaf60bb450c508af0528dbe9c0729e6aa07b3b
> [OPT] Fix handling of analyses rebuild

- CMakeLists.txt
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4281
add_custom_target will run a command on every build, even when the output file doesn't need to be rebuilt. Using add_custom_command and specifying an output file for the command ensures that the output will only be regenerated when it's dependencies change, and we use a no-op custom target to require those outputs to be generated at least once.
This doesn't really change anything, but it does clean up the build output, particularly when taking in SPIRV tools as a subdirectory in a larger cmake project. It also changes the build output from something like:
``` 
"C:\Program Files\CMake\bin\cmake.EXE" --build e:/hotreload/build --config RelWithDebInfo --target all --
[2/2  50% :: 0.036] C:\WINDOWS\system32\cmd.exe /C "cd /D …
```
> Change CMake to avoid pkg-config file when there are no changes

- README.md
- docs/downloads.md
GitHub releases were just the exact same as the LunarG releases, since the same commit were used for both.
For this reason, we don't think it brings any value, and will stop publishing new releases on the GitHub page.
> docs: explain LunarG is the source of truth for releases

- source/opt/inline_pass.cpp
- test/opt/inline_test.cpp
Fix #5607
When inlining, decorate return variable with AliasedPointer if the storage class of the pointee type is PhysicalStorageBuffer.
> Add AliasedPointer decoration

- source/opt/type_manager.cpp
- source/opt/type_manager.h
- test/opt/type_manager_test.cpp
This fixes the problem reported in #5623 using the observation that if we are re-building a type that already exists in the type pool, we should just return that type.
This makes type rebuilding more efficient, and it also prevents the type builder from getting itself into infinite recursion (as reported in this issue).
In fixing this, I found a couple of other bugs in the type builder:
- When rebuilding an Array type, we were not re-building the element type. This caused stale type references in the rebuilt type.
- This bug had not been caught by the test, because the test itself had a bug in it: the test was rebuilding types on top of the same ID (the ID counter was never incremented).
Initially, the bug in the test caused a failure with the new logic in the builder because we now …
> Fix rebuilding types with circular references (#5623).

- source/opcode.cpp
- source/val/validate_annotation.cpp
- source/val/validate_decorations.cpp
- source/val/validate_memory.cpp
- test/val/CMakeLists.txt
- test/val/val_extension_spv_nv_raw_access_chains.cpp
Add support for https://github.com/KhronosGroup/SPIRV-Registry/pull/238 .
> Validator: Support SPV_NV_raw_access_chains

- source/fuzz/transformation_add_no_contraction_decoration.cpp
- source/fuzz/transformation_add_relaxed_decoration.cpp
- source/val/validate.cpp
- source/val/validate.h
- source/val/validate_decorations.cpp
- source/val/validate_interfaces.cpp
- source/val/validate_mode_setting.cpp
- test/fuzz/transformation_add_no_contraction_decoration_test.cpp
- test/fuzz/transformation_add_relaxed_decoration_test.cpp
- test/val/val_interfaces_test.cpp
- test/val/val_modes_test.cpp
Disallow duplicate decorations generally
* Only FuncParamAttr and UserSemantic can be applied to the same target
multiple times
* Unchecked: completely duplicate UserSemantic and FuncParamAttr
Disallow duplicate execution modes generally
* Exceptions for float controls, float controls2 and some intel
execution modes
* Checks that args must be different for these
Addresses Khronos SPIR-V issues 638 and 695.
> Validate duplicate decorations and execution modes

- source/val/validate_image.cpp
- test/val/val_image_test.cpp
This patch set fixes validation of decorations attached to
texture/sampler operands of OpImageBlockMatchWindowSSDQCOM and OpImageBlockMatchWindowSADQCOM
> A fix to support of SPV_QCOM_image_processing2

- include/spirv-tools/libspirv.h
- include/spirv-tools/libspirv.hpp
- include/spirv-tools/linker.hpp
- include/spirv-tools/linter.hpp
- include/spirv-tools/optimizer.hpp
In contrast to the C API, the C++ API did not have symbol visibility specified.  An application using the C++ API would fail to link against a shared SPIRV-Tools library built with `-fvisibility=hidden`; see e.g. https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2358
Mark all classes in the public `.hpp` files with `SPIRV_TOOLS_EXPORT`. Add `SPIRV_TOOLS_LOCAL` to hide nested structs containing implementation details.
> Add `SPIRV_TOOLS_EXPORT` to public C++ API

- source/val/validate_memory.cpp
- test/val/val_memory_test.cpp
Reject `OpCooperativeMatrixStoreKHR` with a `MakePointerVisibleKHR` MemoryAccess operand, as `MakePointerVisibleKHR` is not supposed to be used with store operations.
The `CoopMatKHRStoreMemoryAccessFail` test failed to catch this because it used the helper function `GenCoopMatLoadStoreShader` which generates `...NV` instead of `...KHR` instructions.  Add a new helper function to generate similar shaders for the KHR extension, as the NV and KHR extensions have various differences that makes parameterizing the original helper function non-trivial.
> spirv-val: Validate MemoryAccessMask of OpCooperativeMatrixStoreKHR

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
* Check for matrix decorations on arrays of matrices
* MatrixStide, RowMajor and ColMajor can be applied to matrix or arrays of matrix members
* Check that matrix stride satisfies alignment in arrays
cc @jrprice 
See https://crbug.com/339270841
> Improve matrix layout validation

- utils/git-sync-deps
The original code seems to forget to use the raw string mark, so Python is treating `\d` as an invalid escaped char (but still can parse the version correctly, idk why):
```
git-sync-deps:81: SyntaxWarning: invalid escape sequence '\d'
match = re.search("^git version (\d+)\.(\d+)",version_info)
```
This simple PR fixes this.
> Use raw string to avoid unintended escapes in regex

- source/val/validate_misc.cpp
- test/val/val_misc_test.cpp
The Scope operand of `OpReadClockKHR` was always validated using the Vulkan environment rules, which only allow `Subgroup` or `Device`. For the OpenCL environment, [`Workgroup` is also a valid Scope](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_cl_khr_kernel_clock), so `Workgroup` should not be rejected in the universal environment.
Guard the existing Scope check behind `spvIsVulkanEnv()` and add a new Scope check for the OpenCL environment.
> spirv-val: Consider target env for OpReadClockKHR scope

- utils/roll_deps.sh
The autoroller does not update abseil, and that it stopping us from
updating RE2. This change will update the auto roller, then the next
time it runs, we should be able to update everything.
> Add abseil to the autoroller

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
This removes the folding rules added in #4783 and #4808. They lead to
poor code generation on Adreno devices when 16-bit floating point values
were used. Since this change is transformation is suppose to be neutral,
there is no general reason to continue doing it.
I have talked to the owners of SwiftShader, and they do not mind if the
transform is removed. They were the ones the requested the change in the
first place.
Fixes #5658
> Do not fold mul and adds to generate fmas

- source/val/decoration.h
- source/val/validate_builtins.cpp
- source/val/validate_decorations.cpp
- source/val/validation_state.cpp
- test/val/val_decoration_test.cpp
From https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6625 (added in 1.3.285) (original issue https://github.com/KhronosGroup/SPIRV-Cross/issues/2313)
This adds 
- VUID-StandaloneSpirv-OpEntryPoint-09658
- VUID-StandaloneSpirv-OpEntryPoint-09659
> spirv-val: Add Duplicate EntryPoint Builtin check

- tools/val/val.cpp
The last three elements in the list of supported targets were misaligned:
```
Targets:
SPIR-V 1.0
SPIR-V 1.1
...
SPIR-V 1.3 (under Vulkan 1.1 semantics)
SPIR-V 1.4 (under Vulkan 1.1 semantics)
SPIR-V 1.5 (under Vulkan 1.2 semantics)
SPIR-V 1.6 (under Vulkan 1.3 semantics)
```
> spirv-val: Fix indentation of --version output

- source/opt/convert_to_sampled_image_pass.cpp
- source/opt/type_manager.cpp
We replace getting the id of a poitner type with a specific funciton
call to FindPointerToType. Also, FindPointerToType is updated to not
indirectly call GetId. This leads to a linear search for an existing
type in all cases, but it is necessary.
Note that this function could have a similar problem. There could be two
pointer types with the same pointee and storage class, and the first one
will be returned. I have checked the ~20 uses, and they are all used in
situations where the id is used to create something new, and it does not
have to match an existing type. These will not cause problems.
Part of #5691
> Remove implicit call to GetId in ConvertToSampledImagePass.

- source/val/decoration.h
Some platforms fail to compile if the cassert header is not included in
decoration.h. Adding it to make those work.
> Add assert header to val/decoration.h

- DEPS
- source/wasm/build.sh
- test/opt/aggressive_dead_code_elim_test.cpp
- test/opt/spread_volatile_semantics_test.cpp
Updates in line with https://github.com/KhronosGroup/SPIRV-Headers/pull/432.
Needs to wait until that PR is merged and deps are updated.
> update tests for disassembly changes

- DEPS
- source/opcode.cpp
- source/opcode.h
- source/operand.cpp
- source/opt/ir_context.h
- source/val/validate_adjacency.cpp
- source/val/validate_decorations.cpp
- source/val/validate_id.cpp
- source/val/validate_layout.cpp
- source/val/validation_state.cpp
- test/val/val_ext_inst_test.cpp
- test/val/val_extensions_test.cpp
- test/val/val_id_test.cpp
The KHR suffix was missing from the published SPIR-V extension. This is now fixed, but requires some patches in SPIRV-Tools.
> Add KHR suffix to OpExtInstWithForwardRef opcode.

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
PR #5648 added support for the GroupNonUniformPartitionedNV. But there was an issue: the opcodes are enabled by multiple capabilities, and the actual operand is what matters.
Added testing coverage and the implementation to correctly trim a few NonUniform capabilities.
Once merged in DXC, should address https://github.com/microsoft/DirectXShaderCompiler/issues/6672
> opt: fix Subgroup* trimming

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/opextinst_forward_ref_fixup_pass.cpp
- source/opt/opextinst_forward_ref_fixup_pass.h
- source/opt/optimizer.cpp
- source/opt/passes.h
- test/opt/CMakeLists.txt
- test/opt/opextinst_forward_ref_fixup_pass_test.cpp
This pass fixups the opcode used for OpExtInst instructions to use OpExtInstWithForwardRefsKHR when it contains a forward reference.
This pass is agnostic to the extension used, hence the validity of the code depends of the validity of the usage:
If a forward reference is used on a non-semantic extended instruction, the generated code will remain invalid, but the opcode will change. What this pass guarantees is valid code won't become invalid.
> opt: add OpExtInst forward ref fixup pass

- include/spirv-tools/libspirv.h
- source/disassemble.cpp
- source/disassemble.h
- source/opt/build_module.h
- test/binary_to_text.literal_test.cpp
- test/binary_to_text_test.cpp
- test/ext_inst.non_semantic_test.cpp
- test/test_fixture.h
- test/text_to_binary.annotation_test.cpp
- test/text_to_binary.composite_test.cpp
- test/text_to_binary.extension_test.cpp
- test/text_to_binary.memory_test.cpp
- tools/dis/dis.cpp
With --nested-indent, the SPIR-V blocks are nested according to the
structured control flow.  Each OpLabel is nested that much with the
contents of the block nested a little more.  The blocks are separated by
a blank line for better visualization.
With --reorder-blocks, the SPIR-V blocks are reordered according to the
structured control flow.  This is particularly useful with
--nested-indent.
Note that with --nested-indent, the disassembly does not exactly show
the binary as-is, and the instructions may be reordered.
> spirv-dis: Add --nested-indent and --reorder-blocks

- utils/generate_registry_tables.py
Those scripts are running on Python2.7 if build with the NDK tools. Under python2.7, io.open will load as "utf-8" since we give the encoding option, and return a "unicode" string.
Under Python3, the open() function will return a UTF-8 string. This means the XMLParser needs to have a different 'encoding' option depending on the python version.
For some reason I don't know, the XMLParser still fails if we use 'unicode' under Python2.7. But converting the unicode string to utf-8 does work.
> misc: fix encoding read for Python2.7

- BUILD.bazel
- MODULE.bazel
- WORKSPACE
This explicit dep was removed in #5707 but it is still used by the test library. Not sure why the Bazel build didn't catch the indirect dependence on another module but it is causing build failures downstream.
> Add re2 dep back to Bazel build

- source/disassemble.cpp
Fixing a clusterfuzz finding.
If the given binary has debug instruction which contained a badly formatted ANSI escape sequence, the iteration could go beyond the string length.
> [NFC] Fix potential buffer overflow

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/folding_rules.cpp
- source/opt/local_access_chain_convert_pass.cpp
- source/opt/local_single_block_elim_pass.cpp
- source/opt/local_single_store_elim_pass.cpp
- source/opt/mem_pass.cpp
- test/opt/fold_test.cpp
Some optimizations are not aware of cooperative matrices, and either do
nothing or assert. This commits fixes that up.
> Add knowledge of cooperative matrices

- utils/generate_grammar_tables.py
Insert a placeholder enum that is never valid.
This allows compilation to pass on MSVC, which doesn't like creating an array with explicit type elem[] but which has an empty initializer.
Bug: crbug.com/351140758
> Allow for empty list of enums for an operand

- source/val/validate_extensions.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_ext_inst_test.cpp
- utils/generate_grammar_tables.py
If SPV_EXT_relaxed_printf_string_address_space is enabled llvm-spirv allows the format argument to be in Generic space.  Also allow format argument to point to an array of i8 instead of only an i8.
> Allow fmt arg to printf to be an array of i8 in non-constant space

- source/binary.cpp
- test/binary_to_text_test.cpp
Without handling these operand types, disassembling a SPIR-V module that uses the cache control extension produces an invalid operand type error: "error: 33: Internal error: Unhandled operand type: 81".
> properly handle the load and store cache control operand types

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
When a trying to mark store that use the same address as a load live, we
consider any use of the pointer in the store instruction enough to make
the store live. This is not correct. We should only mark the store as
live if it store to the pointer, and not storing the pointer to another
memory location.
This causes DCE to miss some dead code.
> [opt] Fix pointer stores in DCE

- include/spirv-tools/linker.hpp
- source/link/linker.cpp
- test/link/matching_imports_to_exports_test.cpp
- tools/link/linker.cpp
Since llvm-17 there are no typed pointers and hte SPIRV-LLVM-Translator doesn't know the function signature of imported functions.
I'm investigating different ways of solving this problem and adding an option to work around it inside `spirv-link` is one of those.
The code is almost complete, just I'm having troubles constructing the bitcast to cast the pointer parameters to the final type.
If anybody here has any better ideas on how to fix this, please tell.
Some background:
Supporting this is useful for OpenCL implementations using SPIR-V binaries as the internal program representation and not using LLVM for backend compilation. `spirv-link` is used to link program objects together before handing it off into the backend compiler. It's just that llvm-17 dropping typed pointers broke …
> spirv-link: allow linking functions with different pointer arguments

- .github/workflows/wasm.yml
The wasm github action is using the deprecated `docker-compose` command.
This is update to use `docker compose`.
> Use "docker compose" in wasm build

- source/util/bitutils.h
> Workaround issue in MSVC arm64 compiler returning random upper 32-bits in function spvtools::util::CountSetBits.

- BUILD.bazel
I know I said I tested the Bazel rules back in [PR 5280](https://github.com/KhronosGroup/SPIRV-Tools/pull/5280#issuecomment-1601387655), however I must have done something wrong because the existing rules don't work on my Mac laptop (Mac host platform) when compiling using RBE (a Linux execution platform) for a Linux target platform. (This use-case didn't come up for some time, thus the delay in noticing/fixing).
I think this is because of the `local` flag. Having the `update_build_version` binary be listed in genrule's `tools` mean the python binary that runs the script is for `the exec configuration, since these tools are executed as part of the build` [citation](https://bazel.build/reference/be/general#genrule.tools), that is, the Linux RBE environment, however the rule is being run …
> Remove local attribute from build_version_inc genrule

- source/val/validate_memory.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
- test/val/val_memory_test.cpp
The specification requires the Stride operand for the RowMajorKHR and ColumnMajorKHR layouts.
Change-Id: I51084b9b8dedebf9cab7ae25334ee56b75ef0126
> Validate presence of Stride operand to OpCooperativeMatrix{Load,Store}KHR

- source/val/validate_image.cpp
- test/val/val_image_test.cpp
Reverts KhronosGroup/SPIRV-Tools#5695
Contributes to #5781 
SPIR WG 2024-09-04: decision to relax validation requirement in the spec.
> Revert "OpSampledImage extra validation"

- utils/update_build_version.py
FORCED_BUILD_VERSION_DESCRIPTION envvar can be used to force a version description instead of resorting to git describe which can change for a given commit if multiple lightweight commits point ot it.
This patch was needed to fix a non-reproducibility caused by git-describe while reproducibility testing in the Yocto Project: 
https://bugzilla.yoctoproject.org/show_bug.cgi?id=15567
> update_build_version.py: support an envvar to force the description

- source/val/validate_extensions.cpp
Allow `p` to be untyped pointer:
```
operand must be a pointer(p1, ...).If it is a typed pointer, it must point to data types.
```
https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_untyped_pointers.html#_modifications_to_the_opencl_std_extended_instruction_set
> [SPV_KHR_untyped_pointers] Fix verification of vload/vstore OpenCL.std instructions

- source/val/validate_image.cpp
- test/val/val_image_test.cpp
Fixes #5781
* Requires all image operands to match except for depth between operand and result
> Update sampled image validation

- source/val/validate_cfg.cpp
- test/val/val_cfg_test.cpp
Fixes #5784
* Rules only apply to structurally reachable blocks
> Do not check structurally unreachable continue target predecessors

- Android.mk
- BUILD.gn
- source/CMakeLists.txt
- source/name_mapper.cpp
- source/opt/inst_debug_printf_pass.cpp
- source/to_string.cpp
- source/to_string.h
- test/CMakeLists.txt
- test/to_string_test.cpp
Using the locale takes a mutex deep in the C++ library. Avoid this on hot compilation paths, e.g. in the validator.
Fixed: #5802
> Implement to_string(uint32_t) without using the locale

- source/opt/debug_info_manager.cpp
- test/opt/debug_info_manager_test.cpp
The code converting the global to local was generating an extra operand
that was incorrect. Fixed the code, and added a unit test.
Fixes #5776
> [OPT] Fix generating debugLocalVariable from debugGlobalVariable

- source/val/validate_extensions.cpp
- source/val/validate_memory.cpp
Allow `p` to be untyped pointer for `fract`, `frexp`, `lgamma_r`, `modf`, `remquo`, and `sincos`:
```
operand must be a pointer(p1, ...).If it is a typed pointer, it must
point to data types.
```
https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_untyped_pointers.html#_modifications_to_the_opencl_std_extended_instruction_set
Also fix check for module-scope variables.
> [SPV_KHR_untyped_pointers] Fix verification for OpenCL.std instructions

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- test/val/val_memory_test.cpp
Ensure that the validator rejects stores to objects of types
`OpTypeImage`, `OpTypeSampler`, `OpTypeSampledImage`,
`OpTypeAccelerationStructureKHR`, and arrays of these types, according
to `VUID-StandaloneSpirv-OpTypeImage-06924`.
Guard the check behind the before_hlsl_legalization option, as
sometimes we may have temporaries or local variables that are expected
to get optimized away.
Fixes #4796
> spirv-val: Disallow stores according to VUID 06924

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/local_access_chain_convert_pass.cpp
- source/opt/local_single_block_elim_pass.cpp
- source/opt/local_single_store_elim_pass.cpp
- source/opt/trim_capabilities_pass.h
- source/val/validate_derivatives.cpp
- source/val/validate_image.cpp
- test/val/val_derivatives_test.cpp
- test/val/val_image_test.cpp
Replace support for SPV_NV_compute_shader_derivatives with the new KHR (many lists had the vendor extension twice, replace one with the new KHR).
> Add support for SPV_KHR_compute_shader_derivative

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
We cannot apply the negate to an operand of an OpUDiv instead of it
result. This is because the operands of the OpUDiv are interpreted as
unsigned. We stop the optimizer from doing that.
There were no tests for distributing a negate into OpIMul, OpSDiv, and
OpUDiv. Tests are added for all of these.
Fixes #5822
> Do not distrubute OpSNegate into OpUDiv

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
The GLSL 450 InterpolateAt* instructions should be treated as a load by dead code elimination. This is part of https://github.com/microsoft/DirectXShaderCompiler/issues/3649.
> opt: Mark InterpolateAt* argument as live for DCE

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
The grammar does track required capabilities for extended instruction set operations, so we just need to look them up.
> opt: Add support for OpExtInst to capability trim pass

- source/opt/copy_prop_arrays.cpp
- test/opt/copy_prop_array_test.cpp
#5827 is broken for situations where a loaded value is stored to a pointer resulting from an `OpAccessChain`. Traverse access chains to find the original `OpVariable` to add to the worklist.
For https://github.com/microsoft/DirectXShaderCompiler/issues/6960
> opt: Fix array copy propagation of access chain pointers

- source/val/validate_cfg.cpp
- test/val/val_cfg_test.cpp
Fixes https://crbug.com/tint/372311599
* Stop using block depth in switch validation and instead use the more robust structured exit logic from the switch construct
* This is valid because the function has already handled the additional valid cases for case constructs
> Fix switch case construct validation

- .github/workflows/ios.yml
> The macOS 12 runner image will be removed by December 3rd, 2024.
> ...
> Jobs using the macos-12 YAML workflow label should be updated to macos-15, macos-14, macos-13, or macos-latest.
> ci: Update MacOS to latest OS

- BUILD.bazel
- BUILD.gn
- test/fuzz/CMakeLists.txt
- test/reduce/CMakeLists.txt
- tools/CMakeLists.txt
- tools/as/as.cpp
- tools/cfg/cfg.cpp
- tools/diff/diff.cpp
- tools/dis/dis.cpp
- tools/fuzz/fuzz.cpp
- tools/io.cpp
- tools/io.h
- tools/link/linker.cpp
- tools/opt/opt.cpp
- tools/reduce/reduce.cpp
- tools/val/val.cpp
In preparation for more code in that file, which would get unwieldy in a header.
> tools: Move io utils to cpp

- test/fuzz/fuzz_test_util.cpp
- tools/fuzz/fuzz.cpp
This CL updates the usage of JsonOptions which is deprecated to the newer JsonPrintOptions.
> Update proto JSON options call.

- source/val/validate_memory.cpp
The storage class restriction for `OpCooperativeMatrixLoadKHR` and `OpCooperativeMatrixStoreKHR` comes from the Vulkan specification; as such VUID 08973 should not be reported outside of Vulkan target environments.
> spirv-val: Report VUID 08973 only in Vulkan environments

- .github/workflows/bazel.yml
- .github/workflows/ios.yml
Recently we have found productivty slow down in other KhronosGroups repos because it can take hours for CI to run due to running out of Github Actions minutes. We have found that MacOS/iOS are charged as 10x the minute cost which really starts to add up. The goal is to not have those expensive CI actions run unless we know other things work first.
(There is an internal issue on this, but for short term, I have just been apply these types of YAML chanegs aroudn the repos https://gitlab.khronos.org/khronos-general/khronos-issues/-/issues/127)
> ci: Make MacOS builds only run if other things pass

- source/disassemble.cpp
- source/disassemble.h
- source/opt/folding_rules.cpp
- source/opt/loop_fission.cpp
- source/val/validate_decorations.cpp
- source/val/validate_function.cpp
- source/val/validate_non_uniform.cpp
- test/enum_set_test.cpp
- test/opt/ir_context_test.cpp
- test/opt/propagator_test.cpp
- test/opt/trim_capabilities_pass_test.cpp
- const for passed-by-value has no effect on prototypes.
- transitive includes.
- dead stores
- uses after move
> [NFC] Apply small clang-tidy fixes

- source/val/validate_id.cpp
- test/val/val_misc_test.cpp
Ensure valid `OpSizeOf` instructions are not rejected by spirv-val. Until now, validation of a valid `OpSizeOf` instruction would fail with the message that the operand "cannot be a type".
> spirv-val: Accept valid OpSizeOf instructions

- source/val/function.h
- source/val/validate_extensions.cpp
- source/val/validate_layout.cpp
- test/opt/inline_test.cpp
- test/opt/loop_optimizations/unroll_simple.cpp
- test/val/val_ext_inst_debug_test.cpp
Adds missing coverage for NonSemantic.Shader.DebugInfo.100 where it was different from `OpenCL.DebugInfo.100`
(Created 2 commits prior to reduce the copy-and-pasting in the tests)
> spirv-val: Add missing NonSemantic.Shader.DebugInfo.100

- external/CMakeLists.txt
- source/spirv_target_env.cpp
- source/spirv_target_env.h
- test/target_env_test.cpp
- tools/as/as.cpp
Assume the desired SPIR-V target version when the command line option is
not provided. This is especially important when the source being
assembled does not match the default (latest version), because it may
create an invalid SPIR-V binary result.
Also, clarify the wording for where a copy of spirv-headers is expected
(to match expected capitalization).
> spirv-as: Assume target from spvasm text

- tools/sva/yarn.lock
This change updates path-to-regexp, to address
https://nvd.nist.gov/vuln/detail/CVE-2024-45296
> Update path-to-regexp to address CVE-2024-45296

- CHANGES
- DEPS
This is the second release candidate for v2024.4. Includes new commits since September, including Vulkan 1.4 support.
> Prepare release

- source/spirv_target_env.cpp
- test/target_env_test.cpp
When trying to parse SPIR-V version from assembly comments, ensure a match against an initial comment doesn't cause the scanner to go back to the beginning of the assembly text.
Fixed: #5909
> assembler: ensure progress when seeking the version string

- source/val/validate_extensions.cpp
- test/val/val_ext_inst_debug_test.cpp
* In NonSemantic.Shader.DebugInfo.100, DebugLine validation should only check column end >= column start if line start == line end
See https://github.com/KhronosGroup/SPIRV-Registry/issues/302
cc @spencer-lunarg
> Relax DebugLine validation

- source/enum_set.h
- source/opt/optimizer.cpp
- source/val/function.h
This is to fix build error when we set use_libcxx_modules=true in chromium build.
> build: Add missing include headers

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
This PR stops the optimizer from removing OpSource instructions.  If an OpSource contains solely preprocessor instructions, it was being eliminated.  Debuggers cannot recompile shaders unless all OpSource instructions are present.
> opt: keep all OpSource instructions

- source/opcode.cpp
- source/val/validate_image.cpp
> Add OpImageSampleFootprintNV to IsAllowedSampledImageOperand

- README.md
- docs/downloads.md
- Point to MSVC from VS 2019 instead of defunct MSVC from VS 2017
- Rearrange the table and add badges to show build status.
- Update compiler versions in the README.
> Update downloads badges and matrix

- source/val/validate_builtins.cpp
- test/val/val_modes_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/5939
Allows Workgroup to be a vector of 64-bit int for OpenCL
> spirv-val: Fix Workgroup for 64-bit int with Kernel

- source/val/validate_annotation.cpp
- source/val/validate_builtins.cpp
- source/val/validate_decorations.cpp
- source/val/validate_instruction.cpp
- source/val/validate_mesh_shading.cpp
- source/val/validate_mode_setting.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_builtins_test.cpp
- test/val/val_mesh_shading_test.cpp
- test/val/val_modes_test.cpp
1. Each OpEntryPoint with the MeshEXT Execution Model can have at most one global OpVariable of storage class TaskPayloadWorkgroupEXT.
2. PerPrimitiveEXT only be used on a memory object declaration or a member of a structure type
3. PerPrimitiveEXT only Input in Fragment and Output in MeshEXT
4. Added Mesh vulkan validation support for following rules: VUID-Layer-Layer-07039 VUID-PrimitiveId-PrimitiveId-07040,VUID-PrimitivePointIndicesEXT-PrimitivePointIndicesEXT-07042, VUID-PrimitiveLineIndicesEXT-PrimitiveLineIndicesEXT-07048, VUID-PrimitiveTriangleIndicesEXT-PrimitiveTriangleIndicesEXT-07054, VUID-ViewportIndex-ViewportIndex-07060 VUID-StandaloneSpirv-ExecutionModel-07330 VUID-StandaloneSpirv-ExecutionModel-07331
For bug #4919
> Add EXT_mesh_shader validation support

- source/link/linker.cpp
- test/link/matching_imports_to_exports_test.cpp
I ran into issue with linker in OpenCl-CTS [tests for LinkOnceODR extension](https://github.com/KhronosGroup/OpenCL-CTS/blob/d99b302f901867fc1e5b196f5f6071c1dd0a10c1/test_conformance/spirv_new/test_linkage.cpp)
It didn't link 2 binaries:
[First](https://github.com/KhronosGroup/OpenCL-CTS/blob/d99b302f901867fc1e5b196f5f6071c1dd0a10c1/test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_obj.spvasm64#L11)
```
...
OpDecorate %a LinkageAttributes "a" LinkOnceODR
...
```
[Second](https://github.com/KhronosGroup/OpenCL-CTS/blob/d99b302f901867fc1e5b196f5f6071c1dd0a10c1/test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_noa_main.spvasm64#L16)
```
...
OpDecorate %a LinkageAttributes "a" Import
...
```
Linking failed with error `Unresolved external reference to "a".` so the issue was not …
> linker: fix LinkOnceODR handling

- source/opt/local_single_store_elim_pass.cpp
- test/opt/local_single_store_elim_test.cpp
When adding SPV_KHR_ray_tracing to the allow lists, we missed the list
in local-single-store-elim. Adding it now.
https://github.com/microsoft/DirectXShaderCompiler/issues/7063
> [OPT] Add SPV_KHR_ray_tracing to allow list

- source/cfa.h
- tools/util/flags.cpp
This is for C++ modules build in chromium.
> Add missing include headers

- source/val/validate_type.cpp
- test/val/val_decoration_test.cpp
- test/val/val_memory_test.cpp
* Strengthen the checks that Block/BufferBlock cannot be nested in another Block/BufferBlock
* previously missed arrays
* Add check that arrays containing a Block/BufferBlock must not be decorated with array stride
Relevant SPIR-V rules:
> Block and BufferBlock [decorations](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration) must not decorate a structure type that is nested at any level inside another structure type decorated with Block or BufferBlock.
(within the explicit layout rules)
> Each array type must have an ArrayStride [decoration](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration), unless it is an array that contains a structure decorated with Block or BufferBlock, in which case it must not have an ArrayStride decoration.
> More explicit layout validation

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
* Handle the case where an untyped pointer represents a descriptor array
* the array should not be required to have an array stride, but the element layout should be checked
> Fix layout checks with untyped pointers

- source/val/validate_memory.cpp
- test/val/val_id_test.cpp
- test/val/val_memory_test.cpp
Fixes #3263
* The checks relating to structure indexing used the index disassembly instead of the access chain making it difficult to determine where the actual error occurred
> Improve the instruction diagnostic for some access chain errors

- source/spirv_target_env.cpp
strncmp is used on the map to allow subset matching without having the subset explicitly defined in the map.
This however required the elements to be ordered in a specific way.
> spirv-val: fix env parsing for vk1.1spv1.4

- source/link/linker.cpp
- test/link/linker_fixture.h
- test/link/matching_imports_to_exports_test.cpp
Just a small oversight with the original fix of linkonce_odr. spirv-val complains about those decoration existing while the linkage capability is missing. However, simply removing it as we do with other linking specific decoration is easy enough.
Fixes: 17321728 ("fix: handle LinkOnceODR correctly (#5938)")
> linker: remove LinkOnceODR decorations when linking executables

- source/val/validate_memory.cpp
- test/val/val_memory_test.cpp
* OpPtrEqual and OpPtrNotEqual both allow mixed operands
* If both are typed they must be the same type
* If either is untyped they must match storage class
* OpPtrDiff must match operand types
> Fix untyped pointer comparison validation

- source/opt/ir_builder.h
- test/opt/ir_builder.cpp
The storage class operand was being added with the wrong operand type.  It was assumed to be an ID.  Then trying to analyze the new variable declaration instruction's defs and uses could get confused and assert out.
Added a test for this.
> [opt] Fix bug opt::InstructionBuilder::AddVariable

- kokoro/scripts/linux/build.sh
> kokoro: linux: use cpp-builder instead of radial-build

- source/opt/inline_exhaustive_pass.cpp
- source/opt/inline_pass.cpp
- source/opt/inline_pass.h
- source/val/validate_function.cpp
- test/opt/inline_test.cpp
When inlining, DXC can pass the result of an OpAccessChain as a
parameter. Even if this is not valid SPIR-V, HLSL allows this for the
`this` pointer in member function. Part of legalizing is to inline these
functions.
When this happens, the `var` operand on a debug declare for the parameter
will be replaced by the result of the OpAccessChain. This in invalid.
The debug declare needs the variable with the indexes.
This commit add a pass over each function after inlining that will fix
up the debug declares that are invalid in this way.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5191
> [OPT] Update DebugDeclare if the var is not an OpVariable

- source/val/validate_decorations.cpp
- test/fuzz/transformation_set_memory_operands_mask_test.cpp
- test/opt/inline_test.cpp
- test/val/val_builtins_test.cpp
- test/val/val_decoration_test.cpp
* Checks that Block, BufferBlock, Offset, ArrayStride, and MatrixStride are not used in a Vulkan environment in disallowed storage classes
> Add validation for invalid layout decoration usage

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
This commits adds support for StorageBuffer16BitAccess, which shares the same ID as StorageUniformBufferBlock16.
Fixes #5849
> [opt] Add StorageBuffer16BitAccess to trim pass.

- BUILD.gn
- docs/syntax.md
- source/text.cpp
- source/text_handler.cpp
- test/CMakeLists.txt
- test/op_unknown_test.cpp
We are adding support for `vk::SpirvType` to HLSL in Clang. This is a language feature that allows users to directly specify the SPIR-V opcode of a type they want to use in HLSL. Knowing the opcode, we can generate a valid binary directly. But LLVM also provides the option for producing text output, which is used for FileCheck tests that match regular expressions against that output. We do not have a way to generate SPIR-V assembly text for instructions with unknown opcodes.
We will also need this when we add support for HLSL’s `vk::ext_instruction`, which allows users to create functions representing arbitrary instructions.
> spirv-as: Add OpUnknown pseudo-instruction

- source/opt/copy_prop_arrays.cpp
- source/opt/ir_context.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
- test/opt/copy_prop_array_test.cpp
This PR fixes an issue where redundant OpCopyLogical copies are not removed by SPIRV-Tools-opt. OpCopyLogical is generated by default by glslang for conversions between types with potentially differing layouts in SPIR-V 1.4 and later, such as when reading uniform/storage buffers into local and/or function parameter variables.
When the following GLSL is compiled using glslang targeting SPIR-V 1.4 or later and then optimized by SPIRV-Tools-opt, the entire contents of the uniform buffer are copied into local memory even though only a small subset of the uniform buffer is actually read from. With the improvements in this PR, the unnecessary copy of the entire uniform buffer into local memory is removed, and the data is instead read directly from the uniform buffer itself.
````
#version 430 …
```
> Support optimization of OpCopyLogical

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Closes #6028.
Layout decorations on ptr types of allowed storage class shouldn't be as explicit layout decorations of struct types that uses it.
> Fix explicit layout validation on ptr type

- source/val/validate_interfaces.cpp
- test/val/val_decoration_test.cpp
- test/val/val_interfaces_test.cpp
Refs #5989
* Update input/output interface validation to treat arrays and matrices as consuming all 4 components in each location
This handles the removal of interleaving components among array/matrix elements.
> Update location/component conflict validation

- source/opt/split_combined_image_sampler_pass.cpp
- source/opt/split_combined_image_sampler_pass.h
- source/util/small_vector.h
- source/util/string_utils.h
- test/opt/split_combined_image_sampler_pass_test.cpp
- test/string_utils_test.cpp
If the original combined value has an OpName, then create names for the image and sampler parts by appending "_image" or "_sampler", respectively.
Bug: crbug.com/398231475
> split-combined-image-sampler: synthesize names

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/optimizer.cpp
- source/opt/passes.h
- source/opt/resolve_binding_conflicts_pass.cpp
- source/opt/resolve_binding_conflicts_pass.h
- test/opt/CMakeLists.txt
- test/opt/resolve_binding_conflicts_pass_test.cpp
- tools/opt/opt.cpp
Assumes the input is a valid Vulkan module.
A conflict exists when an entry point uses two variables with the same descriptor set and binding. Vulkan allows one kind of conflict: where the two variables are an image (array of images) variable and a sampler (array of samplers) variable.
The sampler variable's binding is incremented, and that increment ripples up through higher numbered bindings until no more conflicts remain.
Bug: crbug.com/398231475
> opt: add resolve-binding-conflicts pass

- source/opt/split_combined_image_sampler_pass.cpp
- test/opt/split_combined_image_sampler_pass_test.cpp
> split-combined-image-samplers: clone decorations on loads

- source/val/validate_decorations.cpp
- test/val/val_decoration_test.cpp
Fixes #6039
* Layouts can be out of order so ensure that runtime arrays are both the last member of the structure (already checked), but also largest offset (new check)
> Check that layouts match runtime array requirement

- source/val/validate_memory_semantics.cpp
- source/val/validation_state.cpp
- test/val/val_barriers_test.cpp
This commit aligns OpControlBarrier semantics validation with the Vulkan memory model. It disallows combining a relaxed memory order with non-zero storage class semantics in the Vulkan target environment. To my knowledge, this combination is not generated by any compiler.
> Validation for relaxed control barrier with storage class semantics

- source/opt/fold.cpp
Fixes: error: implicit conversion loses integer precision: 'int32_t' (aka 'int') to 'uint32_t' (aka 'unsigned int') [-Werror,-Wimplicit-int-conversion]
> Fix implicit conversion warning

- source/opt/value_number_table.cpp
- test/opt/pass_fixture.h
- test/opt/redundancy_elimination_test.cpp
- test/opt/value_table_test.cpp
Consider load yielding an image, sampler, or sampled image, to always have distinct value numbers.
This causes redundancy elimination avoid violating the 'single-block' rule:
All OpSampledImage instructions, or instructions that load an
image or sampler reference, must be in the same block in which
their Result <id> are consumed.
Note that this is strictly more than necessary: it would be ok to eliminate loads when they occur in the same basic block. This patch follows precedent where different OpSampledImage instructions are always given different value numbers.
Fixed: #6054
> opt: value numbering: preserve loads of image, sampler, sampled image

- source/val/validate_extensions.cpp
- source/val/validate_mode_setting.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
- test/val/val_arithmetics_test.cpp
- test/val/val_atomics_test.cpp
- test/val/val_barriers_test.cpp
- test/val/val_capability_test.cpp
- test/val/val_composites_test.cpp
- test/val/val_conversion_test.cpp
- test/val/val_image_test.cpp
- test/val/val_memory_test.cpp
- test/val/val_misc_test.cpp
- test/val/val_opencl_test.cpp
* SPV_KHR_vulkan_memory_model requires SPIR-V 1.3
* Additionally, validate that if Shader and CooperativeMatrixKHR are declared, VulkanMemoryModel must also be declared
> Validate version requirement for Vulkan Memory Model

- source/opt/trim_capabilities_pass.cpp
- test/opt/trim_capabilities_pass_test.cpp
When a type was recursive (or for the matter any instruction ID usage), the DFSWhile implementation would loop indefinitely. Added a history map to keep track of the visited instructions.
Required for https://github.com/microsoft/DirectXShaderCompiler/pull/7163
> [OPT] fix loop with recursive types in trim pass

- source/opt/local_single_store_elim_pass.cpp
The SPV_GOOGLE_user_type extension was not added to one of the allow
list. Adding it now.
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/7181.
> [OPT] Add extension to allow list

- source/val/validate_decorations.cpp
- source/val/validation_state.cpp
- test/val/val_decoration_test.cpp
Adds new `VUID-StandaloneSpirv-None-10684` VUID label from 1.4.312 headers
> spirv-val: Label new VUID from 312 headers

- source/val/validate_interfaces.cpp
The validation added in #6000 seems specific to Vulkan environments. Ensure it only runs for Vulkan environments.
> spirv-val: Restrict VUID 09557 to Vulkan environments

- source/opt/ir_loader.cpp
- source/opt/type_manager.cpp
- source/opt/type_manager.h
- source/opt/types.cpp
- source/opt/types.h
- test/opt/type_manager_test.cpp
- test/opt/types_test.cpp
* Added support for global OpUntypedVariableKHR in IRLoader
* Added support for untyped pointers as Pointer types using a null element
* Updates to type manager
* No specific pass allowances yet, but untyped pointers no longer break the whole pipeline
> Minimal opt support for SPV_KHR_untyped_pointers

- source/table.cpp
Compiling with `/GL` (Whole program optimization) and `/LTCG` (Link-time code generation) flags on MSVC 2022 causes an error/warning (depends if `/sdl` flag is also used) to be issued:
```
C:\Users\puma\.conan2\p\b\spirv2755296b2b5cb\b\src\source\table.cpp(60): error C4703: potentially uninitialized local pointer variable 'ext_inst_table' used [C:\Users\puma\.conan2\p\b\spirv2755296b2b5cb\b\bui
ld\source\SPIRV-Tools-shared.vcxproj]
LINK : fatal error LNK1257: code generation failed [C:\Users\puma\.conan2\p\b\spirv2755296b2b5cb\b\build\source\SPIRV-Tools-shared.vcxproj]
```
The code should actually be OK, as `spvExtInstTableGet` does check the same set of values for the `env` variable as is in the switch case above the modified code which does an early return.
> Fix compile error when compiling with whole program optimization enabled

- source/val/validate_type.cpp
- test/val/val_data_test.cpp
These should not require the Float16/Float16Buffer capabilities.
Change-Id: I3b50260ba634502befb36b6a67dac5961f102fa3
> spirv-val: fix validation of BFloat16 FP types

- CHANGES
Update the changes. DEPS will be updated by
https://github.com/KhronosGroup/SPIRV-Tools/pull/6091.
> Prepare for 2025.2 release.

- Android.mk
- BUILD.gn
- build_defs.bzl
- source/CMakeLists.txt
- utils/generate_grammar_tables.py
Remove the ability to emit C declarations for core instruction and operand tables.
Non-functional change
> generate_grammar_tables.py: remove unused option to emit C enums

- source/opt/folding_rules.cpp
- test/opt/fold_test.cpp
If values are not whole number, then the result is not 0. For example,
`(1.5 % 1.0) == 0.5`.
Fixes #6097
> [OPT] Don't fold n % 1.0

- utils/check_copyright.py
This allows something like: "Copyright 2025 Google LLC"
Also:
- update the current year.
- properly escape \ in the Python regular expression strings
> Allow copyright line without '(c)'

- source/val/validate_mode_setting.cpp
- source/val/validation_state.cpp
- test/val/val_modes_test.cpp
I noticed this VUID was altered, but I have zero idea how `TileShadingRateQCOM` work and leaving that up to the vendor if they wish to actually add tooling support for their vendor extensions
> spirv-val: Update 1.4.312 VUID churn

- tools/diff/diff.cpp
Trying to build SpirV with Clang-20 I have the following error which I find interesting.
```
[328/373] Building CXX object tools/CMakeFiles/spirv-diff.dir/diff/diff.cpp.o
FAILED: tools/CMakeFiles/spirv-diff.dir/diff/diff.cpp.o
/usr/bin/clang++-20 -DSPIRV_COLOR_TERMINAL -DSPIRV_TIMER_ENABLED -I/home/elvisdukaj/.conan2/p/b/spirv6b92024eb0385/b/src -I/home/elvisdukaj/.conan2/p/b/spirv6b92024eb0385/b/build/Release -I/home/elvisdukaj/.conan2/p/b/spirv6b92024eb0385/b/src/include -I/home/elvisdukaj/.conan2/p/spirva7c686f153c5c/p/include -m64 -stdlib=libc++ -O3 -DNDEBUG -std=c++26 -fPIE -Wextra-semi -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-self-assign -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -fno-exceptions -ftemplate-depth=1024 -MD -MT …
```
> fix clang-20 build issue

- source/util/index_range.h
- test/util/CMakeLists.txt
- test/util/index_range_test.cpp
Add spvtools::utils::IndexRange
It's a span, but without the base pointer.
Use the 'apply' method on a base pointer to generate a corresponding span.
> Add spvtools::utils::IndexRange

- Android.mk
- BUILD.bazel
- build_defs.bzl
- source/CMakeLists.txt
- source/ext_inst.cpp
- utils/generate_grammar_tables.py
Simplify ext inst table generation
Generate glsl.std.450 and opencl.std.100 extended instruction tables
the same way other vendor extended instruction tables are generated.
Also:
- Don't always assume operand_kinds exists
> Simplify extinst generation

- source/val/validate_capability.cpp
- test/val/val_capability_test.cpp
Until now, the Float16 capability was reported as not allowed under the various OpenCL environments.
> spirv-val: allow Float16 in OpenCL environments

- kokoro/dxc-smoketest/build.sh
- kokoro/dxc-smoketest/continuous.cfg
- kokoro/dxc-smoketest/presubmit.cfg
- kokoro/scripts/linux/build-docker.sh
New validation check in spir-val can identify invalid code generated by DXC.
This will generally only be caught when DXC or SPIR-V tools is imported into
Google3. This can take a while. Adding the smoke test will enable us to get an
early warning that DXC needs to be updated.
> [Kokoro] Add dxc-smoketest

- BUILD.gn
- source/table2.cpp
- source/table2.h
- Fix build.gn for recent updates in table generation
- GLSL and OpenCL extended instructions are generated like other vendor extended instruction sets
- Core table generation was reworked.  We don't need a GN template.
- Add more constructors for InstructionDesc and OperandDesc. The compiler didn't like the brace-initialization without a matching constructor with exactly the same parameters.
> Fixes for Dawn gn build.

- Android.mk
- BUILD.gn
- build_defs.bzl
- source/CMakeLists.txt
- source/table2.cpp
- source/table2.h
- test/opcode_lookup_test.cpp
- utils/ggt.py
The compressed tables content now goes to:
core_tables_headers.h, included by table2.h
core_tables_body.h, included by table2.cpp
Fixes: #6067
> Add instruction printingClass value to InstructionDesc

- source/assembly_grammar.cpp
- source/binary.cpp
- source/disassemble.cpp
- source/link/linker.cpp
- source/name_mapper.cpp
- source/opcode.cpp
- source/operand.cpp
- source/opt/feature_manager.cpp
- source/opt/replace_invalid_opc.cpp
- source/opt/trim_capabilities_pass.cpp
- source/table2.cpp
- source/table2.h
- source/text.cpp
- source/val/validate_capability.cpp
- source/val/validate_extensions.cpp
- source/val/validate_instruction.cpp
- source/val/validate_mode_setting.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/opcode_lookup_test.cpp
- test/opcode_require_capabilities_test.cpp
- test/operand_capabilities_test.cpp
- test/operand_lookup_test.cpp
- test/val/val_capability_test.cpp
- utils/ggt.py
Chromium bans static initializers of class objects.
Wrap the std::array static variables with a function that returns a reference to them.
This is option 2 to remove static initializers, at https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/static_initializers.md#Removing-Static-Initializers
Also, lookup methods update a pointer-to-const pointer.
> no static initializers

- source/table2.cpp
- source/table2.h
- utils/ggt.py
This avoids the C++ global initializers by making the constructors for OperandDesc and InstructionDesc constexpr. In turn, the std::array static variables over those types can be initialized at compile time, not at runtime.
This also avoids the implied mutex inside the function bodies.
> use static std::array for grammar tables again

- utils/ggt.py
Use sys.exit() instead.
Fixes: #6107
> Fix exit in ggt.py

- source/opt/redundancy_elimination.cpp
- source/opt/redundancy_elimination.h
Remove unnecessary recursion from redundancy elimination. This should
avoid potenitail stack overflows for function with deep dominator trees.
Fixes #6104
> [OPT] Remove recursion from redundancy_elimination

- utils/ggt.py
If a grammar change introduces a new optional operand kind, then currently the error message is very unfriendly.  It's a Python dictionary key error, with a call stack.
With this change, we get a single friendly error line like this, but all on one line:
error: unknown operand type SPV_OPERAND_TYPE_TENSOR_OPERANDS,
from JSON grammar operand 'TensorOperands':
consider updating spv_operand_type_t in spirv-tools/libspirv.h
> grammar tables: emit good error when missing an operand type

- source/opt/instruction.cpp
- source/opt/mem_pass.cpp
- test/opt/local_ssa_elim_test.cpp
The `MemPass::GetPtr` assumed that variable pointers were not used. So
if the pointer instruction was not a variable or function parameter, it
assumed it was something like an OpAccessChain. This is not correct with
variable pointers. It could be a load or a phi or other things.
This modifies the code the have a default case that assumes the base
variable could not be found. It will only return a variable id if it
recornizes all of the instructions.
Fixes #6157
> [OPT] Use conservative default case for `GetPtr`

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/optimizer_test.cpp
It is expected that no other instructions should refer to the DebugBuildIdentifier instruction, but this causes it to be removed during dead code elimination. Instead keep the instruction if it is found.
> Keep DebugBuildIdentifier during dce

- DEPS
- include/spirv-tools/libspirv.h
- source/binary.cpp
- source/name_mapper.cpp
- source/operand.cpp
- source/operand.h
- source/opt/types.cpp
- source/parsed_operand.cpp
- source/text.cpp
- source/text_handler.cpp
- source/text_handler.h
- source/util/hex_float.h
- source/util/parse_number.cpp
- source/util/parse_number.h
- source/val/validate_capability.cpp
- source/val/validate_conversion.cpp
- source/val/validate_interfaces.cpp
- source/val/validate_invalid_type.cpp
- source/val/validate_type.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/hex_float_test.cpp
- test/parse_number_test.cpp
- test/text_to_binary.extension_test.cpp
- test/val/val_conversion_test.cpp
- test/val/val_data_test.cpp
- test/val/val_extensions_test.cpp
- test/val/val_interfaces_test.cpp
- test/val/val_invalid_type_test.cpp
This also overhauls the number parsing code. It seems further work will be needed to correctly handle BFloat16. This change intends to leave the code no worse than it was. TODOs were added where relevant.
Co-authored-by: Guillaume Trebuchet <guillaume.trebuchet@arm.com>
Co-authored-by: Kevin Petit <kevin.petit@arm.com>
> Add initial support for SPV_EXT_float8

- DEPS
- test/val/val_data_test.cpp
The headers need updating to pick up
https://github.com/KhronosGroup/SPIRV-Headers/pull/519 which this test uncovered as an issue.
Change-Id: I79c292db6d2fbff6e31a7ccc9dfd4d65f4f49ab2
> spirv-val: add positive test for FP8 cooperative matrices

- .gitignore
- BUILD.bazel
- DEPS
- README.md
- external/CMakeLists.txt
- source/CMakeLists.txt
- source/diff/CMakeLists.txt
- source/fuzz/CMakeLists.txt
- source/mimalloc.cpp
- source/opt/CMakeLists.txt
- tools/CMakeLists.txt
- utils/roll_deps.sh
This is PR #6172 after resolving the conflict on DEPS
original comment from @daniel-story 
-----
This PR adds an option for SPIRV-Tools to use the mimalloc allocator to substantially improve the performance of memory allocation, especially in multithreaded operation. Because of this approach's overwhelming performance advantages in our extensive benchmarking and in production use with real world shaders, this option is enabled by default when building SPIRV-Tools as a dynamic library and when building the standalone executables (but is not enabled when building as a static library in order to avoid unexpected side effects on whatever the static libraries are statically linked to).
In profiling highly multithreaded (i.e., -j %NUMBER_OF_PROCESSORS%) compilation/optimization of complex, real …
> Add mimalloc to improve multithreaded performance

- Android.mk
- BUILD.gn
- include/spirv-tools/optimizer.hpp
- source/opt/CMakeLists.txt
- source/opt/canonicalize_ids_pass.cpp
- source/opt/canonicalize_ids_pass.h
- source/opt/optimizer.cpp
- source/opt/passes.h
- test/opt/CMakeLists.txt
- test/opt/canonicalize_ids_test.cpp
- tools/opt/opt.cpp
This is a port of the spirv-remap utility in glslang.
The canonicalize-ids pass is an optimization to improve compression of SPIR-V binary files via entropy reduction. It transforms SPIR-V to SPIR-V, remapping IDs. The resulting modules have an increased ID range (IDs are not as tightly packed around zero), but will compress better when multiple modules are compressed together, since the compressor's dictionary can find better cross module commonality. Remapping is accomplished via canonicalization. Thus, modules can be compressed one at a time with no loss of quality relative to operating on many modules at once.
This pass should be run after most optimization passes except for --strip-debug because this pass will use OpName to remap IDs. i.e. Run --strip-debug after this pass.
> Add --canonicalize-ids pass

- DEPS
- include/spirv-tools/libspirv.h
- source/binary.cpp
- source/disassemble.cpp
- source/operand.cpp
- test/text_to_binary.extension_test.cpp
- utils/ggt.py
The challenging part is that there are instructions that take zero or more Capability operands.  So we have to introduce SPV_TYPE_OPERAND_VARIABLE_CAPABILITY and SPV_TYPE_OPERAND_OPTIONAL_CAPABILITY.
Remove deprecated enums for the first and last variable or optional enums.
> SPV_INTEL_function_variants: basic asm, dis support

- source/opt/type_manager.cpp
- source/opt/types.cpp
- source/opt/types.h
- test/opt/type_manager_test.cpp
As specified by SPV_ARM_tensors.
Change-Id: I229ea1a3232eb04a4124363d1641218acb298ac4
> spirv-opt: add support for tensors to type manager

- source/val/validate_builtins.cpp
- source/val/validation_state.cpp
- test/val/val_builtins_test.cpp
Adds new ` VUID-StandaloneSpirv-TessLevelInner-10880`
> spirv-val: Add Patch Decoration check

- source/opcode.cpp
- source/val/validate_id.cpp
- source/val/validate_type.cpp
- test/val/CMakeLists.txt
- test/val/val_extension_spv_intel_inline_assembly.cpp
Previously, validating a module using the [SPV_INTEL_inline_assembly](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_inline_assembly.asciidoc) extension would fail. This PR fixes it.
> Add validation for SPV_INTEL_inline_assembly

- source/val/validate_memory.cpp
- test/opt/eliminate_dead_member_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_memory_test.cpp
* If a PtrAccessChain is rooted on a block, element (if constant) must
be zero
* UntypedAccessChains check that block arrays must not be reinterpreted
* Basic element operand checks for ptr access chains
> Extra restrictions for accesses of block arrays

- .github/workflows/bazel.yml
We have a github action that will create a new PR to udpate the
dependencies. Because this is done by a GH action, it will not trigger
the GH Actions to run the presubmits. To get them to run, I currently
close the PR, and then reopen it.
To make this easier, I'd like to have the presubmits be trigged by the
removal of the `kokoro:run` label. The work flow will become:
1. GH Action to create a new PR, and it adds the `kokoro:run` labal.
2. Kokoro will see the label, remove it and run the kokoro presubmits.
3. When the GH Action bot sees the label is removed, I expect it to run
the GH action presubmits.
4. Someone reviews the PR, and it will automerge of all of the tests
have passed.
> [GH Actions] Trigger when the `kokoro:run` label is removed

- .github/workflows/wasm.yml
I made a change to the bazel build to run when the label was removed:
https://github.com/KhronosGroup/SPIRV-Tools/pull/6230, but I did not
do it for the wasm build.
At the same time, I modified the wasm build to run on a push only if the branch is main. This matches the bazel build, and should run when we need it.
> [GH Actions] Run wasm build when kokoro:run is removed.

- source/val/validate_builtins.cpp
I broke the chromium build because I made a global static map, so just moved it inside the only spot it is used
> spirv-val: Fix using global static map

- source/CMakeLists.txt
I am currently running into the following issue when trying to build Vulkan CTS 1.4.3.1 (latest release of CTS) on macOS:
```
CMake Error in external/glslang/src/CMakeLists.txt:
The custom command generating
/Users/aitor/LunarG/builds/cts/main/debug/external/spirv-tools/spirv-tools/core_tables_body.inc
is attached to multiple targets:
spirv-tools-tables
core_tables
but none of these is a common dependency of the other(s).  This is not
allowed by the Xcode "new build system".
```
The command I use to run into this is the following:
```
cmake <path/to/cts> -GXcode -DCMAKE_BUILD_TYPE=Debug -DDEQP_TARGET=osx -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
```
OS version is: 15.4.1 (haven't updated to 15.5, but I expect the same issue there too)
This patch fixes the issue, but I am unsure if this …
> Fix xcode generation failure due to missing dependency

- source/val/validate_decorations.cpp
- test/val/val_data_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_image_test.cpp
- test/val/val_memory_test.cpp
- test/val/val_tensor_test.cpp
Extract the check out of buffer checks and make it generic so it matches VUID-6677 a bit better and applies to other variable types (e.g. OpTypeTensorARM).
Change-Id: I7ef7830ae55b3b402a20d9f786e8bd8a64e2263f
> spirv-val: validate DescriptorSet and Binding decorations for all relevant variables

- BUILD.gn
https://github.com/KhronosGroup/SPIRV-Tools/commit/bf98dd7287a5081f8c1a88b2dd003aa4e9487d05#diff-61d4552092a400db7dcdb41c965fc08429b58881fc86bc8f7e4e15c664490355 seems to never added the new file to BUILD.gn and causing VVL to fail to pull it in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10533
> linker: Fix BUILD.gn

- source/val/validate_memory.cpp
- source/val/validation_state.cpp
- source/val/validation_state.h
- test/val/val_memory_test.cpp
Adds `VUID-StandaloneSpirv-PhysicalStorageBuffer64-06314` (was recently `VUID-Runtime-PhysicalStorageBuffer64-06314`)
Glslang currently has some known issues allowing `Aligned` values that are lower than they should be allowed to be
> spirv-val: Validate PhysicalStorageBuffer Align are large enough

- source/opt/trim_capabilities_pass.cpp
- source/opt/trim_capabilities_pass.h
- test/opt/trim_capabilities_pass_test.cpp
Adds support to strip Geometry capability from a module when not used. The capability is required by other instructions, but all require the Geometry execution mode, meaning checking OpEntryPoint or OpConditionalEntryPointINTEL is enough.
2 tests are disabled for now: https://github.com/KhronosGroup/SPIRV-Tools/issues/6277
Related to https://github.com/microsoft/DirectXShaderCompiler/issues/7715
> spirv-opt: add Geometry capability to the trim pass

- source/opt/aggressive_dead_code_elim_pass.cpp
- source/opt/aggressive_dead_code_elim_pass.h
- source/opt/instruction.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
The spirv-opt ADCE pass currently does not mark NS100 DebugDeclare instructions as safe to delete.  A cursory review of ADCE results when NS100 is enabled shows that virtually no dead code is ever eliminated.  This is because DebugDeclare instructions are placed in the worklist during initialization.  When the worklist is processed, every operand referenced by all the DebugDeclares are then marked live as well.  So no blocks with a DebugDeclare can be eliminated.  This PR simply marks DebugDeclare as "safe to delete" at worklist initialization.  DebugDeclare's which should remain are still found when a live OpStore referencing them is processed on the worklist.  This change allows ADCE results when NS100 is enabled to approximate other levels of debug info, or no debug info.
> opt: Allow ADCE to kill DebugDeclare

- source/opt/trim_capabilities_pass.cpp
The grammar links the Geometry capability to the entrypoint operand, meaning the code I previously added is useless. Cleaning this up (tests are still there)
> spirv-opt: remove useless code

- source/val/validate_barriers.cpp
- source/val/validate_conversion.cpp
- source/val/validate_decorations.cpp
- source/val/validate_extensions.cpp
- source/val/validate_non_uniform.cpp
- source/val/validate_scopes.cpp
- test/val/val_conversion_test.cpp
- test/val/val_decoration_test.cpp
- test/val/val_interfaces_test.cpp
- test/val/val_mesh_shading_test.cpp
- test/val/val_non_uniform_test.cpp
basically someone on the Vulkan discord hit this case https://godbolt.org/z/M7n9YMsnG and didn't realize they needed to increase their `apiVersion` so VVL would pass it down
I have made improvements in VVL, but wanted to have all the errors in `spirv-val` that depend on a version, report that in the error message
> spirv-val: Print SPIR-V version info in error message

- source/disassemble.cpp
A previous refactoring of the code
(c3178da8eac9bc7d1788e95f8d555918ba483c23) accidentally broke coloring
of result ids, which this change fixes.
> spirv-dis: Fix missing color on result ID

- source/opt/merge_return_pass.cpp
- source/opt/merge_return_pass.h
The merge return pass can fail to create new basic blocks and
instructions if the module runs out of ids. This can lead to a crash.
This change modifies the pass to check if new ids can be created. If
not, the pass will be aborted for the current function.
> spirv-opt: Handle id overflow in merge return pass

- source/opt/trim_capabilities_pass.cpp
- test/opt/trim_capabilities_pass_test.cpp
In another PR I removed 2 handlers from the opcode handler arrays but forgot to resize the array. This causes the handler map to register 2 null function pointers for the opcode `OpNop` because its opcode is `0`.
DXC can end-up generating `OpNop` in some cases, causing the compiler to crash in those cases.
Added a test to catch this in the future.
> spirv-opt: fix trimming pass with OpNop

- source/opt/ir_context.cpp
- source/opt/loop_fission.cpp
- source/opt/loop_peeling.cpp
- source/opt/loop_peeling.h
- source/opt/loop_unswitch_pass.cpp
- source/opt/loop_unswitch_pass.h
- source/opt/loop_utils.cpp
- source/opt/loop_utils.h
- source/opt/ssa_rewrite_pass.cpp
- source/opt/ssa_rewrite_pass.h
Several loop passes can fail to create new instructions and basic
blocks if the module runs out of ids. This can lead to a crash.
This change modifies the passes to check if new ids can be created. If
not, the passes will be aborted and return a failure.
> spirv-opt: Handle id overflow in loop passes

- include/spirv-tools/libspirv.h
in libspirv.h is defined a constant `kDefaultMaxIdBound`. defining constants in headers is a bad practice, as it causes duplicate symbols if you include it in more than 1 compilation unit.
better solution, that will not cause this issue, would be to make it a compile-time macro.
> fix duplicate constant from libspirv.h

- source/val/validate_memory.cpp
- test/val/val_memory_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/6322
I want to get the crashing of CTS fixed, this still leaves a gap where things like `OpStore`/`OpCopyMemorySize` with invalid `Aligned` values will not be caught
> spirv-val: Fix GetLargestScalarType with untyped PSB

- source/opt/aggressive_dead_code_elim_pass.cpp
- test/opt/aggressive_dead_code_elim_test.cpp
ADCE was modifying an existing instruction in order to get the OpUndef.
This would leave the OpUndef in an invalid position. Even through it is
allowed for an OpUndef to be in a function. We are moving away from
that.
This commit create a new instruction for the OpUndef, and places it in
the right place.
Fixes #6316
> spirv-opt: Fix OpUndef placement in ADCE

- source/fuzz/transformation_inline_function.cpp
- source/fuzz/transformation_outline_function.cpp
- source/opt/basic_block.cpp
- source/opt/cfg.cpp
- source/opt/function.cpp
- source/opt/instruction.cpp
- source/opt/instruction.h
- source/opt/licm_pass.cpp
- source/opt/loop_descriptor.cpp
- source/opt/loop_descriptor.h
- source/opt/loop_fusion_pass.cpp
- source/opt/loop_fusion_pass.h
- source/opt/loop_peeling.cpp
- source/opt/loop_unroller.cpp
- source/opt/loop_unswitch_pass.cpp
- source/opt/loop_utils.cpp
- source/opt/loop_utils.h
- test/opt/loop_optimizations/fusion_legal.cpp
This CL modifies several loop transformation passes and their utility
functions to propagate failures, primarily caused by ID overflows when
creating new instructions or basic blocks.
Many functions that previously had a void return type now return a bool
or a status enum to indicate success or failure. The callers are updated
to check these return values and abort the transformation if a failure
occurs.
This affects loop unrolling, peeling, fusion, unswitching, and LICM,
as well as core IR cloning and manipulation functions.
The fuzzer transformations for inlining and outlining also get assertions
to detect cloning failures.
> spirv-opt: Propagate failures in loop transformations

- tools/val/val.cpp
In C++17 the type is std::string, in C++20 it's std::u8string. Then the .c_str() for both have incompatible types. Paper over this difference by copying to a std::string before invoking the helper function
> [tools/val] Paper over type change for std::filesystem::path::u8string

- source/opt/merge_return_pass.cpp
- source/opt/merge_return_pass.h
This CL adds error handling to the MergeReturnPass to gracefully handle cases where the pass runs out of IDs.
The following functions were modified to return a boolean indicating success or failure:
- AddNewPhiNodes
- AddReturnFlag
- AddReturnValue
- BranchToBlock
- CreatePhiNodesForInst
- ProcessStructuredBlock
- RecordReturned
- UpdatePhiNodes
The callers of these functions were updated to check the return value and propagate the failure. This prevents the pass from crashing when it runs out of IDs.
> spirv-opt: Handle id overflow in MergeReturnPass
