include/util/hex_float.h, source/binary.cpp
Also fixes VS2015 build due to missing #include <iterator>
=> Minor fixes to remove warnings in VS2013.

source/validate.cpp, source/validate_types.cpp
Fixes #53 
Not as clean but follows the Google style guide.
=> Remove static vector from GetModuleOrder

CMakeLists.txt, include/libspirv/libspirv.h, source/validate.cpp, source/validate_cfg.cpp, source/validate_instruction.cpp, source/validate_layout.cpp, source/validate_passes.h, source/validate_ssa.cpp, source/validate_types.cpp, source/validate_types.h, test/Validate.Layout.cpp
* Organize passes into seperate files
* Remove module layout logic from Cfg pass
* Remove module layout logic from Functions class
* Refactor ModuleLayoutPass for readability
* Adapt consistent naming of layout sections (Stage/Section -> Section)
=> Validation refactor

CMakeLists.txt, include/libspirv/libspirv.h, source/validate.h, source/validate_instruction.cpp, source/validate_types.cpp, test/Validate.Capability.cpp, test/ValidateFixtures.cpp
This PR adds capability registration and querying through the ValidationState_t class. 
* 5657 unit tests
* Capability checks for OpDecorate, OpVariable and OpTypeMatrix
Additional instructions will be added in future PRs
=> Capability tracking

source/validate_id.cpp, test/Validate.Layout.cpp, test/ValidateFixtures.cpp, test/ValidateID.cpp
Also ensure we don't get thrown off by too many parameters.
=> Eliminate parameter-order check from ID validation

tools/as/as.cpp, tools/val/val.cpp
This allows getting output from other utilities using pipe.
=> Support using stdin to supply input in as and val.

source/validate.h
=> Use unordered_map to store defs in UseDefTracker for fast lookup.

source/binary.cpp, source/diagnostic.cpp, source/text.cpp
=> Remove unnecessary null pointer checks

utils/update_build_version.py
Replaces use of subprocess.check_output
=> Use subprocess.Popen, hoping for Windows portability

utils/update_build_version.py
Address @dekimir's comments posted in #147.
=> Return str in describe() as said by the blurb.

source/text.cpp, source/text_handler.cpp, source/text_handler.h, test/TextToBinary.Miscellaneous.cpp, test/TextToBinary.cpp
=> Remove AssemblyContext::getWord().

CMakeLists.txt, source/print.cpp
Supports Shaderc https://github.com/google/shaderc/pull/169
=> Support Linux-to-Windows cross compile via MinGW

tools/as/as.cpp, tools/val/val.cpp
The spirv-dis command already supports both.
=> Support both -h, --help on spirv-as, spirv-val

source/text_handler.cpp, test/TextAdvance.cpp, test/TextToBinary.cpp, test/TextWordGet.cpp
Fixes #166.
@AWoloszyn @dneto0 @antiagainst @Qining PTAL.
=> Handle CRLF in assembly text.

source/extinst.glsl.std.450.grammar.json
* Add names to operands.
* Fix capability requirements for `UnpackDouble2x32`.
* Fix operands list error for `NClamp`.
=> GLSL grammar update.

README.md
=> Mention 1.1 support in the README.

source/spirv_definition.h, source/validate.h, source/validate_types.cpp
Turn module_capabilities_ into a spv_capability_mask_t.
=> Eliminate kCapabilitiesMin/Max.

utils/generate_grammar_tables.py
=> Make grammar-generation fail if over 64 capabilities.

test/TextToBinary.TypeDeclaration.cpp
=> Add OpSizeOf tests.

test/TextToBinary.ControlFlow.cpp
=> Add v1.1 tests for OpLoopMerge.

test/CMakeLists.txt, test/TextToBinary.PipeStorage.cpp
=> Add PipeStorage tests.

test/OperandCapabilities.cpp, test/TestFixture.h, test/TextToBinary.Annotation.cpp, test/Validate.Capability.cpp
=> Add tests for MaxByteOffset.

test/TextToBinary.Debug.cpp
@antiagainst @AWoloszyn @Qining @dneto0 PTAL.
=> Test OpModuleProcessed.

tools/CMakeLists.txt
=> Remove needless include dir for spirv-dis.

test/OperandCapabilities.cpp
=> Test ABGR in both 1.0 and 1.1.

.appveyor.yml, README.md
Tested and worked: https://ci.appveyor.com/project/antiagainst/spirv-tools
=> Add Appveyor configuration for Windows build.

source/validate_cfg.cpp
@umar456 @antiagainst @AWoloszyn @dneto0 @Qining PTAL
=> Avoid accessing invalid iterator.

source/validate_id.cpp, test/ValidateID.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/229
=> In physical addressing, functions can return pointers

source/CMakeLists.txt, source/opt/CMakeLists.txt, source/opt/basic_block.h, source/opt/function.cpp, source/opt/function.h, source/opt/instruction.cpp, source/opt/instruction.h, source/opt/module.cpp, source/opt/module.h, source/opt/reflect.h
The first offspring from #219.
=> Add classes for representing SPIR-V constructs in memory.

source/opt/CMakeLists.txt, source/opt/ir_loader.cpp, source/opt/ir_loader.h, source/opt/module.cpp, source/opt/module.h, test/CMakeLists.txt, test/opt/CMakeLists.txt, test/opt/opt_test_common.cpp, test/opt/opt_test_common.h, test/opt/test_ir_loader.cpp
=> Classes & tests for in-memory IR builder

source/opt/CMakeLists.txt, source/opt/pass_manager.h, source/opt/passes.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/pass_fixture.h, test/opt/pass_utils.cpp, test/opt/pass_utils.h, test/opt/test_pass_manager.cpp, test/opt/test_strip_debug_info.cpp, test/opt/test_utils.cpp
=> Add Pass, PassManager, and StripDebugInfoPass.

tools/CMakeLists.txt, tools/opt/opt.cpp
=> Add the spirv-opt command line tool.

source/validate_id.cpp, test/Validate.SSA.cpp
This is a workaround to https://github.com/KhronosGroup/SPIRV-Tools/issues/286 
It disables def-use dominance checks for OpPhi (variable,predecessor) arguments.
=> Phi dominance check

CHANGES, source/name_mapper.cpp, test/NameMapper.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/290
=> Never generate % for a friendly disassembled Id

CHANGES, source/validate_id.cpp, test/Validate.SSA.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/295
=> Only check def dominance of reachable uses

source/CMakeLists.txt, utils/update_build_version.py
Also with a face lifting commit.
=> update_build_version.py: create directory first if not existing and always refresh.

source/opt/passes.h
Add back the missing blurbs of pass: freeze-spec-consts
=> Add blurbs for freeze-spec-const pass

source/validate_cfg.cpp, test/Validate.CFG.cpp
Fixes dominance calculation when there is a forward arc from an
unreachable block A to a reachable block B.  Before this fix, we would
say that B is not dominated by the graph entry node, and instead say
that the immediate dominator of B is the psuedo-entry node of the
augmented CFG.
The fix:
- Dominance is defined in terms of a traversal from the entry block
of the CFG.  So the forward DFS should start from the function
entry block, not the pseudo-entry-block.
- When following edges backward during dominance calculations, only go to
nodes that are actually reachable in the forward traversal.
Important: the sense of reachability flips around when computing
post-dominance.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/297
=> Fix dominance calculation

CHANGES, README.md, tools/CMakeLists.txt, tools/cfg/bin_to_dot.cpp, tools/cfg/bin_to_dot.h, tools/cfg/cfg.cpp
This is experimental, and has not tests.
It's been used to debug validation of structured control flow.
=> Add spirv-cfg to dump a GraphViz graph of the CFG

source/opt/function.h, source/opt/ir_loader.cpp, source/opt/iterator.h, source/opt/module.h, source/opt/passes.cpp, source/opt/type_manager.cpp, test/opt/CMakeLists.txt, test/opt/test_iterator.cpp, test/opt/test_pass_manager.cpp
This PR depends on #322.
The third commit is interesting here.
=> Create an iterator class for in-memory representation.

source/opt/def_use_manager.cpp, source/opt/def_use_manager.h
This is to fix the bug in #336
=> Clear old def-use record when re-analyze an ID

source/val/ValidationState.cpp, test/Validate.Layout.cpp
=> OpUndef can appear in type declaration section(9)

CHANGES, utils/generate_grammar_tables.py, utils/update_build_version.py
Should fix https://github.com/KhronosGroup/SPIRV-Tools/issues/340
=> Avoid race on mkdir

source/opt/def_use_manager.cpp, source/opt/def_use_manager.h, source/opt/passes.cpp, source/opt/type_manager.h, test/opt/test_def_use.cpp
=> Make analyses RAII-like and turn disable copy/move constructors.

source/opt/libspirv.cpp, source/opt/make_unique.h, test/opt/pass_fixture.h, test/opt/test_iterator.cpp, test/opt/test_pass_manager.cpp, test/opt/test_types.cpp
@Qining PTAL.
Should also benefit your #324.
=> Add a home brewed make_unique to ease creating unique_ptrs.

CHANGES, source/validate_instruction.cpp, test/Validate.Capability.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/365 which
was reopened for this.
=> Mere mention of PointSize BuiltIn does not require Shader capability

CHANGES, README.md, tools/CMakeLists.txt, tools/lesspipe/CMakeLists.txt, tools/lesspipe/spirv-lesspipe.sh
Suggested by @steve-lunarg in issue 359.
=> Add spirv-lesspipe.sh

source/opt/instruction.h, test/opt/test_instruction.cpp
Refactored the instuction test.
=> Add Instruction begin and end mutable iterators

source/opt/CMakeLists.txt, source/opt/eliminate_dead_constant_pass.cpp, source/opt/eliminate_dead_constant_pass.h, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/opt/fold_spec_constant_op_and_composite_pass.h, source/opt/freeze_spec_constant_value_pass.cpp, source/opt/freeze_spec_constant_value_pass.h, source/opt/null_pass.h, source/opt/strip_debug_info_pass.cpp, source/opt/strip_debug_info_pass.h
Just refactoring. No new functionalities.
=> Create a separate header and source file for each pass.

source/opt/CMakeLists.txt, source/opt/build_module.cpp, source/opt/build_module.h, source/opt/libspirv.cpp, source/opt/libspirv.hpp, test/cpp_interface.cpp, test/opt/pass_fixture.h, test/opt/test_def_use.cpp, test/opt/test_ir_loader.cpp, test/opt/test_module.cpp, test/opt/test_type_manager.cpp, tools/opt/opt.cpp
=> 4. C++ interface for assembling, disassembling, & validating

source/opt/CMakeLists.txt, source/opt/build_module.cpp, source/opt/build_module.h, source/opt/eliminate_dead_constant_pass.cpp, source/opt/eliminate_dead_constant_pass.h, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/opt/fold_spec_constant_op_and_composite_pass.h, source/opt/freeze_spec_constant_value_pass.cpp, source/opt/freeze_spec_constant_value_pass.h, source/opt/null_pass.h, source/opt/optimizer.cpp, source/opt/optimizer.hpp, source/opt/pass.h, source/opt/pass_manager.cpp, source/opt/pass_manager.h, source/opt/set_spec_constant_default_value_pass.cpp, source/opt/set_spec_constant_default_value_pass.h, source/opt/strip_debug_info_pass.h, source/opt/unify_const_pass.cpp, source/opt/unify_const_pass.h, test/cpp_interface.cpp, test/opt/pass_fixture.h, test/opt/test_fold_spec_const_op_composite.cpp, test/opt/test_line_debug_info.cpp, test/opt/test_pass_manager.cpp, test/opt/test_unify_const.cpp, tools/opt/opt.cpp
Depends on #410.
A step towards addressing #2.
=> 5. C++ interface for optimization

CHANGES, CMakeLists.txt, README.md, include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, include/spirv-tools/optimizer.hpp, source/CMakeLists.txt, source/diagnostic.cpp, source/diagnostic.h, source/libspirv.cpp, source/message.h, source/opt/CMakeLists.txt, source/opt/build_module.cpp, source/opt/build_module.h, source/opt/libspirv.cpp, source/opt/libspirv.hpp, source/opt/optimizer.cpp, source/table.h, source/validate_cfg.cpp, test/BinaryParse.cpp, test/TextLiteral.cpp, test/cpp_interface.cpp, test/opt/CMakeLists.txt, test/opt/pass_fixture.h, test/opt/test_def_use.cpp, test/opt/test_ir_loader.cpp, test/opt/test_module.cpp
The user may not be able to control the input; it's performance defect to force making a `vector` from C array in cases.
Depends on #424.
=> Add some more overloads into the C++ interface

test/operand-class-test-coverage.csv
This will make the table beautiful and searchable on Github.
Autumn house cleaning no.2.
=> Fix operand class test coverage table missing column.

test/HexFloat.cpp
This will make it easier to port these tests to different contexts.
=> Remove unnecessary #include

CHANGES, test/TextToBinary.Extension.cpp
In assembler, disassembler, parser.
=> Test SPV_KHR_shader_draw_parameters support

examples/cpp-interface/CMakeLists.txt
Fixes Android build for vulkan-cts-1.0-dev
=> Skip building example executable when asked

CHANGES, README.md
Indicate it's future work to allow parameterization of those
limits.
=> Say how the validator checks universal limits

source/validate_id.cpp, test/val/val_id_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/482
=> An OpVariable initializer can be a module-scope variable

README.md, projects.md
So far I've only made a GitHub project for the Validator feature.
=> Document the use of the GitHub Project feature

test/val/val_id_test.cpp
Using parameterized unit tests to avoid duplicate code that runs the
tests of OpAccessChain and OpInBoundsAccessChain.
This is also a steppingstone to adding tests for OpPtrAccessChain and
OpInBoundsPtrAccessChain.
=> Refactoring unit tests

source/validate_id.cpp, test/val/val_id_test.cpp
Validation for OpPtrAccessChain is similar to OpAccessChain with the
following difference: OpPtrAccessChain takes an extra argument (word 4)
which is the Element <id> argument.
Validation for OpInBoundsPtrAccessChain is also similar to OpPtrAccessChain.
Also added tests for all access chain instructions:
Modified the existing parameterized tests to accommodate OpPtrAccessChain and
OpInBoundsPtrAccessChain.
Also fixed a typo in previous commits.
=> Adding validation code for PtrAccessChain.

utils/update_build_version.py
see https://reproducible-builds.org/ for why this is good
=> make build reproducible

README.md
=> Add vim-spirv plugin description to the README

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, source/diagnostic.cpp, source/libspirv.cpp, source/message.cpp, test/cpp_interface_test.cpp, tools/val/val.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/568
=> spirv-val prints info and warning messages to stdout

CHANGES, README.md, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/basic_block.cpp, source/opt/basic_block.h, source/opt/build_module.cpp, source/opt/function.cpp, source/opt/function.h, source/opt/inline_pass.cpp, source/opt/inline_pass.h, source/opt/instruction.h, source/opt/iterator.h, source/opt/module.cpp, source/opt/module.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/types.cpp, test/opt/CMakeLists.txt, test/opt/inline_test.cpp, test/opt/pass_fixture.h, tools/opt/opt.cpp
Tiny fixup for https://github.com/KhronosGroup/SPIRV-Tools/pull/534
I'm not looking for a code review. :-)
=> Dneto inline from mr534 by greg lunarg

source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h
Also add a method comment for it.
=> Fix typo in method name Struct::AddMemberName

CHANGES, source/opt/optimizer.cpp, test/opt/CMakeLists.txt, test/opt/optimizer_test.cpp, tools/opt/opt.cpp
This builds on https://github.com/KhronosGroup/SPIRV-Tools/pull/612
=> Spirv opt uses optimizer class

CMakeLists.txt, examples/CMakeLists.txt, examples/cpp-interface/CMakeLists.txt, external/CMakeLists.txt, source/CMakeLists.txt, source/opt/CMakeLists.txt, test/CMakeLists.txt, tools/CMakeLists.txt
=> Group targets into folders

source/opt/module.cpp
=> Remove unused this in lambda capture

.appveyor.yml, .travis.yml
=> Bots print output from timed out tests

test/opt/aggressive_dead_code_elim_test.cpp, test/opt/insert_extract_elim_test.cpp, test/opt/local_access_chain_convert_test.cpp, test/opt/local_single_block_elim.cpp
This is a follow-up to support for opaque types.
=> Opt: Add opaque tests for "size" passes

CMakeLists.txt, README.md
For addressing https://github.com/Microsoft/DirectXShaderCompiler/pull/529
=> Support supplying extra definitions via CMAKE variable

CHANGES, tools/as/as.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/798
=> spirv-as: Fail for unrecognized long option

source/opt/local_ssa_elim_pass.cpp, source/opt/local_ssa_elim_pass.h
Fixes crash reported in issue #824
=> ElimLocalMultiStore: Reset structured successors for each function

source/validate_bitwise.cpp
=> No use to check OpBitCount result width

test/val/val_id_test.cpp
The check already existed.  I added a test for it.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/876
=> Validator: Test OpReturnValue type check

source/opt/eliminate_dead_constant_pass.cpp, source/opt/ir_loader.cpp, source/opt/module.cpp, source/opt/module.h, source/opt/reflect.h, source/opt/strip_debug_info_pass.cpp, test/opt/ir_loader_test.cpp, test/opt/strip_debug_info_test.cpp
This is a recent decision from the SPIR WG.  The spec update
has not yet been published.
Khronos SPIR-V internal issue 199
=> Optimizer: OpModuleProcessed is in its own layout section

source/opt/reflect.h
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/911
=> Optimizer: Line and NoLine are not debug1 or debug2

.travis.yml
Pushing a commit to the master branch will trigger a build on
Travis. If the build is successful, the artifacts will be
collected and pushed to GitHub Releases, under the "master-tot"
release.
=> Travis: auto deploy build artifacts to GitHub Releases

test/opt/propagator_test.cpp
This will fix the windows bots (https://travis-ci.org/KhronosGroup/SPIRV-Tools/jobs/308381700)
=> Fix windows build. unsigned vs signed comparison in EXPECT_EQ.

CONTRIBUTING.md
I'm about to change this file.  I re-formatted it for easier editing.
=> Re-format CONTRIBUTING.md - NFC.

source/validate_image.cpp, test/val/val_image_test.cpp
Applied some of the spec clarifications made in conversation with
@johnkslang.
=> Fix some of the known issues in image validation

.travis.yml, utils/check_code_format.sh
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1029
=> Travis CI: add clang-format check

Android.mk, source/CMakeLists.txt, source/validate.cpp, source/validate.h, source/validate_composites.cpp, source/validate_id.cpp, test/val/CMakeLists.txt, test/val/val_composites_test.cpp, test/val/val_id_test.cpp
Validates instructions in the opcode range from OpVectorExtractDynamic
to OpTranspose.
=> Add composite instruction validation pass

tools/opt/opt.cpp
The option --skip-validation is added.  When used it will skip the
validation step.
Also rearranged the help text to fix two options that are out of order.
Implements issue #1068.
=> Add option to spirv-opt to skip the validator.

source/validate_composites.cpp, test/val/val_composites_test.cpp
Vulkan CTS fix has been submitted.
=> Reenable OpCopyObject validation rules

.appveyor.yml
VS 2017 is the newest compiler, with the most interesting feedback.
Place it first so we get its feedback first.
=> AppVeyor: Put VS 2017 first

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/propagator.h
This addresses the review comments from #985.
=> Address review comments from #985

source/opt/basic_block.h
=> Fix method comment for BasicBlock::MegeBlockIdIfAny

source/opt/common_uniform_elim_pass.cpp, test/opt/common_uniform_elim_test.cpp
* Addresses #1203
* Increments inIdx in IsConstantIndexAccessChain
* added test to catch the bug
=> Fixes missing increment in common uniform elim

tools/dis/dis.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1170
=> spirv-dis: Add --color option to force color disassembly

source/opt/fold.cpp, test/opt/fold_test.cpp
The folding routines are suppose to use the id_map provided to map the
ids in the instruction.  The ones I just added are missing it.
=> Use id_map in Fold*ToConstant

source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h
The loop descriptor must explicitly manage the storage for contained
Loop objects.
Fixes #1262
=> VS2013: LoopDescriptor LoopContainerType can't contain unique_ptr

source/opt/fold.cpp, source/opt/fold.h, source/opt/instruction.cpp, source/opt/instruction.h, test/opt/ccp_test.cpp
=> Get CCP to use the constant floating point rules.

source/opt/dead_branch_elim_pass.cpp, test/opt/dead_branch_elim_test.cpp
In dead branch elimination, we already recognize unreachable continue
blocks, and update OpPhi instruction accordingly.  This change adds an
extra check: if the head block has exactly 1 other incoming edge, then
replace the OpPhi with the value from that edge.
Fixes #1314.
=> Simplify OpPhi instructions referencing unreachable continues

source/opt/mem_pass.cpp, source/opt/mem_pass.h
On some shader code we have in our testsuite, Phi insertion is showing
massive compile time slowdowns, particularly during destruction.  The
specific shader I was looking at has about 600 variables to keep track
of and around 3200 basic blocks.  The algorithm is currently O(var x
blocks), which means maps with around 2M entries.  This was taking about
8 minutes of compile time.
This patch changes the tracking of stored variables to be more sparse.
Instead of having every basic block contain all the tracked variables in
the map, they now have only the variables actually stored in that block.
This speeds up deallocation, which brings down compile time to about
1m20s.
Note that this is not the definite fix for this.  I will re-write Phi
insertion to use a standard SSA rewriting algorithm …
=> Speed up Phi insertion.

source/opt/inline_pass.cpp
When inlining a function call the instructions in the same basic block
as the call get cloned.  The clone is added to the set of new blocks
containing the inlined code, and the original instructions are deleted.
This PR will change this so that we simply move the instructions to the
new blocks.  This saves on the creation and deletion of the
instructions.
Contributes to #1328.
=> Reduce instruction create and deletion during inlining.

source/opt/const_folding_rules.cpp, source/opt/folding_rules.cpp, test/opt/fold_test.cpp
Adds rule to fold OpVectorShuffle with constant inputs.
Adds rules to fold OpCompositeExtrac being fed by an OpVectorShuffle.
=> Add more folding rules for vector shuffle.

source/opt/ccp_pass.cpp, test/opt/ccp_test.cpp
Fixes #1361
* Mark all non-compile time constant global values as varying
* Mark function parameters as varying
* Conservatively mark assignment instructions as varying if any input is
varying after attempting to fold
* Added a test to catch this case
=> Fix CCP handling of global values

Android.mk, README.md, include/spirv-tools/libspirv.h, source/CMakeLists.txt, source/ext_inst.cpp, source/opcode.cpp, source/operand.cpp, source/spirv_target_env.cpp, source/table.cpp, test/binary_header_get_test.cpp, test/binary_to_text_test.cpp, test/target_env_test.cpp, test/text_to_binary.extension_test.cpp, test/unit_spirv.h, tools/as/as.cpp, tools/dis/dis.cpp, tools/opt/opt.cpp, tools/val/val.cpp
This requires the latest SPIRV-Headers that supports SPIR-V 1.3.
=> Support SPIR-V 1.3 and Vulkan 1.1

source/opt/folding_rules.cpp
=> Fix InsertFeedingExtract rule when extract remains.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp
Fixes #1404
Added test. Checked against testcase in #1404.
=> Don't DCE workgroup size

source/opt/types.cpp, test/opt/types_test.cpp
=> Removing assertion against void pointer

source/opt/copy_prop_arrays.h
=> Preserve analyses after copy propagate arrays

source/opt/mem_pass.cpp, source/opt/mem_pass.h
Since the SSA rewriter was added, the code old phi insertion code is no
longer used.  It is going stale and should be deleted.
=> Delete unused code in MemPass

source/validate_builtins.cpp, test/val/val_builtins_test.cpp
Fixes #1470
* Removed restriction that workgroup size can only be on Input storage
class
* added test
=> Don't restrict WGS storage class

source/validate_builtins.cpp, test/val/val_builtins_test.cpp
Fixes #1472
Relaxes checks for per-vertex builtin variables. If the builtin
decoration is applied to a variable, then those checks now allow a level
of arraying on the variable before checking the type consistency.
To maintain some strictness on stages that allow per-vertex variables, I moved these checks into the reference checking methods where the execution model is available.
* Allows arrays of variables to be present for the per-vertex variables:
* Position
* PointSize
* ClipDistance
* CullDistance
* Updated tests
* Breaks a few type checking functions into two entries and a helper
=> Per-vertex variable validation fixes.

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
Let `OpFNegate` against a constant be the negative of the operand.
Contributes to #709.
=> Add constant folding for FNegate

source/opcode.h, source/opt/optimizer.cpp
This should have been part of the previous PR that introduced vector DCE.  It address @greg-lunarg comments.
=> Add Dead insert elmination back in.

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
If there is a shader with a variable in the workgroup storage class that
is stored to, but not loadeds, then we know nothing will read those
loads.  It should be safe to remove them.
This is implemented in ADCE by treating workgroup variables the same
way that private variables are treated.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1550.
=> Remove dead Workgroup variables in ADCE.

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
ADCE does not treat OpCopyMemory as an instruction that references
memory.  Because of that stores are removed that should not be.
This change teaches ADCE that OpCopyMemory and OpCopyMemorySize both
loads from and stores to memory.  This will keep other stores live when
needed, and will allows ADCE to remove OpCopyMemory instructions as
well.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1556.
=> Get ADCE to handle OpCopyMemory

source/opt/inline_pass.cpp, test/opt/inline_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1591.
=> Add store for var initializer in inlining.

source/opt/vector_dce.cpp, test/opt/vector_dce_test.cpp
Fixes #1634
* Vector components of composite constructs used wrong accessor
=> Use type id when looking up vector type

source/validate_decorations.cpp, test/diagnostic_test.cpp, test/val/val_decoration_test.cpp
Additionally, implmentes code review feedback.
Fixes #1638
=> Block-decorated structs must list members in offset-order

test/opt/compact_ids_test.cpp
The Compact IDs pass can corrupt the CFG, but first the CFG has to
be setup. To do this, a test that builds the CFG, then performs the
compact IDs pass, then checks context consistency.
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1648
=> Add test for CFG alteration by compact IDs

source/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Layout validation : RowMajor, ArrayStride, MatrixStride

tools/io.h
=> Reopen stdin for binary as needed

source/val/validate_barriers.cpp
This CL updates validate_barriers to provide an explicit instruction
when calling diag().
=> Update diag() in validate_barriers

source/val/validate_builtins.cpp
This CL updates the calls to diag() in vlidate_builtings to provide the
instruction.
=> Update diag() use in validate_builtin.

source/val/validate_conversion.cpp
This CL updates validate_conversion to provide the instruction to diag()
calls.
=> Update diag() calls in validate_conversion.

source/val/validate_datarules.cpp
This CL updates validate_datarules to provide the instruction to diag().
=> Update diag() calls in validate_datarules.

source/val/validate_decorations.cpp
Several of the diag() calls in validate_decorations do not provide the
line number, and will output the last line in the file. This CL updates
the diag() calls to provide the instruction of interest.
=> Update diag() calls in validate_decorations.

source/val/validate_derivatives.cpp
This CL updates diag() in validate_derivatives to provide the
instruction of interest.
=> Update diag() calls in validate_derivatives.

source/val/validate_ext_inst.cpp
This CL updates the diag() usage in validate_ext_inst to provide the
=> Update diag() calls in validate_ext_inst.

source/val/validate_image.cpp
This CL updates the diag() calls in validate_image to provide the
relvant instruction.
=> Update diag() calls in validate_image.

source/val/validate_instruction.cpp
This CL updates validate_instruction to pass the Instruction to diag().
=> Update diag() calls in validate_instruction.

source/val/validate_interfaces.cpp
This CL upldates validate_interface to pass the instruction to the
diag() method.
=> Update diag() call in validate_interface.

source/val/validate_layout.cpp
This CL updates the diag() calls in validate_layout to pass the relevant
instruction.
=> Update diag() calls in validate_layout.

source/val/validate_logicals.cpp
This CL updates the diag() calls in validate_logicals to provide the
Instruction.
=> Update diag() calls in validate_logicals.

source/val/validate_non_uniform.cpp
This CL upldates diag() calls in validate_non_uniform to provide the
=> Update diag() calls in validate_non_uniform.

source/val/validate_primitives.cpp
This CL updates the diag() calls in validate_primitives to provide the
=> Update diag() calls in validate_primitives.

source/val/validate_type_unique.cpp
This CL updates the diag() calls in validate_type_unique to pass the
=> Update diag() calls in validate_type_unique.

source/val/validate_capability.cpp
This CL updates the diag() call in validate_capability to provide the
instruction.
=> Update diag() calls in validate_capability.

source/val/validate.cpp, source/val/validate.h, source/val/validate_adjacency.cpp, source/val/validate_id.cpp, source/val/validate_memory.cpp
There are several validation passes which loop over all ordered
instructions. This CL combines those into a single loop, calling each
pass as needed.
=> Combine ordered_instruction loops in validation.

PRESUBMIT.py, test/opt/fold_test.cpp, test/opt/loop_optimizations/hoist_single_nested_loops.cpp, tools/opt/opt.cpp
This CL removes the last two 'using namespace' commands.
=> Remove using namespace commands.

Android.mk, BUILD.gn, source/CMakeLists.txt, source/val/validate.cpp, source/val/validate.h, source/val/validate_debug.cpp, source/val/validate_id.cpp
* Removes debug opcode validation from idUsage and puts it in a separate
file
* minor updates
=> Split debug opcode validation into new file

source/val/validate_type.cpp, test/val/val_id_test.cpp
Fixes #1831
* Adds validation check that void is not a member of a struct
* added a test
=> Disallow void types in structs

source/comp/bit_stream.h, source/comp/markv_codec.cpp, source/comp/markv_decoder.h, source/comp/markv_encoder.h, source/disassemble.cpp, source/enum_set.h, source/opt/inline_pass.cpp, source/opt/ir_context.h, source/opt/ir_loader.cpp, source/opt/type_manager.cpp, source/opt/types.cpp, source/util/make_unique.h, source/util/parse_number.cpp, source/util/small_vector.h, test/opt/pass_fixture.h, test/opt/types_test.cpp, tools/comp/markv_model_factory.cpp, tools/comp/markv_model_shader.cpp
This CL replaces instances of reset(new ..) with MakeUnique.
=> Use MakeUnique.

Android.mk, include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, include/spirv-tools/optimizer.hpp, source/CMakeLists.txt, source/libspirv.cpp, source/opt/ir_context.h, source/opt/module.cpp, source/opt/module.h, source/opt/optimizer.cpp, source/opt/passes.h, source/spirv_optimizer_options.cpp, source/spirv_optimizer_options.h, source/util/string_utils.cpp, source/util/string_utils.h, test/opt/module_test.cpp, tools/opt/opt.cpp
* Adds an option to the CLI and API to specify the limit for the id
bound.
* Modify `TakeNextIdBound` to return 0 when the limit is reached.
Part of #1841.
=> Add option for the max id bound.

DEPS
=> Roll DEPS for spirv-headers

test/comp/markv_codec_test.cpp
This CL removes the use of SetContextMessageConsumer from
markv_codec_test and replaces it with a spvtools::Context instead.
=> Remove SetContextMessageConsumer from markv_codec_test

.appveyor.yml, CMakeLists.txt, kokoro/android/build.sh, kokoro/check-format/build.sh, kokoro/ndk-build/build.sh, kokoro/scripts/linux/build.sh, kokoro/scripts/macos/build.sh, kokoro/scripts/windows/build.bat
Recent builds have been failing due to updated googletest warnings about non-c++11 code. Set the cmake c++ version to c++11.
=> Set the C++ version to C++11

source/val/validate_memory.cpp, test/val/val_id_test.cpp
* MakePointerVisibleKHR cannot be used with OpStore
* MakePointerAvailableKHR cannot be used with OpLoad
* MakePointerAvailableKHR and MakePointerVisibleKHR both require
NonPrivatePointerKHR
* NonPrivatePointerKHR is limited to a subset of storage classes
* many tests
=> Memory access checks for vulkan mem model

source/CMakeLists.txt
Breaks the build when using makefiles.  The ninja build is fine.  Reopen #1941.
This reverts commit 67ebe3f7aebe73426a3bf9718dba56f051d75db5.
=> Revert "Add custom target to wrap around custom commands. (#1986)"

source/opt/if_conversion.cpp, test/opt/if_conversion_test.cpp
Fixes #1991
* Improved identification of potential conditional branches
* Pass changed to only work for shaders
* added a test to catch the bug
=> Fix restrictions in if conversion

source/val/validate_composites.cpp, test/val/val_composites_test.cpp
Fixes https://crbug.com/897069
* Code previously assumed the index instruction had a type
* Added a test to reproduce
=> Better checking of the index operand

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
Fixes #1985
* Added test to catch bug
* Tested aginst Vulkan CTS
=> Layout checks should recurse through runtime arrays

source/opcode.cpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/common_uniform_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, source/val/validate_builtins.cpp, test/operand_capabilities_test.cpp
@johnkslang for review
Let me know if i missed anything else
Thanks
=> Add support for nv-raytracing-final

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
Add missing case to the switch statement for the annotation
instructions.
See https://github.com/KhronosGroup/glslang/issues/1561.
=> Handle OpMemberDecorateStringGOOGLE in ACDE

tools/opt/opt.cpp
=> Fix up comment for |ParseFlags|.

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
Part of the test for this is in the Glslang test suite. :-(
=> UniformConstant variables can have RuntimeArray, TypeAccelerationStructureNV

source/spirv_target_env.cpp, source/spirv_target_env.h, source/val/validate_composites.cpp, test/val/val_id_test.cpp
=> Validate component literals for OpVectorShuffle in WebGPU environment

source/val/validate_conversion.cpp, test/val/val_conversion_test.cpp
Fixes https://crbug.com/906426
* Added a test
=> Catch invalid input type to OpConvertUToPtr

source/val/validate_capability.cpp, test/val/val_capability_test.cpp
Based on #2011, but fix up the tests.
@brett19, this will replace your PR.
=> Xfb support

test/val/val_id_test.cpp
=> Add tests coverage for OpTypeVector column count validation

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/common_uniform_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/local_ssa_elim_pass.cpp, source/val/validate_builtins.cpp
(copying what was done for NV_shading_rate)
=> Add basic support for EXT_fragment_invocation_density

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
Add precise check for allowing use of gl_InstanceID for specific vulkan raytracing stages .
=> Validate gl_InstanceID for raytracing

source/val/validate_type.cpp, test/val/val_id_test.cpp
=> Ensure that function parameter's type is not void

source/val/validate_extensions.cpp, test/val/val_webgpu_test.cpp
=> Ensure that only whitelisted extensions are used in WebGPU

source/val/validate_atomics.cpp, source/val/validate_barriers.cpp, source/val/validate_scopes.cpp, source/val/validate_scopes.h, test/val/val_atomics_test.cpp
=> Merging two ValidateMemoryScope implementations

source/val/validate_scopes.cpp, test/val/val_atomics_test.cpp
This also fixes a small typo that was causing my test case to fail.
Fixes #2136
=> Add check for QueueFamilyKHMR memory scope

source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Add WebGPU Execution scope check

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp, test/val/val_image_test.cpp, test/val/val_memory_test.cpp
=> Check binding annotations in resource variables

source/val/validate.cpp, source/val/validation_state.h, test/val/val_layout_test.cpp
=> Check that if A calls B, B is defined before A for WebGPU

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Validate that there is at most one push constant block

source/val/validate.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_validation_state_test.cpp
=> Check for recursion in Vulkan and WebGPU entry points

test/val/val_validation_state_test.cpp
This fixes tests that were broken by adding in validation of the order
of function definitions.
=> Fix broken recurison validation tests

source/opt/cfg.cpp, source/opt/cfg.h, source/opt/constants.cpp, source/opt/ir_builder.h, source/opt/ir_context.cpp, source/opt/ir_context.h, source/opt/licm_pass.cpp, source/opt/licm_pass.h, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_fission.cpp, source/opt/loop_peeling.cpp, source/opt/loop_unroller.cpp, source/opt/loop_unswitch_pass.cpp, source/opt/loop_utils.cpp, source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, source/opt/pass.h, source/opt/ssa_rewrite_pass.cpp, source/opt/type_manager.cpp, test/opt/ir_builder.cpp, test/opt/ir_context_test.cpp, test/opt/loop_optimizations/hoist_without_preheader.cpp
#1841: Handle id overflow is some places.  Leaves TODOs for other places that still need to be handled.
=> Partially handle Id overflow 

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Check that certain decorations cannot be used more than once and/or are mutually exclusive

tools/opt/opt.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2165.
=> Add documentation for licm option to the spirv-opt help.

test/reduce/structured_loop_to_selection_reduction_pass_test.cpp
The test should be extended when issue #2183 is addressed.
=> Added test related to access chains

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, tools/opt/opt.cpp
=> Add --target-env flag to spirv-opt

source/val/validate_memory_semantics.cpp, test/val/val_atomics_test.cpp
Per conversation on
https://github.com/KhronosGroup/glslang/issues/1618 and other places.
=> Remove check for SpvCapabilityAtomicStorage

source/opt/function.cpp, source/opt/function.h, source/opt/inline_exhaustive_pass.cpp, source/opt/inline_exhaustive_pass.h, source/opt/inline_opaque_pass.cpp, source/opt/inline_opaque_pass.h, source/opt/inline_pass.cpp, source/opt/inline_pass.h
Have inlining return Failure if the ids overflow.
Part of #1841.
=> Handle id overflow in inlining.

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, tools/opt/opt.cpp
=> Implement initial --webgpu-mode flag

source/opt/licm_pass.cpp, source/opt/licm_pass.h, test/opt/loop_optimizations/hoist_single_nested_loops.cpp
=> In LICM don't place code between merge instruction and branch.

source/opt/reduce_load_size.cpp, test/opt/reduce_load_size_test.cpp
Fixes https://crbug.com/917774
=> Have replace load size handle extact with no index.

source/val/validate_constants.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_constants_test.cpp
See https://github.com/KhronosGroup/glslang/issues/848
=> WIP: Permit UConvert spec-constant op for SPV_AMD_gpu_shader_int16

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
Validates NoSignedWrap, NoUnsignedWrap.
We are permissive by allowing any extended instruction.
=> Validate decorations from SPV_KHR_no_integer_wrap

source/val/validate.cpp, test/val/val_validation_state_test.cpp
=> Ensure that entry point names are unique for WebGPU

source/val/validation_state.h
=> Removing unused const version of id_decorations

source/val/validate_memory.cpp, source/val/validate_type.cpp, source/val/validation_state.h, test/val/val_data_test.cpp, test/val/val_memory_test.cpp
=> Enforce rules for OpTypeRuntimeArray on Vulkan

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
=> Ensure that required storage classes have initializer for WebGPU

test/val/val_data_test.cpp
=> Add tests to validate allowed lengths of int and floats for WebGPU

include/spirv-tools/instrument.hpp, source/opt/instrument_pass.cpp, source/opt/ir_context.cpp, test/opt/inst_bindless_check_test.cpp
...instead of VertexId and InstanceId
=> Instrumentation: Fix vertex instrumentation to use VertexIndex and InstanceIndex

source/val/validate_memory.cpp, source/val/validate_type.cpp, test/val/val_data_test.cpp, test/val/val_memory_test.cpp
=> Add WebGPU specific RTA validation rules

source/val/validate_scopes.cpp, test/val/val_atomics_test.cpp
=> Add in WebGPU specific memory scope validation

source/spirv_target_env.cpp, source/spirv_target_env.h, source/val/validate_type.cpp, test/val/val_memory_test.cpp
=> Add utility to generate a logging string for a given environment

README.md, tools/reduce/reduce.cpp
Added a short description to the top-level README.
Extended the -h option of the tool with brief notes on how to write an interestingness test (though they are not that brief for typical -h notes).
=> Added some documentation about the reducer.

source/spirv_target_env.cpp, source/spirv_target_env.h, source/val/validate.cpp, source/val/validate_memory.cpp, source/val/validate_type.cpp, test/val/val_memory_test.cpp
=> Add helper for 'is Vulkan or WebGPU'

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
This PR adds in the specific checks required for WebGPU, enables
running the builtin checks in WebGPU, and refactors the existing
testing infrastructure to support testing the new checks.
=> Add WebGPU specific validation for Position BuiltIn decoration

test/val/CMakeLists.txt, test/val/val_builtins_test.cpp, test/val/val_code_generator.cpp, test/val/val_code_generator.h
=> Move CodeGenerator to be accessible by other validation tests

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
=> Add WebGPU validation for LocalInvocationIndex BuiltIn decoration

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
=> Add whitelist of allowed BuiltIn decorations for WebGPU

source/opt/block_merge_util.cpp
This fixed my compile on my macbook.
=> Remove unused lambda capture

test/val/val_builtins_test.cpp
I made a mistake merging a PR, and it contained tests that break with
the latest google test.  I've fixed them up.
=> Fix up some test

source/reduce/CMakeLists.txt, source/reduce/merge_blocks_reduction_opportunity.cpp, source/reduce/merge_blocks_reduction_opportunity.h, source/reduce/merge_blocks_reduction_opportunity_finder.cpp, source/reduce/merge_blocks_reduction_opportunity_finder.h, test/reduce/CMakeLists.txt, test/reduce/merge_blocks_reduction_pass_test.cpp, test/reduce/merge_blocks_test.cpp, tools/reduce/reduce.cpp
Enhanced the reducer so that it can merge blocks together, leveraging the functionality extracted from the block_merge pass in the optimizer.
=> Merge blocks in reducer

test/val/val_builtins_test.cpp
=> Convert deprecated GoogleTest fixture to the new version

source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
=> Add flatten-decorations flag to webgpu-mode flags

source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
=> Add strip-debug to webgpu-mode passes

source/reduce/merge_blocks_reduction_opportunity.cpp, test/reduce/merge_blocks_test.cpp
=> Fix merge blocks opportunity to check if still enabled

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/eliminate_dead_members_pass.cpp, source/opt/eliminate_dead_members_pass.h, source/opt/optimizer.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/eliminate_dead_member_test.cpp
Add a pass that looks for members of structs whose values do not affects
the output of the shader.  Those members are then removed and just
treated like padding in the struct.
=> Add pass to remove dead members.

source/opt/eliminate_dead_members_pass.cpp, test/opt/eliminate_dead_member_test.cpp
Mark type id of unknown instructions at fully used.
=> Fix bug in dead member elimination.

test/opt/optimizer_test.cpp
=> Refactor webgpu-mode pass ran tests to be parameterized

source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
Also fix test to use non-zero set and binding which will make error
more obvious.
=> Bindless: Fix computation of set and binding for runtime bounds check

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> In Vulkan, disallow BufferBlock on StorageBuffer variables 

DEPS, source/assembly_grammar.cpp, source/opcode.cpp, source/opt/reflect.h, source/val/validate_arithmetics.cpp, source/val/validate_composites.cpp, source/val/validate_constants.cpp, source/val/validate_conversion.cpp, source/val/validate_id.cpp, source/val/validate_memory.cpp, source/val/validate_scopes.cpp, source/val/validate_type.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_arithmetics_test.cpp, test/val/val_composites_test.cpp, test/val/val_conversion_test.cpp, test/val/val_memory_test.cpp
WIP because this will fail CI until https://github.com/KhronosGroup/SPIRV-Headers/pull/94 is merged and DEPS is updated to use it.
=> Add validation for SPV_NV_cooperative_matrix

source/text.cpp
=> Use correct option in spvTextToBinary.

kokoro/linux-clang-asan/build.sh, kokoro/linux-clang-asan/continuous.cfg, kokoro/linux-clang-asan/presubmit.cfg, kokoro/scripts/linux/build.sh
Fix the ASAN part of build script.
Add continuous Linux ASAN bot.
=> Add continuous Linux ASAN bot.

source/val/validate_mode_setting.cpp, test/val/val_modes_test.cpp
=> Add missing DepthGreater case to Fragment only check

source/val/validate_mode_setting.cpp, test/val/val_modes_test.cpp
=> Add validation for ExecutionMode in WebGPU

source/val/validate_instruction.cpp, test/val/val_storage_test.cpp
=> Add validation of storage classes for WebGPU

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
=> Remove duplicates from list of interface IDs in OpEntryPoint instruction

source/val/validate_image.cpp, test/val/val_image_test.cpp
=> Check OpSampledImage is only passed into valid instructions

source/reduce/CMakeLists.txt, source/reduce/reducer.cpp, source/reduce/remove_selection_reduction_opportunity.cpp, source/reduce/remove_selection_reduction_opportunity.h, source/reduce/remove_selection_reduction_opportunity_finder.cpp, source/reduce/remove_selection_reduction_opportunity_finder.h, test/reduce/CMakeLists.txt, test/reduce/remove_selection_test.cpp
=> reduce: add remove_selection_reduction_opportunity

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
Fixes #2456
* When eliminating a structured construct that has an unreachable merge,
replace that unreachable terminator with an appropriate return
* New tests
This gets into a case of exposing undefined behaviour.
=> Handle dead infinite loops in DCE

source/opt/dead_branch_elim_pass.cpp, test/opt/dead_branch_elim_test.cpp
Fixes #2452
* Swaps priority of handling unreachable merge and continues so that the
back-edge is retained in the case a block is both a loop continue and
loop merge
* New test
=> Change prioritization of unreachable merge and continue

source/opt/fix_storage_class.cpp, test/opt/fix_storage_class_test.cpp
Fixes http://crbug.com/950889.
=> Accept OpBitCast in fix storage class.

source/val/validate_memory_semantics.cpp, test/val/val_barriers_test.cpp
=> Remove Acquire and Release from allowed Mem Sem bits for WebGPU

source/opt/decompose_initialized_variables_pass.cpp, test/opt/decompose_initialized_variables_test.cpp
=> Add support for Private & Output to initializer decompose flag

tools/CMakeLists.txt
=> Add spirv-lesspipe.sh into SPIRV_SKIP_EXECUTABLES umbrella

examples/cpp-interface/main.cpp
=> fix example.cpp

source/opt/basic_block.cpp, source/opt/basic_block.h, source/opt/cfg.cpp, test/opt/CMakeLists.txt, test/opt/cfg_test.cpp
It seems like the recursion is going very deep, and causing some problem
is particular situations.  I've reimplemented the CFG post order
traversal to not use recursion.
Fixes #2539.
=> Change implementation of post order CFG traversal

source/val/validate_mode_setting.cpp, test/val/val_modes_test.cpp
=> Add validation specific to OpExecutionModeId

source/val/validate_type.cpp, test/val/val_literals_test.cpp
Fixes https://crbug.com/959011.
=> Validate sign of int types.

test/opt/fold_test.cpp
Fixes #2554
* Folding rules already handle 1.4 selects so I simply added some tests
=> Add tests for folding 1.4 selects

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/function.cpp, source/opt/function.h, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/split_invalid_unreachable_pass.cpp, source/opt/split_invalid_unreachable_pass.h, test/opt/CMakeLists.txt, test/opt/optimizer_test.cpp, test/opt/split_invalid_unreachable_test.cpp
Attempts to split up unreachable blocks that are used both as a
merge-block and a continue-target.
Fixes #2429
=> Add pass to fix some invalid unreachable blocks for WebGPU

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp, test/val/val_limits_test.cpp
Fixes #2559
* Validate OpLoopMerge including loop controls
* add tests
* fix some bad tests
=> Validate loop merge

source/opt/inst_bindless_check_pass.cpp, source/opt/inst_bindless_check_pass.h, test/opt/inst_bindless_check_test.cpp
Essentially, support UBOs and SSBOs, scalar and array (sized and unsized).
=> Bindless Validation: Instrument descriptor-based loads and stores

source/val/validate_instruction.cpp, test/val/CMakeLists.txt, test/val/val_opencl_test.cpp, test/val/val_version_test.cpp
=> Validate OpenCL memory and addressing model environment rules

source/opt/const_folding_rules.cpp, source/opt/fold_spec_constant_op_and_composite_pass.cpp, test/opt/fold_spec_const_op_composite_test.cpp, test/opt/fold_test.cpp
Adding the folding rules for OpQuantizeToF16, and fixed some matching
tests to check identify new lines.
Fixes #2586
=> Add folding rules for OpQuantizeToF16

source/opt/optimizer.cpp, tools/opt/opt.cpp
Adds flags and/or documentation for individual transformation passes
that had been missed in previous patches.
Fixes #2574
=> Add in individual flags for Vulkan <-> WebGPU passes

source/val/validate_image.cpp, test/val/val_opencl_test.cpp
=> Validate OpenCL environment rules for OpImageWrite

utils/check_code_format.sh
=> Enable the base branch to be overridden in the code format check script

test/fuzzers/BUILD.gn, test/fuzzers/spvtools_opt_webgputovulkan_fuzzer.cpp
=>  Add fuzzer for WebGPU->Vulkan spirv-opt passes

source/opt/optimizer.cpp, test/opt/optimizer_test.cpp
=> Add compact ids to WebGPU <-> Vulkan transformations

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_permute_blocks.cpp, source/fuzz/fuzzer_pass_permute_blocks.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_move_block_down.cpp, source/fuzz/transformation_move_block_down.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_move_block_down_test.cpp
The blocks within each function in the module will be permuted in a randomized manner that respects dominance.
=> Add spirv-fuzz pass to permute blocks.

source/val/validate_image.cpp, test/val/val_opencl_test.cpp
=> Validate OpenCL rules for ImageRead and OpImageSampleExplicitLod

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
=> Remove asserts from GetUnderlyingType

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_breaks.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_break.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_dead_break_test.cpp
This pass randomly add breaks to the merge blocks of selection and
loop constructs, such that the breaking edges will not be dynamically
reachable.
=> Add fuzzer pass to add dead breaks.

source/opt/instrument_pass.cpp, test/opt/inst_bindless_check_test.cpp
Correct record size. Also bring version 2 tests up to version 1
equivalence.
=> Instrument: Fix code for version 2 output format.

source/opt/log.h
=> Cast __LINE__ to size_t

tools/fuzz/fuzz.cpp
=> Fix uint -> uint32_t in fuzz.cpp

source/val/validate_memory.cpp, test/opt/aggressive_dead_code_elim_test.cpp, test/opt/dead_variable_elim_test.cpp, test/val/val_memory_test.cpp
Fixes #249
* The pointed to type of Result Type must match the initializer type
* Had to update some opt tests to be valid
=> Validate variable initializer type

source/val/validate_memory.cpp, source/val/validation_state.cpp, source/val/validation_state.h, test/val/val_memory_test.cpp
Fixes #2638
* Adds a check that errors out if there is a store to a UBO in the
Vulkan environment
* tests
=> Disallow stores to UBOs

source/val/validate_memory.cpp, test/val/val_memory_test.cpp
* Wrong operands were used for pointer and array types
* added tests to catch the wierd number corner
=> Fix store to uniform Vulkan check

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Fix Component decoration validation for arrays

DEPS, source/opt/constants.h, source/opt/loop_dependence.h, source/opt/scalar_analysis_nodes.h, source/opt/types.cpp, source/opt/types.h, test/reduce/validation_during_reduction_test.cpp, test/timer_test.cpp
Remove extra semi-colons found through (-Werror -Wextra-semi which is a Clang-only option). Also update re2 to newer version which avoids extra semi-colons.
=> Remove extra semis

source/val/validate_scopes.cpp, test/val/val_atomics_test.cpp
=> Update memory scope rules for WebGPU

DEPS, source/val/validate_misc.cpp, test/val/val_modes_test.cpp
This depends on https://github.com/KhronosGroup/SPIRV-Headers/pull/121 and won't pass CI until that gets merged and I can update DEPS.
=> Add validation for SPV_EXT_demote_to_helper_invocation

Android.mk, BUILD.gn, source/CMakeLists.txt, source/val/validate.cpp, source/val/validate.h, source/val/validate_misc.cpp, source/val/validate_small_type_uses.cpp, test/val/CMakeLists.txt, test/val/val_misc_test.cpp, test/val/val_small_type_uses_test.cpp
Fixes #2729
* Check acceptable uses of small type generators
=> Extra small storage validation

source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Update execution scope rules for WebGPU

test/tools/expect.py, test/tools/opt/flags.py, tools/opt/opt.cpp
=> Correctly implement WebGPU related flag exclusions

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
Fixes #2686
* Update validation to handle the default case being mentioned multiple
times
* new tests
=> Case validation with repeated labels

source/val/validate_annotation.cpp, source/val/validate_memory_semantics.cpp, source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Update OpControlBarriers rules for WebGPU

test/opt/pass_fixture.h
Checks for failure status code and matches against
the expected error message.
=> Add opt test fixture method SinglePassRunAndFail

source/val/validate_memory_semantics.cpp, source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Update OpMemoryBarriers rules for WebGPU

source/val/validate_memory_semantics.cpp, source/val/validate_scopes.cpp, test/val/val_atomics_test.cpp
=> Update WebGPU validation rules of OpAtomic*s

tools/fuzz/fuzz.cpp
=> fuzz: change output extension and fix usage string

source/opt/scalar_replacement_pass.cpp, test/opt/scalar_replacement_test.cpp
If a member of a struct has a relaxed precision, sroa will not split the
struct.  This means we do not get all cases.  This commit handles these
cases.  The other part is that the decoration needs to be passed on to
the new variables.
Fixes #2786
=> Handle RelaxedPrecision in SROA

source/opt/instrument_pass.cpp, source/opt/instrument_pass.h, source/opt/ir_context.cpp, source/opt/optimizer.cpp, test/opt/inst_bindless_check_test.cpp
Also change command line for bindless instrumentation to use use
output record version 2.
=> Instrument: Fix version 2 output record write for tess eval shaders.

source/opt/ir_builder.h, source/opt/wrap_opkill.cpp, source/opt/wrap_opkill.h, test/opt/wrap_opkill_test.cpp
Fixes https://crbug.com/994203
=> Handle overflow in wrap-opkill

source/opt/desc_sroa.cpp, test/opt/desc_sroa_test.cpp
=> Add name for variables in desc sroa

source/opt/copy_prop_arrays.cpp, source/opt/pass.cpp, source/opt/private_to_local_pass.cpp, source/opt/private_to_local_pass.h, source/opt/type_manager.cpp, source/opt/type_manager.h, test/opt/private_to_local_test.cpp
We need to handle id overflow in the private to local pass.
Fixes https://crbug.com/962295
=> Handle Id overflow in private-to-local

source/opt/amd_ext_to_khr.cpp, source/opt/type_manager.h, test/opt/amd_ext_to_khr.cpp
=> Replace SwizzleInvocationsMaskedAMD extended instruction.

source/opt/amd_ext_to_khr.cpp, test/opt/amd_ext_to_khr.cpp
=> Replace SwizzleInvocationsAMD extended instruction.

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
=> Fold Fmix should accept vector operands.

source/opt/amd_ext_to_khr.cpp, source/opt/feature_manager.h, source/opt/ir_builder.h, source/opt/ir_context.h, test/opt/amd_ext_to_khr.cpp
=> Replace uses of SPV_AMD_shader_trinary_minmax extension

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
=> Fold Min, Max, and Clamp instructions.

source/opt/amd_ext_to_khr.cpp, source/opt/constants.cpp, source/opt/constants.h, test/opt/amd_ext_to_khr.cpp
=> Replace CubeFaceCoord

source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp, test/val/val_capability_test.cpp
* Validate the target's opcode is acceptable
* Update tests
* New tests
* move early exit for builtins a bit later in the pass
Tested against CTS also.
=> Add generic builtin validation of target

source/opt/fold.cpp, test/opt/constant_manager_test.cpp
=> Handle id overflow in the constant manager.

source/opt/generate_webgpu_initializers_pass.cpp
=> Handle creating a new constant failing gracefully

source/opt/generate_webgpu_initializers_pass.cpp
=> Handle another case where creating a constant can fail

source/fuzz/fuzzer_util.cpp, test/fuzz/transformation_add_dead_continue_test.cpp
Fixes a case where the algorithm used to determine which blocks a new break or continue edge was incomplete.
=> Fuzzer: fix block bypass detection

DEPS
Include change that added SPV_KHR_physical_storage_buffer
=> Update SPIRV-Headers in DEPS

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
This change rectifies a problem where an absolute operand index was
being used when an index restricted to input operands was required.
Fixes #2893.
=> Fix operand index in spirv-fuzz

source/opt/local_access_chain_convert_pass.cpp, source/opt/local_access_chain_convert_pass.h, test/opt/local_access_chain_convert_test.cpp
Fixes https://crbug.com/1004453
=> Handle id overflow in convert local access chains

.gitignore, BUILD.bazel, README.md, WORKSPACE, build_defs.bzl
I will add a Kokoro bot to exercise this once it has landed (it works when I use it locally).
=> Add Bazel build configuration.

source/opt/instruction.h, source/opt/ir_context.h, source/opt/module.h, source/opt/strip_debug_info_pass.cpp, test/opt/strip_debug_info_test.cpp
=> Add removing references to debug instructions when removing them

source/opt/inst_buff_addr_check_pass.cpp, test/opt/inst_buff_addr_check_test.cpp
=> Generate null pointer by converting uint64 zero to pointer.

source/opt/ir_context.cpp, test/opt/ir_context_test.cpp
=> Link cfg and dominator analysis in the context

source/val/validate_misc.cpp, test/val/val_misc_test.cpp
See #2952
Disabled until specification is clarified
=> Disable scope validation for OpReadClockKHR

source/reduce/conditional_branch_to_simple_conditional_branch_opportunity_finder.cpp, source/reduce/conditional_branch_to_simple_conditional_branch_reduction_opportunity.cpp, source/reduce/conditional_branch_to_simple_conditional_branch_reduction_opportunity.h, source/reduce/reduction_util.cpp, source/reduce/reduction_util.h, source/reduce/structured_loop_to_selection_reduction_opportunity.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.h, test/reduce/reducer_test.cpp
* Add larger reducer tests.
* Fix conditional_branch_to_simple_conditional_branch_opportunity pass.
=> reduce: add large tests and fix

test/fuzzers/BUILD.gn, test/fuzzers/spvtools_as_fuzzer.cpp
=> Add fuzzer for spirv-as call path

source/opt/fold.cpp, source/opt/fold_spec_constant_op_and_composite_pass.cpp, source/util/bitutils.h, test/opt/fold_spec_const_op_composite_test.cpp, test/util/CMakeLists.txt, test/util/bitutils_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2557.
=> Support constant-folding UConvert and SConvert

source/binary.cpp
=> Check binary->code existence before destroying

test/fuzzers/BUILD.gn, test/fuzzers/spvtools_dis_fuzzer.cpp
=> Add fuzzer for spirv-dis call path

source/text.cpp
=> Check text->str before destroying

source/opt/instrument_pass.cpp, test/opt/inst_bindless_check_test.cpp
Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1226
=> Instrument: Add missing def-use analysis.

tools/opt/opt.cpp
=> Add description of wrap-opkill.

BUILD.gn
Detected via ANGLE's export_targets.py.
Fixes #3008
@dj2 PTAL
=> Add missing headers to GN.

utils/vscode/src/grammar/grammar.go
=> Fix Go lint issues: comment exported symbols

source/val/validate_misc.cpp, source/val/validate_scopes.cpp, source/val/validate_scopes.h, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp, test/val/val_decoration_test.cpp, test/val/val_misc_test.cpp
Fixes #2952
* Refactor some common scope validation
* Perform correct validation for scope in OpReadClockKHR
* new tests
Tested against CTS.
=> Re-enable OpReadClockKHR validation

source/opt/value_number_table.cpp, test/opt/value_table_test.cpp
=> Handle OpPhi with no in operands in value numbering

test/fuzzers/spvtools_as_fuzzer.cpp
=> Initialize binary for use as guard later

test/fuzzers/spvtools_as_fuzzer.cpp
=> Add missing dealloc

CMakeLists.txt
=> Respect CMAKE_INSTALL_LIBDIR in installed CMake files

utils/vscode/README.md, utils/vscode/install.bat, utils/vscode/src/tools/gen-grammar.go
Installs the language server on windows.
Also add info to / corrects `README.md`.
=> utils/vscode: Add install.bat

source/opt/register_pressure.cpp, test/opt/register_liveness.cpp
=> Handle unreachable block when computing register pressure

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
=> Folding: perform add and sub on mismatched integer types

source/fuzz/transformation_outline_function.cpp, test/fuzz/transformation_outline_function_test.cpp
This change prevents the spirv-fuzz function outliner from outlining a
region that uses the result of an OpAccessChain not defined inside the
region.  Such accesses were turning into parameters to the outlined
function, and the result of an OpAccessChain cannot be passed as a
function parameter according to the SPIR-V specification.
=> spirv-fuzz: Avoid passing access chains as parameters

source/fuzz/CMakeLists.txt, source/fuzz/instruction_message.cpp, source/fuzz/instruction_message.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_add_function.h, test/fuzz/transformation_add_function_test.cpp
This adds a large transformation that can add a new function to a
SPIR-V module.  This paves the way for donation of code from one
module to another.
=> spirv-fuzz: Transformation to add a new function to a module

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
=> Fix typo in validation message

source/operand.cpp, test/val/val_id_test.cpp
Fixes https://crbug.com/1031049
* Disallow forward references in arrays
* Add a test
=> Disallow forward references in arrays

source/operand.cpp, test/val/val_id_test.cpp
* Change is now under active discussion in Khronos
=> Revert PR #3093

source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, test/opt/pass_merge_return_test.cpp
=> Use dummy switch instead of dummy loop in MergeReturn pass.

include/spirv-tools/libspirv.h, include/spirv-tools/libspirv.hpp, include/spirv-tools/optimizer.hpp
=> Clarify mapping of target env to SPIR-V version

test/fuzz/transformation_outline_function_test.cpp
Adds a test to check that we do outline code that uses pointer
parameters.
=> spirv-fuzz: Add outlining test

tools/opt/opt.cpp
The environment version update is based on the value of the `kDefaultEnvironment` constant.
=> Fix typos in opt's help. Update environment version.

CMakeLists.txt
=> Fix static libraries linking order

source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Adding WebGPU specific Workgroup scope rule

.gitignore, source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_permute_function_parameters.cpp, source/fuzz/fuzzer_pass_permute_function_parameters.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_type_function.h, source/fuzz/transformation_permute_function_parameters.cpp, source/fuzz/transformation_permute_function_parameters.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_permute_function_parameters_test.cpp, utils/check_copyright.py
=> spirv-fuzz: Add fuzzer pass to permute function parameters

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
In this PR, the class `FuzzerPassApplyIdSynonyms` was updated to allow `OpPhi` operand to be replaced with a composite synonym.
Fixes #3209.
=> spirv-fuzz: Allow OpPhi operand to be replaced with a composite synonym

source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_function_call.cpp, source/fuzz/transformation_function_call.h
=> spirv-fuzz: Remove duplicated functionality

source/fuzz/fuzzer_pass_add_equation_instructions.cpp, test/fuzz/fuzzer_replayer_test.cpp
=> spirv-fuzz: Fix vector width issue in 'add equation instructions' pass

Android.mk, BUILD.gn, include/spirv-tools/instrument.hpp, include/spirv-tools/optimizer.hpp, source/enum_set.h, source/opt/CMakeLists.txt, source/opt/feature_manager.cpp, source/opt/feature_manager.h, source/opt/inst_debug_printf_pass.cpp, source/opt/inst_debug_printf_pass.h, source/opt/instrument_pass.cpp, source/opt/instrument_pass.h, source/opt/optimizer.cpp, source/opt/passes.h, test/opt/CMakeLists.txt, test/opt/inst_debug_printf_test.cpp
=> Instrument: Debug Printf support

source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h
Add missing RayQueryProvisionalKHR types
=> Add RayQueryProvisionalKHR to opt types

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
* Disallow phis of sampled images always
* Disallow phis of samplers and images for shaders
* Add tests
=> Disallow phis of images, samplers and sampled images

source/opt/dominator_tree.cpp, test/opt/loop_optimizations/loop_descriptions.cpp
Fixes #3270
* Dominates using tree nodes now checks for null nodes
* Added a test
=> Update dominates to check for null nodes

source/opt/optimizer.cpp, test/tools/opt/flags.py
We have not added tests for the new command line options recently.  I've
updated the test and fixed on option that was incorrect.
Fixes #3247
=> Add tests for recently added command line option

source/val/validate_cfg.cpp
Fixes #3296
* Make OpReturn its own case fully
=> Remove implicit fallthrough

source/fuzz/transformation_outline_function.cpp, test/fuzz/transformation_outline_function_test.cpp
Adds an extra condition on when a region can be outlined to avoid the
case where a region ends with a loop head but such that the loop's
continue target is in the region.  (Outlining such a region would mean
that the loop merge is in the original function and the continue target
in the outlined function.)
=> spirv-fuzz: Fix to outliner

source/fuzz/fact_manager.cpp
Fixes a bug where, while recursively adding id equation facts, a
reference to a set of id equations could be used after it had been
freed (due to equivalence classes of equations being merged).
=> spirv-fuzz: Fix memory management in the fact manager

source/fuzz/transformation_add_function.cpp, test/fuzz/transformation_add_function_test.cpp
It has been resolved that statically out-of-bounds accesses are not
invalid in SPIR-V (they lead to undefind behaviour at runtime but
should not cause a module to be rejected during validation).  This
change tolerates such accesses in donated code, clamping them in-bound
as part of making a function live-safe.
=> spirv-fuzz: Clamp statically out-of-bounds accesses in code donation

source/val/validate_scopes.cpp, test/val/val_barriers_test.cpp
=> Validate ShaderCallKHR memory scope

source/fuzz/fact_manager.cpp, test/fuzz/fact_manager_test.cpp
Reworks the way uniforms with known constants are queried to avoid
unintended side effects to the constant manager.
Fixes #3338.
=> spirv-fuzz: Fix to fact manager

source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_opaque_test.cpp, test/opt/inline_test.cpp
Reverts KhronosGroup/SPIRV-Tools#3328
=> Revert "[spirv-opt] refactor inlining pass"

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_adjust_branch_weights.cpp, source/fuzz/fuzzer_pass_adjust_branch_weights.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_adjust_branch_weights.cpp, source/fuzz/transformation_adjust_branch_weights.h, source/opt/instruction.cpp, source/opt/instruction.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_adjust_branch_weights_test.cpp
In this PR, the classes that represent the adjust branch weights transformation and fuzzer pass were implemented. This transformation adjusts the branch weights of a `OpBranchConditional` instruction.
=> Add adjust branch weights transformation

source/opt/inline_pass.cpp, source/opt/inline_pass.h, test/opt/inline_opaque_test.cpp, test/opt/inline_test.cpp
Reverts KhronosGroup/SPIRV-Tools#3342
=> Revert "Revert "[spirv-opt] refactor inlining pass""

source/opt/merge_return_pass.cpp, test/opt/pass_merge_return_test.cpp
=> Don't register edges twice in merge return

source/fuzz/fuzzer_pass_donate_modules.cpp
=> spirv-fuzz: Add support for StorageBuffer

BUILD.gn
=> Remove stale entries from BUILD.gn

source/fuzz/fuzzer_pass_add_loads.cpp, source/fuzz/fuzzer_pass_add_stores.cpp
This PR fixes a function use of a `Instruction` object.
=> Fix function use

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_add_composite_types.cpp, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp
This PR add support to pass bit width of integer and float types as argument.
=> Support bit width argument for int and float types

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_push_id_through_variable.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_push_id_through_variable_test.cpp
=> spirv-fuzz: Add push id through variable transformation

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_global_variable.h, source/fuzz/transformation_push_id_through_variable.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp
=> spirv-fuzz: Fix regression in shrinker test and replayer test

source/fuzz/fact_manager.cpp
=> spirv-fuzz: Fix replayer bug

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_spec_constant_op.cpp, source/fuzz/transformation_add_spec_constant_op.h, test/fuzz/fuzzer_pass_donate_modules_test.cpp
=> spirv-fuzz: Add support for OpSpecConstant*

source/fuzz/transformation_set_memory_operands_mask.cpp, test/fuzz/transformation_set_memory_operands_mask_test.cpp
=> spirv-fuzz: Fix memory operand access

source/operand.cpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_access_chain_convert_pass.h, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_block_elim_pass.h, source/opt/local_single_store_elim_pass.cpp, source/opt/local_single_store_elim_pass.h, test/opt/aggressive_dead_code_elim_test.cpp, test/val/val_builtins_test.cpp, test/val/val_decoration_test.cpp, test/val/val_modes_test.cpp, test/val/val_webgpu_test.cpp, utils/check_symbol_exports.py
This CL updates the access control lists used in SPIRV-Tools to the more
descriptive allow/deny naming.
=> Update access control lists.

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_vector_shuffle_instructions.cpp, source/fuzz/fuzzer_pass_add_vector_shuffle_instructions.h
=> spirv-fuzz: Implement vector shuffle fuzzer pass

source/opt/instruction_list.h
=> spirv-opt: Fix return type

source/opt/function.h
=> spirv-opt: Add RemoveParameter method

source/opt/loop_descriptor.cpp, test/opt/loop_optimizations/loop_fission.cpp, test/opt/loop_optimizations/unroll_simple.cpp
=> Use structured order to unroll loops.

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_swap_conditional_branch_operands.cpp, source/fuzz/fuzzer_pass_swap_conditional_branch_operands.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_swap_conditional_branch_operands.cpp, source/fuzz/transformation_swap_conditional_branch_operands.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_swap_conditional_branch_operands_test.cpp
=> spirv-fuzz: Swap operands in OpBranchConditional

source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_global_variable.cpp, source/fuzz/transformation_add_local_variable.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_push_id_through_variable.h, test/fuzz/transformation_push_id_through_variable_test.cpp
=> spirv-fuzz: Refactor variable creation

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_parameter.cpp, source/fuzz/transformation_add_type_float.cpp, source/fuzz/transformation_add_type_int.cpp, source/fuzz/transformation_add_type_struct.cpp, source/fuzz/transformation_add_type_vector.cpp
=> spirv-fuzz: Add fuzzerutil::FindOrCreate*

source/fuzz/transformation_add_parameter.cpp, test/fuzz/transformation_add_parameter_test.cpp
=> spirv-fuzz: Fix regression in TransformationAddParameter

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_invert_comparison_operators.cpp, source/fuzz/fuzzer_pass_invert_comparison_operators.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_invert_comparison_operator.cpp, source/fuzz/transformation_invert_comparison_operator.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_invert_comparison_operator_test.cpp
=> spirv-fuzz: TransformationInvertComparisonOperator

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp
=> spirv-fuzz: fuzzerutil::MaybeGetConstant*

source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_global_variables.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.cpp
=> spirv-fuzz: Add variables with workgroup storage class

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp, source/fuzz/fuzzer_pass_add_image_sample_unused_components.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_image_sample_unused_components.cpp, source/fuzz/transformation_add_image_sample_unused_components.h, source/opcode.cpp, source/opcode.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_add_image_sample_unused_components_test.cpp
=> spirv-fuzz: Add image sample unused components transformation

source/opt/debug_info_manager.cpp, source/opt/debug_info_manager.h, source/opt/local_single_block_elim_pass.cpp, test/opt/local_single_block_elim.cpp
Essentially creates a DebugValue when removing a store to a local variable.
=> Upgrade elim-local-single-block for OpenCL.DebugInfo.100

source/opt/local_single_block_elim_pass.cpp
As a mistake, I submitted #3451 without rebasing it, which causes build failures.
=> Fix build failure

source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/transformation_replace_boolean_constant_with_constant_binary.cpp, test/fuzz/transformation_replace_boolean_constant_with_constant_binary_test.cpp
=> spirv-fuzz: Support OpPhi when replacing boolean constant operand

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/opt/basic_block.cpp, test/fuzz/transformation_add_dead_break_test.cpp
=> spirv-fuzz: Support adding dead break from back-edge block

source/fuzz/transformation_push_id_through_variable.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp
=> spirv-fuzz: Fix instruction insertion issue

source/opt/dominator_analysis.cpp, test/opt/dominator_tree/generated.cpp
=> spirv-opt: Add support for OpLabel to dominator analysis

source/fuzz/fact_manager.cpp, source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/transformation_equation_instruction.cpp, test/fuzz/fact_manager_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp
=> spirv-fuzz: Add support for OpBitcast to TransformationEquationInstruction

source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_permute_blocks.cpp
Also refactor the code accordingly.
Follow-up to comment in #3540 .
=> spirv-fuzz: Change MaybeApplyTransformation to return a boolean

source/fuzz/fact_manager.cpp, source/fuzz/fact_manager.h, source/fuzz/protobufs/spvtoolsfuzz.proto, test/fuzz/fact_manager_test.cpp
Part of #3177.
This PR adds a fact to the fact manager.
=> spirv-fuzz: Add IdIsIrrelevant fact

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_constant_boolean.cpp, source/fuzz/transformation_add_constant_boolean.h, source/fuzz/transformation_add_constant_composite.cpp, source/fuzz/transformation_add_constant_composite.h, source/fuzz/transformation_add_constant_scalar.cpp, source/fuzz/transformation_add_constant_scalar.h, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_break.h, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, source/fuzz/transformation_add_synonym.cpp, source/fuzz/transformation_add_synonym.h, source/fuzz/transformation_replace_parameter_with_global.cpp
Part of #3177. 
Adjusts functions to create constants.
=> spirv-fuzz: Create irrelevant constants

source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_pass_add_function_calls.h, source/fuzz/fuzzer_pass_add_parameters.cpp, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_parameter.cpp, source/fuzz/transformation_replace_parameter_with_global.cpp
=> spirv-fuzz: Use irrelevant constants

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_replace_params_with_struct.cpp, source/fuzz/fuzzer_pass_replace_params_with_struct.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_permute_function_parameters.cpp, source/fuzz/transformation_replace_parameter_with_global.cpp, source/fuzz/transformation_replace_params_with_struct.cpp, source/fuzz/transformation_replace_params_with_struct.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_permute_function_parameters_test.cpp, test/fuzz/transformation_replace_parameter_with_global_test.cpp, test/fuzz/transformation_replace_params_with_struct_test.cpp
=> spirv-fuzz: TransformationReplaceParamsWithStruct

include/spirv-tools/optimizer.hpp, source/opcode.cpp, source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/dominator_tree.cpp, source/opt/inline_pass.cpp, source/opt/inline_pass.h, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/loop_unroller.cpp, source/opt/reflect.h, source/opt/replace_invalid_opc.cpp, source/opt/wrap_opkill.cpp, source/opt/wrap_opkill.h, source/val/validate_cfg.cpp, source/val/validate_instruction.cpp, test/opt/block_merge_test.cpp, test/opt/inline_test.cpp, test/opt/loop_optimizations/unroll_assumptions.cpp, test/opt/wrap_opkill_test.cpp, test/text_to_binary.control_flow_test.cpp, test/val/CMakeLists.txt, test/val/val_extension_spv_khr_terminate_invocation.cpp, test/val/val_extensions_test.cpp
Covers:
- assembler
- disassembler
- validator
- optimizer
=> Support SPV_KHR_terminate_invocation

source/fuzz/fuzzer_pass_add_synonyms.cpp, source/fuzz/fuzzer_pass_add_vector_shuffle_instructions.cpp, source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_construct_composites.cpp, source/fuzz/fuzzer_pass_copy_objects.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_synonym.cpp, source/fuzz/transformation_add_synonym.h, source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_composite_construct.h, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_composite_extract.h, source/fuzz/transformation_equation_instruction.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_push_id_through_variable.h, source/fuzz/transformation_record_synonymous_constants.cpp, source/fuzz/transformation_record_synonymous_constants.h, source/fuzz/transformation_vector_shuffle.cpp, source/fuzz/transformation_vector_shuffle.h
=> spirv-fuzz: Fix usages of irrelevant constants

source/fuzz/fact_manager.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_push_id_through_variable.h, test/fuzz/transformation_add_constant_boolean_test.cpp, test/fuzz/transformation_add_constant_composite_test.cpp, test/fuzz/transformation_add_constant_scalar_test.cpp, test/fuzz/transformation_add_parameter_test.cpp, test/fuzz/transformation_add_synonym_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_equation_instruction_test.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp, test/fuzz/transformation_record_synonymous_constants_test.cpp, test/fuzz/transformation_replace_parameter_with_global_test.cpp, test/fuzz/transformation_vector_shuffle_test.cpp
=> spirv-fuzz: Test usages of IdIsIrrelevant fact

source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_access_chains.cpp, source/fuzz/fuzzer_pass_add_composite_types.cpp, source/fuzz/fuzzer_pass_add_copy_memory.cpp, source/fuzz/fuzzer_pass_add_dead_blocks.cpp, source/fuzz/fuzzer_pass_add_dead_breaks.cpp, source/fuzz/fuzzer_pass_add_dead_continues.cpp, source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/fuzzer_pass_add_function_calls.cpp, source/fuzz/fuzzer_pass_add_global_variables.cpp, source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp, source/fuzz/fuzzer_pass_add_local_variables.cpp, source/fuzz/fuzzer_pass_add_synonyms.cpp, source/fuzz/fuzzer_pass_donate_modules.cpp, source/fuzz/fuzzer_pass_interchange_zero_like_constants.cpp, source/fuzz/fuzzer_pass_obfuscate_constants.cpp, source/fuzz/fuzzer_pass_push_ids_through_variables.cpp, source/fuzz/fuzzer_pass_replace_copy_objects_with_stores_loads.cpp, source/fuzz/fuzzer_pass_replace_parameter_with_global.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_constant_boolean.h, source/fuzz/transformation_add_constant_composite.h, source/fuzz/transformation_add_constant_scalar.h, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_synonym.cpp, source/fuzz/transformation_replace_parameter_with_global.cpp
=> spirv-fuzz: Make is_irrelevant parameters non-default

source/fuzz/transformation_add_function.cpp, test/fuzz/transformation_add_function_test.cpp
=> spirv-fuzz: Add condition to make functions livesafe

source/fuzz/fuzzer_pass_replace_params_with_struct.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_replace_params_with_struct.cpp, source/fuzz/transformation_replace_params_with_struct.h
=> spirv-fuzz: Remove non-deterministic behaviour

CHANGES, source/fuzz/transformation_outline_function.h, source/name_mapper.cpp, source/opt/dominator_tree.cpp, source/opt/ir_builder.h, source/opt/loop_descriptor.cpp, source/opt/loop_descriptor.h, source/opt/loop_unroller.cpp, source/opt/loop_unswitch_pass.cpp, source/opt/merge_return_pass.cpp, source/opt/merge_return_pass.h, source/opt/register_pressure.cpp, source/reduce/structured_loop_to_selection_reduction_opportunity.h, source/val/validate_image.cpp, test/opt/inline_test.cpp, test/opt/ir_context_test.cpp, test/opt/pass_merge_return_test.cpp, test/reduce/validation_during_reduction_test.cpp, test/val/val_adjacency_test.cpp, test/val/val_cfg_test.cpp, test/val/val_primitives_test.cpp
This CL updates various bits of language in line with the guidelines
provided by Android
(https://source.android.com/setup/contribute/respectful-code)
=> Update some language usage.

source/fuzz/fuzzer_pass_replace_linear_algebra_instructions.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_replace_linear_algebra_instruction.cpp, source/fuzz/transformation_replace_linear_algebra_instruction.h, test/fuzz/transformation_replace_linear_algebra_instruction_test.cpp
=> spirv-fuzz: Implement the OpOuterProduct linear algebra case

source/fuzz/fuzzer_pass_add_equation_instructions.cpp, source/fuzz/fuzzer_pass_outline_functions.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_replace_parameter_with_global.cpp, source/fuzz/transformation_replace_params_with_struct.cpp
=> spirv-fuzz: Fix memory bugs

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_parameter.cpp, test/fuzz/transformation_add_parameter_test.cpp
Part of #3534. I forgot to implement this functionality in the original PR.
=> spirv-fuzz: Refactor boilerplate in TransformationAddParameter

source/fuzz/fuzzer_pass_donate_modules.cpp, test/fuzz/fuzzer_pass_donate_modules_test.cpp
=> spirv-fuzz: Handle capabilities during module donation

source/fuzz/fuzzer_pass_copy_objects.cpp
=> spirv-fuzz: Fix FuzzerPassCopyObjects

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_replace_constant_with_uniform.cpp, source/fuzz/transformation_replace_constant_with_uniform.h, test/fuzz/transformation_replace_constant_with_uniform_test.cpp
=> spirv-fuzz: Handle OpPhi during constant obfuscation

source/CMakeLists.txt, source/fuzz/CMakeLists.txt, source/opt/CMakeLists.txt, source/reduce/CMakeLists.txt
The clang compiler does not accept that option.
=> Avoid using /MP4 for clang on windows.

source/opt/local_access_chain_convert_pass.cpp, test/opt/local_access_chain_convert_test.cpp
=> Handle no index access chain in local access chain convert

source/val/validate_extensions.cpp, test/val/val_ext_inst_test.cpp
- DebugTypeTemplate
- DebugTypeTemplateParameter
- DebugGlobalVariable
- DebugInlinedAt
- DebugValue
=> Validate OpenCL.DebugInfo.100 instructions for legalization passes

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
=> spirv-opt: Fix off-by-1 error

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_util.cpp
=> spirv-fuzz: Fix MaybeGetZeroConstant

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_inline_functions.cpp, source/fuzz/fuzzer_pass_inline_functions.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_inline_function.cpp, source/fuzz/transformation_inline_function.h, source/opt/function.cpp, test/fuzz/CMakeLists.txt, test/fuzz/transformation_inline_function_test.cpp
=> spirv-fuzz: Add inline function transformation

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_add_composite_inserts.cpp, source/fuzz/fuzzer_pass_mutate_pointers.cpp, source/fuzz/fuzzer_pass_mutate_pointers.h, source/fuzz/fuzzer_pass_replace_copy_objects_with_stores_loads.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_parameter.cpp, source/fuzz/transformation_mutate_pointer.cpp, source/fuzz/transformation_mutate_pointer.h, source/fuzz/transformation_replace_parameter_with_global.cpp, source/fuzz/transformation_replace_params_with_struct.cpp, test/fuzz/CMakeLists.txt, test/fuzz/transformation_mutate_pointer_test.cpp
=> spirv-fuzz: TransformationMutatePointer

source/fuzz/fuzzer_pass_add_composite_types.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_type_struct.cpp, source/fuzz/transformation_add_type_struct.h, test/fuzz/transformation_add_type_struct_test.cpp
=> spirv-fuzz: Add support for BuiltIn decoration

tools/io.h
Missing include in io.h for strcmp.
=> Add missing include

BUILD.gn
=> Add missing file to BUILD.gn

source/fuzz/transformation_move_instruction_down.cpp, source/fuzz/transformation_move_instruction_down.h, test/fuzz/transformation_move_instruction_down_test.cpp
=> spirv-fuzz: Support memory instructions MoveInstructionDown

source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_opphi_synonym.cpp, source/fuzz/transformation_add_parameter.cpp, source/fuzz/transformation_replace_irrelevant_id.cpp, test/fuzz/CMakeLists.txt, test/fuzz/fuzzer_pass_test.cpp
Fixes #3722, fixes #3713, fixes #3714.
=> spirv-fuzz: Skip unreachable blocks

source/opt/graphics_robust_access_pass.cpp, test/opt/graphics_robust_access_test.cpp
=> Fix missed modification flagging

source/fuzz/transformation_inline_function.cpp, test/fuzz/transformation_inline_function_test.cpp
=> spirv-fuzz: Handle OpPhis in TransformationInlineFunction

source/fuzz/fuzzer_pass_add_synonyms.cpp, source/fuzz/fuzzer_pass_copy_objects.cpp, source/fuzz/transformation_add_synonym.cpp, test/fuzz/transformation_add_synonym_test.cpp
=> spirv-fuzz: Support dead blocks in TransformationAddSynonym

test/fuzz/transformation_add_synonym_test.cpp
Fix test that broke due to a merge.
=> spirv-fuzz: fix test

source/fuzz/transformation_flatten_conditional_branch.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Fix flatten conditional branch transformation

source/fuzz/transformation_record_synonymous_constants.cpp, test/fuzz/transformation_record_synonymous_constants_test.cpp
=> spirv-fuzz: Fix TransformationRecordSynonymousConstants

source/fuzz/fuzzer_pass_flatten_conditional_branches.cpp
=> spirv-fuzz: Fix to FuzzerPassFlattenConditionalBranches

source/fuzz/fuzzer.cpp, source/fuzz/fuzzer.h
=> spirv-fuzz: Enable some passes with high probability

source/fuzz/fact_manager/constant_uniform_facts.cpp, source/fuzz/fact_manager/constant_uniform_facts.h, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.h, source/fuzz/fact_manager/dead_block_facts.cpp, source/fuzz/fact_manager/dead_block_facts.h, source/fuzz/fact_manager/fact_manager.cpp, source/fuzz/fact_manager/fact_manager.h, source/fuzz/fact_manager/irrelevant_value_facts.cpp, source/fuzz/fact_manager/irrelevant_value_facts.h, source/fuzz/fact_manager/livesafe_function_facts.cpp, source/fuzz/fact_manager/livesafe_function_facts.h, source/fuzz/force_render_red.cpp, source/fuzz/fuzzer.cpp, source/fuzz/replayer.cpp, source/fuzz/transformation_add_dead_block.cpp, source/fuzz/transformation_add_function.cpp, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, source/fuzz/transformation_split_block.cpp, test/fuzz/data_synonym_transformation_test.cpp, test/fuzz/fact_manager_test.cpp, test/fuzz/fuzzer_pass_add_opphi_synonyms_test.cpp, test/fuzz/transformation_add_opphi_synonym_test.cpp, test/fuzz/transformation_replace_constant_with_uniform_test.cpp, test/fuzz/transformation_replace_id_with_synonym_test.cpp
Refactors conditions and names of some methods in the fact manager. Part of #3698.
=> spirv-fuzz: Refactor conditions in the fact manager

source/opt/local_redundancy_elimination.cpp, source/opt/value_number_table.cpp, test/opt/redundancy_elimination_test.cpp, test/opt/value_table_test.cpp
=> Debug info preservation in redundancy-elimination pass

source/fuzz/fuzzer.cpp, source/fuzz/pass_management/repeated_pass_manager.h, source/fuzz/pass_management/repeated_pass_manager_looped_with_recommendations.cpp, source/fuzz/pass_management/repeated_pass_manager_looped_with_recommendations.h, source/fuzz/pass_management/repeated_pass_manager_random_with_recommendations.cpp, source/fuzz/pass_management/repeated_pass_manager_random_with_recommendations.h, source/fuzz/pass_management/repeated_pass_manager_simple.cpp, source/fuzz/pass_management/repeated_pass_manager_simple.h
=> spirv-fuzz: Only recommend passes when a pass had an effect

source/opt/local_access_chain_convert_pass.cpp, source/opt/local_access_chain_convert_pass.h, test/opt/local_access_chain_convert_test.cpp
=> Debug info preservation in convert-local-access-chains pass

source/fuzz/data_descriptor.cpp, source/fuzz/data_descriptor.h, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fuzzer_pass_outline_functions.cpp, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_composite_extract.h, source/fuzz/transformation_composite_insert.cpp, source/fuzz/transformation_outline_function.cpp, source/fuzz/transformation_outline_function.h, test/fuzz/data_synonym_transformation_test.cpp
=> spirv-fuzz: Fix rvalue references

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_replace_branches_from_dead_blocks_with_exits.cpp, source/fuzz/fuzzer_pass_replace_branches_from_dead_blocks_with_exits.h, source/fuzz/pass_management/repeated_pass_instances.h, source/fuzz/pass_management/repeated_pass_recommender_standard.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_replace_branch_from_dead_block_with_exit.cpp, source/fuzz/transformation_replace_branch_from_dead_block_with_exit.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_replace_branch_from_dead_block_with_exit_test.cpp
=> spirv-fuzz: Replace dead-block terminators with OpKill etc.

source/fuzz/CMakeLists.txt, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_wrap_early_terminator_in_function.cpp, source/fuzz/transformation_wrap_early_terminator_in_function.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_wrap_early_terminator_in_function_test.cpp
=> spirv-fuzz: Wrap OpKill and similar in function calls

source/fuzz/transformation_add_bit_instruction_synonym.cpp, source/fuzz/transformation_add_loop_to_create_int_constant_synonym.cpp, source/fuzz/transformation_add_loop_to_create_int_constant_synonym.h, source/fuzz/transformation_add_opphi_synonym.cpp, source/fuzz/transformation_add_opphi_synonym.h, source/fuzz/transformation_composite_construct.cpp, source/fuzz/transformation_composite_construct.h, source/fuzz/transformation_composite_extract.cpp, source/fuzz/transformation_composite_extract.h, source/fuzz/transformation_composite_insert.cpp, source/fuzz/transformation_composite_insert.h, source/fuzz/transformation_push_id_through_variable.cpp, source/fuzz/transformation_push_id_through_variable.h, source/fuzz/transformation_replace_copy_object_with_store_load.cpp, source/fuzz/transformation_vector_shuffle.cpp, source/fuzz/transformation_vector_shuffle.h, test/fuzz/transformation_add_bit_instruction_synonym_test.cpp, test/fuzz/transformation_add_loop_to_create_int_constant_synonym_test.cpp, test/fuzz/transformation_add_opphi_synonym_test.cpp, test/fuzz/transformation_composite_construct_test.cpp, test/fuzz/transformation_composite_extract_test.cpp, test/fuzz/transformation_composite_insert_test.cpp, test/fuzz/transformation_push_id_through_variable_test.cpp, test/fuzz/transformation_replace_copy_object_with_store_load_test.cpp, test/fuzz/transformation_vector_shuffle_test.cpp
=> spirv-fuzz: Do not add synonyms involving irrelevant ids

source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, test/fuzz/fact_manager/data_synonym_and_id_equation_facts_test.cpp
=> spirv-fuzz: Do not expose synonym facts for non-existent ids

source/fuzz/transformation_duplicate_region_with_selection.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
=> spirv-fuzz: Fix to duplicate region with selection

source/fuzz/fuzzer_pass_apply_id_synonyms.cpp, source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp, source/fuzz/transformation_replace_irrelevant_id.cpp, source/fuzz/transformation_replace_irrelevant_id.h, test/fuzz/transformation_replace_irrelevant_id_test.cpp
=> spirv-fuzz: Fixes related to irrelevant ids

source/fuzz/fuzzer_pass_add_composite_inserts.cpp, source/fuzz/fuzzer_pass_flatten_conditional_branches.cpp, source/fuzz/fuzzer_pass_replace_branches_from_dead_blocks_with_exits.cpp, source/fuzz/fuzzer_pass_replace_copy_objects_with_stores_loads.cpp, source/fuzz/fuzzer_pass_replace_parameter_with_global.cpp, source/fuzz/fuzzer_pass_replace_params_with_struct.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_mutate_pointer.cpp, source/fuzz/transformation_replace_parameter_with_global.cpp, source/fuzz/transformation_replace_parameter_with_global.h, source/fuzz/transformation_replace_params_with_struct.cpp, source/fuzz/transformation_replace_params_with_struct.h, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Do not allow creation of constants of block-decorated structs

source/fuzz/transformation_flatten_conditional_branch.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Fix handling of OpPhi in FlattenConditionalBranch

source/fuzz/fuzzer_context.cpp
=> spirv-fuzz: Lower probability of adding bit instruction synonyms

source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fuzzer_pass.cpp, source/fuzz/fuzzer_pass.h, source/fuzz/fuzzer_pass_merge_function_returns.cpp, source/fuzz/fuzzer_pass_merge_function_returns.h, source/fuzz/fuzzer_pass_propagate_instructions_up.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_add_loop_preheader.cpp, source/fuzz/transformation_merge_function_returns.cpp, source/fuzz/transformation_wrap_early_terminator_in_function.cpp, source/fuzz/transformation_wrap_early_terminator_in_function.h, test/fuzz/fuzzer_replayer_test.cpp, test/fuzz/transformation_compute_data_synonym_fact_closure_test.cpp, test/fuzz/transformation_merge_function_returns_test.cpp
=> spirv-fuzz: Wrap early terminators before merging returns

source/fuzz/transformation_inline_function.cpp, test/fuzz/transformation_inline_function_test.cpp
=> spirv-fuzz: Take care of OpPhi instructions when inlining

source/fuzz/transformation_equation_instruction.cpp, test/fuzz/transformation_equation_instruction_test.cpp
=> spirv-fuzz: Handle dead blocks in TransformationEquationInstruction

source/fuzz/transformation_replace_branch_from_dead_block_with_exit.cpp, test/fuzz/transformation_replace_branch_from_dead_block_with_exit_test.cpp
=> spirv-fuzz: Fix to operand id type

include/spirv-tools/libspirv.h, source/operand.cpp, source/val/validate_builtins.cpp, test/val/val_builtins_test.cpp
Relies on https://github.com/KhronosGroup/SPIRV-Headers/pull/172
=> Support SPV_KHR_fragment_shading_rate

source/val/validate_atomics.cpp, source/val/validate_image.cpp, test/enum_string_mapping_test.cpp, test/val/val_image_test.cpp
Relies on https://github.com/KhronosGroup/SPIRV-Headers/pull/170
=> Add SPV_EXT_shader_image_int64

source/fuzz/fuzzer_pass_replace_opphi_ids_from_dead_predecessors.cpp
=> spirv-fuzz: Restrict fuzzer pass to reachable blocks

source/fuzz/transformation_duplicate_region_with_selection.cpp, test/fuzz/transformation_duplicate_region_with_selection_test.cpp
Also removes some redundant validity checks in tests.
Fixes #3950.
=> spirv-fuzz: Do not produce OpPhis of type OpTypeSampledImage

DEPS
This is breaking autorollers into Chrome and ANGLE
https://chromium-review.googlesource.com/c/angle/angle/+/2489234
https://chromium-review.googlesource.com/c/chromium/src/+/2489335
=> Update SPIRV-Headers revision in DEPS file

source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_merge_function_returns.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp, test/fuzz/transformation_merge_function_returns_test.cpp
=> spirv-fuzz: Fix operand types

source/fuzz/fuzzer_util.cpp, test/fuzz/transformation_add_copy_memory_test.cpp, test/fuzz/transformation_mutate_pointer_test.cpp
=> spirv-fuzz: Fix to id availability

source/fuzz/transformation_composite_construct.cpp, test/fuzz/transformation_composite_construct_test.cpp
=> spirv-fuzz: Fix off-by-one in TransformationCompositeConstruct

source/fuzz/transformation_flatten_conditional_branch.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Get order right for OpSelect arguments

source/fuzz/replayer.cpp, test/fuzz/replayer_test.cpp
=> spirv-fuzz: Fix off-by-one error in replayer

source/fuzz/added_function_reducer.cpp, source/fuzz/added_function_reducer.h, test/fuzz/shrinker_test.cpp
=> spirv-fuzz: Fix mismatch with shrinker step limit

source/fuzz/CMakeLists.txt, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp, source/fuzz/fact_manager/data_synonym_and_id_equation_facts.h, source/fuzz/fact_manager/fact_manager.cpp, source/fuzz/fact_manager/fact_manager.h, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_composite_extract.cpp, source/fuzz/fuzzer_pass_add_composite_extract.h, source/fuzz/pass_management/repeated_pass_instances.h, source/fuzz/pass_management/repeated_pass_recommender_standard.cpp, source/fuzz/transformation_composite_extract.cpp, test/fuzz/transformation_composite_extract_test.cpp
=> spirv-fuzz: Add FuzzerPassAddCompositeExtract

source/opt/inst_bindless_check_pass.cpp, source/opt/instrument_pass.cpp, source/opt/instrument_pass.h, test/opt/inst_bindless_check_test.cpp
Fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2234
=> Fix bounds check instrumentation to handle 16-bit values

source/fuzz/fact_manager/data_synonym_and_id_equation_facts.cpp
=> spirv-fuzz: Fix invalid equation facts

source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_flatten_conditional_branch.h, test/fuzz/transformation_flatten_conditional_branch_test.cpp
=> spirv-fuzz: Do not flatten conditionals that create synonyms

source/fuzz/transformation_composite_construct.cpp, test/fuzz/transformation_composite_construct_test.cpp
=> spirv-fuzz: Fix facts arising from CompositeConstruct

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
Fix VUID-Position-Position-04320
Adds VUID-Position-Position-04319
=> spirv-val: Add last Position VUID

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
adds
VUID-Layer-Layer-04273
VUID-ViewportIndex-ViewportIndex-04405
=> spirv-val: Add last ViewportIndex and Layer VUID

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
add
VUID-ClipDistance-ClipDistance-04188
VUID-ClipDistance-ClipDistance-04189
VUID-ClipDistance-ClipDistance-04190
VUID-ClipDistance-ClipDistance-04191
VUID-CullDistance-CullDistance-04196
VUID-CullDistance-CullDistance-04197
VUID-CullDistance-CullDistance-04198
VUID-CullDistance-CullDistance-04199
=> spirv-val: Add last ClipDistance and CullDistance VUID

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
add
VUID-TessLevelOuter-TessLevelOuter-04391
VUID-TessLevelOuter-TessLevelOuter-04392
VUID-TessLevelInner-TessLevelInner-04395
VUID-TessLevelInner-TessLevelInner-04396
=> spirv-val: Add last TessLevelOuter and TessLevelInner VUID

source/val/validate_image.cpp, test/val/val_image_test.cpp, test/val/val_opencl_test.cpp
=> validate OpTypeImage Sampled values for environemnts

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
Took Daniel's idea of putting some of the very repetitive VUs in the array, let me know if you are not a fan of that
=> spirv-val: Add Subgroup VUIDs

source/val/validate_scopes.cpp, source/val/validation_state.cpp, test/val/val_atomics_test.cpp, test/val/val_barriers_test.cpp
Adds validation for
- VUID-StandaloneSpirv-None-04638
- VUID-StandaloneSpirv-None-04639
- VUID-StandaloneSpirv-None-04640
=> spirv-val: Add Vulkan Memory Scope VUs

source/val/validate_image.cpp, test/val/val_image_test.cpp
=> Validate Sampled=1 for Vulkan ImageQuerySizeLod, ImageQueryLevels, ImageQueryLod

source/val/validate_builtins.cpp, source/val/validation_state.cpp, test/val/val_builtins_test.cpp
Add remaining `VK_EXT_` builtins to validation
=> spirv-val: Add Vulkan EXT builtins

source/val/validate_mode_setting.cpp, source/val/validation_state.cpp, test/val/val_modes_test.cpp
VUID-StandaloneSpirv-LocalSize-04683
=> spirv-val: Label VUID 04683

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
VUID-StandaloneSpirv-Offset-04662
=> spirv-val: Label VUID 04662

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
VUID-StandaloneSpirv-Offset-04663
=> spirv-val: Add Vulkan image gather offset VUID

source/val/validate_memory.cpp, source/val/validation_state.cpp, test/val/val_memory_test.cpp
VUID-StandaloneSpirv-Invariant-04677
=> spirv-val: Add Vulkan Invariant Decoration VUID

source/val/validate_memory.cpp, source/val/validation_state.cpp, test/val/val_memory_test.cpp
closes #4131
VUID-StandaloneSpirv-UniformConstant-04655
=> spirv-val: Fix/Label UniformConstant VUID

source/val/validate_image.cpp, source/val/validation_state.cpp, test/val/val_image_test.cpp
VUID-StandaloneSpirv-OpImageGather-04664
=> spriv-val: Vulkan image gather constant component

source/opt/instruction.h, source/opt/instruction_list.h
These methods are overriding their base class, so switch to override
from virtual.
=> Update a few virtuals to overrides.

source/fuzz/fuzzer_util.cpp, source/fuzz/transformation_flatten_conditional_branch.cpp, source/fuzz/transformation_set_loop_control.cpp, source/fuzz/transformation_set_memory_operands_mask.cpp, test/fuzz/transformation_add_global_variable_test.cpp, test/fuzz/transformation_flatten_conditional_branch_test.cpp, test/fuzz/transformation_set_loop_control_test.cpp, test/fuzz/transformation_set_memory_operands_mask_test.cpp
=> spirv-fuzz: Handle Vulkan SPIR-V versions

source/fuzz/transformation_set_loop_control.cpp, test/fuzz/transformation_set_loop_control_test.cpp
=> spirv-fuzz: Fix PartialCount

source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/transformation_add_dead_break.cpp, source/fuzz/transformation_add_dead_break.h, source/fuzz/transformation_add_dead_continue.cpp, source/fuzz/transformation_add_dead_continue.h, source/fuzz/transformation_replace_branch_from_dead_block_with_exit.cpp, source/fuzz/transformation_replace_branch_from_dead_block_with_exit.h, test/fuzz/transformation_replace_branch_from_dead_block_with_exit_test.cpp
=> spirv-fuzz: Fix the bug in TransformationReplaceBranchFromDeadBlockWithExit

BUILD.gn
=> Suppress warning

test/fuzz/transformation_add_bit_instruction_synonym_test.cpp
=> spirv-fuzz: Add buggy signedness test

source/val/validate_misc.cpp, test/text_to_binary.extension_test.cpp, test/val/CMakeLists.txt, test/val/val_extension_spv_khr_expect_assume.cpp, test/val/val_extension_spv_khr_linkonce_odr.cpp
This requires support in https://github.com/KhronosGroup/SPIRV-Headers/pull/200
=> Support SPV_KHR_linkonce_odr, SPV_KHR_expect_assume

source/fuzz/transformation_equation_instruction.cpp
Avoids unnecessary invalidation of analyses.
=> spirv-fuzz: Make adding equation instructions more efficient

source/fuzz/instruction_descriptor.cpp
Avoids redundantly searching the whome module when locating an
instruction from its descriptor - instead, only the block containing
the instruction needs to be searched.
=> spirv-fuzz: Locate instructions more efficiently

source/fuzz/fuzzer.cpp
=> spirv-fuzz: Apply fuzzer pass before checking exit conditions

source/fuzz/fuzzer.cpp
=> spirv-fuzz: Fix comments

source/fuzz/CMakeLists.txt, source/fuzz/fuzzer.cpp, source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_permute_function_variables.cpp, source/fuzz/fuzzer_pass_permute_function_variables.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation.cpp, source/fuzz/transformation_swap_function_variables.cpp, source/fuzz/transformation_swap_function_variables.h, test/fuzz/CMakeLists.txt, test/fuzz/transformation_swap_function_variables_test.cpp, utils/check_copyright.py
=> solve Permute the order of variables at function scope 

source/opt/graphics_robust_access_pass.cpp, test/opt/graphics_robust_access_test.cpp
When calling `replace_index`.
Fixes: #4166
=> GraphicsRobustAccessPass: Set module_status_.modified

source/opt/constants.cpp, source/opt/constants.h, source/opt/folding_rules.cpp, test/opt/fold_test.cpp
Add constant folding rule for OpBitcast with numeric scalar or vector
constants.
=> Support folding OpBitcast with numeric constants

source/opt/eliminate_dead_functions_util.cpp, source/opt/ir_context.cpp, source/opt/ir_context.h, test/opt/eliminate_dead_functions_test.cpp
=> Fix crash when optimizing shaders with DebugPrintf

source/fuzz/fuzzer_pass_permute_function_variables.cpp, source/fuzz/transformation_swap_function_variables.cpp, test/fuzz/transformation_swap_function_variables_test.cpp
=> Spirv-fuzz: Enhancing permute function variables and it's testing

test/fuzz/transformation_composite_construct_test.cpp
Fixes [#4288 ](https://github.com/KhronosGroup/SPIRV-Tools/issues/4288l)
=> spirv-fuzz: Added tests to increase coverage of TransformationCompositeConstruct

test/fuzz/transformation_add_parameter_test.cpp
Fixes [#4294](https://github.com/KhronosGroup/SPIRV-Tools/issues/4294)
=> spirv-fuzz: Added test to increase coverage of the add_parameter transformation

source/fuzz/fuzzer_pass_add_synonyms.cpp, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_add_synonym.cpp, test/fuzz/transformation_add_synonym_test.cpp
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/4172
=> spirv-fuzz: Added support for OpBitwiseOr and OpBitwiseXor

utils/check_symbol_exports.py
- Ignore symbols marked as .hidden
- Ignore weakly linked thunks (_ZT prefix)
Without this, the exports check fails on the Android NDK build.
=> fix symbol exports check, for Android build cases

test/fuzz/transformation_replace_id_with_synonym_test.cpp
Adds (currently disabled) tests related to #4345 and #4346.
=> spirv-fuzz: Add illustrative tests for new issues

source/diagnostic.cpp
Fixes compiling as Release/RelWithDebInfo with gcc 11
=> fix strncpy bound error

source/val/validate_extensions.cpp, test/text_to_binary.extension_test.cpp, test/val/CMakeLists.txt, test/val/val_extension_spv_khr_bit_instructions.cpp
See: https://github.com/KhronosGroup/SPIRV-Registry/pull/120
See also: https://github.com/KhronosGroup/SPIRV-Headers/pull/225
=> add tests for SPV_KHR_bit_instructions

test/fuzz/transformation_replace_id_with_synonym_test.cpp
Adds skeleton tests to support #4345.
=> spirv-fuzz: Added tests for signedness analysis

DEPS
Needed to roll vulkan-deps into Chromium and ANGLE, see crbug.com/1226709
@s-perron
=> Update SPIRV-Headers deps

BUILD.gn
=> Fix vendor table build in BUILD.gn for nonsemantic.vulkan.debuginfo.100

tools/cfg/cfg.cpp
=> Fix -Wunreachable-code-aggressive.

README.md
=> Explain how to run tests with CMake and Bazel

CONTRIBUTING.md
Visual Studio 2013 is not supported anymore.
=> Don't mention VS2013 in PR review instructions

source/fuzz/fuzzer_pass_add_local_variables.cpp
=> spirv-fuzz: Avoid out-of-bounds access

source/fuzz/fuzzer_context.cpp, source/fuzz/fuzzer_context.h, source/fuzz/fuzzer_pass_add_loads.cpp, source/fuzz/fuzzer_pass_add_stores.cpp, source/fuzz/fuzzer_util.cpp, source/fuzz/fuzzer_util.h, source/fuzz/protobufs/spvtoolsfuzz.proto, source/fuzz/transformation_load.cpp, source/fuzz/transformation_load.h, source/fuzz/transformation_store.cpp, source/fuzz/transformation_store.h, test/fuzz/transformation_store_test.cpp
=> spirv-fuzz: Support AtomicStore

source/val/validate_decorations.cpp
* Improve the early exit logic for array layout validation to handle
more cases
=> Fix array layout validation slowdown

source/lint/CMakeLists.txt
=> Remove PCH from source/lint/CMakeLists.txt

include/spirv-tools/optimizer.hpp, source/opt/optimizer.cpp, source/opt/reduce_load_size.cpp, source/opt/reduce_load_size.h, test/opt/reduce_load_size_test.cpp, tools/opt/opt.cpp
It will be used to fix https://github.com/microsoft/DirectXShaderCompiler/issues/3889
=> Set threshold for reduce-load-size pass

source/util/hex_float.h, test/hex_float_test.cpp
- The binary exponent must have some decimal digits
- A + or - after the binary exponent digits should not be interpreted as
part of the binary exponent.
Fixes: #4500
=> fix parsing of bad binary exponents in hex floats

source/val/validate_cfg.cpp, test/val/val_cfg_test.cpp
Fixes #4506
* Add validation of selector and default operands
=> Add some missing switch validation

source/val/validate_type.cpp, test/val/val_arithmetics_test.cpp
=> Fix validation message for cooperative matrix column type

source/val/validation_state.cpp, test/val/val_ext_inst_test.cpp
Fixes https://crbug.com/38102
Fixes #4516 
* Check for valid instructions in many boolean tests instead of
asserting in ValidationState_t
=> Change validator boolean tests to avoid asserts

kokoro/scripts/linux/build-docker.sh, test/text_to_binary_test.cpp
Corrects a UBSan-related flag.
=> Fix UBSan kokoro config

source/val/construct.cpp, test/val/val_cfg_test.cpp
Fixes https://crbug.com/38548
* Fixes an issue in structured exit checking where an invalid merge
could result in an infinite traversal
=> Fix infinite loop in validation

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
Fixes https://crbug.com/38771
* Fixes offset checks to look through arrays for nested structures
=> Fix checks for offset in nested structs

BUILD.gn
Fixes #4535
@alan-baker PTAL
@jonahryandavis FYI
=> GN: Fix build for debuginfo codegen.

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/aggressive_dead_code_elim_pass.h, source/opt/ir_context.cpp
This PR has two commits that are just refactors of the ADCE code.  The refactoring is not complete.  Please do not ask me to do more at this time, but check that the new code is okay.  You can look at each commit on its if you want.
=> Adce refactor (NFC)

source/text_handler.cpp
The cleverness is probably not worth it.
=> Avoid implicit fallthrough, by duplicating code

source/opt/convert_to_half_pass.cpp, source/opt/convert_to_half_pass.h, test/opt/convert_relaxed_to_half_test.cpp
=> Fix handling of OpPhi in convert-relaxed-to-half

source/val/validate_annotation.cpp, test/val/val_annotation_test.cpp, test/val/val_capability_test.cpp
=> Allow WorkgroupSize on variables for Kernels

source/opt/amd_ext_to_khr.cpp, source/opt/const_folding_rules.cpp, source/opt/constants.cpp, source/opt/constants.h, source/opt/type_manager.h, test/opt/fold_test.cpp
See https://github.com/KhronosGroup/SPIRV-Tools/issues/4636 for details.
Fixes #4636.
=> Manually fold floating point division by zero

source/opt/ir_context.h
Currently if an ID overflow occurs, spirv-opt (and other users of
IRContext) emits a warning and starts returning 0 when fresh ids are
requested. This tends to lead to crashes - such as null pointer
exceptions. When these arise during fuzzing they lead to auto-reported
bugs.
This change uses an ifdef guard to instead gracefully exit as soon as an
ID overflow occurs when the build is a fuzzing build.
Related issue: #4539.
=> Exit when ID overflow occurs in a fuzzing build

source/opt/strip_reflect_info_pass.cpp
It's a backport from diligent fork
=> treat google user type as normal semantic google.

source/opt/strip_nonsemantic_info_pass.cpp, test/opt/strip_nonsemantic_info_test.cpp
- Rename strip reflect to strip nonsemantic
- Don't remove debug info in strip-nonsemantic
=> reflect debug

DEPS
Updated using `utils/rolls_deps.sh`
=> Update DEPS file

include/spirv-tools/optimizer.hpp
=> Fix typo in comment: SPIR-V section for debug instructions

source/val/validate_image.cpp, test/val/val_image_test.cpp
* Nontemporal image operand shouldn't expect a following operand
=> Fix handling of Nontemporal image operand

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, test/text_to_binary.extension_test.cpp
Spec: https://github.com/KhronosGroup/SPIRV-Registry/pull/138
SPIR-V Headers: https://github.com/KhronosGroup/SPIRV-Headers/pull/269
=> Support SPV_KHR_uniform_group_instructions

tools/opt/opt.cpp
=> Remove deprecated flags from spirv-opt help message

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
This change adds a folding rule which transforms x * y - a and a - x * y
into FMA(x, y, -a) and FMA(-x, y, a), respectively.
While the SPIR-V instruction count remains the same, target instruction
sets typically feature FMA instruction variants that can negate an
operand. Also this transformation may unlock further optimizations which
eliminate the negation.
(Google bug: b/226145988)
=> Fold multiply and subtraction into FMA with negation

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
=> Ability to fold Constant Vector times Matrix and Matrix times vector instructions

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
=> Fail validation when RelaxedPrecision is applied to a type.

source/opt/loop_unroller.cpp
Uses a preprocessor macro to bail out of unrolling loops with large
iteration counts during fuzzing, to reduce the number of
timeouts/memouts that arise.
Related issue: #4728.
=> Avoid unrolling large loops while fuzzing

tools/io.h
We currently do not set stdout to binary mode when writing a binary
file on Windows.  This cause some extra characters to be written that
mess up the output.  We try to fix that.
Fixes #4793
=> Write binary files to stdout in binary on windows.

Android.mk, BUILD.gn, source/CMakeLists.txt, source/val/validate.cpp, source/val/validate.h, source/val/validate_cfg.cpp, source/val/validate_ray_tracing.cpp, test/val/CMakeLists.txt, test/val/val_ray_tracing.cpp
(tasklist https://github.com/KhronosGroup/Vulkan-Docs/issues/1402)
=> spirv-val: Add SPV_KHR_ray_tracing instructions

source/val/validate_ray_tracing.cpp, test/val/val_ray_tracing.cpp
based on https://github.com/KhronosGroup/SPIRV-Registry/pull/160
=> spirv-val: SBT Index for OpExecuteCallableKHR

source/opt/debug_info_manager.cpp, test/opt/inline_test.cpp
Line instructions may be OpLine or DebugLine. This commit adds support for DebugLine.
=> Fix DebugInlinedAt Line operand

source/val/validation_state.cpp, test/val/val_storage_test.cpp
This was added to the 1.3.227 Vulkan spec
=> spirv-val: Label ShaderRecordBufferKHR VUID

BUILD.gn
closes #4945 sorry @aabdolrashidi not sure why that was not found/caught in the CI build
=> build: Fix BUILD.gn build error

.clang-format, CMakeLists.txt, source/opt/feature_manager.cpp
This reverts commit da215f10c991675b9c1ecb7eef2378e23b2d1276.
=> Revert "test"

source/val/validate_interfaces.cpp, source/val/validation_state.cpp, test/val/val_decoration_test.cpp, test/val/val_ray_tracing_test.cpp
adds
- VUID-StandaloneSpirv-OpVariable-06673
- VUID-StandaloneSpirv-IncomingRayPayloadKHR-04700
- VUID-StandaloneSpirv-HitAttributeKHR-04702
- VUID-StandaloneSpirv-IncomingCallableDataKHR-04706
=> spirv-val: Multiple interface var with same SC

source/opt/const_folding_rules.cpp, test/opt/fold_spec_const_op_composite_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/4996 
cc @ShabbyX
=> spirv-opt: Handle null CompositeInsert

source/opt/block_merge_util.cpp, test/opt/block_merge_test.cpp
Fixes https://crbug.com/1395415
* Block merging needed to invalid structured cfg analysis
=> Fix use of invalid analysis

DEPS, test/cpp_interface_test.cpp
=> Test operator overloads for SPIR-V C++ mask enums

source/util/hex_float.h, test/hex_float_test.cpp
When the parser saw more significant hex digits than fit in the target type, it would compute a nonsensical shift amount, resulting in undefined behaviour.
Now, drop the excess bits, effectively truncating the significand.
Also guard against overflow of the exponent in the extraordinary (and untested) case where we see more than, for example, 2**(32-4+1) significant hex digits for a 32-bit float, or 2**(16-4+1) significant hex digits for a 16-bit float.
Fixes: #4724
=> Fix undef behaviour in hex float parsing

.github/workflows/wasm.yml, CMakeLists.txt, source/wasm/docker-compose.yml
=> Update minimum required CMake to 3.17.2

DEPS
=> DEPS: update to last googletest release supporting C++11

CHANGES, README.md
=> Update README.md: Development occurs on the "main" branch

.github/workflows/bazel.yml, .github/workflows/wasm.yml, kokoro/check-format/build.sh, kokoro/macos-clang-debug/build.sh, kokoro/macos-clang-release-bazel/build.sh, kokoro/macos-clang-release/build.sh, kokoro/scripts/linux/build-docker.sh, kokoro/scripts/macos/build.sh, source/wasm/build.sh
Causing build failures. I did not pick up on it because the github actions simply did not run.  I did not get an error from them.  
See: https://github.com/KhronosGroup/SPIRV-Tools/actions/runs/3987317002
Reverts KhronosGroup/SPIRV-Tools#5078
=> Revert "kokoro: fix dubious ownership"

source/opt/const_folding_rules.cpp, test/opt/fold_test.cpp
Struct types are not supported in constant folding yet.
=> Fix null pointer in FoldInsertWithConstants.

source/opt/reflect.h
* Found during an internal build
=> Add missing header include

BUILD.gn
=> build: fix build.gn missing comma

tools/link/linker.cpp
replace the old parser with the common utility.
=> linker: refactorize flag parsing

test/tools/flags_test.cpp, tools/util/flags.cpp, tools/util/flags.h
This will be required to refactorize other tools.
=> tools: add uint32_t flags parsing

tools/lint/lint.cpp
Change custom flag parsing to the built-in one.
=> linter: refactorize linter flag parsing

tools/diff/diff.cpp
Remove custom flag parsing to use the common one.
=> diff: refactorize flag parsing

source/opt/remove_unused_interface_variables_pass.h
=> Add missing header guard

source/opt/aggressive_dead_code_elim_pass.cpp, test/opt/aggressive_dead_code_elim_test.cpp
This is for
https://github.com/microsoft/DirectXShaderCompiler/issues/5136.
=> Run ADCE when the printf extension is used.

CHANGES, DEPS
Roll deps and update CHANGES to prepare 2023.3 release.
=> Prepare release 2023.3

source/diff/diff.cpp, test/diff/diff_files/multiple_same_entry_points_autogen.cpp
Addresses one case mentioned in #5218.
=> diff: Don't give up entry point matching too early.

utils/roll_deps.sh
This reverts commit e357a36ccfac9a1fa71e00b04237d117b53093b6.
=> Revert "Disable RE2 autoroll (#5234)"

kokoro/scripts/linux/build-docker.sh
Now that shaderc knows about abseil, we want to check it out. Hopefully
this fixes the smoketest.
=> Checkout abseil in the smoketest

test/diff/diff_files/ray_query_types_autogen.cpp
Seems to have been left out due to submission race condition
=> spirv-diff: Update test expectations

source/opt/const_folding_rules.cpp, source/opt/constants.cpp, source/opt/constants.h, source/opt/type_manager.h, test/opt/fold_test.cpp
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5247
=> Fold negation of integer vectors

utils/generate_language_headers.py
as python2 may not recgonize utf encoding, per https://bugs.python.org/issue11033
=> Add python3 requirement for the script

source/opt/trim_capabilities_pass.cpp, source/opt/trim_capabilities_pass.h, test/opt/trim_capabilities_pass_test.cpp
Add StoragePushConstant16 to the list of enabled capabilities.
=> opt: add StoragePushConstant16 to trim pass

source/opt/decoration_manager.cpp, source/opt/decoration_manager.h, source/opt/trim_capabilities_pass.cpp, source/opt/trim_capabilities_pass.h, test/opt/trim_capabilities_pass_test.cpp
Add StorageUniformBufferBlock16 to the list of enabled capabilities.
=> opt: add StorageUniformBufferBlock16 to trim pass

source/operand.cpp
Converts for-loop with unreachable increment statement into an assignment and if
=> Fix -Wunreachable-code-loop-increment warning

Android.mk, BUILD.gn, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/switch_descriptorset_pass.cpp, source/opt/switch_descriptorset_pass.h, test/opt/CMakeLists.txt, test/opt/switch_descriptorset_test.cpp, tools/opt/opt.cpp
This is a simple pass to change  DescriptorSet decoration values.
=> opt: Add SwitchDescriptorSetPass

source/opt/trim_capabilities_pass.cpp, source/opt/trim_capabilities_pass.h, test/opt/trim_capabilities_pass_test.cpp
Adds support for Int64 capability trimming.
Fixes #4778
=> opt: add Int64 capability to trim pass

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
No tests added for the reasons specified in #5348.
=> Add SPV_EXT_fragment_shader_interlock to allow lists

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
=> Add SPV_KHR_physical_storage_buffer to allowlists

source/val/validate_image.cpp, test/val/val_image_test.cpp
This has been removed in #4752, but not added since.
=> val: re-add ImageMSArray validation

test/opt/aggressive_dead_code_elim_test.cpp
@s-perron correct me if I'm wrong, but it seems like AggressiveDCE is treating `OpBeginInvocationInterlockEXT` and `OpEndInvocationInterlockEXT` by not removing them? Are there any other tests I should add?
=> Make sure that fragment shader interlock instructions are not removed by DCE

.github/workflows/autoroll.yml
The autoroll pr reviews add me as the reviewer. I want to change this so
that it requests a reveiw from a team instead.
=> Change autoroll pr review id

BUILD.gn
=> Update BUILD.gn to include header for new pass

source/opt/trim_capabilities_pass.cpp, source/opt/trim_capabilities_pass.h, test/opt/trim_capabilities_pass_test.cpp
=> opt: add Float64 capability to trim pass

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/5459
=> spirv-val: Add WorkgroupMemoryExplicitLayoutKHR check for Block

.github/workflows/ios.yml
=> Add iOS build to CI

DEPS, test/enum_set_test.cpp
Fixes #5503
* SPIRV-Headers name change broke the build
* Update SPIRV-Headers deps and fix
=> Fix broken build

external/CMakeLists.txt
This reverts commit 7d2429594d84f09d0aef2c0a36d1a7234941a040.
=> Revert "Fix(cmake): CMake doesn't find system installed SPIRV-Headers (#5422)"

source/val/validate.cpp, source/val/validate.h, source/val/validate_annotation.cpp, source/val/validate_instruction.cpp, source/val/validate_mode_setting.cpp, test/operand_capabilities_test.cpp, test/text_to_binary.extension_test.cpp, test/val/val_annotation_test.cpp, test/val/val_modes_test.cpp
Depends on https://github.com/KhronosGroup/SPIRV-Headers/pull/408. I will update deps after it is merged.
Adds support for:
* validation
* parsing assembly
cc @gnl21
=> Add support for SPV_KHR_float_controls2

source/opt/optimizer.cpp, tools/opt/opt.cpp
Add an option to the spirv-opt tool to run the TrimCapabilitiesPass.
=> opt: Add TrimCapabilities pass to spirv-opt tool

README.md, kokoro/scripts/linux/build-docker.sh
I think this is the last thing needed to get #5601 working.
=> Ubuntu bazel

source/opt/eliminate_dead_output_stores_pass.cpp, source/opt/liveness.cpp, source/opt/liveness.h
=> Remove calls to GetId in liveness analysis

BUILD.bazel, MODULE.bazel, WORKSPACE
Ideally this is the last bzlmod-related change needed.
=> Use bzlmod for effcee

kokoro/scripts/linux/build-docker.sh
=> kokoro: use Python 3.12 in Linux builds

source/binary.cpp, test/binary_parse_test.cpp, test/val/val_misc_test.cpp
Fix all occurrences of "spriv" typos (irrespective of case).
=> Fix SPRIV -> SPIRV typos

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/6844
=> [OPT] Add SPV_KHR_ray_tracing_position_fetch to allow lists

Android.mk, include/spirv-tools/optimizer.hpp, source/opt/CMakeLists.txt, source/opt/optimizer.cpp, source/opt/passes.h, source/opt/struct_packing_pass.cpp, source/opt/struct_packing_pass.h, test/opt/CMakeLists.txt, test/opt/struct_packing_test.cpp, tools/opt/opt.cpp, utils/check_copyright.py
This pass allows to re-assign offset layout decorations to tightly pack a struct according to its packing rules.
=> [opt] Add struct-packing pass and unit test.

source/opt/remove_unused_interface_variables_pass.cpp
The unordered_map was used to re-emit some IDs, meaning the order could change depending on the hashtable usage.
This could cause instability in the DXC codegen.
Related to https://github.com/microsoft/DirectXShaderCompiler/issues/6804
=> spirv-opt: make traversal deterministic

source/val/validate_decorations.cpp, test/val/val_decoration_test.cpp
Fixes #5819
* Allow multiple levels of arrays in a variable with component decoration
=> Allow more levels of arrays with component decoration

DEPS, source/opcode.cpp, source/operand.cpp, source/table.h, utils/generate_grammar_tables.py, utils/generate_vim_syntax.py
This PR requires https://github.com/KhronosGroup/SPIRV-Headers/pull/447.
Handles building tables when the alias entry is present in instructions and enumerants.
=> Handle aliases field in the grammar

source/val/validate_image.cpp, test/val/val_image_test.cpp
Fixes https://crbug.com/oss-fuzz/42537207
* Fix check and messages in ValidateImageTexelPointer
=> Fix result type check in ValidateImageTexelPointer

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
Allowing this extensions to the few gated optimization passes.
=> opt: add KHR_fragment_shading_rate to allowlist

source/val/validate_decorations.cpp, source/val/validation_state.cpp, test/val/val_decoration_test.cpp
Created https://github.com/KhronosGroup/SPIRV-Tools/issues/5989
For now just swapping the VUID, but still need to go in and update things for the various other new cases, but likely won't get to for a while
=> spirv-val: Update VUIDs for 308 header

kokoro/check-format/build-docker.sh, utils/check_code_format.sh
Use a special Docker image that has only the necessary tools.
BUG=392135092
=> kokoro: Streamline check-format

source/opt/folding_rules.cpp, test/opt/fold_test.cpp
(Draft because based on #6013)
=> Fold 0 <<,>>,/,% n to 0. Fold a / 1 to a. Fold a % 1 to 0. Fold f % 1.0 to 0.0. Fold 0.0 % f to 0.0

source/val/validate_interfaces.cpp, test/val/val_interfaces_test.cpp
* Incorrectly assumed vec3/4 as the element of the matrix so double matrices were too large
=> Fix calculation of locations for matrices

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp, source/opt/trim_capabilities_pass.h, test/opt/trim_capabilities_pass_test.cpp
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/7247
=> opt: Support QuadControlKHR

source/util/span.h, test/util/CMakeLists.txt, test/util/span_test.cpp
It's a subset of C++20's std::span, but only using C++17 features.
=> Add spvtools::utils::Span

tools/objdump/extract_source.cpp
Fixes `-Wodr` warning with GCC, objdump seems to be the only remaining place where `spirv.hpp` header is used.
```
/mnt/work/git/SPIRV-Tools/external/spirv-headers/include/spirv/unified1/spirv.hpp:1483:6: warning: type ‘spv::Op’ violates the C++ One Definition Rule [-Wodr]
1483 | enum Op {
|      ^
/mnt/work/git/SPIRV-Tools/external/spirv-headers/include/spirv/unified1/spirv.hpp11:1483:12: note: an enum with different value name is defined in another translation unit
1483 | enum class Op : unsigned {
|            ^
/mnt/work/git/SPIRV-Tools/external/spirv-headers/include/spirv/unified1/spirv.hpp:2254:5: note: name ‘OpMax’ differs from name ‘Max’ defined in another translation unit
2254 |     OpMax = 0x7fffffff,
|     ^
/mnt/work/git/SPIRV-Tools/external/spirv-headers/include/spirv/unified1 …
```
=> Replace spirv.hpp with spirv.hpp11 in objdump

source/opt/copy_prop_arrays.cpp, test/opt/copy_prop_array_test.cpp
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/7182
=> [OPT] Set the BB for the debug instruction when moved.

source/opcode.cpp, source/val/validation_state.cpp
--Modfied files so that OpTypeTaskSequenceINTEL is identified as a type instruction
--Made changes in opcode.cpp and validation_state.cpp
=> OpTypeTaskSequenceINTEL recognisition as a type instruction

source/opt/aggressive_dead_code_elim_pass.cpp, source/opt/local_access_chain_convert_pass.cpp, source/opt/local_single_block_elim_pass.cpp, source/opt/local_single_store_elim_pass.cpp
Had missed adding extension to whitelist in initial change
=> Add SPV_NV_linear_swept_spheres to allow list.

source/opt/upgrade_memory_model.cpp, test/opt/upgrade_memory_model_test.cpp
We want to use extension `SPV_KHR_variable_pointers` with vulkan memory model, but shader compiler crashes.
The typical case is passing the buffer to a function and use it.
In function, we need to load the real buffer from variable pointers, it's okay.
But when we run pass `upgrade-memory-model`, we missed to handle the `OpLoad` with variable pointers, which resulted in missing 1 dimension to calculate the access element type. `OpStore` also has the same problem.
Moreover, `OpLoad` and `OpStore` shouldn't be marked as `NonPrivatePointer` if the target pointer is storage class Function or Private.
=> [spirv-opt] Fix errors if upgrade memory model with variable pointers

README.md
This should have been part of my previous PR.
=> Update README with canonicalize IDs pass

source/parsed_operand.cpp, source/util/hex_float.h, source/util/parse_number.cpp, test/hex_float_test.cpp
closes https://github.com/KhronosGroup/SPIRV-Tools/issues/6221
based off of https://github.com/KhronosGroup/SPIRV-Tools/commit/6061b72049a037215dfaba87399e1910a97b350e#diff-4d5ed3d2bacfcecb48ce69a8c4f2446d283865792abf7c058fbf220989224619
(Draft until i get testing up as well)
=> Add BFloat16 encoding support

source/opt/type_manager.cpp, source/opt/types.cpp, source/opt/types.h, test/opt/type_manager_test.cpp
Change-Id: Ibfa48eaf265bdab7b9d15c5adb9a3b8d62e5840c
=> spirv-opt: add support for OpTypeGraphARM to type manager

source/val/validation_state.cpp, test/val/val_memory_test.cpp
Add missing types
Clean returns for types already there
=> spirv-val: fix GetLargestScalarType

source/opt/desc_sroa.cpp
The descriptor SROA pass was crashing on ID overflow because it was not
checking if new IDs could be allocated for replacement variables and
instructions. This could lead to a null pointer dereference when trying
to use the new ID.
This change adds checks for ID overflow when creating new variables and
instructions in the pass. This ensures the pass fails gracefully when it
runs out of IDs.
=> spirv-opt: Fix ID overflow in descriptor SROA pass
